### ISSUE TITLE
onnx related c++ code

### ISSUE THREAD

**Issue by EmreOzkose** [k2-fsa/sherpa-onnx#1]
Hi @csukuangfj, 

> Would you mind porting your onnx related c++ code to https://github.com/k2-fsa/sherpa-onnx

I haven't written c++ code yet, [my fork](https://github.com/EmreOzkose/sherpa/tree/onnx) includes search functions in Python. c++ code will be done probably in a few days.

**Comment by csukuangfj** [comment]
Note that you don't need to add Python code to this repo.

**Comment by csukuangfj** [comment]
Is there any progress?

**Comment by EmreOzkose** [comment]
Yes. I wrote greedy search, and it is working now, but I have to refactor the code. I just wrote in a simple way without `OfflineAsr` or `OfflineRecognizer` classes like sherpa cpp-api. Should I push the code and then refactor it later according to your feedback?

**Comment by csukuangfj** [comment]
I suggest pushing the code first. At least we have something.

By the way, you may find the following code useful.

https://github.com/k2-fsa/sherpa-ncnn/blob/master/sherpa-ncnn/csrc/decode.cc

Thanks!

**Comment by csukuangfj** [comment]
@EmreOzkose 
Thanks for pushing the code.

Would you mind creating a separate PR to refactor the code?
I suggest creating pull-requests to push the code and then we can merge PRs into the master.

**Comment by EmreOzkose** [comment]
Yes, I pushed here wrongly. Now I reverted and make a PR now

**Comment by EmreOzkose** [comment]
I made a PR, sorry for the mistake.
