### ISSUE TITLE
Hi, when will Chinese onnx support and when will all-in-one inference will be ready?

### ISSUE THREAD

**Issue by jinfagang** [k2-fsa/sherpa-onnx#10]
Hi, when will Chinese onnx support and when will all-in-one inference will be ready?
Really hoping for a workable Chinese ASR ONNX support here.

**Comment by csukuangfj** [comment]
hi, the current master should support that.

Please refer to README.md for usage.

**Comment by jinfagang** [comment]
thank u, let me have a try.  Also, if I need a stream inference, does it support stream demo?  Do u have a good keyworrd spotting model suggest? Eventually I want implement something like: keyword aware, then start streaming, and then wating for keyword wake up, and loop the scheduler.

**Comment by csukuangfj** [comment]
No, only non-streaming at present.

**Comment by jinfagang** [comment]
thank u , will think about support streaming ifnerence?

**Comment by csukuangfj** [comment]
Yes, we are definitely going to support streaming ASR.

**Comment by jinfagang** [comment]
How about keyword spotting. Do u know how to make a simple and fast keyword spotting model upon sherpon?

**Comment by csukuangfj** [comment]
> How about keyword spotting. Do u know how to make a simple and fast keyword spotting model upon sherpon?

Do you already have a model?

**Comment by jinfagang** [comment]
not really. I am totally blank at this area.

**Comment by jinfagang** [comment]
not really. I am totally blank at this area.

**Comment by csukuangfj** [comment]
Please see
https://k2-fsa.github.io/sherpa/onnx/pretrained_models/lstm-transducer-models.html#csukuangfj-sherpa-onnx-lstm-zh-2023-02-20-chinese
