### ISSUE TITLE
在做ASR时，如果对麦克风收音做降噪处理？

### ISSUE THREAD

**Issue by alonge** [k2-fsa/sherpa-onnx#1000]
您好，非常感谢你们的工作，我现在的场景是对麦克风说话做流式识别。
服务端通过sherpa-onnx-online-websocket-server  起了websocket服务，选择的模型是sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20。
现在测试结果是，说中英文都有不错的识别效果，但是识别结果比较敏感，把周围的杂音也收进去做识别了，想请教一下这个问题该怎么解决，例如设定一个音量阈值，或者其他更好的办法。如果有相关的参数或者给一些示例的话就太感谢了！

**Comment by csukuangfj** [comment]
这个属于信号处理范畴。

**Comment by zzk2021** [comment]
英伟达降噪
