### ISSUE TITLE
TTS，除了命令行调用外，能否在Python里直接调用？想避免模型重复加载耗时

### ISSUE THREAD

**Issue by xkkjiayou** [k2-fsa/sherpa-onnx#1002]
TTS，除了命令行调用外，能否在Python里直接调用？
想避免模型重复加载耗时，做模型持久化，给不同的文本输出音频，不用重复加载模型

**Comment by csukuangfj** [comment]
可以的。请看我们的 python-api-examples 下的例子。

**Comment by xkkjiayou** [comment]
> 可以的。请看我们的 python-api-examples 下的例子。

csukuangfj/vits-zh-hf-theresa (Chinese, 804 speakers)[](https://k2-fsa.github.io/sherpa/onnx/tts/pretrained_models/vits.html#csukuangfj-vits-zh-hf-theresa-chinese-804-speakers)

这个模型也可以用py脚本调用吧？根据示例该模型等相关参数就可以了吧，谢谢我试试，感谢回复。项目特别棒

我只看到了aishell3 (Chinese, multi-speaker, 174 speakers)[](https://k2-fsa.github.io/sherpa/onnx/tts/pretrained_models/vits.html#aishell3-chinese-multi-speaker-174-speakers)这个有python示例，以为只有他可以python脚本调用。

**Comment by csukuangfj** [comment]
所有提供的 tts 模型，都可以用 python-api-examples 下面的例子

**Comment by xkkjiayou** [comment]
> 所有提供的 tts 模型，都可以用 python-api-examples 下面的例子

谢谢，我试试，感谢
