### ISSUE TITLE
[Help wanted] Flutter APP for text-to-speech

### ISSUE THREAD

**Issue by csukuangfj** [k2-fsa/sherpa-onnx#1012]
https://github.com/k2-fsa/sherpa-onnx/pull/1010
added Dart API for text-to-speech

We have published the Dart API package to
https://pub.dev/packages/sherpa_onnx

Currently, we only have text-to-speech [examples](https://github.com/k2-fsa/sherpa-onnx/tree/master/dart-api-examples/tts) for pure Dart.

We want to build a text-to-speech Flutter APP using the Dart API from sherpa-onnx.
As the first step, we only need the APP to work on Linux, macOS, and Windows. We can support iOS and Android later.

Community help on this issue is greatly appreciated.

Note: You don't need knowledge about C++ for this issue. All you need is Flutter + Dart.

**Comment by liu731** [comment]
"We can support iOS and Android later"
Looking forward to it
