### ISSUE TITLE
把SherpaOnnx 样例的Android kotlin代码转成Java就无法识别声音

### ISSUE THREAD

**Issue by bookly2022** [k2-fsa/sherpa-onnx#1013]
private final int sampleRateInHz = 16000; // 采样率
    private final int channelConfig = AudioFormat.CHANNEL_IN_MONO; // 单声道
    private final int audioFormat = AudioFormat.ENCODING_PCM_16BIT; // 16位PCM编码
    private final int audioSource = MediaRecorder.AudioSource.MIC;                       

    public void startRecording() {
        mIsRecording = true;
        if (mAudioRecord != null && mIsRecording) {
            if (mAudioRecord.getState() == AudioRecord.STATE_INITIALIZED) {
                Log.i(Tag,"startRecording");
                mAudioRecord.startRecording();
                new Thread(new Runnable() {
                    @Override
                    public void run() {
                        mStreamObj = mRecognizerObj.createStream();
                        float interval = 0.1f;
                        int bufferSize = (int)(interval * sampleRateInHz);
                        Log.i(Tag,"bufferSize=" + Integer.toString(bufferSize));
                        byte[] audioData = new byte[bufferSize];
                        while (mIsRecording) {
                            int readSize = mAudioRecord.read(audioData, 0, bufferSize);
                            if (readSize > 0) {
                                float[] samples = new float[readSize];
                                for (int i = 0; i < readSize; ++i) {
                                    samples[i] = audioData[i] / 32768.0f;
                                }
                                mStreamObj.acceptWaveform(samples,sampleRateInHz);
                                while (mRecognizerObj.isReady(mStreamObj)) {
                                    mRecognizerObj.decode(mStreamObj);
                                }

                                String nowText = mRecognizerObj.getResult(mStreamObj).getText();
                                if (!nowText.isEmpty()) {
                                    Log.i(Tag, nowText);
                                }

把SherpaOnnx 样例的Android kotlin代码转成Java无法识别麦克风声音。
加载模型后，如果传入wav文件是可以正常识别。

**Comment by csukuangfj** [comment]
录音参数，请发一下。

还有，你为什么直接把byte除以32768？kotlin代码，请你仔细读一下

**Comment by bookly2022** [comment]
谢谢大佬指点

**Comment by csukuangfj** [comment]
已通过qq群解决

**Comment by ArvinC** [comment]
求大佬分享一份Java版本的Android代码

**Comment by csukuangfj** [comment]
android java 里面，可以调用 kotlin api 的。

**Comment by ArvinC** [comment]
谢谢大佬解惑

**Comment by litao-zhx** [comment]
> 求大佬分享一份Java版本的Android代码

大佬，你有解决这个问题么？
