### ISSUE TITLE
The command line tool named 'sherpa-onnx-cli' for convert the original keywords to tokens

### ISSUE THREAD

**Issue by ScWen7** [k2-fsa/sherpa-onnx#1018]
Doc: https://k2-fsa.github.io/sherpa/onnx/kws/index.html#keywords-file 

Can not find command line tool  sherpa-onnx-cli'

**Comment by ScWen7** [comment]
<img width="533" alt="image" src="https://github.com/k2-fsa/sherpa-onnx/assets/22461932/ac4161ff-3b79-4223-bbad-e8fc732b942b">

**Comment by csukuangfj** [comment]
Please first run
```
pip install sherpa-onnx
```
