### ISSUE TITLE
Could you upload the apk of the latest update

### ISSUE THREAD

**Issue by Sphyker789** [k2-fsa/sherpa-onnx#1023]
Could you please upload the apk of the latest update so we can access it using an android device

**Comment by csukuangfj** [comment]
Please find the list of APKs at
https://k2-fsa.github.io/sherpa/onnx/android/prebuilt-apk.html

(GitHub actions is building the latest v1.10.0. However, version v1.9.30 or v1.9.29 is also usable.)

**Comment by Sphyker789** [comment]
I mean a pre-built apk, the link contains compressed files only

**Comment by Sphyker789** [comment]
I'm looking for the apk that supports English language

**Comment by csukuangfj** [comment]
What do you mean by `pre-built apk`?

All APKs we provide are `pre-built apk`.

**Comment by csukuangfj** [comment]
Are you looking for an APK for text to speech or speech to text or something else?

**Comment by Sphyker789** [comment]
Could you please provide the apk that is for chatting with LLM locally that supports English language?

**Comment by csukuangfj** [comment]
https://huggingface.co/csukuangfj/sherpa-onnx-apk/resolve/main/vad-asr/sherpa-onnx-1.9.29-arm64-v8a-vad_asr-en-whisper_tiny.apk

Please try this one.  It uses silero vad + whisper tiny.

You can find more at
https://k2-fsa.github.io/sherpa/onnx/vad/apk-asr.html

**Comment by Sphyker789** [comment]
I apologize for misunderstanding, I'm searching for the app similar to chatterui where the user can load a gguf model locally and chat with it using text messages
