### ISSUE TITLE
发型的paraformer 2pass apk包，这个paraformer是large模型吗

### ISSUE THREAD

**Issue by lj19950508** [k2-fsa/sherpa-onnx#1031]
发型的paraformer 2pass apk包，这个paraformer是large模型吗，感觉精确度不太够

**Comment by csukuangfj** [comment]
用的是
https://github.com/k2-fsa/sherpa-onnx/blob/167bc76db0f7980dec4387302613ce53ffb0cece/scripts/apk/generate-asr-2pass-apk-script.py#L70-L78

**Comment by lj19950508** [comment]
好的感谢
