### ISSUE TITLE
win x64  使用paraformer模型的问题

### ISSUE THREAD

**Issue by lj19950508** [k2-fsa/sherpa-onnx#1032]
sherpa-onnx-streaming-asr-x64-v1.10.0.exe
下载好模型后发现需要joiner.onnx,但是paraformer应该是没有joiner

Creating recognizer...
It will take several seconds. Please wait
./joiner.onnx does not exist!

**Comment by csukuangfj** [comment]
不需要 joiner.
删掉 exe 所在目录 onnx 文件，然后，然后请贴运行的截图

**Comment by csukuangfj** [comment]
请查看最后面的 paraformer 的帮助。
你要把下载的模型，重命名为  paraformer-encoder.onnx 和 paraformer-decoder.onnx.

不需要 joiner!

**Comment by lj19950508** [comment]
sorry 我的问题

**Comment by lj19950508** [comment]
可以了，然后自己编译了一个paraformer,发现在安卓上跑大模型还是性能上跑不动。
但是我切换了别的模型，发现除了没标点效果也不错。
很不错的fsa，多谢大佬

**Comment by csukuangfj** [comment]
> 然后自己编译了一个paraformer,发现在安卓上跑大模型还是性能上跑不动

1. 你用 int8 的模型没？
2. 你是什么安卓手机？

**Comment by lj19950508** [comment]
1.用的int8模型
2.安卓机不是市面上的，性能确实会偏弱很多，就是  2pass下 第一遍很快 ，paraformer修正的话会偶尔卡一下。

**Comment by csukuangfj** [comment]
你换个好点的手机，效果会非常好的

**Comment by csukuangfj** [comment]
好马配好鞍

**Comment by lj19950508** [comment]
可以的，感谢大佬，教程做的很全，很容易就编译出来了
