### ISSUE TITLE
[example] sample config file for starting the server

### ISSUE THREAD

**Issue by manickavela29** [k2-fsa/sherpa-onnx#1057]
Observed this option for starting the server with config file, would be great to have a sample config file.
if maybe I have missed it while looking at the code, please share the path

> Standard options:
>   --print-args                : Print the command line arguments (to stderr) (bool, default = true)
>   --help                      : Print out usage message (bool, default = false)
>   --config                    : Configuration file to read (this option may be repeated) (string, default = "")
> 

Thank you!

**Comment by csukuangfj** [comment]
If you use
```
./a.out --foo=bar --baz=apple
```

Then you can use
```
./a.out --config=./foobar.abc
```
where `./foobar.abc` is a text file containing
```
--foo=bar
--baz=apple # you can add a comment to a line like this
```

**Comment by csukuangfj** [comment]
This approach is inherited from Kaldi, as the C++ code is copied directly from Kaldi.

**Comment by manickavela29** [comment]
Alright!, Thanks for the info!
