### ISSUE TITLE
android 低版本4.4 启动报错

### ISSUE THREAD

**Issue by yolanda0628** [k2-fsa/sherpa-onnx#1063]
java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "libsherpa-onnx-core.so" needed by "libsherpa-onnx-jni.so"; caused by could not load library "libkaldi-native-fbank-core.so" needed by "libsherpa-onnx-core.so"; caused by cannot locate symbol "rand_r" referenced by "libkaldi-native-fbank-core.so"...

**Comment by csukuangfj** [comment]
你的 apk ，是如何得到的？

**Comment by pbq18785109289** [comment]
集成的v1.10.2开发的唤醒，高版本运行正常。

**Comment by csukuangfj** [comment]
> 集成的v1.10.2开发的唤醒，高版本运行正常。

能说详细点么？

是用我们提供的 apk, 是否有问题？

**Comment by pbq18785109289** [comment]
1.低版本（安卓4.4）加载armeabi-v7a目录下的so包报错，运行不起来；在高版本上加载的是arm64-v8a下的so包，运行正常，功能也能正常使用。（https://github.com/k2-fsa/sherpa-onnx/releases/tag/v1.10.2）
2.使用您们提供的apk低版本安装失败（Failure [INSTALL_FAILED_OLDER_SDK]），应该是minSDK没到Android19。

**Comment by csukuangfj** [comment]
我们只支持 Android API >= 21。

你的 android 4.4, API level 是 19. 太低了。

---

https://github.com/k2-fsa/sherpa-onnx/blob/8c4f576f1bbf9ef16b1bc34e6ab0afe79fad254e/build-android-armv7-eabi.sh#L88
你把上面的
android-21 改成 android-19 然后自己从源码编译。如果还不行，我们也没办发了。

**Comment by csukuangfj** [comment]
我们只支持 Android API >= 21。

Android 4.4 版本太低了。
