### ISSUE TITLE
Question: ASR on Android + iOS via flutter

### ISSUE THREAD

**Issue by jtdLab** [k2-fsa/sherpa-onnx#1069]
Is it possible to run ASR on mobile using dart/flutter api. Are there any additional steps required as currently the example only contains desktop support?

**Comment by csukuangfj** [comment]
> Is it possible to run ASR on mobile using dart/flutter API.

Yes, it is possible.

> Are there any additional steps 

Yes, there are.

---

We need to first fix https://github.com/k2-fsa/sherpa-onnx/issues/379#issuecomment-2184962513

Pre-built libs are pre-packaged in the dart/flutter package and we need to support macos, linux, windows, ios, 
and android,  but pub.dev limits that each package cannot exceed 100MB. We need to first refactor the current approach
to use [the federated plugin](https://docs.flutter.dev/packages-and-plugins/developing-packages)

I don't have extra time to do that. Help from the community is needed to finish that.

**Comment by csukuangfj** [comment]
Closing via #1079 

Android as well as iOS with Flutter is supported now.

See also
https://pub.dev/packages/sherpa_onnx

<img width="910" alt="Screenshot 2024-07-06 at 19 31 56" src="https://github.com/k2-fsa/sherpa-onnx/assets/5284924/4a3c2b32-5993-4aaf-bcbb-4de0cc67f021">
