### ISSUE TITLE
wasm: index.html error

### ISSUE THREAD

**Issue by yushanyong** [k2-fsa/sherpa-onnx#1070]
提示找不到sherpa-onnx-wasm-main-kws.js文件，但是有一个sherpa-onnx-wasm-main-kws.cc
　　
　　
![image](https://github.com/k2-fsa/sherpa-onnx/assets/30676802/7b4a685d-f20b-425e-bc15-79750f687706)

**Comment by csukuangfj** [comment]
请详细描述你的操作步骤

你是否有看https://k2-fsa.github.io/sherpa/onnx/wasm/build.html

是否有运行
```
python3 -m http.server 6006
```

**Comment by yushanyong** [comment]
只看了README😂，谢谢，搞定了

**Comment by csukuangfj** [comment]
那我关闭啦
