### ISSUE TITLE
实时语音识别报错：terminate called after throwing an instance of 'std::out_of_range'what(): _Map_base::at

### ISSUE THREAD

**Issue by Mactarvish** [k2-fsa/sherpa-onnx#1071]
Ubuntu22.04
编译完成后运行sherpa-onnx-alsa的demo，demo运行后一旦说话就报错：
```
Current sample rate: 16000
Recording started!
Use recording device: plughw:1,0
Please speak! press ctrl + c to exit
terminate called after throwing an instance of 'std::out_of_range'what(): _Map_base::at
```

**Comment by csukuangfj** [comment]
用最新的代码么？什么板子，什么芯片？用了几个线程？

**Comment by csukuangfj** [comment]
@Mactarvish  可以回复一下么？不然我们要 close 这个 issue 了.

**Comment by Mactarvish** [comment]
> @Mactarvish 可以回复一下么？不然我们要 close 这个 issue 了.

不好意思我一直在排查嗷，
平台是x86 Ubuntu22.04 在戴尔笔记本上运行的
线程数是1

代码基于 [8af2af8](https://github.com/fengyongronglu/sherpa-onnx/commit/8af2af84664d3285ba452bf453bb928a3eb6e978)

我根据`c-api-alsa.cc`改写的代码，目前来看好像是因为我定义了一个全局的std::unordered_map对象（没有声明为static），然后就会引起这个问题（相同的代码在Ubuntu 20.04上编译运行是正常的），怀疑是堆结构被破坏了

我这两天整理一下最小可复现代码发上来。多谢支持

**Comment by Mactarvish** [comment]
澄清了😅是我这边的一个问题 两个cpp同时include了一个hpp，这个hpp里定义了一个全局的unordered_map导致析构的时候重复析构 不过只有在被访问到的时候才会出错，误以为是sherpa的问题了

**Comment by csukuangfj** [comment]
建议加header guard

**Comment by csukuangfj** [comment]
建议不要在头文件里定义全局变量
