### ISSUE TITLE
Flutter android demo 运行报错

### ISSUE THREAD

**Issue by guixin567** [k2-fsa/sherpa-onnx#1075]
<img width="1153" alt="image" src="https://github.com/k2-fsa/sherpa-onnx/assets/19410324/0567bbb0-d46a-4ada-ac10-6c9d5874faa8">
<img width="1141" alt="image" src="https://github.com/k2-fsa/sherpa-onnx/assets/19410324/1460977d-46dd-4fef-a388-b81b2d66ad40">

Assets目录下面确实没有，代码运行的时候找不到

**Comment by csukuangfj** [comment]
1. Please follow
https://k2-fsa.github.io/sherpa/onnx/pretrained_models/online-transducer/zipformer-transducer-models.html#csukuangfj-sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20-bilingual-chinese-english
to download the model to the `assets` directory

2. Unzip it and delete unused files

3. Please refer to the following screenshot for which files to be kept
<img width="1150" alt="Screenshot 2024-07-04 at 16 03 05" src="https://github.com/k2-fsa/sherpa-onnx/assets/5284924/ea0f9873-5315-4e30-9519-bf24ad3bc6db">

**Comment by guixin567** [comment]
> 1. Please follow
>    https://k2-fsa.github.io/sherpa/onnx/pretrained_models/online-transducer/zipformer-transducer-models.html#csukuangfj-sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20-bilingual-chinese-english
>    to download the model to the `assets` directory
> 2. Unzip it and delete unused files
> 3. Please refer to the following screenshot for which files to be kept
> 
> <img alt="Screenshot 2024-07-04 at 16 03 05" width="1150" src="https://private-user-images.githubusercontent.com/5284924/345974834-ea0f9873-5315-4e30-9519-bf24ad3bc6db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNDU5NzYsIm5iZiI6MTcyMDE0NTY3NiwicGF0aCI6Ii81Mjg0OTI0LzM0NTk3NDgzNC1lYTBmOTg3My01MzE1LTRlMzAtOTUxOS1iZjI0YWQzYmM2ZGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDVUMDIxNDM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTllN2ExMzAwNWQ5NTBjOTA0NWJlZWM1ZmIxMWZjZjg1NTQ0ZDVjMzM1MDFlNDg3YjU5NGUxMWQ1N2E3YzEzZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZLyTQMiRWUsXBxU-5FLYjmiOdG4JuPdrKla-WBWc_b4">

非常感谢，帅气

**Comment by csukuangfj** [comment]
现在没问题了吧？

**Comment by guixin567** [comment]
很帅气 没有问题了，这个模型是2023年的，有新的模型吗，我这个试的中文识别率稍微高一些，但是也不是很完美，英文识别率也不理想，想问下这个周末优化

**Comment by csukuangfj** [comment]
这是是流式中文目前我们有的里面，最好的
