### ISSUE TITLE
Can i use sherpa onnx directly on python ?

### ISSUE THREAD

**Issue by Yessine1e** [k2-fsa/sherpa-onnx#1076]
HI,
i want to use sherpa directly on python editor, not using cmd
i can't find that on documentation
is that possible ?
thanks in advance

**Comment by csukuangfj** [comment]
Definitely possible.

It's just a Python package, like PyTorch and numpy. There is nothing special with sherpa-onmx.

Please see the folder python-api-examples for usage.

We also have doc for it.

Please read it first.
