### ISSUE TITLE
C#的API没有Hotwords 和 keyword spotting，能加下吗？

### ISSUE THREAD

**Issue by x-light-ai** [k2-fsa/sherpa-onnx#1082]
缺少C#的API没有Hotwords 和 keyword spotting，能加下吗？java的api已经实现keyword spotting

**Comment by csukuangfj** [comment]
> 缺少C#的API没有Hotwords

是有的. 

----

> 缺少C#的API没有 keyword spotting
 
好的，尽快安排上

**Comment by csukuangfj** [comment]
基础知识，请自己看文档
