### ISSUE TITLE
max speakers for speaker embedding manager

### ISSUE THREAD

**Issue by thewh1teagle** [k2-fsa/sherpa-onnx#1096]
It would be useful if I there was an option in  embedding manager to find the closest one from existing speakers.
This way, I can handle myself the case where I know how many speakers there are, and there's already enough speakers detected.

**Comment by csukuangfj** [comment]
That sounds reasonable.

Could you follow
https://github.com/k2-fsa/sherpa-onnx/blob/3e4307e2fb88d4b1b648211c14f2fff6db11bca4/sherpa-onnx/csrc/speaker-embedding-manager.cc#L126
to add a `TopK` to return the name and scores for the topK match?

**Comment by thewh1teagle** [comment]
> to add a `TopK` to return the name and scores for the topK match?

I assume we just need to sort the scores, then iterate through them, collect, and return. Could you share any specific IntelliSense settings used in the repository so I can feel more comfortable working in VSCode?

**Comment by csukuangfj** [comment]
We are using `clang-format`, which can be installed with
```
pip install clang-format
```
I don't use VSCode. Maybe you can find a way to integrate clang-format with it.

You don't need to care about the style issues. We can reformat the file later.
