### ISSUE TITLE
What natural languages does this library support？

### ISSUE THREAD

**Issue by woniu163** [k2-fsa/sherpa-onnx#1103]
Thanks

**Comment by csukuangfj** [comment]
Do you mean speech to text or text to speech or any other speech related tasks?

Could you be more specific?

**Comment by woniu163** [comment]
text to speech

**Comment by woniu163** [comment]
I look at the example apk package, each package only supports one language, may I ask the real project, can a package support multiple languages?

**Comment by csukuangfj** [comment]
The APKs we provided are to show what we support.

It is 100% possible to integrate many models into a single APK. You can use the APIs and models from us to do that.

**Comment by woniu163** [comment]
So a model can only support one language? How much do you charge for your api?

**Comment by csukuangfj** [comment]
> How much do you charge for your API?

100% free. We use Apache 2.0 license.


> So a model can only support one language?

I assume you mean speech to text.

Most of the models support only 1 language.

Some of them support two, e.g., English + Chinese. Please see our doc for details.

**Comment by woniu163** [comment]
Thanks for your answer, I would like to add reading aloud to our reader, our novel is multilingual, so we need a multilingual tts

**Comment by csukuangfj** [comment]
I see. You are asking for text to speech.

Please have a look at
https://github.com/jing332/SherpaOnnxTtsEngineAndroid

It supports using multi-models but each model supports only one language.

**Comment by woniu163** [comment]
thanks a lot
