### ISSUE TITLE
Some tts engines are crashing since 1.10.13 (Android)

### ISSUE THREAD

**Issue by kulmegil** [k2-fsa/sherpa-onnx#1123]
Since 1.10.13 some apk-engines are crashing often during operation.

Crashing voices (incomplete list):
- sherpa-onnx-1.10.14-arm64-v8a-en-tts-engine-vits-piper-en_GB-alba-medium
- sherpa-onnx-1.10.14-arm64-v8a-en-tts-engine-vits-piper-en_GB-semaine-medium
- sherpa-onnx-1.10.14-arm64-v8a-en-tts-engine-vits-piper-en_US-joe-medium
- sherpa-onnx-1.10.14-arm64-v8a-pl-tts-engine-vits-piper-pl_PL-darkman-medium
- sherpa-onnx-1.10.14-arm64-v8a-pl-tts-engine-vits-piper-pl_PL-gosia-medium
- sherpa-onnx-1.10.14-arm64-v8a-pl-tts-engine-vits-piper-pl_PL-mc_speech-medium

Working stable so far:
- sherpa-onnx-1.10.14-arm64-v8a-en-tts-engine-vits-piper-en_GB-cori-medium
- sherpa-onnx-1.10.14-arm64-v8a-en-tts-engine-vits-piper-en_US-bryce-medium
- sherpa-onnx-1.10.14-arm64-v8a-en-tts-engine-vits-piper-en_US-glados
- sherpa-onnx-1.10.14-arm64-v8a-en-tts-engine-vits-piper-en_US-john-medium
- sherpa-onnx-1.10.14-arm64-v8a-en-tts-engine-vits-piper-en_US-ljspeech-medium
- sherpa-onnx-1.10.14-arm64-v8a-en-tts-engine-vits-piper-en_US-norman-medium

Device:
OnePlus 9 Pro

OS:
Android 14 ([AOSP based rom](https://www.nameless.wiki/getting-started/downloads/oneplus/lemonadep))

Tested on content:
- epubs using [Moon+ Reader Pro](https://play.google.com/store/apps/details?id=com.flyersoft.moonreaderp)
- Reddit comments thru [Joey for Reddit](https://play.google.com/store/apps/details?id=o.o.joey) (legacy app)

Crashes:
  
- [crash-com-k2fsa-sherpa-onnx-tts-engine_vits_piper_en_us_joe_medium-13_07-13-24-47_861.zip](https://github.com/user-attachments/files/16202132/crash-com-k2fsa-sherpa-onnx-tts-engine_vits_piper_en_us_joe_medium-13_07-13-24-47_861.zip) - epub reading
- [crash-com-k2fsa-sherpa-onnx-tts-engine_vits_piper_pl_pl_mc_speech_medium-13_07-11-30-16_033.zip](https://github.com/user-attachments/files/16202133/crash-com-k2fsa-sherpa-onnx-tts-engine_vits_piper_pl_pl_mc_speech_medium-13_07-11-30-16_033.zip) - epub reading
- [crash-com-k2fsa-sherpa-onnx-tts-engine_vits_piper_pl_pl_darkman_medium-13_07-11-27-13_497.zip](https://github.com/user-attachments/files/16202134/crash-com-k2fsa-sherpa-onnx-tts-engine_vits_piper_pl_pl_darkman_medium-13_07-11-27-13_497.zip) - epub reading
- [crash-com-k2fsa-sherpa-onnx-tts-engine_vits_piper_pl_pl_gosia_medium-13_07-11-23-58_296.zip](https://github.com/user-attachments/files/16202135/crash-com-k2fsa-sherpa-onnx-tts-engine_vits_piper_pl_pl_gosia_medium-13_07-11-23-58_296.zip) - epub reading
- [crash-com-k2fsa-sherpa-onnx-tts-engine_vits_piper_en_gb_semaine_medium-13_07-02-08-56_607.zip](https://github.com/user-attachments/files/16202136/crash-com-k2fsa-sherpa-onnx-tts-engine_vits_piper_en_gb_semaine_medium-13_07-02-08-56_607.zip) - epub reading
- [crash-com-k2fsa-sherpa-onnx-tts-engine-vits-piper-en_GB-alba-medium-13_07-14-40-09_914.zip](https://github.com/user-attachments/files/16202172/crash-com-k2fsa-sherpa-onnx-tts-engine-vits-piper-en_GB-alba-medium-13_07-14-40-09_914.zip) - epub reading

- [crash-com-k2fsa-sherpa-onnx-tts-engine_vits_piper_pl_pl_mc_speech_medium-13_07-11-32-52_713.zip](https://github.com/user-attachments/files/16202138/crash-com-k2fsa-sherpa-onnx-tts-engine_vits_piper_pl_pl_mc_speech_medium-13_07-11-32-52_713.zip) - Reddit comments reading
- [crash-com-k2fsa-sherpa-onnx-tts-engine_vits_piper_pl_pl_gosia_medium-13_07-11-11-05_646.zip](https://github.com/user-attachments/files/16202139/crash-com-k2fsa-sherpa-onnx-tts-engine_vits_piper_pl_pl_gosia_medium-13_07-11-11-05_646.zip) - Reddit comments reading
- [crash-com-k2fsa-sherpa-onnx-tts-engine_vits_piper_pl_pl_gosia_medium-13_07-11-01-31_309.zip](https://github.com/user-attachments/files/16202140/crash-com-k2fsa-sherpa-onnx-tts-engine_vits_piper_pl_pl_gosia_medium-13_07-11-01-31_309.zip) - Reddit comments reading
- [crash-com-k2fsa-sherpa-onnx-tts-engine_vits_piper_pl_pl_gosia_medium-13_07-10-56-25_611.zip](https://github.com/user-attachments/files/16202141/crash-com-k2fsa-sherpa-onnx-tts-engine_vits_piper_pl_pl_gosia_medium-13_07-10-56-25_611.zip) - Reddit comments reading
- [crash-com-k2fsa-sherpa-onnx-tts-engine_vits_piper_en_gb_semaine_medium-13_07-01-55-21_191.zip](https://github.com/user-attachments/files/16202142/crash-com-k2fsa-sherpa-onnx-tts-engine_vits_piper_en_gb_semaine_medium-13_07-01-55-21_191.zip) - Reddit comments reading
- [crash-com-k2fsa-sherpa-onnx-tts-engine_vits_piper_pl_pl_darkman_medium-12_07-22-12-16_133.zip](https://github.com/user-attachments/files/16202143/crash-com-k2fsa-sherpa-onnx-tts-engine_vits_piper_pl_pl_darkman_medium-12_07-22-12-16_133.zip) - Reddit comments reading
- [crash-com-k2fsa-sherpa-onnx-tts-engine_vits_piper_en_gb_semaine_medium-13_07-01-51-36_712.zip](https://github.com/user-attachments/files/16202144/crash-com-k2fsa-sherpa-onnx-tts-engine_vits_piper_en_gb_semaine_medium-13_07-01-51-36_712.zip) - Reddit comments reading

**Comment by aureliensoria** [comment]
Hello !
I have the same issue on sherpa-onnx-1.10.14-arm64-v8a-fr-tts-engine-vits-piper-fr_FR-siwis-low.apk and sherpa-onnx-1.10.13-arm64-v8a-fr-tts-engine-vits-piper-fr_FR-siwis-low.apk
