### ISSUE TITLE
libtool: error: unrecognised option: '-static' on Mac M1

### ISSUE THREAD

**Issue by minchopm** [k2-fsa/sherpa-onnx#1135]
I am using Mac M1 chipset, and when I execute build-swift-macos.h it is throwing an error: 
```
libtool:   error: unrecognised option: '-static'
```

**Comment by csukuangfj** [comment]
Could you post more logs?

**Comment by minchopm** [comment]
I tried with old Xcode 17, and it was building the onnx framework for iOS, but with Xcode beta 3 throw this error:
just before executig: libtool -static -o build/simulator/sherpa-onnx.a \
got: libtool:   error: unrecognised option: '-static'
```
Interesting point is the framework for iOS has been build but sherpa xcframework does not because of the issue.
I even tried to downgrade libtool 2.4.6 to 2.4.2 but does not work at all.

**Comment by csukuangfj** [comment]
```
(py38) fangjuns-MacBook-Pro:workflows fangjun$ libtool -V
Apple Inc. version cctools-1001.2
(py38) fangjuns-MacBook-Pro:workflows fangjun$ which libtool
/usr/bin/libtool
```

Here is the output on my mac.
