### ISSUE TITLE
语音识别测试使用非流式模型比流式模型识别率更高，是否可以更换NAudio组件录音wav文件

### ISSUE THREAD

**Issue by try3** [k2-fsa/sherpa-onnx#1137]
语音识别测试使用非流式模型比流式模型识别率更高，demo是否可以更换NAudio组件，现在使用的是PortAudioSharp2没有录音存wav文件功能

**Comment by csukuangfj** [comment]
naudio 只支持 windows, 不支持 linux 和 macos

demo 只是 demo. 你自己可以改的。
