### ISSUE TITLE
How do I use cuda with sherpa-onnx-node?

### ISSUE THREAD

**Issue by Eyalm321** [k2-fsa/sherpa-onnx#1146]
Hi!
I installed sherpa-onnx-node, cloned sherpa-onnx built it, what do I do next? I tried create offlineRecognizer with cuda set in config but it keep saying to compile it doesnt matter where I set $LD_LIBRARY_PATH to, wether to build or build/lib build/bin it will still give me same error.
Docs is missing info about this, where do I place files and which ones?

**Comment by csukuangfj** [comment]
Are you using Linux x64?

**Comment by Eyalm321** [comment]
yes sir

**Comment by csukuangfj** [comment]
You don't need to re-build sherpa-onnx. You can do that, but it requires extra effort.

Please do the following steps

```
git clone https://github.com/k2-fsa/sherpa-onnx
cd nodejs-addon-examples
npm install
```

You will find it creates a new directory `node_modules` inside `nodejs-addon-examples`.

Inside `node_modules`, you can find a directory `sherpa-onnx-linux-x64`.

Inside `sherpa-onnx-linux-x64`, you can find several `.so` files.

Please download the new `.so` files from
https://github.com/k2-fsa/sherpa-onnx/releases/download/v1.10.16/sherpa-onnx-v1.10.16-linux-x64-gpu.tar.bz2
and replace those inside `sherpa-onnx-linux-x64`.

Note that there are several `.so` files in `sherpa-onnx-v1.10.16-linux-x64-gpu.tar.bz2` that are not present in
the original `sherpa-onnx-linux-x64`. Please copy all of the `.so` files from `sherpa-onnx-v1.10.16-linux-x64-gpu.tar.bz2` to
`sherpa-onnx-linux-x64`.

Then everything should work as expected, provided that you have installed CUDA toolkit 11.8.
If not, please follow
https://k2-fsa.github.io/k2/installation/cuda-cudnn.html#cuda-11-8
to install CUDA 11.8

Note again you don't need `sudo` permission to install CUDA 11.8. Just follow the above doc.

**Comment by Eyalm321** [comment]
It worked! Much appreciated!
