### ISSUE TITLE
在windows上语音识别

### ISSUE THREAD

**Issue by kyn817046** [k2-fsa/sherpa-onnx#1150]
请问在可以设置热词，只识别中文的情况下，流式和非流式中识别最好的是那个模型呀？我看onnx和ncnn提供了好多模型。

**Comment by csukuangfj** [comment]
请用
- https://k2-fsa.github.io/sherpa/onnx/pretrained_models/online-transducer/zipformer-transducer-models.html#csukuangfj-sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20-bilingual-chinese-english
- https://k2-fsa.github.io/sherpa/ncnn/pretrained_models/zipformer-transucer-models.html#csukuangfj-sherpa-ncnn-streaming-zipformer-bilingual-zh-en-2023-02-13-bilingual-chinese-english

**Comment by kyn817046** [comment]
谢谢您
