### ISSUE TITLE
python wheels targeting linux

### ISSUE THREAD

**Issue by willwade** [k2-fsa/sherpa-onnx#1173]
We have wheels for Windows and MacOS but not linux - https://pypi.org/project/sherpa-onnx/#files

please can we have wheels for linux?!

**Comment by willwade** [comment]
So it is being built: https://github.com/k2-fsa/sherpa-onnx/blob/master/.github/workflows/build-wheels-linux.yaml 

So then why is pypi not listing these?

**Comment by csukuangfj** [comment]
As you have found, it is still being built.

Please see
https://github.com/k2-fsa/sherpa-onnx/actions/runs/10110036096

**Comment by csukuangfj** [comment]
Done. Please recheck.
