### ISSUE TITLE
希望OfflineTts能加个流式合成的方法

### ISSUE THREAD

**Issue by GeminiX369** [k2-fsa/sherpa-onnx#1175]
能给OfflineTts添加一个流式生成音频数据的方法吗？现在通过generateImpl方法合成音频，全部合成完成后才一次性返回所有数据。如果能够边合成数据边通过回调函数返回，应该能显著降低响应延迟。

**Comment by csukuangfj** [comment]
支持的，有一个callback，你自己找下例子？

**Comment by GeminiX369** [comment]
> 支持的，有一个callback，你自己找下例子？

感谢回复，我使用的是java-api中的/sherpa-onnx/sherpa-onnx/java-api/src/com/k2fsa/sherpa/onnx/OfflineTts.java类，没有在 /java-api-examples 下找到TTS流式合成的示例。你能再确认一下吗？

**Comment by csukuangfj** [comment]
支持的，有一个callback，你自己找下例子？


请不要把流式和callback混淆在一起。


你要边合成，边播放，不一定需要流式。

Python例子有callback，b站也有视频。

java你自己也可以写的。

你看我们的kotlin例子就有提供

**Comment by GeminiX369** [comment]
> 支持的，有一个callback，你自己找下例子？
> 
> 请不要把流式和callback混淆在一起。
> 
> 你要边合成，边播放，不一定需要流式。
> 
> Python例子有callback，b站也有视频。
> 
> java你自己也可以写的。
> 
> 你看我们的kotlin例子就有提供

jni中确实有定义generateWithCallback方法，只是java-api中没加上。我自己加了下，可以正常使用。感谢帮助！

**Comment by csukuangfj** [comment]
> GeminiX369

@GeminiX369 

我们在 #1176 里面，加了一个边合成、边播放的 java api 例子。

**Comment by GeminiX369** [comment]
> > GeminiX369
> 
> @GeminiX369
> 
> 我们在 #1176 里面，加了一个边合成、边播放的 java api 例子。

看到了，感谢你的辛苦工作！
