### ISSUE TITLE
请问是否可以返回 SenseVoice 的情感标签

### ISSUE THREAD

**Issue by wingjoezhou** [k2-fsa/sherpa-onnx#1184]
使用 sherpa-onnx  + SenceVoice 的onnx 
vad-with-non-streaming-asr.py  就是 使用 microphone 去 asr

现在是这样
<img width="339" alt="image" src="https://github.com/user-attachments/assets/327b5e4d-bf92-402c-8bad-d7d8e5fa9318">

原来 SenseVoice 是有情感输出的。
ban_emo_unk：禁用 emo_unk 标签，禁用后所有的句子都会被赋与情感标签。默认 False

是否可以像 SenseVoice 那样，能有开关，输出 情感标签？ 
毕竟， 情感输出也是 Sensevoice 的一大特色。谢谢。

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/sherpa-onnx/blob/646f99c8701981fa44dc7c5ba59ca5d26f320347/sherpa-onnx/csrc/offline-recognizer-sense-voice-impl.h#L38-L42

请自己修改这个代码，

你需要给
https://github.com/k2-fsa/sherpa-onnx/blob/646f99c8701981fa44dc7c5ba59ca5d26f320347/sherpa-onnx/csrc/offline-stream.h#L19
再加一些 fields

欢迎 PR

除了返回 emotion 标签，你还可以返回 language等信息

**Comment by wingjoezhou** [comment]
emmmm.... C 语言不会,  😭
 
期待其他大侠协助。

**Comment by 20246688** [comment]
期待ing

**Comment by fbzhong** [comment]
@csukuangfj 

你好，我看了一下，这里的 **src.tokens[i]** 并没有大于 24884 的token，是之前的某个地方被“吃”掉了么？麻烦指点一下，我再继续看看。

![CleanShot 2024-08-09 at 23 53 14@2x](https://github.com/user-attachments/assets/2ae0fa84-349e-4a94-86d3-2e7d805abb49)

![CleanShot 2024-08-09 at 23 52 48@2x](https://github.com/user-attachments/assets/03e00854-dee7-4e5e-9f84-21ea5f4a6c8d)


> https://github.com/k2-fsa/sherpa-onnx/blob/646f99c8701981fa44dc7c5ba59ca5d26f320347/sherpa-onnx/csrc/offline-recognizer-sense-voice-impl.h#L38-L42
> 
> 请自己修改这个代码，
>

**Comment by csukuangfj** [comment]
把38和48行的4，改成0即可

**Comment by fbzhong** [comment]
收到！我来改改，测试好了提个pr

**Comment by csukuangfj** [comment]
已通过 #1257 解决
