### ISSUE TITLE
Is tensorrt supported for transducer encoder?

### ISSUE THREAD

**Issue by Vergissmeinicht** [k2-fsa/sherpa-onnx#1189]
It seems that tensorrt is only supported for online model. And i try using trtexec to convert encoder onnx but it fails with log saying 
"terminate called after throwing an instance of 'std::out_of_range'
what(): Attribute not found: axes".
Since i have read about the tensorrt acceleration tutorial here: https://k2-fsa.github.io/sherpa/triton/trt/index.html, i wonder whether it is still supported?

**Comment by csukuangfj** [comment]
> Since i have read about the tensorrt acceleration tutorial here: https://k2-fsa.github.io/sherpa/triton/trt/index.html, i wonder

That is for another repo. Please see
https://github.com/k2-fsa/sherpa/tree/master/triton
