### ISSUE TITLE
TTS model (vits-melo-tts-zh_en) does not work

### ISSUE THREAD

**Issue by YonghaoHe** [k2-fsa/sherpa-onnx#1195]
![image](https://github.com/user-attachments/assets/2a50b908-3ddd-40ca-aa11-8da7deab7f28)
I follow the instructions to try TTS model vits-melo-tts-zh_en, but the script proposed the bug : 
    audio = tts.generate(args.text, sid=args.sid, speed=args.speed)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: invalid unordered_map<K, T> key
what's going on?

**Comment by csukuangfj** [comment]
Please post complete error logs

**Comment by YonghaoHe** [comment]
command: 
--vits-model=./vits-melo-tts-zh_en/model.onnx
--vits-lexicon=./vits-melo-tts-zh_en/lexicon.txt
--vits-tokens=./vits-melo-tts-zh_en/tokens.txt
--vits-dict-dir=./vits-melo-tts-zh_en/dict
--output-filename=./zh-en-3.wav
"它也支持繁体字. 我相信你們一定聽過愛迪生說過的這句話Genius is one percent inspiration and ninety-nine percent perspiration. "

error:
2024-07-31 16:13:47,214 INFO [offline-tts-play.py:327] Loading model ...
2024-07-31 16:13:49,712 INFO [offline-tts-play.py:329] Loading model done.
2024-07-31 16:13:49,712 INFO [offline-tts-play.py:337] Start generating ...
Traceback (most recent call last):
  File "D:\python_projects\robot-demo\tts\offline-tts-play.py", line 390, in <module>
    main()
  File "D:\python_projects\robot-demo\tts\offline-tts-play.py", line 339, in main
    audio = tts.generate(
            ^^^^^^^^^^^^^
IndexError: invalid unordered_map<K, T> key

@csukuangfj

**Comment by csukuangfj** [comment]
please post the complete command and logs

**Comment by csukuangfj** [comment]
by the way, you can  post screenshots.

**Comment by YonghaoHe** [comment]
this screenshot should contain all you need:
![image](https://github.com/user-attachments/assets/c046fde5-cde0-449d-9b1a-85b3510c36d1)

@csukuangfj

**Comment by YonghaoHe** [comment]
I checked the model files and they are correct. I think something wrong with encoding?

**Comment by csukuangfj** [comment]
Maybe you can use git bash or cmd to replace powershell and try again.

**Comment by csukuangfj** [comment]
make sure you are using the latest version of `sherpa-onnx`.
Please use
```
pip install -U sherpa-onnx
```
to install the latest version.

**Comment by csukuangfj** [comment]
@YonghaoHe Are you able to run it now?
