### ISSUE TITLE
Using the WSL2 runtime in Windows 11 prompts an issue with no input/output device found

### ISSUE THREAD

**Issue by andriyhuang** [k2-fsa/sherpa-onnx#1201]
As mentioned in the title, I use the Ubuntu 22.04.4 LTS distribution Linux system under WSL 2 in the Windows 11 Professional 23H2 version system as the running environment. After successfully running all the previous installations and downloading the pre-trained model, I will be reminded "no output device found" when performing the TTS conversion of the'vits-melo-tts- zh_en 'model, and then the audio file is not normally output to the specified directory. Is there a reserved solution for this situation?
![image](https://github.com/user-attachments/assets/322b8b6d-7910-4221-aa29-6c9be838e622)

**Comment by csukuangfj** [comment]
Could you try the python script?

WSL may have issues about accessing the speaker on Windows.

**Comment by csukuangfj** [comment]
> But I can't execute Python scripts in a WSL environment, right?

No, you can as long as you have installed python.

Python is known to work on linux, macos, and windows.

**Comment by andriyhuang** [comment]
> > But I can't execute Python scripts in a WSL environment, right?
> 
> No, you can as long as you have installed python.
> 
> Python is known to work on linux, macos, and windows.

@csukuangfj I tried to install and use it directly in the Windows environment and the Python environment in WSL, and the current Python-based operation is successful. Thanks for your help!

**Comment by csukuangfj** [comment]
Happy to hear it works for you.
