### ISSUE TITLE
Please add example for node using onnx-nemo-streaming

### ISSUE THREAD

**Issue by Eyalm321** [k2-fsa/sherpa-onnx#1205]
Hi! 

Please add example of how to implement onnx-nemo-streaming ? what is the binding? 

Thank you

**Comment by csukuangfj** [comment]
We already have a demo for streaming transducer.
Please see
https://github.com/k2-fsa/sherpa-onnx/blob/master/nodejs-addon-examples/test_asr_streaming_transducer.js

If you want to use a streaming NeMo transducer, say,
https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-nemo-streaming-fast-conformer-transducer-en-480ms.tar.bz2

please replace
https://github.com/k2-fsa/sherpa-onnx/blob/35c1b4a7a9376c6bb80ac461e1b2169be563f908/nodejs-addon-examples/test_asr_streaming_transducer.js#L13-L21
with the files from NeMo.

**Comment by Eyalm321** [comment]
Appreciate the fast comment!

Since its online should I still use VAD?

**Comment by csukuangfj** [comment]
No, you don't need a VAD for a streaming model.

The following is a VAD + Non-streaming NeMo model example
https://github.com/k2-fsa/sherpa-onnx/blob/master/nodejs-addon-examples/test_vad_asr_non_streaming_nemo_ctc_microphone.js
