### ISSUE TITLE
官方可否release一个win版的Restful的API server

### ISSUE THREAD

**Issue by syumi-1** [k2-fsa/sherpa-onnx#1207]
比如调用 http://127.0.0.1:1234/tts?text=xxxxxxxxxxxx&rate=1.0&id=1 之类的get方法能直接返回一个wav文件 这样就可以方便的供三方软件调用了, 可以尝试用[cpp-httplib](https://github.com/yhirose/cpp-httplib) 这个库 ,嘛 我就是希望示例程序能做到开箱即用就比较方便了

**Comment by csukuangfj** [comment]
我们提供了 tts 的 python api. 你自己可以进行第二次开发
