### ISSUE TITLE
keyword-spotter-from-microphone可以提供调试信息吗？急需帮助，求大佬帮忙。在线等。谢谢！！！

### ISSUE THREAD

**Issue by zzb181** [k2-fsa/sherpa-onnx#1213]
使用模型：sherpa-onnx-kws-zipformer-wenetspeech-3.3M-2024-01-01 (Chinese)
使用例子中的代码：python-api-examples/keyword-spotter-from-microphone.py
sherpa-onnx版本1.10.20 
python版本3.11
现象：连续说同一个关键词，前面很容易识别，有时说着说着就出现怎么说都无法识别的情况，换个关键词或重启又恢复正常。控制台什么信息也没有，查看API没有看到有设置debug的参数。程序也没有卡死。急需帮助，求大佬帮忙。在线等。谢谢！！！
1、能否提供debug信息，让我能看到，我当时说的关键词被模型识别成什么了。方便后续处理，如做拼音相似度比较
![image](https://github.com/user-attachments/assets/2fb0d72b-2ff8-4860-8a3f-344a2b5ac4ee)

2、请教下有没有支持模糊拼音的模型，1）、不带声调。如： 中国 -> ``zhong guo``。2）z=zh c=ch s=sh f=h an=ang in=ing ...

**Comment by csukuangfj** [comment]
> 现象：连续说同一个关键词，前面很容易识别，有时说着说着就出现怎么说都无法识别的情况，换个关键词或重启又恢复正常。控制台什么信息也没有，查看API没有看到有设置debug的参数。程序也没有卡死。急需帮助，求大佬帮忙。在线等。谢谢！！！

请提供完整的命令，以及运行时，命令行的截图

**Comment by csukuangfj** [comment]
@zzb181 在线等回复

**Comment by zzb181** [comment]
[sherpa-onnx.zip](https://github.com/user-attachments/files/16487237/sherpa-onnx.zip)
![image](https://github.com/user-attachments/assets/2287cbfa-7f8b-4e84-be55-5d350a9c77ce)
@csukuangfj 谢谢。我改了下源代码，自己加了debug参数，有返回模型的信息了，但还是无法看到我当时说的关键词被模型识别成什么了。

**Comment by csukuangfj** [comment]
> 但还是无法看到我当时说的关键词被模型识别成什么了。

输出的结果，就是模型识别到的，比如
`开始采集`, `采集数据` 等等，都是模型识别到的。

**Comment by zzb181** [comment]
我知道，这些是识别成功的，我想要看到识别不成功的，模型识别成什么了，比如关键词中有”张三“，说的时候，有可能发音不准，模型”张山“”张啥“什么的，我想知道模型识别的过程数据。

**Comment by csukuangfj** [comment]
> 我想要看到识别不成功的时候

这个看不到。kws 只会输出 keywords.txt 里面的结果。

**Comment by csukuangfj** [comment]
你可以试试通用的ASR

**Comment by zzb181** [comment]
我的需求一个可本地部署，识别速度快，占用资源小，在这些基础上追求准确率。可以只识别用户配置的关键词，只识别相似的声音也行，同音或相似音的也行。
我试过sherpa-onnx-kws-zipformer-wenetspeech-3.3M-2024-01-01。识别速度没有这个kws模型快。
这个kws模型的识别速度是真的快,又一点不占用资源，也符合我需求，可惜看不到识别不成功时的内容。要是可以拿到，我再比较下与关键词的拼音相似度，拿相似度最高的拿结果，就更好了。
我之前还试过vosk模型，识别速度和准确率和这个都没法比。
我还试过用最原型的，用DWT比较音频特征，效果不理想。自己手搓太难了，什么降噪，分段。。。一大堆

**Comment by longshiming** [comment]
我在android开发板上跑android的kws demo用英文的模型也会遇到你说的这种现象

**Comment by csukuangfj** [comment]
额， kws 只能识别 keywords.txt 里面指定的词。
（上面一句话，请阅读 3 遍，以便加深理解)

**Comment by longshiming** [comment]
> 使用模型：sherpa-onnx-kws-zipformer-wenetspeech-3.3M-2024-01-01 (Chinese) 使用例子中的代码：python-api-examples/keyword-spotter-from-microphone.py sherpa-onnx版本1.10.20 python版本3.11 现象：连续说同一个关键词，前面很容易识别，有时说着说着就出现怎么说都无法识别的情况，换个关键词或重启又恢复正常。控制台什么信息也没有，查看API没有看到有设置debug的参数。程序也没有卡死。急需帮助，求大佬帮忙。在线等。谢谢！！！ 1、能否提供debug信息，让我能看到，我当时说的关键词被模型识别成什么了。方便后续处理，如做拼音相似度比较 ![image](https://private-user-images.githubusercontent.com/163224602/354894146-2fb0d72b-2ff8-4860-8a3f-344a2b5ac4ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4Mjk4NjksIm5iZiI6MTcyMjgyOTU2OSwicGF0aCI6Ii8xNjMyMjQ2MDIvMzU0ODk0MTQ2LTJmYjBkNzJiLTJmZjgtNDg2MC04YTNmLTM0NGEyYjVhYzRlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQwMzQ2MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YmFjZjVlNzAyM2FiOWEyNGMxNzFjMDk4MTY1M2U0Yzg1YjZiYjg0NmMxOWU4MzJiYzk3YzE3OGQxMzJhYTMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Cct8d0gPGb8L5C0NAQJBenCkC64mWx3Y5O0NlOzYuuM)
> 
> 2、请教下有没有支持模糊拼音的模型，1）、不带声调。如： 中国 -> `zhong guo`。2）z=zh c=ch s=sh f=h an=ang in=ing ...

我在android开发板上跑android的kws demo用英文的模型也会遇到你说的这种现象，同一个录音播放同一个关键词，有时就突然一直识别不了了，前面都是能正常识别到的。这个应该是kws源码的bug。

**Comment by pkufool** [comment]
> > 使用模型：sherpa-onnx-kws-zipformer-wenetspeech-3.3M-2024-01-01 (Chinese) 使用例子中的代码：python-api-examples/keyword-spotter-from-microphone.py sherpa-onnx版本1.10.20 python版本3.11 现象：连续说同一个关键词，前面很容易识别，有时说着说着就出现怎么说都无法识别的情况，换个关键词或重启又恢复正常。控制台什么信息也没有，查看API没有看到有设置debug的参数。程序也没有卡死。急需帮助，求大佬帮忙。在线等。谢谢！！！ 1、能否提供debug信息，让我能看到，我当时说的关键词被模型识别成什么了。方便后续处理，如做拼音相似度比较 ![image](https://private-user-images.githubusercontent.com/163224602/354894146-2fb0d72b-2ff8-4860-8a3f-344a2b5ac4ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4Mjk4NjksIm5iZiI6MTcyMjgyOTU2OSwicGF0aCI6Ii8xNjMyMjQ2MDIvMzU0ODk0MTQ2LTJmYjBkNzJiLTJmZjgtNDg2MC04YTNmLTM0NGEyYjVhYzRlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQwMzQ2MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YmFjZjVlNzAyM2FiOWEyNGMxNzFjMDk4MTY1M2U0Yzg1YjZiYjg0NmMxOWU4MzJiYzk3YzE3OGQxMzJhYTMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Cct8d0gPGb8L5C0NAQJBenCkC64mWx3Y5O0NlOzYuuM)
> > 2、请教下有没有支持模糊拼音的模型，1）、不带声调。如： 中国 -> `zhong guo`。2）z=zh c=ch s=sh f=h an=ang in=ing ...
> 
> 我在android开发板上跑android的kws demo用英文的模型也会遇到你说的这种现象，同一个录音播放同一个关键词，有时就突然一直识别不了了，前面都是能正常识别到的。这个应该是kws源码的bug。

这个是已知问题，命令行不太好复现，debug 难度比较大，一直还未解决。

**Comment by pkufool** [comment]
> 我知道，这些是识别成功的，我想要看到识别不成功的时候，模型识别成什么了，比如关键词中有”张三“，说的时候，有可能发音不准，模型识别成”张山“”张啥“什么的，我想知道模型识别的过程数据。现在只能输出识别成功的结果数据。如果识别不成功的数据也可以输出，我可以把”张啥“也设置成关键词。

你可以把相似的发音加到 keywords.txt 里面，映射到同一个词。关键词系统只会识别给定的词和其他，没法返回你说的相似音结果。

**Comment by zzb181** [comment]
> > 我知道，这些是识别成功的，我想要看到识别不成功的时候，模型识别成什么了，比如关键词中有”张三“，说的时候，有可能发音不准，模型识别成”张山“”张啥“什么的，我想知道模型识别的过程数据。现在只能输出识别成功的结果数据。如果识别不成功的数据也可以输出，我可以把”张啥“也设置成关键词。
> 
> 你可以把相似的发音加到 keywords.txt 里面，映射到同一个词。关键词系统只会识别给定的词和其他，没法返回你说的相似音结果。

1、我就是想把“相似”的发音加进来 keywords.txt 里面，但是每个人说出来的“相似”音还会有很大区别，而且就算是同一个人，因为环境，情绪等因素说同一个词，也会有很大区别，所以最好的办法是在配制关键词时，可以让用户用这个模型识别的结果来做关键词。用户说什么就设置什么成关键词，而不是让用户打字设置关键词，因为用户也不知道他说的张三能被模型识别成什么。如果可以让用户自己“录”几个关键词，我们后期再做这些关键词拼音的模糊匹配处理。针对这个用户的识别率一定会提高很多。
2、唤醒词，指令词识别不要根据语境语意推理训练，因唤醒词不要同义词，只要同音近音就行。
3、我今天又找了一个模型：speech_paraformer-tiny_asr_kws-zh-16k-vocab192-online，这个模型是直接返回拼音的，不过资源占用太大了，我转onxx后，funasr-onxx不支持返回的拼音处理，报错了。
4、现在尝试用sherpa-onnx-streaming-zipformer-zh-14M-2023-02-23，为了能有kws模型的响应速度，我只能设置enable_endpoint_detection=False，让模型听到什么就马上返回，我在后期处理，不过这个模型本身识别率不高，不知道后面效果怎么样。

**Comment by pkufool** [comment]
> 用户说什么就设置什么成关键词，而不是让用户打字设置关键词，因为用户也不知道他说的张三能被模型识别成什么。如果可以让用户自己“录”几个关键词，我们后期再做这些关键词拼音的模糊匹配处理。针对这个用户的识别率一定会提高很多。

**Comment by pkufool** [comment]
@zzb181  你得先搞清楚你想要一个怎样的场景，然后才看怎么样的模型才能满足你的需求。

**Comment by HuntZhaozq** [comment]
> > > 我知道，这些是识别成功的，我想要看到识别不成功的时候，模型识别成什么了，比如关键词中有”张三“，说的时候，有可能发音不准，模型识别成”张山“”张啥“什么的，我想知道模型识别的过程数据。现在只能输出识别成功的结果数据。如果识别不成功的数据也可以输出，我可以把”张啥“也设置成关键词。
> > 
> > 
> > 你可以把相似的发音加到 keywords.txt 里面，映射到同一个词。关键词系统只会识别给定的词和其他，没法返回你说的相似音结果。
> 
> 1、我就是想把“相似”的发音加进来 keywords.txt 里面，但是每个人说出来的“相似”音还会有很大区别，而且就算是同一个人，因为环境，情绪等因素说同一个词，也会有很大区别，所以最好的办法是在配制关键词时，可以让用户用这个模型识别的结果来做关键词。用户说什么就设置什么成关键词，而不是让用户打字设置关键词，因为用户也不知道他说的张三能被模型识别成什么。如果可以让用户自己“录”几个关键词，我们后期再做这些关键词拼音的模糊匹配处理。针对这个用户的识别率一定会提高很多。 2、唤醒词，指令词识别不要根据语境语意推理训练，因唤醒词不要同义词，只要同音近音就行。 3、我今天又找了一个模型：speech_paraformer-tiny_asr_kws-zh-16k-vocab192-online，这个模型是直接返回拼音的，不过资源占用太大了，我转onxx后，funasr-onxx不支持返回的拼音处理，报错了。 4、现在尝试用sherpa-onnx-streaming-zipformer-zh-14M-2023-02-23，为了能有kws模型的响应速度，我只能设置enable_endpoint_detection=False，让模型听到什么就马上返回，我在后期处理，不过这个模型本身识别率不高，不知道后面效果怎么样。

老哥好，我遇到的问题和你相似，请问你最后是怎么解决的呀？ @zzb181

**Comment by csukuangfj** [comment]
https://k2-fsa.github.io/sherpa/onnx/pretrained_models/online-ctc/zipformer-ctc-models.html#sherpa-onnx-streaming-zipformer-small-ctc-zh-int8-2025-04-01-chinese

这个模型比 14M 那个模型的准确率更高.

**Comment by HuntZhaozq** [comment]
> https://k2-fsa.github.io/sherpa/onnx/pretrained_models/online-ctc/zipformer-ctc-models.html#sherpa-onnx-streaming-zipformer-small-ctc-zh-int8-2025-04-01-chinese
> 
> 这个模型比 14M 那个模型的准确率更高.

这个模型有时候会漏字，请问是什么原因呀，如何优化？

**Comment by csukuangfj** [comment]
信息有限，没法提供帮助。

**Comment by HuntZhaozq** [comment]
> 信息有限，没法提供帮助。

比如涂胶槽，非常难识别出后面2个字

**Comment by Andrewzzz** [comment]
https://github.com/k2-fsa/sherpa-onnx/issues/634#issuecomment-1978107257
@pkufool 大佬你好，这个issue想要的可能是类似这里你提出的同时加入前后鼻音的优化方法。对于kws未识别的音频，我是不是应该换用 [wenetspeech](https://k2-fsa.github.io/sherpa/onnx/pretrained_models/offline-transducer/zipformer-transducer-models.html#pkufool-icefall-asr-zipformer-wenetspeech-20230615-chinese) 看一下 ASR 被识别为什么拼音了，然后再加入对应的关键字？

**Comment by Jasmin-Fun** [comment]
> > > 使用模型：sherpa-onnx-kws-zipformer-wenetspeech-3.3M-2024-01-01 (Chinese) 使用例子中的代码：python-api-examples/keyword-spotter-from-microphone.py sherpa-onnx版本1.10.20 python版本3.11 现象：连续说同一个关键词，前面很容易识别，有时说着说着就出现怎么说都无法识别的情况，换个关键词或重启又恢复正常。控制台什么信息也没有，查看API没有看到有设置debug的参数。程序也没有卡死。急需帮助，求大佬帮忙。在线等。谢谢！！！ 1、能否提供debug信息，让我能看到，我当时说的关键词被模型识别成什么了。方便后续处理，如做拼音相似度比较 ![image](https://private-user-images.githubusercontent.com/163224602/354894146-2fb0d72b-2ff8-4860-8a3f-344a2b5ac4ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4Mjk4NjksIm5iZiI6MTcyMjgyOTU2OSwicGF0aCI6Ii8xNjMyMjQ2MDIvMzU0ODk0MTQ2LTJmYjBkNzJiLTJmZjgtNDg2MC04YTNmLTM0NGEyYjVhYzRlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQwMzQ2MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YmFjZjVlNzAyM2FiOWEyNGMxNzFjMDk4MTY1M2U0Yzg1YjZiYjg0NmMxOWU4MzJiYzk3YzE3OGQxMzJhYTMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Cct8d0gPGb8L5C0NAQJBenCkC64mWx3Y5O0NlOzYuuM)
> > > 2、请教下有没有支持模糊拼音的模型，1）、不带声调。如： 中国 -> `zhong guo`。2）z=zh c=ch s=sh f=h an=ang in=ing ...
> > 
> > 
> > 我在android开发板上跑android的kws demo用英文的模型也会遇到你说的这种现象，同一个录音播放同一个关键词，有时就突然一直识别不了了，前面都是能正常识别到的。这个应该是kws源码的bug。
> 
> 这个是已知问题，命令行不太好复现，debug 难度比较大，一直还未解决。

@pkufool 关于这个突然不能识别的问题，想知道大概是什么原因呢，有没有暂时规避或改善的方法

**Comment by csukuangfj** [comment]
都几个月了，请问你是用master还能复现吗
