### ISSUE TITLE
Call KWS and ASR

### ISSUE THREAD

**Issue by kyn817046** [k2-fsa/sherpa-onnx#1228]
I want to call at the same time KWS and ASR, a microphone input data, but the two model receiving data are SherpaOnnxOnlineStreamAcceptWaveform () function, how to do it, or have any other ideas, looking forward to your reply, thank you!

**Comment by csukuangfj** [comment]
You can send the same audio samples to both the ASR stream and the KWS stream in two consecutive function calls.

**Comment by kyn817046** [comment]
Do we have similar routines? I can run both programs separately now. thank you!

**Comment by csukuangfj** [comment]
We have already provided APIs for you . Please combine them by yourself.

**Comment by kyn817046** [comment]
I received the microphone in the callback function, the use of mutex, condition variables and copy data, other calls did not run successfully, I go to debug again, thank you

**Comment by csukuangfj** [comment]
By the way, you can post your code if you are not sure what to do.
