### ISSUE TITLE
Whisper recognizer creation is very slow

### ISSUE THREAD

**Issue by thewh1teagle** [k2-fsa/sherpa-onnx#1239]
I tested with 
https://github.com/k2-fsa/sherpa-onnx/blob/master/c-api-examples/whisper-c-api.c
On medium model.

```console
Time taken for create recognizer: 24.27 seconds
Decoded text:  After early nightfall the yellow lamps would light up here and there the squalid quarter of the brothels.
Time taken: 17.23 seconds
Decoded text:  After early nightfall the yellow lamps would light up here and there the squalid quarter of the brothels.
```

In whisper.cpp it loads the model in 5 seconds or less.

**Comment by csukuangfj** [comment]
I suggest that you use int8.onnx.

That is an issue of onnxruntime, not sherpa-onnx.

**Comment by thewh1teagle** [comment]
Thanks! now with int8 medium model loads in 13 seconds.
