### ISSUE TITLE
Publish on accrescent

### ISSUE THREAD

**Issue by jujubeja** [k2-fsa/sherpa-onnx#1244]
https://github.com/accrescent/accrescent
https://github.com/accrescent/parcelo Accrescent developer console

* Only arm64-v8a version

**Comment by csukuangfj** [comment]
Could you describe it in detail? Sorry that I cannot understand what you want.

**Comment by csukuangfj** [comment]
You can find all pre-built Android APKs at
https://k2-fsa.github.io/sherpa/onnx/android/prebuilt-apk.html

**Comment by csukuangfj** [comment]
Please see
https://github.com/jing332/SherpaOnnxTtsEngineAndroid
if you want to use several models in a single APK.

Our APKs are just examples to show how to use our APIs.

Our main focus is to provide users APIs, not develop APPs.
