### ISSUE TITLE
wasm kws 报错

### ISSUE THREAD

**Issue by kangkang721** [k2-fsa/sherpa-onnx#1245]
![image](https://github.com/user-attachments/assets/083e23d1-cc5d-4214-ac39-6f81529375b4)

**Comment by csukuangfj** [comment]
![b790d02f85c653d6119b67331df8065e](https://github.com/user-attachments/assets/4d466381-f21b-4c25-8e26-86f64baf5bb4)

请看这个图。你提供的 log 太有限，请大方一点.

**Comment by kangkang721** [comment]
你好，抱歉，我再详细说明一下具体的问题。
我下载下了本项目的源代码，在本地的 Debian GNU/Linux 12 环境下进行了 
![image](https://github.com/user-attachments/assets/b0db0b4d-388b-4842-b4db-55bf1a4823f6)
build-wasm-simd-kws.sh 模块的编译，编译也是成功的。
![image](https://github.com/user-attachments/assets/6bedad9f-30e7-4847-a4d2-98c8878dce10)
于是我就把这个项目进行部署跑起来了，然后进行访问，然后报上面的错误。

**Comment by csukuangfj** [comment]
It works perfectly on my side.
<img width="1345" alt="Screenshot 2024-08-14 at 15 28 15" src="https://github.com/user-attachments/assets/307bb6d4-f0a1-4c19-9bdf-904a53b1f6e8">

**Comment by csukuangfj** [comment]
> ![image](https://private-user-images.githubusercontent.com/39193387/356977439-083e23d1-cc5d-4214-ac39-6f81529375b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MjA4NDEsIm5iZiI6MTcyMzYyMDU0MSwicGF0aCI6Ii8zOTE5MzM4Ny8zNTY5Nzc0MzktMDgzZTIzZDEtY2M1ZC00MjE0LWFjMzktNmY4MTUyOTM3NWI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA3MjkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkM2QxZGU2Mjk4MjdiYWY2MWVlZmZkZTZkYjRkN2U1ZmQ0ZGIyNjJiMzIxMjYwYmYwMzkzYjc4YjkwMTA1MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Owg83OPtbBMtcjkXgEj-Ce7dNyCtUCsYbtchFlMIA1s)

请大方一点，不要有保留，请把全部的 log 发过来.

**Comment by kangkang721** [comment]
![image](https://github.com/user-attachments/assets/d13dae18-384e-4a30-b4af-73345da558a4)
![image](https://github.com/user-attachments/assets/990929cc-64ce-41bd-9275-4a9c0e2099ea)
![image](https://github.com/user-attachments/assets/21c3590b-1f63-4386-abbf-fe13bc916905)
![image](https://github.com/user-attachments/assets/b64465ee-8a81-4b31-9cf8-eec4eaee56e4)

**Comment by kangkang721** [comment]
![image](https://github.com/user-attachments/assets/f08074b0-25ab-4aaf-bbf6-8812b46654b9)

**Comment by csukuangfj** [comment]
![357730637-b64465ee-8a81-4b31-9cf8-eec4eaee56e4](https://github.com/user-attachments/assets/e08889e6-8dc7-4b81-8815-2a99ba0d6a92)


Log  全了，就好办啦！

请用最新的代码测试。

**Comment by csukuangfj** [comment]
友情提示，默认的例子，只能识别下面两个词
https://github.com/k2-fsa/sherpa-onnx/blob/62c4d4ab624007f2d44d9f11f2faa16729ecd427/wasm/kws/sherpa-onnx-kws.js#L292-L293

如果你想添加更多的词，请看文档里 keyword spotting 章节.

**Comment by kangkang721** [comment]
因为新版本不可以用我才降的版本
![image](https://github.com/user-attachments/assets/0c8a2fe0-e717-414c-976c-12cbd407c19c)
这个是master分支编译的

**Comment by csukuangfj** [comment]
> It works perfectly on my side. <img alt="Screenshot 2024-08-14 at 15 28 15" width="1345" src="https://private-user-images.githubusercontent.com/5284924/357716792-307bb6d4-f0a1-4c19-9bdf-904a53b1f6e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MjQxNDUsIm5iZiI6MTcyMzYyMzg0NSwicGF0aCI6Ii81Mjg0OTI0LzM1NzcxNjc5Mi0zMDdiYjZkNC1mMGExLTRjMTktOWJkZi05MDRhNTNiMWY2ZTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTRUMDgyNDA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzljNWNmOTNkM2MxNjliM2ZkMTkwOTgyZjc1OGY2Y2U0NjBkNDIyNDhjYzU4YTc3MDIzZTVlNjdmNzZlZWNlMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Y2J2KxjhzKmQatdvCYMNbSV-7hyXglPoSwGspF0QnCs">

我刚刚测试过， master 代码没问题的.

**Comment by csukuangfj** [comment]
> 因为新版本不可以用我才降的版本

能解详细解释下，为什么不可以用么？

**Comment by kangkang721** [comment]
https://ideal-space-journey-vgjv5xprxpp2wq9q-33759.app.github.dev/

**Comment by csukuangfj** [comment]
请贴 log

**Comment by kangkang721** [comment]
![image](https://github.com/user-attachments/assets/569dbbae-e67b-47f8-b767-c565dae2f62e)
![image](https://github.com/user-attachments/assets/be11d3e6-958d-4c09-8ff5-993343564e88)
![image](https://github.com/user-attachments/assets/7c71f52b-6f23-431f-a34e-2e30452c7558)
这个是log，我编译的时候一切正常

**Comment by csukuangfj** [comment]
看一下 sherpa-onnx/wasm/kws/assets 目录下有些什么文件 以及各个文件的 md5 哈希值

**Comment by kangkang721** [comment]
![image](https://github.com/user-attachments/assets/689bb63f-9c5c-4f4d-83ae-d2dab539bed3)

**Comment by csukuangfj** [comment]
请描述你的 tokens.txt 从哪里得到的。

并且，请把 tokens.txt 的前10行发过来。

**Comment by kangkang721** [comment]
<blk> 0
<sos/eos> 1
<unk> 2
S 3
T 4
▁THE 5
▁A 6
▁TO 7
▁AND 8
N 9

**Comment by kangkang721** [comment]
![image](https://github.com/user-attachments/assets/b195d65e-9cdc-4972-9511-02b94190a85d)

**Comment by csukuangfj** [comment]
https://k2-fsa.github.io/sherpa/onnx/kws/pretrained_models/index.html#sherpa-onnx-kws-zipformer-wenetspeech-3-3m-2024-01-01-chinese

请去这里下载正确的文件.

**Comment by csukuangfj** [comment]
请删掉你 assets 里面的文件，然后用上面链接下载的文件。

**Comment by csukuangfj** [comment]
现在好了没

**Comment by csukuangfj** [comment]
太棒啦！
