### ISSUE TITLE
How can I use japanese as the language for keyword spotting 

### ISSUE THREAD

**Issue by itsrealkk** [k2-fsa/sherpa-onnx#1250]
Hi, i have tried the Chinese wenet model, it's awesome. 

Btw, I need a japanese model for kws. I have noticed that `sherpa-onnx-zipformer-ja-reazonspeech-2024-08-01` model. However, this model is so large.

How can I train a 3.3M ja model and use japanese for kws

**Comment by csukuangfj** [comment]
Currently, we don't have a KWS model for Japanese.

You can train it by yourself.

**Comment by csukuangfj** [comment]
> How can I train a 3.3M ja model and use japanese for kws

Please refer to how we train a KWS English model or KWS Chinese model in icefa..
