### ISSUE TITLE
offline model ，how do I configure the device id？

### ISSUE THREAD

**Issue by laochen** [k2-fsa/sherpa-onnx#1256]
Hello，Why doesn't offline-model-config.h use the ProviderConfig parameter like online-model-config.h? offline-model-config.h only has the provider parameter. In this case, when the provider is 'cuda', how do I configure the device id?

**Comment by csukuangfj** [comment]
Please use the environment variable CUDA_VISIBLE_DEVICES.

For instance, if you have 8 GPUs and if you want to use GPU 5 with sherpa-onnx, you can run
```
 export CUDA_VISIBLE_DEVICES="5"
```
