### ISSUE TITLE
[Feature Request] Add support to onnxruntime-wasm-simd-threaded for better performance in TTS

### ISSUE THREAD

**Issue by xqe2011** [k2-fsa/sherpa-onnx#1259]
The speed of TTS when running tts model in wasm is too low. I tested for 5 rounds, average value of RTF is `4.3`. I try to set numThreads to any value above `1`, it crashed when initalized the runtime. It seems that this library depends on an `onnxruntime-wasm` without multi-threading support, maybe we can change it to the version supports this feature for faster responseding.

Testing platform
4-cores Intel I7 Macbook Pro 2020
16GB RAM
Access the demo by localhost, web page, not node.js
Using Chrome 127
Mandarin

Exception Logs
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/4f0b781c-55fe-463f-ba69-efc8493f9eed">

TTS在wasm环境下运行速度缓慢。我测试了 5 轮，RTF 的平均值是 `4.3`。我尝试将 numThreads 设置为任何大于 `1` 的值但是崩溃了。看上去是因为依赖了一个不支持多线程的 `onnxruntime-wasm`，也许可以换成支持这个功能的库来提升速度。

**Comment by csukuangfj** [comment]
请换一个英文模型进行测试。

目前无法支持多线程
