### ISSUE TITLE
[BUG] The herpa-onnx-wasm-main-asr.js has serious errors

### ISSUE THREAD

**Issue by 0xlau** [k2-fsa/sherpa-onnx#1262]
The file `sherpa-onnx-wasm-main-asr.js ` from [web-assembly-asr-sherpa-onnx-zh-en-paraformer](https://huggingface.co/spaces/k2-fsa/web-assembly-asr-sherpa-onnx-zh-en-paraformer/tree/main) has serious errors.

When I use the file protocol , `file://` , to read the data file, the script will definitely fail to run.

It is may trigger by below

<img width="817" alt="image" src="https://github.com/user-attachments/assets/5e2ae9b5-8bfe-45fa-9516-308d5ac1267f">

And this is my solution.

 
![img_v3_02dq_781f7fca-69b1-4e3e-8634-be8d516fb44g](https://github.com/user-attachments/assets/df533076-34eb-4f43-a5d9-8139c52d2407)

**Comment by csukuangfj** [comment]
The space is running at present without errors.


Do you have any issues if you don't change any code?

**Comment by 0xlau** [comment]
It has been confirmed that the issue is caused by emscripten.
https://github.com/emscripten-core/emscripten/pull/22283

**Comment by csukuangfj** [comment]
> It has been confirmed that the issue is caused by emscripten. [emscripten-core/emscripten#22283](https://github.com/emscripten-core/emscripten/pull/22283)

Have you tested the merged changes with sherpa-onnx? @0xlau

**Comment by 0xlau** [comment]
Yes. I tested the merged changes with sherpa-onnx. It works fine in electron now.

**Comment by csukuangfj** [comment]
So can it be closed now?
