### ISSUE TITLE
paraformer如何启用热词

### ISSUE THREAD

**Issue by WanwanLinLin** [k2-fsa/sherpa-onnx#1274]
我看了好多遍文档，无论是e2e还是websocket都没有说paraformer如何启用热词，我想知道在这个项目里paraformer相关模型是否支持热词？有的话麻烦发一下相关链接

**Comment by yuyun2000** [comment]
所以他不支持热词~

**Comment by WanwanLinLin** [comment]
![image](https://github.com/user-attachments/assets/7c19e314-0b6f-46ed-8fac-5aa344762ac9)
sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20模型识别中英文混合语句的效果不好，本来应该是 祝你生日快乐happy birthday to you，他识别成了 祝你生日快乐嗨皮波，不然我也不会想着用 paraformer模型

**Comment by yuyun2000** [comment]
是的 这个中英混的英文很弱

**Comment by csukuangfj** [comment]
无法支持.
