### ISSUE TITLE
[Flutter] Can not work on iOS Simulator

### ISSUE THREAD

**Issue by hantrungkien** [k2-fsa/sherpa-onnx#1283]
I got a error when tap on the Generate button from the example:

`
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libsherpa-onnx-c-api.dylib': dlopen(libsherpa-onnx-c-api.dylib, 0x0001): tried: '/Library/Developer/CoreSimulator/Volumes/iOS_21F79/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.5.simruntime/Contents/Resources/RuntimeRootlibsherpa-onnx-c-api.dylib' (no such file), '/Library/Developer/CoreSimulator/Volumes/iOS_21F79/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.5.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libsherpa-onnx-c-api.dylib' (no such file), '/usr/lib/swift/libsherpa-onnx-c-api.dylib' (no such file, not in dyld cache), '/Users/kienht/Library/Developer/CoreSimulator/Devices/5E910182-EC7E-48A6-99AC-E2FA3CBDF9D4/data/Containers/Bundle/Application/91543D27-FF1F-4554-B087-036C4127DDB2/Runner.app/Frameworks/libsherpa-onnx-c-api.dylib' (mach-o file (/Users/kienht/Library/Developer/CoreSimulator/Devices/5E910182-EC7E-48A6-99AC-E2FA3CBDF9D4/data/<…>
`

**Comment by csukuangfj** [comment]
The fix is:

Step 1. Run
https://github.com/k2-fsa/sherpa-onnx/blob/master/build-ios-shared.sh

You have to build the lib for simulator by yourself. The lib in the package published to pub.dev is for iOS Phone only.

The following is a screenshot after running the above script

![48d5179b1d8d3dddb613f581c91027d5](https://github.com/user-attachments/assets/dea37b5b-2d30-4f4e-91f3-98ef2ff1483a)

Note that there are libs for simulator arm64 and for simulator x86_64. You need to select the correct one by yourself.

Step 2. Use the generated lib for simulator from step 1 to replace the one you downloaded from pub.dev

For instance, find the `.dart_tool`  directory in your project,
![image](https://github.com/user-attachments/assets/425d8bc4-d4dd-425d-ba36-35f0d80987b8)

Open `package_config.json` from `.dart_tool`:
![image](https://github.com/user-attachments/assets/54295561-5c56-4131-af4d-29b30f9c6441)


Locate where `sherpa-onnx-ios` is saved from `package_config.json`:

![image](https://github.com/user-attachments/assets/0307baa9-1a21-4cea-a3bc-50e74e77b193)


In the above screenshot,  you can find the directory for the package `sherpa_onnx_ios`

![06849c41b22423bae2a3275ead5bd72f](https://github.com/user-attachments/assets/09878125-33e2-4283-ba61-d3e4225aeb59)

![image](https://github.com/user-attachments/assets/70f723e2-ceb2-4fda-a13f-0c7ae5402456)


Now copy the `libonnxruntime.a` and `libsherpa-onnx-c-api.dylib` from step1 to the above directory
and everything should work as expected.

**Comment by csukuangfj** [comment]
@hantrungkien Does it work now?

**Comment by hantrungkien** [comment]
@csukuangfj Many thanks. I'm doing on other higher priority tasks for our release day. I will back to it on tonight or tomorrow and give you a feedback. Thanks again 🙏

**Comment by hantrungkien** [comment]
@csukuangfj Sorry for late. I want to report about your way, it works. Many many thanks 🙏

**Comment by csukuangfj** [comment]
Great to hear it fixes your issue!

**Comment by keyur2maru** [comment]
@csukuangfj Thanks for the solution, fixed the same issue for me as well. But I wonder if combining IOS and IOS-simulator into a single binary would be possible? Or is there another way to easily run on a simulator as well as a real device without having to change these libs?

**Comment by csukuangfj** [comment]
yes, it is possible.

The problem is that pub.dev forbids uploading packages more than 100MB

If they were combined, it would be larger than 100MB. The main contribution to the file.size comes from onnxruntime

**Comment by keyur2maru** [comment]
> yes, it is possible.
> 
> The problem is that pub.dev forbids uploading packages more than 100MB
> 
> If they were combined, it would be larger than 100MB. The main contribution to the file.size comes from onnxruntime

Can you please share the method to combine them?
If you can do so, I would create a fork and point my application's pubspec.yaml to my fork allowing for easier testing between real and simulated device.

**Comment by csukuangfj** [comment]
One of the methods is to create a `framework` or a `xcframework`.

We currently don't have code for that, but it is feasible. You need to figure out how to do that by yourself.

**Comment by keyur2maru** [comment]
@csukuangfj Thanks for your suggestion, creating xcframework did the trick!
```
mkdir ios-simulator
lipo -create \                                     
    ios-arm64-simulator/libsherpa-onnx-c-api.dylib \
    ios-x86_64-simulator/libsherpa-onnx-c-api.dylib \
    -output ios-simulator/libsherpa-onnx-c-api.dylib

xcodebuild -create-xcframework \
    -library ios-arm64/libsherpa-onnx-c-api.dylib \
    -headers build/os64/install/include/ \
    -library ios-simulator/libsherpa-onnx-c-api.dylib \
    -headers build/simulator_arm64/install/include/ \
    -output SherpaOnnx.xcframework
```

I copied `SherpaOnnx.xcframework` and `sherpa-onnx/build-ios-shared/ios-onnxruntime/1.17.1/onnxruntime.xcframework` to `.pub-cache/hosted/pub.dev/sherpa_onnx_ios-1.10.27/ios` 

Also replaced the following line @ `.pub-cache/hosted/pub.dev/sherpa_onnx_ios-1.10.27/ios/sherpa_onnx_ios.podspec`
FROM
`s.ios.vendored_libraries = '*.dylib', '*.a'`
TO
`s.vendored_frameworks = 'SherpaOnnx.xcframework', 'onnxruntime.xcframework'`

Finally, added both frameworks to my application Runner
![image](https://github.com/user-attachments/assets/c75f3e39-d3a9-4a4e-aecc-f69969029b3b)

**Comment by hantrungkien** [comment]
@keyur2maru Thanks for your way but I got a error when building

```
Error (Xcode): 21 duplicate symbols
```

Could you please help me?

**Comment by csukuangfj** [comment]
> @keyur2maru Thanks for your way but I got a error when building
> 
> ```
> Error (Xcode): 21 duplicate symbols
> ```
> 
> Could you please help me?

Could you mind posting complete logs?

**Comment by hantrungkien** [comment]
@csukuangfj sorry, let's ignore the above error for now. I'm having trouble distributing the app via Testflight. I don't know if it's really necessary to add them to pubspec.yaml?

`vits-piper-en_US.py`
`vits-piper-en_US.sh`

```
 Error uploading ipa file: 
 [Application Loader Error Output]: [ContentDelivery.Uploader.600003BA41C0] Asset validation failed (90035) Invalid Signature. Code object is not signed at all. The file at path “Runner.app/Frameworks/App.framework/flutter_assets/assets/vits-piper-en_US-libritts_r-medium/vits-piper-en_US.py” is not properly signed. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose “Clean All” in Xcode, delete the “build” directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/support/code-signing. (ID: 86b90e2e-370a-4c09-b95a-8d7c7b19d27d)
[Application Loader Error Output]: [ContentDelivery.Uploader.600003BA41C0] Asset validation failed (90035) Invalid Signature. Code object is not signed at all. The file at path “Runner.app/Frameworks/App.framework/flutter_assets/assets/vits-piper-en_US-libritts_r-medium/vits-piper-en_US.sh” is not properly signed. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose “Clean All” in Xcode, delete the “build” directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/support/code-signing. (ID: bf49fe73-f655-44ac-aa56-9d41e884c5cc)
```
<img width="1195" alt="Screenshot 2024-10-25 at 15 14 43" src="https://github.com/user-attachments/assets/742f9e27-0c3c-4661-893f-83dd06f3867f">

**Comment by csukuangfj** [comment]
please just delete them. You don't need them.

**Comment by hantrungkien** [comment]
@csukuangfj I was able to upload to testflight but it was rejected. Please help me

<img width="687" alt="Screenshot 2024-10-25 at 15 53 43" src="https://github.com/user-attachments/assets/008c9744-4cd9-4123-a425-7a7c5c6cbda1">

**Comment by hantrungkien** [comment]
@csukuangfj If I add a both framework like as @keyur2maru 's way I got error `Error (Xcode): 21 duplicate symbols`. Here is full log:
<img width="555" alt="Screenshot 2024-10-25 at 17 40 06" src="https://github.com/user-attachments/assets/81f3f29c-36a8-4b07-91bd-b035615d127c">
<img width="695" alt="Screenshot 2024-10-25 at 17 39 24" src="https://github.com/user-attachments/assets/91b5e822-39c4-4d35-8777-1139a92a74c0">

**Comment by hantrungkien** [comment]
@csukuangfj I tried like https://github.com/k2-fsa/sherpa-onnx/issues/1172#issuecomment-2261064626 but still can not distribute via testflight. Please help me!

**Comment by csukuangfj** [comment]
sorry, the logs are not informative

**Comment by hantrungkien** [comment]
@csukuangfj After 1 day research, I found a reason is:

```
Dynamic libraries outside of a framework bundle, which typically have the file extension .dylib, are not supported on iOS.
```
But I still don't found a solution...

**Comment by csukuangfj** [comment]
Please use the latest release v1.10.31

You don't need to change any code.
