### ISSUE TITLE
Diarization / unknown speaker 

### ISSUE THREAD

**Issue by renaudcerrato** [k2-fsa/sherpa-onnx#1289]
Is it possible to identify unknown speakers (i.e without registering) and get something like speaker_1, speaker_2, speaker_3?

**Comment by csukuangfj** [comment]
Please see our example.at

https://github.com/k2-fsa/sherpa-onnx/blob/master/python-api-examples/speaker-identification-with-vad-dynamic.py

**Comment by renaudcerrato** [comment]
Thanks! Will take a look!

**Comment by csukuangfj** [comment]
@renaudcerrato 

We have supported speaker diarization.

**Comment by renaudcerrato** [comment]
Thanks @csukuangfj! I didn't had the time yet to try to play with. What do you mean? Did you pushed new examples recently?

**Comment by csukuangfj** [comment]
Please see the usage example at

https://github.com/k2-fsa/sherpa-onnx/pull/1396#issuecomment-2401230284


More APIs for different languages are being added.

![Screenshot 2024-10-10 at 12 24 52](https://github.com/user-attachments/assets/f2ca43b4-e206-4b17-8bf7-91576e141acf)
