### ISSUE TITLE
How can I use CUDA in the python-api-examples/audio-tagging-from-a-file.py script?

### ISSUE THREAD

**Issue by rumi-taorui** [k2-fsa/sherpa-onnx#1292]
I successfully recognized the default parameters when I executed this script `python-api-examples/audio-tagging-from-a-file.py`. 
However, when I changed `provider="cuda"`, it always falls back to CPU. The log information tells me that I need to compile the GPU version. but I couldn't find the corresponding documentation. This is how I compiled it:

```
git clone https://github.com/k2-fsa/sherpa-onnx.git
cd sherpa-onnx
mkdir build
cd build
cmake .. -DSHERPA_ONNX_ENABLE_GPU=ON
make -j$(nproc)
export PYTHONPATH=/workspace/sherpa-onnx:$PYTHONPATH
```
but it doesn't work 

this is the log: 
```
AudioTaggingConfig(model=AudioTaggingModelConfig(zipformer=OfflineZipformerAudioTaggingModelConfig(model="./sherpa-onnx-zipformer-audio-tagging-2024-04-09/model.onnx"), ced="", num_threads=1, debug=True, provider="cuda"), labels="./sherpa-onnx-zipformer-audio-tagging-2024-04-09/class_labels_indices.csv", top_k=5)
/project/sherpa-onnx/csrc/session.cc:GetSessionOptionsImpl:167 Please compile with -DSHERPA_ONNX_ENABLE_GPU=ON. Available providers: CPUExecutionProvider, . Fallback to cpu!
/project/sherpa-onnx/csrc/offline-zipformer-audio-tagging-model.cc:Init:66 url=https://github.com/k2-fsa/icefall/tree/master/egs/audioset/AT/zipformer
comment=zipformer2 audio tagger
version=1
model_author=k2-fsa
model_type=zipformer2
```
I'm not sure if this script can run on CUDA. If it can, how should I proceed?

@csukuangfj

**Comment by csukuangfj** [comment]
Please follow the doc to build sherpa-onnx with Python + GPU.

You didn't follow the doc, right?

For instance, you did not follow the doc to enable
```
  -DSHERPA_ONNX_ENABLE_PYTHON=ON \

```

**Comment by rumi-taorui** [comment]
i find the [doc](https://k2-fsa.github.io/sherpa/onnx/install/linux.html) here
I build it this way :

```
git clone https://github.com/k2-fsa/sherpa-onnx
cd sherpa-onnx
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DSHERPA_ONNX_ENABLE_GPU=ON ..
make -j6
export PYTHONPATH=/workspace/sherpa-onnx/build/bin:$PYTHONPATH
```
I can find an executable `sherpa-onnx` inside the `bin` directory
and then run this script, it show :
```
Traceback (most recent call last):
  File "/workspace/audio_tagging/run.py", line 6, in <module>
    import sherpa_onnx
ModuleNotFoundError: No module named 'sherpa_onnx'
```
I don't know how to use this package? can you help me again
@csukuangfj

**Comment by csukuangfj** [comment]
> i find the [doc](https://k2-fsa.github.io/sherpa/onnx/install/linux.html) here

That is the doc for Linux, not for Python.

Please follow the correct doc.

https://k2-fsa.github.io/sherpa/onnx/python/install.html#method-2-from-pre-compiled-wheels-cpu-cuda
