### ISSUE TITLE
声纹识别未匹配结果，直接调用释放对象方法会抛出内存访问异常错误

### ISSUE THREAD

**Issue by iAInNet** [k2-fsa/sherpa-onnx#1295]
https://github.com/k2-fsa/sherpa-onnx/blob/22c6f8139366dff2e67726bfa0d30e78a5fba7f1/sherpa-onnx/c-api/c-api.cc#L1367-L1403

目前的实现方式，要求调用方额外判断返回结果是否为空（nil，nullptr），不为空才能调用 SherpaOnnxSpeakerEmbeddingManagerFreeBestMatches 。如果不做这一层判断，在结果为空的时候直接调用，就会抛出内存访问异常的错误（SIGSEGV）。

但是事件检测的实现方式，就不会有这个问题： https://github.com/k2-fsa/sherpa-onnx/blob/22c6f8139366dff2e67726bfa0d30e78a5fba7f1/sherpa-onnx/c-api/c-api.cc#L1496-L1540 。可以直接调用释放删除方法。

对 C++ 不是很懂，想问声纹识别这个方法的实现能否在底层提供更加优雅的处理方式，避免上层调用必须做不为空判断。

**Comment by csukuangfj** [comment]
Please see
https://github.com/k2-fsa/sherpa-onnx/pull/1296
