### ISSUE TITLE
cannot use CUDA provider with go app

### ISSUE THREAD

**Issue by eschmidbauer** [k2-fsa/sherpa-onnx#1299]
when i set provider to "cuda" in my go app, i get the following error:
```
/project/sherpa-onnx/csrc/session.cc:GetSessionOptionsImpl:167 
Please compile with -DSHERPA_ONNX_ENABLE_GPU=ON. Available providers: CPUExecutionProvider, .
Fallback to cpu!
```

**Comment by csukuangfj** [comment]
1. Please either download pre-built GPU enabled sherpa-onnx shared libs from the release page or build sherpa-onnx from source with GPU support by following our doc

2. Use the libs from step 1 to replace those in the go package

3. make sure you have an NVIDIA GPU and you have installed cuda 11.8

4 Done

**Comment by eschmidbauer** [comment]
thanks for the info, i will try that out and report what i find

**Comment by eschmidbauer** [comment]
Thanks, i was able to get it working 
using shared library download 
```
wget 'https://github.com/k2-fsa/sherpa-onnx/releases/download/v1.10.23/sherpa-onnx-v1.10.23-linux-x64-gpu.tar.bz2'
tar xf sherpa-onnx-v1.10.23-linux-x64-gpu.tar.bz2
```
and  `conda` with `LD_LIBRARY_PATH=/lib/x86_64-linux-gnu:sherpa-onnx-v1.10.23-linux-x64-gpu/lib:venv/lib`
