### ISSUE TITLE
语音识别asr种添加阿拉伯数字支持后，在识别带有数字的词组时会转成阿拉伯数字

### ISSUE THREAD

**Issue by zhouyi2016** [k2-fsa/sherpa-onnx#1308]
语音输入：一起去散步，
识别结果：1起去散步
输入：四舍五入
输出：4舍5入
诸如此类问题，请问有什么解决方案

**Comment by yuyun2000** [comment]
这个暂时没有更好的解决方案，如果你不嫌麻烦，可以换其他的itn仓库，可能会好点

**Comment by zhouyi2016** [comment]
有没有推荐的itn仓库呢？

**Comment by yuyun2000** [comment]
https://github.com/wenet-e2e/WeTextProcessing

**Comment by zhouyi2016** [comment]
我们现在使用的是流式的预训练模型，如果更换itn仓库的话，这个有没有指导怎么的文档？

**Comment by yuyun2000** [comment]
我都说了如果你不嫌麻烦就可以换，你要换的话就需要自己麻烦了

**Comment by csukuangfj** [comment]
你用的是非流式模型？如果是的话，直接用文档里的sense voice模型就好了，不需要再给fst文件，自动解决了你的问题。

详见文档

**Comment by csukuangfj** [comment]
目前无法解决这个。
