### ISSUE TITLE
SherpaOnnx安卓示例中的大部分kotlin代码都是空的

### ISSUE THREAD

**Issue by 644683848** [k2-fsa/sherpa-onnx#1310]
详细目录如下：android/SherpaOnnx/app/src/main/java/com/k2fsa/sherpa/onnx/
只有“android/SherpaOnnx/app/src/main/java/com/k2fsa/sherpa/onnx/MainActivity.kt”这个文件幸存
![image](https://github.com/user-attachments/assets/7df1827f-4977-45ce-b71c-da4327aa33cc)

**Comment by csukuangfj** [comment]
这个叫做符号链接。你看到的是一个相对路径。你根据这个路径，就能找到具体的文件

**Comment by AvatarQing** [comment]
Windows下运行报错，链接不到源文件。
`e: D:\dev\projects\opensource\sherpa-onnx\android\SherpaOnnx\app\src\main\java\com\k2fsa\sherpa\onnx\FeatureConfig.kt: (1, 1): Expecting a top level declaration`

**Comment by csukuangfj** [comment]
这是一个符号链接，你打开它，里面有一个相对路径，你去找到它本来的文件，复制过来，替换掉这个文件。
