### ISSUE TITLE
How can i enable cuda support for my C# project

### ISSUE THREAD

**Issue by kiraYuukiAsuna** [k2-fsa/sherpa-onnx#1313]
Hi! I didn't see any pre-built nuget package. So if i want to use cuda in my C# project, i need to compile everything by myself, right?

**Comment by csukuangfj** [comment]
Please search for existing issues.


You can.download prebuilt libs.

**Comment by kiraYuukiAsuna** [comment]
I searched but found nothing about it. I am using version 1.10.23. I tried to replace these files:
![image](https://github.com/user-attachments/assets/27ae80b5-6ae8-4603-8ccf-9260d9b7582d)
But when i run my C# program, i got a 0x00 handle:
![image](https://github.com/user-attachments/assets/0138f764-4421-4cd5-b31a-e8799d0f3bab)
I guess i need to replace the sherpa-onnx.dll, the binding to sherpa-onnx-c-api.dll. But i don't know how to generate it?

**Comment by csukuangfj** [comment]
> I guess i need to replace the sherpa-onnx.dll, the binding to sherpa-onnx-c-api.dll. But i don't know how to generate it?


Please have a look at
https://github.com/k2-fsa/sherpa-onnx/issues/1146

(You need to replace linux with windows)

---

The screenshot shows the Handle is 0x0, which means your config is not correct.

Please check the output logs in you console carefully and you will find which field in your config is wrong, e.g., some path does not exist, etc.

**Comment by philipag** [comment]
@csukuangfj  I looked at #1146 but I do not find release files with the word 'cuda' except those for Linux.  Could someone point me to instructions for how to get CUDA working with any of the c# samples?

**Comment by csukuangfj** [comment]
Thank you for the report. We will look into it.

As a workaround, please download a whl for windows from
https://k2-fsa.github.io/sherpa/onnx/cuda.html
and unzip it.

You can find required dlls after unzipping.


Hint: Any wheel for windows is ok.
