### ISSUE TITLE
Problem with Flush function in  voice-activity-detector.cc

### ISSUE THREAD

**Issue by laochen** [k2-fsa/sherpa-onnx#1314]
It is best to keep all the original data in the flush action to facilitate splicing with the remaining buffer for the final recognition. The current code will cause the accuracy of the last sentence recognition. My modification suggestions
voice-activity-detector.cc
line:126
    //int32_t end = buffer_.Tail() - model_->MinSilenceDurationSamples();
    int32_t end = buffer_.Tail();

**Comment by yuyun2000** [comment]
Happy man has something going on recently, so he might reply to you late.
