### ISSUE TITLE
WASM ASR “loadPackage” fails in Safari running on IOS

### ISSUE THREAD

**Issue by Glenn-TR** [k2-fsa/sherpa-onnx#1315]
First I wanted to say THANKS to the your team for developing this awesome software!

I am seeing a problem with the WASM ASR package using Safari running on IOS.

This occurs in the ONNX version but **_NOT_** in the NCNN version.

Are there any ONNX workarounds that I could try?

Thanks — Glenn

Details:

1. The failure occurs in **_BOTH_** my iPad and iPhone (both running the latest IOS version, 17.6.1)
2. The failure does _**NOT**_ occur using Safari on MacOS (Mac mini - M1 Sonoma 14.6.1 / Safari 17.6)
3. [ipad-oynx.txt](https://github.com/user-attachments/files/16853260/ipad-oynx.txt) shows the Safari console output from running on my iPad. I captured this by connecting the iPad to my Mac mini and using the “save console to file” feature. 
4. The first pic below shows more details of the “[Error] Aborted()” log entry seen in item 3.
5. The second pic shows the details of the second to last line in item # 4 - i.e. the “shrpa-onnx-wasm-main-asr.js:164” line).

![error-screen-shot](https://github.com/user-attachments/assets/5e4a01a9-d20c-4c75-9975-c3eaa38d1f56)
![loadPackageError](https://github.com/user-attachments/assets/5e02f266-24b5-4800-960a-50c18fe86430)

**Comment by csukuangfj** [comment]
could you un-minimize the downloaded   .js files and run again and post the logs?

**Comment by csukuangfj** [comment]
The following is a screenshot of cloning your huggingface repo and run it locally on my mac
<img width="1355" alt="Screenshot 2024-09-05 at 08 22 43" src="https://github.com/user-attachments/assets/78241d47-ad91-4f1d-999b-14bd81388881">


There must be something wrong with your `.wasm` file. Please recheck how you generate it.

---

The following is a screenshot of a run using the files from 
https://github.com/k2-fsa/sherpa-onnx/actions/runs/10630269658

<img width="1349" alt="Screenshot 2024-09-05 at 08 22 54" src="https://github.com/user-attachments/assets/1f33280a-4404-4021-ac36-b0e56ba44fab">


You can see that it runs normally as expected.

**Comment by csukuangfj** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this issue for now. Please don't hesitate to comment on the issue if you have any more information for us; we will reopen it right away!
