### ISSUE TITLE
Can i convert non-stream zipformer2 into streaming mode?

### ISSUE THREAD

**Issue by Pick1eman** [k2-fsa/sherpa-onnx#1318]
Hello! I have a model trained in non-streaming mode. Is there any way to convert the model to streaming mode? I understand that only the metadata changes?

**Comment by yuyun2000** [comment]
no 
Their training process is different.

**Comment by yuyun2000** [comment]
You can try it, it's almost unrecognizable.

**Comment by csukuangfj** [comment]
it's not possible.
