### ISSUE TITLE
Support conformer models

### ISSUE THREAD

**Issue by jingzhaoou** [k2-fsa/sherpa-onnx#132]
Look like that `sherpa-onnx` only supports LSTM and ZipFormer models. I wonder if anyone has code to support conformer models. Thanks!

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/sherpa-onnx/blob/aa7108729bd07e773f03ea1a49eb8bb27367ff8b/sherpa-onnx/csrc/offline-recognizer-impl.cc#L70

Please either read our code or the [documentation](https://k2-fsa.github.io/sherpa/onnx/pretrained_models/offline-transducer/conformer-transducer-models.html)

We already support non-streaming Conformer models from icefall.

**Comment by jingzhaoou** [comment]
Really appreciate the prompt reply. I am looking for conformer support for the online flow. 

https://github.com/k2-fsa/sherpa-onnx/blob/aa7108729bd07e773f03ea1a49eb8bb27367ff8b/sherpa-onnx/csrc/online-transducer-model.cc#L80

Something similar to the following from `k2-sherpa`: 

https://github.com/k2-fsa/sherpa/blob/acd84986fbb83169174b3e0e17b536f9458b8726/sherpa/csrc/online-conformer-transducer-model.cc#L13

I can help to write a version of `online-conformer-transducer-model.cc` in the context of ONNX if needed. Please advice.

**Comment by csukuangfj** [comment]
> I can help to write a version of online-conformer-transducer-model.cc in the context of ONNX if needed.

That would be great.

I am writing code to export a streaming conformer to onnx in icefall. After finishing that (probably today), I will describe the steps to add it to sherpa-onnx.

**Comment by jingzhaoou** [comment]
This is awesome! Look forward to seeing your check-ins soon. After that, I will create a fork and submit a PR for review.

**Comment by csukuangfj** [comment]
> This is awesome! Look forward to seeing your check-ins soon. After that, I will create a fork and submit a PR for review.

Sorry, I did not manage to export it to onnx. But I am still working on it. Please wait for a while.

**Comment by jingzhaoou** [comment]
@csukuangfj Thanks for keeping me updated. Please take your time. I am spending more time to learn more about ONNX and TensorRT these days. I am very excited about this `sherpa-onnx` project.

**Comment by csukuangfj** [comment]
@jingzhaoou 
Please find an exported streaming conformer at
https://github.com/k2-fsa/icefall/pull/1047

**Comment by csukuangfj** [comment]
Closing via #141
