### ISSUE TITLE
由于使用更高版本onnxruntime1.18.0报OrtGetApiBase问题

### ISSUE THREAD

**Issue by sdlyxcc** [k2-fsa/sherpa-onnx#1320]
公司项目中已经有用到onnx的1.18.0的版本做其他ai功能，想集成进入本项目VAD的模块，但如果使用项目中提供的libonnxruntime.so就会和项目中1.18.1版本冲突无法编译通过，如果公司项目降低到1.17.1版本，公司项目中AI加载模型也会报问题， 能有啥解决办法吗

**Comment by csukuangfj** [comment]
只用vad功能，还有没有用到其他的模型？

如果只用vad，那么，去项目里cmake文件夹下面，修改onnxruntime的版本就行

**Comment by sdlyxcc** [comment]
嗯，谢谢，修改了.sh内的onnxruntime的版本为1.18.0后重新编译获取的jni.so 文件可以使用了
