### ISSUE TITLE
golang 1.20 构建real-time-speech-recognition-from-microphone 失败

### ISSUE THREAD

**Issue by lllwan** [k2-fsa/sherpa-onnx#1322]
go env：

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/wangxun/Library/Caches/go-build"
GOENV="/Users/wangxun/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/wangxun/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/wangxun/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.20"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/wangxun/mycode/sherpa-onnx/go-api-examples/real-time-speech-recognition-from-microphone/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7x/25_3v9cj6tv4h2w6c49crj4w0000gn/T/go-build2894224188=/tmp/go-build -gno-record-gcc-switches -fno-common"

 go build：
# github.com/csukuangfj/portaudio-go
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:207:27: could not determine kind of name for C.PaDeviceIndex
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:37:12: could not determine kind of name for C.PaError
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:326:19: could not determine kind of name for C.PaHostApiIndex
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:234:40: could not determine kind of name for C.PaHostApiTypeId
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:817:38: could not determine kind of name for C.PaSampleFormat
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:593:26: could not determine kind of name for C.PaStreamCallbackFlags
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:873:89: could not determine kind of name for C.PaStreamCallbackTimeInfo
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:401:18: could not determine kind of name for C.PaStreamFlags
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:520:23: could not determine kind of name for C.PaStreamParameters
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:367:22: could not determine kind of name for C.PaTime
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:928:18: could not determine kind of name for C.Pa_AbortStream
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:860:19: could not determine kind of name for C.Pa_CloseStream
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:250:7: could not determine kind of name for C.Pa_GetDefaultHostApi
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:273:7: could not determine kind of name for C.Pa_GetDefaultInputDevice
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:290:7: could not determine kind of name for C.Pa_GetDefaultOutputDevice
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:318:12: could not determine kind of name for C.Pa_GetDeviceCount
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:329:13: could not determine kind of name for C.Pa_GetDeviceInfo
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:46:20: could not determine kind of name for C.Pa_GetErrorText
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:317:13: could not determine kind of name for C.Pa_GetHostApiCount
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:346:14: could not determine kind of name for C.Pa_GetHostApiInfo
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:97:14: could not determine kind of name for C.Pa_GetLastHostErrorInfo
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:963:17: could not determine kind of name for C.Pa_GetStreamCpuLoad
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:933:7: could not determine kind of name for C.Pa_GetStreamInfo
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:969:7: could not determine kind of name for C.Pa_GetStreamReadAvailable
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:949:18: could not determine kind of name for C.Pa_GetStreamTime
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:979:7: could not determine kind of name for C.Pa_GetStreamWriteAvailable
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:28:13: could not determine kind of name for C.Pa_GetVersion
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:33:20: could not determine kind of name for C.Pa_GetVersionText
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:349:23: could not determine kind of name for C.Pa_HostApiDeviceIndexToDeviceIndex
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:234:7: could not determine kind of name for C.Pa_HostApiTypeIdToHostApiIndex
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:122:11: could not determine kind of name for C.Pa_Initialize
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:484:18: could not determine kind of name for C.Pa_IsFormatSupported
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:650:11: could not determine kind of name for C.Pa_OpenStream
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:999:18: could not determine kind of name for C.Pa_ReadStream
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:869:18: could not determine kind of name for C.Pa_StartStream
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:922:18: could not determine kind of name for C.Pa_StopStream
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:142:11: could not determine kind of name for C.Pa_Terminate
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:1015:18: could not determine kind of name for C.Pa_WriteStream
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:188:32: could not determine kind of name for C.paAL
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:187:32: could not determine kind of name for C.paALSA
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:183:32: could not determine kind of name for C.paASIO
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:193:32: could not determine kind of name for C.paAudioScienceHPI
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:78:48: could not determine kind of name for C.paBadBufferPtr
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:57:48: could not determine kind of name for C.paBadIODeviceCombination
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:62:48: could not determine kind of name for C.paBadStreamPtr
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:189:32: could not determine kind of name for C.paBeOS
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:59:48: could not determine kind of name for C.paBufferTooBig
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:60:48: could not determine kind of name for C.paBufferTooSmall
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:73:48: could not determine kind of name for C.paCanNotReadFromACallbackStream
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:75:48: could not determine kind of name for C.paCanNotReadFromAnOutputOnlyStream
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:74:48: could not determine kind of name for C.paCanNotWriteToACallbackStream
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:76:48: could not determine kind of name for C.paCanNotWriteToAnInputOnlyStream
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:405:54: could not determine kind of name for C.paClipOff
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:185:32: could not determine kind of name for C.paCoreAudio
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:65:48: could not determine kind of name for C.paDeviceUnavailable
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:181:32: could not determine kind of name for C.paDirectSound
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:406:54: could not determine kind of name for C.paDitherOff
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:828:8: could not determine kind of name for C.paFloat32
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:398:36: could not determine kind of name for C.paFramesPerBufferUnspecified
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:71:48: could not determine kind of name for C.paHostApiNotFound
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:180:32: could not determine kind of name for C.paInDevelopment
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:66:48: could not determine kind of name for C.paIncompatibleHostApiSpecificStreamInfo
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:77:48: could not determine kind of name for C.paIncompatibleStreamHostApi
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:613:38: could not determine kind of name for C.paInputOverflow
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:69:48: could not determine kind of name for C.paInputOverflowed
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:604:39: could not determine kind of name for C.paInputUnderflow
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:58:48: could not determine kind of name for C.paInsufficientMemory
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:838:8: could not determine kind of name for C.paInt16
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:833:9: could not determine kind of name for C.paInt24
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:830:8: could not determine kind of name for C.paInt32
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:840:8: could not determine kind of name for C.paInt8
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:64:48: could not determine kind of name for C.paInternalError
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:52:48: could not determine kind of name for C.paInvalidChannelCount
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:54:48: could not determine kind of name for C.paInvalidDevice
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:55:48: could not determine kind of name for C.paInvalidFlag
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:72:48: could not determine kind of name for C.paInvalidHostApi
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:53:48: could not determine kind of name for C.paInvalidSampleRate
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:191:32: could not determine kind of name for C.paJACK
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:182:32: could not determine kind of name for C.paMME
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:407:54: could not determine kind of name for C.paNeverDropInput
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:274:10: could not determine kind of name for C.paNoDevice
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:103:7: could not determine kind of name for C.paNoError
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:404:54: could not determine kind of name for C.paNoFlag
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:730:25: could not determine kind of name for C.paNonInterleaved
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:51:48: could not determine kind of name for C.paNotInitialized
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:61:48: could not determine kind of name for C.paNullCallback
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:186:32: could not determine kind of name for C.paOSS
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:620:39: could not determine kind of name for C.paOutputOverflow
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:617:40: could not determine kind of name for C.paOutputUnderflow
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:70:48: could not determine kind of name for C.paOutputUnderflowed
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:409:54: could not determine kind of name for C.paPlatformSpecificFlags
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:408:54: could not determine kind of name for C.paPrimeOutputBuffersUsingStreamCallback
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:624:38: could not determine kind of name for C.paPrimingOutput
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:56:48: could not determine kind of name for C.paSampleFormatNotSupported
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:184:32: could not determine kind of name for C.paSoundManager
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:646:8: could not determine kind of name for C.paStreamCallback
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:68:48: could not determine kind of name for C.paStreamIsNotStopped
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:67:48: could not determine kind of name for C.paStreamIsStopped
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:63:48: could not determine kind of name for C.paTimedOut
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:842:8: could not determine kind of name for C.paUInt8
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:96:7: could not determine kind of name for C.paUnanticipatedHostError
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:192:32: could not determine kind of name for C.paWASAPI
../../../../go/pkg/mod/github.com/csukuangfj/portaudio-go@v1.0.7/portaudio.go:190:32: could not determine kind of name for C.paWDMKS

**Comment by csukuangfj** [comment]
Please do the following:

1. Modify `go.mod`.  Please change the version of portaudio from v1.0.7 to v1.0.1
2. Run `go mod tidy`
3. Run `go build`
4. Done!

**Comment by lllwan** [comment]
可以了， 但是为什么那？

**Comment by csukuangfj** [comment]
应该是portaudio 后面为了增加 windows 的支持，影响了对 macos 的支持。

**Comment by csukuangfj** [comment]
macos 上，你先用 portaudio 1.0.1 ?

**Comment by lllwan** [comment]
OK
