### ISSUE TITLE
Missing warmup process as k2-sherpa

### ISSUE THREAD

**Issue by jingzhaoou** [k2-fsa/sherpa-onnx#134]
In `k2-sherpa`, during warm-up, the encoder is initialized to the model initial states.

```
  void WarmUp(torch::Tensor features, torch::Tensor features_length) {
    torch::IValue states = GetEncoderInitStates();
    states = StackStates({states});
```

However, I don't see similar warm-up process with `sherpa-onnx`. This may cause a bit worse performance at the beginning of a stream. It may be tricky to save the model initial states during ONNX export I guess. 

Appreciate any suggestions.

**Comment by csukuangfj** [comment]
Could you help test the online or offline websocket server in sherpa-onnx and see if the second request is much faster than the very first request?


---

By the way, we have similar methods as k2-fsa/sherpa in sherpa-onnx
https://github.com/k2-fsa/sherpa-onnx/blob/aa7108729bd07e773f03ea1a49eb8bb27367ff8b/sherpa-onnx/csrc/online-transducer-model.h#L61

https://github.com/k2-fsa/sherpa-onnx/blob/aa7108729bd07e773f03ea1a49eb8bb27367ff8b/sherpa-onnx/csrc/online-transducer-model.h#L44-L45

https://github.com/k2-fsa/sherpa-onnx/blob/aa7108729bd07e773f03ea1a49eb8bb27367ff8b/sherpa-onnx/csrc/online-transducer-model.h#L54-L55


It is not difficult to add warmup to sherpa-onnx if you find it is helpful to reduce the latency of the first request.

----

> It may be tricky to save the model initial states during ONNX export I guess.

You don't need to save the initial states during model exporting. The initial state is constructed in the code in sherpa-onnx.
We only need some model parameters to construct the initial states.

**Comment by csukuangfj** [comment]
There is no warmup in sherpa-onnx, I think.
