### ISSUE TITLE
kws 关键字识别，同时手机播放音乐，识别率下降

### ISSUE THREAD

**Issue by solocoder-tech** [k2-fsa/sherpa-onnx#1347]
kws 关键字识别，正常情况是可以识别出来的，但是当我手机同时再播放音乐的时候，关键字识别率会下降，音乐声音很高时，关键字识别不到。请问有办法调整吗？

**Comment by csukuangfj** [comment]
别人和你说话时，如果你把音乐放的很大，你自己也很难听清别人说的话
