### ISSUE TITLE
aarch64 平台编译报错 

### ISSUE THREAD

**Issue by gcoollinux** [k2-fsa/sherpa-onnx#1351]
../../_deps/onnxruntime-src/lib/libonnxruntime.a(mu.c.o):mu.c:(.text._ZN5nsync17nsync_mu_rtrylockEPNS_11nsync_mu_s_E+0x50): more undefined references to `__aarch64_cas4_acq' follow
../../_deps/onnxruntime-src/lib/libonnxruntime.a(mu.c.o): In function `nsync::nsync_remove_from_mu_queue_(nsync::nsync_dll_element_s_*, nsync::nsync_dll_element_s_*)':
mu.c:(.text._ZN5nsync27nsync_remove_from_mu_queue_EPNS_20nsync_dll_element_s_ES1_+0x3c): undefined reference to `__aarch64_cas4_relax'
../../_deps/onnxruntime-src/lib/libonnxruntime.a(mu.c.o): In function `nsync::nsync_mu_unlock_slow_(nsync::nsync_mu_s_*, nsync::lock_type_s*)':
mu.c:(.text._ZN5nsync21nsync_mu_unlock_slow_EPNS_11nsync_mu_s_EPNS_11lock_type_sE+0x60): undefined reference to `__aarch64_cas4_rel'
mu.c:(.text._ZN5nsync21nsync_mu_unlock_slow_EPNS_11nsync_mu_s_EPNS_11lock_type_sE+0xc0): undefined reference to `__aarch64_cas4_acq'
mu.c:(.text._ZN5nsync21nsync_mu_unlock_slow_EPNS_11nsync_mu_s_EPNS_11lock_type_sE+0x14c): undefined reference to `__aarch64_cas4_rel'
mu.c:(.text._ZN5nsync21nsync_mu_unlock_slow_EPNS_11nsync_mu_s_EPNS_11lock_type_sE+0x2e4): undefined reference to `__aarch64_cas4_rel'
mu.c:(.text._ZN5nsync21nsync_mu_unlock_slow_EPNS_11nsync_mu_s_EPNS_11lock_type_sE+0x3a4): undefined reference to `__aarch64_cas4_rel'
mu.c:(.text._ZN5nsync21nsync_mu_unlock_slow_EPNS_11nsync_mu_s_EPNS_11lock_type_sE+0x444): undefined reference to `__aarch64_cas4_rel'
mu.c:(.text._ZN5nsync21nsync_mu_unlock_slow_EPNS_11nsync_mu_s_EPNS_11lock_type_sE+0x488): undefined reference to `__aarch64_cas4_rel'
../../_deps/onnxruntime-src/lib/libonnxruntime.a(mu.c.o):mu.c:(.text._ZN5nsync15nsync_mu_unlockEPNS_11nsync_mu_s_E+0x1c): more undefined references to `__aarch64_cas4_rel' follow
../../_deps/onnxruntime-src/lib/libonnxruntime.a(common.c.o): In function `nsync::nsync_spin_test_and_set_(std::atomic<unsigned int>*, unsigned int, unsigned int, unsigned int)':
common.c:(.text._ZN5nsync24nsync_spin_test_and_set_EPSt6atomicIjEjjj+0x44): undefined reference to `__aarch64_cas4_acq'
../../_deps/onnxruntime-src/lib/libonnxruntime.a(prepacked_weights_container.cc.o): In function `std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<onnxruntime::IAllocator> >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<onnxruntime::IAllocator> > >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_Scoped_node::~_Scoped_node()':
prepacked_weights_container.cc:(.text._ZNSt10_HashtableINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_St10shared_ptrIN11onnxruntime10IAllocatorEEESaISC_ENSt8__detail10_Select1stESt8equal_toIS5_ESt4hashIS5_ENSE_18_Mod_range_hashingENSE_20_Default_ranged_hashENSE_20_Prime_rehash_policyENSE_17_Hashtable_traitsILb1ELb0ELb1EEEE12_Scoped_nodeD2Ev[_ZNSt10_HashtableINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_St10shared_ptrIN11onnxruntime10IAllocatorEEESaISC_ENSt8__detail10_Select1stESt8equal_toIS5_ESt4hashIS5_ENSE_18_Mod_range_hashingENSE_20_Default_ranged_hashENSE_20_Prime_rehash_policyENSE_17_Hashtable_traitsILb1ELb0ELb1EEEE12_Scoped_nodeD5Ev]+0xcc): undefined reference to `__aarch64_ldadd4_acq_rel'
prepacked_weights_container.cc:(.text._ZNSt10_HashtableINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_St10shared_ptrIN11onnxruntime10IAllocatorEEESaISC_ENSt8__detail10_Select1stESt8equal_toIS5_ESt4hashIS5_ENSE_18_Mod_range_hashingENSE_20_Default_ranged_hashENSE_20_Prime_rehash_policyENSE_17_Hashtable_traitsILb1ELb0ELb1EEEE12_Scoped_nodeD2Ev[_ZNSt10_HashtableINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_St10shared_ptrIN11onnxruntime10IAllocatorEEESaISC_ENSt8__detail10_Select1stESt8equal_toIS5_ESt4hashIS5_ENSE_18_Mod_range_hashingENSE_20_Default_ranged_hashENSE_20_Prime_rehash_policyENSE_17_Hashtable_traitsILb1ELb0ELb1EEEE12_Scoped_nodeD5Ev]+0xdc): undefined reference to `__aarch64_ldadd4_acq_rel'
../../_deps/onnxruntime-src/lib/libonnxruntime.a(prepacked_weights_container.cc.o): In function `onnxruntime::PrepackedWeightsContainer::GetOrCreateAllocator(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
prepacked_weights_container.cc:(.text._ZN11onnxruntime25PrepackedWeightsContainer20GetOrCreateAllocatorERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x220): undefined reference to `__aarch64_ldadd4_acq_rel'
prepacked_weights_container.cc:(.text._ZN11onnxruntime25PrepackedWeightsContainer20GetOrCreateAllocatorERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x270): undefined reference to `__aarch64_ldadd4_acq_rel'
prepacked_weights_container.cc:(.text._ZN11onnxruntime25PrepackedWeightsContainer20GetOrCreateAllocatorERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x280): undefined reference to `__aarch64_ldadd4_acq_rel'
../../_deps/onnxruntime-src/lib/libonnxruntime.a(prepacked_weights_container.cc.o):prepacked_weights_container.cc:(.text._ZN11onnxruntime25PrepackedWeightsContainer20GetOrCreateAllocatorERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x298): more undefined references to `__aarch64_ldadd4_acq_rel' follow
../../_deps/onnxruntime-src/lib/libonnxruntime.a(prepacked_weights.cc.o): In function `onnxruntime::PrePackedWeights::GetHash() const':
prepacked_weights.cc:(.text._ZNK11onnxruntime16PrePackedWeights7GetHashEv+0x154): undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()'
../../_deps/onnxruntime-src/lib/libonnxruntime.a(allocator_utils.cc.o): In function `onnxruntime::CreateAllocator(onnxruntime::AllocatorCreationInfo const&)':
allocator_utils.cc:(.text._ZN11onnxruntime15CreateAllocatorERKNS_21AllocatorCreationInfoE+0x7c4): undefined reference to `__aarch64_ldadd4_acq_rel'
allocator_utils.cc:(.text._ZN11onnxruntime15CreateAllocatorERKNS_21AllocatorCreationInfoE+0x7d4): undefined reference to `__aarch64_ldadd4_acq_rel'
allocator_utils.cc:(.text._ZN11onnxruntime15CreateAllocatorERKNS_21AllocatorCreationInfoE+0x7e4): undefined reference to `__aarch64_ldadd4_acq_rel'
allocator_utils.cc:(.text._ZN11onnxruntime15CreateAllocatorERKNS_21AllocatorCreationInfoE+0x850): undefined reference to `__aarch64_ldadd4_acq_rel'
allocator_utils.cc:(.text._ZN11onnxruntime15CreateAllocatorERKNS_21AllocatorCreationInfoE+0x860): undefined reference to `__aarch64_ldadd4_acq_rel'
../../_deps/onnxruntime-src/lib/libonnxruntime.a(allocator_utils.cc.o):allocator_utils.cc:(.text._ZN11onnxruntime15CreateAllocatorERKNS_21AllocatorCreationInfoE+0x8a4): more undefined references to `__aarch64_ldadd4_acq_rel' follow
../../_deps/onnxruntime-src/lib/libonnxruntime.a(per_thread_waiter.c.o): In function `nsync::nsync_per_thread_waiter_(void (*)(void*))':
per_thread_waiter.c:(.text._ZN5nsync24nsync_per_thread_waiter_EPFvPvE+0x38): undefined reference to `__aarch64_cas4_acq'
../../_deps/onnxruntime-src/lib/libonnxruntime.a(per_thread_waiter.c.o): In function `nsync::nsync_set_per_thread_waiter_(void*, void (*)(void*))':
per_thread_waiter.c:(.text._ZN5nsync28nsync_set_per_thread_waiter_EPvPFvS0_E+0x44): undefined reference to `__aarch64_cas4_acq'
../../_deps/onnxruntime-src/lib/libonnxruntime.a(nsync_semaphore_futex.c.o): In function `nsync::nsync_mu_semaphore_p(nsync::nsync_semaphore_s_*)':
nsync_semaphore_futex.c:(.text._ZN5nsync20nsync_mu_semaphore_pEPNS_18nsync_semaphore_s_E+0x24): undefined reference to `__aarch64_cas4_acq'
../../_deps/onnxruntime-src/lib/libonnxruntime.a(nsync_semaphore_futex.c.o): In function `nsync::nsync_mu_semaphore_p_with_deadline(nsync::nsync_semaphore_s_*, timespec)':
nsync_semaphore_futex.c:(.text._ZN5nsync34nsync_mu_semaphore_p_with_deadlineEPNS_18nsync_semaphore_s_E8timespec+0x44): undefined reference to `__aarch64_cas4_acq'
../../_deps/onnxruntime-src/lib/libonnxruntime.a(nsync_semaphore_futex.c.o): In function `nsync::nsync_mu_semaphore_v(nsync::nsync_semaphore_s_*)':
nsync_semaphore_futex.c:(.text._ZN5nsync20nsync_mu_semaphore_vEPNS_18nsync_semaphore_s_E+0x20): undefined reference to `__aarch64_cas4_rel'
../../_deps/onnxruntime-src/lib/libonnxruntime.a(cv.c.o): In function `nsync::wake_waiters(nsync::nsync_dll_element_s_*, int)':
cv.c:(.text._ZN5nsyncL12wake_waitersEPNS_20nsync_dll_element_s_Ei+0x84): undefined reference to `__aarch64_cas4_acq'
cv.c:(.text._ZN5nsyncL12wake_waitersEPNS_20nsync_dll_element_s_Ei+0x190): undefined reference to `__aarch64_cas4_acq'
cv.c:(.text._ZN5nsyncL12wake_waitersEPNS_20nsync_dll_element_s_Ei+0x200): undefined reference to `__aarch64_cas4_rel'
cv.c:(.text._ZN5nsyncL12wake_waitersEPNS_20nsync_dll_element_s_Ei+0x2d0): undefined reference to `__aarch64_cas4_rel'
../../_deps/onnxruntime-src/lib/libonnxruntime.a(cv.c.o): In function `nsync::nsync_cv_wait_with_deadline_generic(nsync::nsync_cv_s_*, void*, void (*)(void*), void (*)(void*), timespec, nsync::nsync_note_s_*)':
cv.c:(.text._ZN5nsync35nsync_cv_wait_with_deadline_genericEPNS_11nsync_cv_s_EPvPFvS2_ES4_8timespecPNS_13nsync_note_s_E+0x21c): undefined reference to `__aarch64_cas4_relax'
../../_deps/onnxruntime-src/lib/libonnxruntime.a(cv.c.o): In function `nsync::nsync_cv_signal(nsync::nsync_cv_s_*)':
cv.c:(.text._ZN5nsync15nsync_cv_signalEPNS_11nsync_cv_s_E+0xb0): undefined reference to `__aarch64_cas4_relax'
cv.c:(.text._ZN5nsync15nsync_cv_signalEPNS_11nsync_cv_s_E+0x1f0): undefined reference to `__aarch64_cas4_relax'
../../_deps/onnxruntime-src/lib/libonnxruntime.a(cv.c.o): In function `nsync::nsync_cv_broadcast(nsync::nsync_cv_s_*)':
cv.c:(.text._ZN5nsync18nsync_cv_broadcastEPNS_11nsync_cv_s_E+0xd8): undefined reference to `__aarch64_cas4_relax'
../../_deps/onnxruntime-src/lib/libonnxruntime.a(mu_wait.c.o): In function `nsync::nsync_mu_wait_with_deadline(nsync::nsync_mu_s_*, int (*)(void const*), void const*, int (*)(void const*, void const*), timespec, nsync::nsync_note_s_*)':
mu_wait.c:(.text._ZN5nsync27nsync_mu_wait_with_deadlineEPNS_11nsync_mu_s_EPFiPKvES3_PFiS3_S3_E8timespecPNS_13nsync_note_s_E+0x120): undefined reference to `__aarch64_cas4_rel'
mu_wait.c:(.text._ZN5nsync27nsync_mu_wait_with_deadlineEPNS_11nsync_mu_s_EPFiPKvES3_PFiS3_S3_E8timespecPNS_13nsync_note_s_E+0x200): undefined reference to `__aarch64_cas4_acq_rel'
mu_wait.c:(.text._ZN5nsync27nsync_mu_wait_with_deadlineEPNS_11nsync_mu_s_EPFiPKvES3_PFiS3_S3_E8timespecPNS_13nsync_note_s_E+0x248): undefined reference to `__aarch64_cas4_acq'
mu_wait.c:(.text._ZN5nsync27nsync_mu_wait_with_deadlineEPNS_11nsync_mu_s_EPFiPKvES3_PFiS3_S3_E8timespecPNS_13nsync_note_s_E+0x2b0): undefined reference to `__aarch64_cas4_rel'
../../_deps/onnxruntime-src/lib/libonnxruntime.a(mu_wait.c.o): In function `nsync::nsync_mu_unlock_without_wakeup(nsync::nsync_mu_s_*)':
mu_wait.c:(.text._ZN5nsync30nsync_mu_unlock_without_wakeupEPNS_11nsync_mu_s_E+0x1c): undefined reference to `__aarch64_cas4_rel'

使用的工具链接为：gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu

[error_001.log](https://github.com/user-attachments/files/17001766/error_001.log)

**Comment by csukuangfj** [comment]
https://k2-fsa.github.io/sherpa/onnx/install/aarch64-embedded-linux.html

这个是文档。

友情提示，请按照文档来。动态库，用 gcc 7.5, 静态库，用 gcc 10.3

文档里写的非常清楚。

**Comment by yuyun2000** [comment]
why not use English

**Comment by 714653430** [comment]
I encountered the same problem
762: undefined reference to `__aarch64_cas4_acq_rel'
.c:265: undefined reference to `__aarch64_ldadd4_relax'

**Comment by csukuangfj** [comment]
which version of gcc are you using?

**Comment by csukuangfj** [comment]
have you followed exactly the doc?

**Comment by 714653430** [comment]
> which version of gcc are you using?

aarch64-none-linux-gnu-gcc-9.5.1 is Ti cross compiler

**Comment by csukuangfj** [comment]
> have you followed exactly the doc?

Please answer this question.

Also, please delete the build directory, re-run, and post all the output from the terminal.
