### ISSUE TITLE
有没有支持所有50种语言的onnx模型

### ISSUE THREAD

**Issue by sdlyxcc** [k2-fsa/sherpa-onnx#1354]
如果有支持所有50种语言的模型，能否提供一下

**Comment by csukuangfj** [comment]
不清楚你说的，所有50种，具体是哪50种。

请看文档里的 whisper, 支持 大于 50 种语言。

**Comment by sdlyxcc** [comment]
那 支持最多语言的模型是多少

**Comment by csukuangfj** [comment]
请看上面的评论，已经告诉你了。

**Comment by sdlyxcc** [comment]
SendVoice的模型有具体下载连接吗？ 在文档内只发现了拆分成多个语言的模型，想要支持所有语言的模型

**Comment by sdlyxcc** [comment]
所有语言合并成一个的模型
