### ISSUE TITLE
请问使用sensevoice生成字幕时如何指定识别的语言？How do Specify the language ?

### ISSUE THREAD

**Issue by zx3777** [k2-fsa/sherpa-onnx#1360]
请问使用sensevoice生成字幕时如何指定识别的语言？
我用python 实现的，不指定语言有时候会误识别为其他语言

How do I specify the language for recognition when generating subtitles with SenseVoice?
I'm using Python, and without specifying the language, it sometimes misidentifies the language.

cd /tmp/sherpa-onnx

# Assuem you have downloaded the SenseVoice model

wget https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/silero_vad.onnx
wget https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/lei-jun-test.wav

python3 ./python-api-examples/generate-subtitles.py \
  --silero-vad-model=./silero_vad.onnx \
  --sense-voice=./sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17/model.onnx \
  --tokens=./sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17/tokens.txt \
  --num-threads=2 \
  ./lei-jun-test.wav

**Comment by csukuangfj** [comment]
1. 可以不指定语言。

---

如果你非要指定语言，你需要修改
https://github.com/k2-fsa/sherpa-onnx/blob/647b63ea44a259be5bb5d4080199f37447ba19c6/python-api-examples/generate-subtitles.py#L305-L311

需要加一个参数
https://github.com/k2-fsa/sherpa-onnx/blob/647b63ea44a259be5bb5d4080199f37447ba19c6/sherpa-onnx/python/sherpa_onnx/offline_recognizer.py#L190

比如，改成
```
 recognizer = sherpa_onnx.OfflineRecognizer.from_sense_voice( 
     model=args.sense_voice, 
     tokens=args.tokens, 
     num_threads=args.num_threads, 
     use_itn=True, 
     debug=args.debug, 
     lang='en',
 ) 
```
就指定语言为 `en`.

注意，即使你指定为 `en`, 它仍然能识别出来其他语言的文字。

不建议指定语言.

**Comment by zx3777** [comment]
谢谢，指定了语言之后好一些了。
不过应该是添加 language='en' 吧？
lang='en' 会报错：TypeError: OfflineRecognizer.from_sense_voice() got an unexpected keyword argument 'lang'

**Comment by csukuangfj** [comment]
>不过应该是添加 language='en' 吧？

你说的很对
