### ISSUE TITLE
generate-subtitles.py 怎么指定使用GPU ?

### ISSUE THREAD

**Issue by zx3777** [k2-fsa/sherpa-onnx#1361]
我已经安装了GPU版本的Sherpa-onnx

但是没找到generate-subtitles.py哪里可以指定GPU, 我用的是sensevoic.

**Comment by csukuangfj** [comment]
provider 设置成 'cuda'

https://github.com/k2-fsa/sherpa-onnx/blob/647b63ea44a259be5bb5d4080199f37447ba19c6/sherpa-onnx/python/sherpa_onnx/offline_recognizer.py#L189
