### ISSUE TITLE
Sensevoice how to limit language output?

### ISSUE THREAD

**Issue by MonolithFoundation** [k2-fsa/sherpa-onnx#1365]
For example, certrain scenario can not possible occured Janpanese, Koera, how to disable these lans, only keep Chinese and English

**Comment by csukuangfj** [comment]
please describe your issue in detail

**Comment by MonolithFoundation** [comment]
Hello, am I not clear enough?
Just want to consult. How to make SenseVoice outputs only Chinese and English? It sometimes outputs Japanese, but this is not expected.

**Comment by csukuangfj** [comment]
Make sure your input audio does not contain Japanese.

If you still see Japanese characters if you use Chinese or English audio files, then please create an issue in the official SenseVoice repo, not here.

**Comment by MonolithFoundation** [comment]
.......
