### ISSUE TITLE
Unable to run it in MacOS with  Swift APi examples

### ISSUE THREAD

**Issue by Intiserahmed** [k2-fsa/sherpa-onnx#1368]
Hi, iOS is properly working, but when i try with MacOS build script with swift api examples, kindda confuse how to use it ? Any step by step guide for macos?

**Comment by csukuangfj** [comment]
The following is an example:
```bash
git clone https://github.com/k2-fsa/sherpa-onnx

cd sherpa-onnx
./build-swift-macos.sh

cd swift-api-examples

# there are several ./run-xxx.sh
# For instance,

./run-decode-file.sh

./run-tts.sh
```

**Comment by Intiserahmed** [comment]
@csukuangfj yeah i already run it, but how to use it with xcode project any example or hints please?

**Comment by csukuangfj** [comment]
We have provided the required header file, libraries, and swift APIs.

Could you tell us the difficulty you have? Would be great if you can post error logs.

**Comment by EnotPoloskun** [comment]
Hey @csukuangfj 

I believe that what @Intiserahmed means is that there is example of how to use shepra-onnx in ios application, but there is no example of how to use it in MacOs(desktop).

I am getting following error during build when I added framework from ios example to my MacOS desktop application

```
/.../Frameworks/sherpa-onnx.xcframework:1:1 While building for macOS, no library for this platform was found in '/../Frameworks/sherpa-onnx.xcframework'.
```

**Comment by csukuangfj** [comment]
> but there is no example of how to use it in MacOs(desktop) if it is even possible.

By the way, there is nothing special with sherpa-onnx.

For macOS app development, we provide shared libraries with C API header files.
The `xcframework` is for iOS development only.

We do provide Swift API examples. Please see https://github.com/k2-fsa/sherpa-onnx/issues/1368#issuecomment-2365064156

**Comment by EnotPoloskun** [comment]
Yeah, I see, but it is still not clear what I need to add and do with my xcode project in order to use shepra-onnx.

In other words - in one of the examples you have code like this:

```swift
  var config = sherpaOnnxOfflineSpeakerDiarizationConfig(
    segmentation: sherpaOnnxOfflineSpeakerSegmentationModelConfig(
      pyannote: sherpaOnnxOfflineSpeakerSegmentationPyannoteModelConfig(model: segmentationModel)),
    embedding: sherpaOnnxSpeakerEmbeddingExtractorConfig(model: embeddingExtractorModel),
    clustering: sherpaOnnxFastClusteringConfig(numClusters: numSpeakers)
  )

  let sd = SherpaOnnxOfflineSpeakerDiarizationWrapper(config: &config
```

What I need to add to xcode project in order to be able to use `sherpaOnnxOfflineSpeakerDiarizationConfig` and other shepra-onnx functions. Thank you in advance.

**Comment by csukuangfj** [comment]
> I am pretty new in ios/macos development and never used external non swift libraries/packages in my project, 

In that case, I suggest that you first spend sometime learning how to do that.

We have provided everything you need to be used in your macos project. You have to learn to add which file to which place.

You may find
https://k2-fsa.github.io/sherpa/ncnn/ios/for-the-more-curious-swift.html
helpful, though you need to replace the xcframework with the shared library since the xcframework is for ios, not for macos.

**Comment by csukuangfj** [comment]
@EnotPoloskun 

https://github.com/k2-fsa/sherpa-onnx/releases/download/v1.10.30/sherpa-onnx-v1.10.30-macos-xcframework-static.tar.bz2

Here is the xcframework for sherpa-onnx that supports both macos x86_64 and macos arm64.

To use it in your macos xcode project, please do the following:

1. Add [the bridging header](https://github.com/k2-fsa/sherpa-onnx/blob/v1.10.30/swift-api-examples/SherpaOnnx-Bridging-Header.h) to your project
![Screenshot 2024-10-29 at 11 19 23](https://github.com/user-attachments/assets/c19ed0d6-e2f9-4343-923b-072b90d220a1)

2. Add [SherpaOnnx.swift](https://github.com/k2-fsa/sherpa-onnx/blob/v1.10.30/swift-api-examples/SherpaOnnx.swift) to your project
![Screenshot 2024-10-29 at 11 21 02](https://github.com/user-attachments/assets/5dc2a625-7925-42e7-b979-eb12ba6b03a8)

3. Add [sherpa-onnx.xcframework](https://github.com/k2-fsa/sherpa-onnx/releases/download/v1.10.30/sherpa-onnx-v1.10.30-macos-xcframework-static.tar.bz2) to your project

![Screenshot 2024-10-29 at 11 22 45](https://github.com/user-attachments/assets/dadeec9f-dfbd-4482-aca2-dfbfdc191626)


4. Add the libonnxruntime.a to your project

You can find it from https://github.com/csukuangfj/onnxruntime-libs/releases/download/v1.17.1/onnxruntime-osx-universal2-static_lib-1.17.1.zip

![Screenshot 2024-10-29 at 11 32 15](https://github.com/user-attachments/assets/c3bdecba-978b-4bf6-9639-1640c74d49bb)


5. Add the directory containing libonnxruntime.a to the library search path

![Screenshot 2024-10-29 at 11 33 56](https://github.com/user-attachments/assets/e55a11cc-f492-45db-80da-ee7c7b31860b)


6. Add `-lc++` as the other linker flag
![Screenshot 2024-10-29 at 11 35 48](https://github.com/user-attachments/assets/f7d44959-52a9-4382-9aae-c962823a2817)


7. Done! Now you can use the Swift API of sherpa-onnx in your xcode project.

Please see how little code you need to write to set it up.

**Comment by Intiserahmed** [comment]
@csukuangfj  Thanks a lot for the specific instructions.

**Comment by EnotPoloskun** [comment]
@csukuangfj Thank you very much. Really appreciate it.
