### ISSUE TITLE
对于安卓平台是否可以自己训练模型进行优化呢，我没有在文档中找到关于模型训练的方法

### ISSUE THREAD

**Issue by JameWade** [k2-fsa/sherpa-onnx#1376]
对于安卓平台是否可以自己训练模型进行优化呢，我没有在文档中找到关于模型训练的方法

**Comment by csukuangfj** [comment]
> 对于安卓平台

模型和平台无关。不管你用 android, ios, windows, 还是什么系统，模型还是那个模型。

---

如何训练模型，请看
https://github.com/k2-fsa/icefall

友情提示：你需要大量的数据、GPU、时间，去训练一个还不错的的模型。
