### ISSUE TITLE
Parakeet TDT CTC 110M support

### ISSUE THREAD

**Issue by info-wordcab** [k2-fsa/sherpa-onnx#1380]
The NeMo conversion script we've been using (below) doesn't work for Parakeet TDT CTC 110M (https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/parakeet-tdt_ctc-110m). Are there additional steps or a different NeMo class we should be trying?

```
import nemo.collections.asr as nemo_asr

model_fname="parakeet-tdt_ctc-110m.nemo"
onnx_model_path = 'onnx_model/' + model_fname.split(".")[0]

model = nemo_asr.models.EncDecCTCModel.restore_from('model/'+ model_fname)

# Export ONNX model
onnx_enc_model_fname = onnx_model_path + "/" + 'encoder.onnx'
onnx_dec_model_fname = onnx_model_path + "/" + 'decoder.onnx'
onnx_joint_model_fname = onnx_model_path + "/" + 'joint.onnx'

model.encoder.export(onnx_enc_model_fname)
model.decoder.export(onnx_dec_model_fname)
model.joint.export(onnx_joint_model_fname)
```

**Comment by csukuangfj** [comment]
Please see our provided scripts at
https://github.com/k2-fsa/sherpa-onnx/tree/master/scripts/nemo/fast-conformer-hybrid-transducer-ctc

**Comment by csukuangfj** [comment]
By the way, we just converted this model to sherpa-onnx.

Please see the doc at
https://k2-fsa.github.io/sherpa/onnx/pretrained_models/offline-transducer/nemo-transducer-models.html#nemo-parakeet-tdt-transducer-110m

![Screenshot 2024-09-27 at 16 59 42](https://github.com/user-attachments/assets/9dceae57-67ea-4dae-a72c-63d3a3c323ef)


---

You can also try the exported models by visiting our huggingface space.
https://huggingface.co/spaces/k2-fsa/automatic-speech-recognition


![Screenshot 2024-09-27 at 16 52 10](https://github.com/user-attachments/assets/7e364436-3cdf-461c-aba0-c7523e87a52e)

![Screenshot 2024-09-27 at 16 52 51](https://github.com/user-attachments/assets/00e1ca08-9129-4a36-a691-7cbf26724d90)

**Comment by info-wordcab** [comment]
@csukuangfj Any parameters or techniques that you'd suggest for tackling very long audios (30 minutes to 3 hours)?
