### ISSUE TITLE
Decoding with Hotwords giving segmentation fault

### ISSUE THREAD

**Issue by chiragpatel39** [k2-fsa/sherpa-onnx#1388]
29166 Segmentation fault      python python-api-examples/online-decode-files.py --encoder $model_dir/encoder-epoch-19-avg-1.onnx --decoder $model_dir/decoder-epoch-19-avg-1.onnx --joiner $model_dir/joiner-epoch-19-avg-1.onnx --tokens $model_dir/tokens.txt --num-threads=1 --decoding-method=modified_beam_search --hotwords-file=local/hotwords.txt --modeling-unit bpe ${wav}"003".wav ${wav}"004".wav ${wav}"005".wav ${wav}"006".wav ${wav}"007".wav ${wav}"008".wav ${wav}"009".wav ${wav}"010".wav

My hotword file looks like:

VMO  :2.0
quarantine :2.0
remdesivir :2.0
oseltamivir :2.0
isolation  :2.0
n ninety five :2.0
NRBM :2.0

Regards,
Chirag Patel

**Comment by csukuangfj** [comment]
What is model_dir?

**Comment by csukuangfj** [comment]
Also, are you able to reproduce the hotwords example in the documentation?

**Comment by csukuangfj** [comment]
Also, please tell us how to reproduce your issue. (You need to provide more details)

**Comment by chiragpatel39** [comment]
model_dir is the directory which contain checkpints of trained model. 
No I haven't tried with the model given in example. I am following example with our own model.
I will try the example with pre-trained model.

**Comment by csukuangfj** [comment]
If you want to debug it with your own model, please try to use C++ binaries. You can use `gdb` to debug it.

**Comment by vsd-vector** [comment]
I think this could related to my last merged PR (preserving context between endpointing). 

If it is, I will try to create fix as soon as possible.
