### ISSUE TITLE
指定模型路径时，考虑支持中文路径，统一使用utf8编码的路径

### ISSUE THREAD

**Issue by sandsc** [k2-fsa/sherpa-onnx#1406]
目前从源码来看, sherpa内部使用c++ ifstream来打开和读取文件，这个在windows平台上不支持带中文的utf8编码路径，需要把路径转换本地系统编码的多字节编码。

**Comment by csukuangfj** [comment]
请提供复现的例子。我的 windows 系统上，复现不了你的问题.

**Comment by sandsc** [comment]
用如下代码可以复现问题, msvc设置/utf8编译选项，设置你的源代码文件编码为utf8：
```
// 把模型放到带中文路径的文件夹下面, 我是使用qt开发，这里演示编码的如何不同导致模型加载失败
QString filepath = QString::fromUtf8((const char*)u8"d:\\中文路径\\sherpa-onnx-paraformer-zh-small-2024-03-09\\model.int8.onnx");

QByteArray model_file = filepath.toUtf8();  // 使用utf8编码路径，模型加载失败
// QByteArray model_file = filepath.toLocal8Bit();  //使用本地多字节编码，加载成功

SherpaOnnxOfflineParaformerModelConfig paraformer_config;
memset(&paraformer_config, 0, sizeof(paraformer_config));
paraformer_config.model = model_file; // QByteArray可隐示转换为const char*
```

**Comment by csukuangfj** [comment]
请用sherpa-onnx提供的代码复现，不要依赖其他第三方代码或者库

**Comment by sandsc** [comment]
更简单的可以用如下代码测试
```
#include <fstream>
#include <iostream>
#include <string>

int main() {
    // 设置源代码编码为utf8，可以安全的强制转换, 在中文系统的windows平台下，应该会打开文件失败

    std::string filename((const char*)u8"中文路径");
    // open file for reading
    std::ifstream istrm(filename, std::ios::binary);
    if (!istrm.is_open())
        std::cout << "failed to open " << filename << '\n';
}
```
在windows平台下，包括c语言的fopen函数一般不支持utf8编码的路径，详见msdn的说明
[fopen](https://learn.microsoft.com/zh-cn/cpp/c-runtime-library/reference/fopen-wfopen?view=msvc-170)

> fopen 函数打开由 filename 指定的文件。 默认情况下，使用 ANSI 代码页 (CP_ACP) 解释窄 filename 字符串。 在 Windows 桌面应用程序中，可以通过使用 [SetFileApisToOEM](https://learn.microsoft.com/zh-cn/windows/win32/api/fileapi/nf-fileapi-setfileapistooem) 函数将它更改为 OEM 代码页 (CP_OEMCP)。 可以使用 [AreFileApisANSI](https://learn.microsoft.com/zh-cn/windows/win32/api/fileapi/nf-fileapi-arefileapisansi) 函数来确定是使用 ANSI 还是系统默认的 OEM 代码页来解释 filename。 _wfopen 是 fopen 的宽字符版本；_wfopen 参数是宽字符串。 除此以外， _wfopen 和 fopen 的行为完全相同。 仅使用 _wfopen 不会影响在文件流中使用的编码字符集。

**Comment by csukuangfj** [comment]
> 在中文系统的windows平台下，应该会打开文件失败

那你如何在代码里检测是中文系统？中文系统是否可以设置 utf8 编码？

C++ 默认用 utf8 编码字符串，可以告诉我们你上面用 `u8` 的理由么？

你加了个应该， 是否有真的测试过？


请看下图，设置用 utf8 编码。
![image](https://github.com/user-attachments/assets/1cffb471-10c8-487a-8870-60db6dc4286e)

**Comment by csukuangfj** [comment]
回到问题本身，我们有提供pre-built binary, 比如 build/bin/sherpa-onnx, 你是否有用它测试，指定中文路径，会失败？

一行代码都不需要你改，你只需要动动手，打开一个命令行，然后按照文档，下载一个模型，跑一下就可以知道结果。

**Comment by sandsc** [comment]
> 回到问题本身，我们有提供pre-built binary, 比如 build/bin/sherpa-onnx, 你是否有用它测试，指定中文路径，会失败？
> 
> 一行代码都不需要你改，你只需要动动手，打开一个命令行，然后按照文档，下载一个模型，跑一下就可以知道结果。

您好，感谢回复，我已经测试了，而且我己经将sherp-onnx集成到软件里面了，非常棒的工作。

我使用utf-8编码的中文路径加载模型确实会失败，我的系统区域设置里面没有勾选utf-8选项（一般用户应该都没有勾选），此时windows默认编码应该是gb2312，utf8编码的string字符串确实却导致会导致模型无法加载，不过这也可能我们的软件字符串编码有关系，我们所有的字符串都使用utf-8编码，而不依赖系统的设定，所以才会导致此问题。

我想说的是，如果咱们对文件名没有编码要求，那么对参数filename的编码解析会依赖操作系统的设定，那么不同的操作系统环境对filename有不同的编码要求，而且如下代码：
`const char* file="中文"；`
此时file的编码还和你的源代码文件的编码有关系，如果file编码和系统编码不一致，会导致模型加载失败。

**Comment by csukuangfj** [comment]
C++ 默认的字符串编码是 utf8.

如果你使用的我们的 api, 你传入的字符串，使用 utf8 编码的话，就不会有任何的问题。

建议你在调用 sherpa-onnx 的 api 时，自己保证，传入的字符串是 utf8 编码。

**Comment by sandsc** [comment]
> C++ 默认的字符串编码是 utf8.
> 
> 如果你使用的我们的 api, 你传入的字符串，使用 utf8 编码的话，就不会有任何的问题。
> 
> 建议你在调用 sherpa-onnx 的 api 时，自己保证，传入的字符串是 utf8 编码。

c++ 字符串常量并不是默认使用utf8编码，这和你的源代码编码以及编译器设置有关，请参考
[char* encoding](https://stackoverflow.com/questions/9739070/char-encoding)

**Comment by csukuangfj** [comment]
> c++ 字符串常量并不是默认使用utf8编码

我们只支持 utf8.

你保证传入给 sherpa-onnx 的字符串，是 utf8 编码的，即可。

**Comment by csukuangfj** [comment]
》 c++ 字符串常量并不是默认使用utf8编码

你这个是由你的 ide 决定的。和 c++ 没关系。

**Comment by sandsc** [comment]
> > c++ 字符串常量并不是默认使用utf8编码
> 
> 我们只支持 utf8.
> 
> 你保证传入给 sherpa-onnx 的字符串，是 utf8 编码的，即可。

我看源代码使用ifstream来读取文件，这个函数在windows平台上，并不总是支持utf8编码的字符串，和系统设置有关。

**Comment by csukuangfj** [comment]
> 我看源代码使用ifstream来读取文件，这个函数在windows平台上，并不总是支持utf8编码的字符串，和系统设置有关

我就只有一个问题，如果你传入给 sherpa-onnx 的字符串，如果是 utf8 编码，你有碰到问题么？

**Comment by sandsc** [comment]
> > 我看源代码使用ifstream来读取文件，这个函数在windows平台上，并不总是支持utf8编码的字符串，和系统设置有关
> 
> 我就只有一个问题，如果你传入给 sherpa-onnx 的字符串，如果是 utf8 编码，你有碰到问题么？

有问题的，上面已经给了代码了，使用QString的toUtf8明确给的utf8编码的char*字符串，模型加载失败。
>
```// 把模型放到带中文路径的文件夹下面, 我是使用qt开发，这里演示编码的如何不同导致模型加载失败
QString filepath = QString::fromUtf8((const char*)u8"d:\\中文路径\\sherpa-onnx-paraformer-zh-small-2024-03-09\\model.int8.onnx");

QByteArray model_file = filepath.toUtf8();  // 使用utf8编码路径，模型加载失败
// QByteArray model_file = filepath.toLocal8Bit();  //使用本地多字节编码，加载成功

SherpaOnnxOfflineParaformerModelConfig paraformer_config;
memset(&paraformer_config, 0, sizeof(paraformer_config));
paraformer_config.model = model_file;```

**Comment by csukuangfj** [comment]
> 有问题的，上面已经给了代码了，使用QString的toUtf8明确给的utf8编码的char*字符串，模型加载失败。


请自己在sherpa-onnx 里面的代码，把你传入的字符串的每个字节都打印出来， 看是否真的传入的是 utf8 编码的字符串

**Comment by sandsc** [comment]
可以用别的方式解决，不影响使用

**Comment by sandsc** [comment]
暂时用别的方式解决，不影响使用

**Comment by zhouzhili** [comment]
@sandsc 老哥，咋解决的，我也遇到了中文路径问题
