### ISSUE TITLE
Hi, support whipser-large-v3-turbo is possible?

### ISSUE THREAD

**Issue by MonolithFoundation** [k2-fsa/sherpa-onnx#1419]
Hi, support whipser-large-v3-turbo is possible?

**Comment by csukuangfj** [comment]
already supported.

**Comment by MonolithFoundation** [comment]
@csukuangfj  Does the turbo model link updated?

**Comment by csukuangfj** [comment]
Of course.

Please see https://github.com/k2-fsa/sherpa-onnx/releases/tag/asr-models

**Comment by MonolithFoundation** [comment]
@csukuangfj Do u think whisper-v3-turbo better than Sensevoice in your experience?

**Comment by csukuangfj** [comment]
please test it by yourself.

**Comment by MonolithFoundation** [comment]
thank u.
