### ISSUE TITLE
issue with nemo models

### ISSUE THREAD

**Issue by RGdevz** [k2-fsa/sherpa-onnx#1422]
Hey, I noticed a problem when using nemo models (checked only the offline variants) when the audio duration is somewhere in the 6:50 long range its crash with this error:

`sequential_executor.cc:514 onnxruntime::ExecuteKernel] Non-zero status code returned while running And node. Name:'/And_1' Status Message: C:\a\_work\1\s\onnx
runtime\core/providers/cpu/math/element_wise_ops.h:540 onnxruntime::BroadcastIterator::Init axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 5000 by 10
279
`

I used version [v1.10.27](https://github.com/k2-fsa/sherpa-onnx/releases/tag/v1.10.27) and see the same crash happen in pc and in android. I added the sound files to the issue (in mp3 format because wav are too large).
[sound.zip](https://github.com/user-attachments/files/17349799/sound.zip)

**Comment by csukuangfj** [comment]
Could you post the detailed command you are using?

**Comment by csukuangfj** [comment]
By the way, for the offline models, i.e., non-streaming models, we suggest that you don't input audio more than 30 seconds.

**Comment by RGdevz** [comment]
Oh I thought that this limitation of the whispers models, this is the settings I using in android

`  FeatureConfig featureConfig = FeatureConfig.builder().setFeatureDim(80).setSampleRate(16000).build();

    OfflineModelConfig modelConfig = OfflineModelConfig.builder().setModelType("nemo_transducer")
      .setTransducer(OfflineTransducerModelConfig.builder().setDecoder("nemo/decoder.onnx")
        .setEncoder("nemo/encoder.onnx")
        .setJoiner("nemo/joiner.onnx")
        .build())

      .setTokens("nemo/tokens.txt")
      .build();

    OfflineRecognizerConfig config = new OfflineRecognizerConfig.Builder()
      .setOfflineModelConfig(modelConfig)
      .setFeatureConfig(featureConfig)
      .build();`

**Comment by RGdevz** [comment]
I tried others offline models too and the crash is happening only in nemo

**Comment by csukuangfj** [comment]
For all non-streaming models, please don't input long audio files.

You can use VAD + ASR for long audio files. Please see

- https://github.com/k2-fsa/sherpa-onnx/tree/master/android/SherpaOnnxVadAsr
- https://github.com/k2-fsa/sherpa-onnx/blob/master/python-api-examples/generate-subtitles.py

**Comment by RGdevz** [comment]
With vad we can't get the correct timestamp of the words in the audio which I need, I might just split the audio to smaller chunks or something
