### ISSUE TITLE
使用go编译时报错：undefined: SherpaOnnxOfflineSpeakerDiarizationSetConfig

### ISSUE THREAD

**Issue by LucisXu** [k2-fsa/sherpa-onnx#1429]
报错内容
`# github.com/k2-fsa/sherpa-onnx-go-macos
../../../../go/pkg/mod/github.com/k2-fsa/sherpa-onnx-go-macos@v1.10.28/sherpa_onnx.go:1286:2: undefined: SherpaOnnxOfflineSpeakerDiarizationSetConfig`

似乎sherpa-onnx-go-macos@v1.10.28源码中并没有定义SherpaOnnxOfflineSpeakerDiarizationSetConfig，另外其他平台应该也有这个问题

**Comment by csukuangfj** [comment]
Thanks for reporting.

Please use `sherpa-onnx-go v1.8.11`, which will use the latest version `sherpa-onnx-go-macos v1.10.29-alpha`
