### ISSUE TITLE
（rk3568）嵌入式linux-aarch64，交叉编译使用阿里的sensevoice-small

### ISSUE THREAD

**Issue by stelldogone** [k2-fsa/sherpa-onnx#1430]
目的：我希望在rk3568上部署离线的sensevoice-small
https://k2-fsa.github.io/sherpa/onnx/install/aarch64-embedded-linux.html
我根据这个网址的教程，我交叉编译了sherpa-onnx，然后我将生成的动态库传输进了嵌入式系统
上述文档提到的运行二进制文件使用的命令为
./sherpa-onnx-alsa \
  --encoder=./sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20/encoder-epoch-99-avg-1.onnx \
  --decoder=./sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20/decoder-epoch-99-avg-1.onnx \
  --joiner=./sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20/joiner-epoch-99-avg-1.onnx \
  --tokens=./sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20/tokens.txt \
  plughw:3,0

参考这个命令和https://k2-fsa.github.io/sherpa/onnx/sense-voice/pretrained.html#decode-a-file-with-model-onnx
阿里提供的sensevoice文档里提到的运行模型的指令
./build/bin/sherpa-onnx-offline \
  --tokens=./sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17/tokens.txt \
  --sense-voice-model=/Users/fangjun/open-source/sherpa-onnx/scripts/sense-voice/model.onnx \
  --num-threads=1 \
  --debug=0 \
  ./sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17/test_wavs/zh.wav \
  ./sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17/test_wavs/en.wav

我最终根据我存储lib的位置修改出了一个指令
./install/bin/sherpa-onnx-offline \
  --tokens=/home/tokens.txt \
  --sense-voice-model=/home/model.int8.onnx \
  --num-threads=1 \
  --sense-voice-use-itn=1 \
  --debug=0 \
  /home/example/zh.mp3 \
plughw:2,0

![1728899697762](https://github.com/user-attachments/assets/f6b35249-f8ee-4f4c-b84a-ef7d61f3b5dd)
但是在命令行运行会出现如上图片中的问题
![1728899963869](https://github.com/user-attachments/assets/547c90b6-27f9-40d8-912c-5bea6f1f5280)
我在仔细查看参考文档的时候发现，教程中有提到，lib复制到嵌入式系统上要和在虚拟机上的路径一致？这不应该吧
具体错误原因我无法获取，希望有移植过这个模型的大哥能提供帮助

有偿，如果是公司，也可以商单形式联系我们，公司：深圳玄智科技
我的qq：2272271，万分感谢

**Comment by csukuangfj** [comment]
> 参考这个命令和https://k2-fsa.github.io/sherpa/onnx/sense-voice/pretrained.html#decode-a-file-with-model-onnx
阿里提供的sensevoice文档里提到的运行模型的指令
./build/bin/sherpa-onnx-offline
--tokens=./sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17/tokens.txt
--sense-voice-model=/Users/fangjun/open-source/sherpa-onnx/scripts/sense-voice/model.onnx
--num-threads=1
--debug=0
./sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17/test_wavs/zh.wav
./sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17/test_wavs/en.wav

你这个命令，能否跑成功？

**Comment by csukuangfj** [comment]
>. 我最终根据我存储lib的位置修改出了一个指令
./install/bin/sherpa-onnx-offline
--tokens=/home/tokens.txt
--sense-voice-model=/home/model.int8.onnx
--num-threads=1
--sense-voice-use-itn=1
--debug=0
/home/example/zh.mp3
plughw:2,0

这个命令是错误的。

sherpa-onnx-offline, 是识别文件，你不能指定一个麦克风设备

你可以试试 sherpa-onnx-offline-microphone.

**Comment by csukuangfj** [comment]
请先复现文档里的命令，复现完后，再自己修改。

**Comment by stelldogone** [comment]
我编写了一个helloworld验证了我的交叉编译是成功的
，目前正在下载文档中的模型来验证，但是下载速度很慢
于是选择一边下载一边继续尝试sensevoice
![1728907242977](https://github.com/user-attachments/assets/18d84fb8-b860-443d-80c3-ee51ca5e9bde)
我发现报错中提到/tmp/sherpa-onnx/sherpa-onnx/csrc
这个目录在我编译最后生成的文件夹里有出现
我目前是只将sherpa-onnx的二进制文件，也就是sherpa-onnx-offline，以及模型，和测试音频，复制到我的嵌入式设备中
其余的文件我是没有放入的，请问还需要把其他文件放进去吗？

**Comment by csukuangfj** [comment]
你的 tokens.txt 和 model.onnx, 是否是来自同一个压缩包？

还有，建议你用解压后的model.int8.onnx

**Comment by csukuangfj** [comment]
请不要乱用  tokens.txt 和 model.onnx

请完全按照文档来，不要重命名模型文件夹。

你跑了没问题，再去重命名。

**Comment by stelldogone** [comment]
是的，来自同一个压缩包

**Comment by stelldogone** [comment]
文档中提到的模型下载速度非常慢，请问有什么办法加快速度吗

**Comment by stelldogone** [comment]
或者您方便提供一下模型吗

**Comment by csukuangfj** [comment]
需要你自己按照文档的链接下载。

网络问题，需要你自己解决。

**Comment by csukuangfj** [comment]
> 是的，来自同一个压缩包

请把 tokens.txt 发过来，我来检查下。

或者，你计算tokens.txt de  md5 哈希值，然后发过来。

请把模型的哈希值，也发过来.

**Comment by stelldogone** [comment]
![image](https://github.com/user-attachments/assets/6e4ee215-2ad7-41a0-af60-d2db9a9f41cb)
![image](https://github.com/user-attachments/assets/bbecb3e6-13a8-4953-b410-7fd4b91b13fe)
![image](https://github.com/user-attachments/assets/5ab36cf1-b148-4c7c-965b-803e5b07dbb7)
我应该只需要把sherpa-onnx这部分移入我的设备吧

**Comment by csukuangfj** [comment]
》 我应该只需要把sherpa-onnx这部分移入我的设备吧

如果你是静态链接，那么，就是的.

---

请回答上面我的问题，我需要看 tokens.txt 和 model.onnx  的哈希值。

**Comment by stelldogone** [comment]
c71f0ce00bec95b07744e116345e33d8cbbe08cef896382cf907bf4b51a2cd51  model.int8.onnx
f449eb28dc567533d7fa59be34e2abca8784f771850c78a47fb731a31429a1dc  tokens.txt

**Comment by stelldogone** [comment]
![1728956303079](https://github.com/user-attachments/assets/26fc77f5-1940-462e-b34c-5bd62ac5dbd3)
我测试了文档里的模型，是可以的，但是是韩语的，而且感觉速度很慢，虽然上面显示时间是3.6s，但是我实际等待的时间超过30s，而且这证明我无法使用阿里的sensevoice还是因为模型参数的问题，还希望您能提供帮助

**Comment by csukuangfj** [comment]
> 但是我实际等待的时间超过30s

说明你的板子，读内存，非常慢。

这个统计的时间，没有包括模型初始化的时间

**Comment by stelldogone** [comment]
所以，其实只要我之后使用c的api提前初始化模型，就不会有这么久的延时，是吧

**Comment by stelldogone** [comment]
但是我对于sensevoice的问题还是得不到解决，希望大哥您能帮帮忙

**Comment by stelldogone** [comment]
不知道大哥在哪里高就，如果有商单意向，也可以联系我们，我们是深圳玄智科技，正在开发一款聊天陪伴机器人，语音模型使用的讯飞提供的，但是效果不是很好，其他功能都开发完毕了，现在属于优化阶段，如果您能提供优秀模型，我们也可以商单详谈

**Comment by csukuangfj** [comment]
> f449eb28dc567533d7fa59be34e2abca8784f771850c78a47fb731a31429a1dc

你的 model.int8.onnx 和我的不一样

<img width="1189" alt="Screenshot 2024-10-15 at 10 28 10" src="https://github.com/user-attachments/assets/c9c7b9a9-38f6-4361-be9e-2244f4387e73">


```
(py38) fangjuns-MacBook-Pro:sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17 fangjun$ shasum -a 256 model.int8.onnx tokens.txt
7ecac382a297cfe10dd23604b470f26f3e65a29c0775cd5f2bd26a52a1075a02  model.int8.onnx
f449eb28dc567533d7fa59be34e2abca8784f771850c78a47fb731a31429a1dc  tokens.txt
```

请确保你没有用错文件，或者没有下载错文件，或者没有用混。tokens.txt 不是通用的.

**Comment by csukuangfj** [comment]
我又看了下代码，你是不是编译的时候，使用了
```
-DCMAKE_BUILD_TYPE=Debug
```

**Comment by csukuangfj** [comment]
> ![1728956303079](https://private-user-images.githubusercontent.com/107794988/376425186-26fc77f5-1940-462e-b34c-5bd62ac5dbd3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NTg2OTUsIm5iZiI6MTcyODk1ODM5NSwicGF0aCI6Ii8xMDc3OTQ5ODgvMzc2NDI1MTg2LTI2ZmM3N2Y1LTE5NDAtNDYyZS1iMzRjLTViZDYyYWM1ZGJkMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQwMjEzMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNGU1YmRiNDZhMzVkOTVmMGUwODZkMTQzOWQ2N2RhMTJiNTlhYjFhOTFhOGE5ZmMyY2Q4N2MxODA0NmI0NzkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.I2VF9vjNgYYyiSHz1Ti5Ze7THq0ImyM-pwYaEhhIGJ8) 我测试了文档里的模型，是可以的，但是是韩语的，而且感觉速度很慢，虽然上面显示时间是3.6s，但是我实际等待的时间超过30s，而且这证明我无法使用阿里的sensevoice还是因为模型参数的问题，还希望您能提供帮助

你这里的 decoder, 用了 int8.onnx.

建议你按照文档来，文档里的例子, 没有对 decoder 使用 int8.onnx
![Screenshot 2024-10-15 at 10 40 04](https://github.com/user-attachments/assets/82bea53e-44c0-407b-85d0-6ba55d7d6638)

**Comment by csukuangfj** [comment]
我本地编译了 Debug 版本，也复现不了你的问题。

请在你的板子上计算你使用的 tokens.txt 的哈希值，并把截图截图发过来。

**Comment by stelldogone** [comment]
![image](https://github.com/user-attachments/assets/41959afc-02d6-4704-8d1b-87304759e426)
我又测试了一个中文模型，虽然效果没有文档中的好，但是也算凑活，

我确实没注意到decoder用的不是int8，我现在修改看看

阿里的sensevoice似乎并没有encoder和decoder的说法

我是要计算阿里的tokens的哈希值吗，稍等

当然非常感谢您的帮助

**Comment by csukuangfj** [comment]
你自己和这里的哈希值对比一下，找找哪里不同？并告诉我们导致不同的原因？

> c71f0ce00bec95b07744e116345e33d8cbbe08cef896382cf907bf4b51a2cd51 model.int8.onnx f449eb28dc567533d7fa59be34e2abca8784f771850c78a47fb731a31429a1dc tokens.txt

**Comment by stelldogone** [comment]
好的，我找找看，非常感谢

**Comment by csukuangfj** [comment]
> 好的，我找找看，非常感谢

解决了没有呢？

**Comment by stelldogone** [comment]
还是不行，还是找不到为什么sensevoice不行，而其他的中文模型可以
其实我不太理解您叫我对比sensevoice的tokens.txt的哈希与其他中文模型的哈希的意义
而且我发现sensevoice似乎是非流式的，这对于长对话影响似乎很大
我目前是想先将c-api跑通，这样方便我测试速度
后续再考虑更换其他模型或者是sensevoice
顺带，我想请教大哥有没有比较推荐的语音识别的模型
最好是流式的，且带多国语言的

**Comment by csukuangfj** [comment]
> 其实我不太理解您叫我对比sensevoice的tokens.txt的哈希与其他中文模型的哈希的意义


意思是，你用错了 tokens.txt 文件。

你在板子上跑 sensevoice small 模型的时候，用错了 tokens.txt 


之所以说用错了，是因为我已经让你对比 哈希值了。你两次贴的哈希值不一样。

上面让你去对比哈希值为什么不一样，你现在都还没回答我。

**Comment by csukuangfj** [comment]
> 我又看了下代码，你是不是编译的时候，使用了
> 
> ```
> -DCMAKE_BUILD_TYPE=Debug
> ```

还有，这个问题，你也没有回答我。

请回答上面提出的每一个问题，谢谢配合。

**Comment by stelldogone** [comment]
![image](https://github.com/user-attachments/assets/f022edd1-9dfe-4892-bec9-a417ed9ca4f3)
nishi你是说这两个哈希值吗，好像还真是，同一个文件，同一个编码方式，还真有可能是我放错了，我再重新下载试试

**Comment by csukuangfj** [comment]
流式识别，推荐

https://k2-fsa.github.io/sherpa/onnx/pretrained_models/online-transducer/zipformer-transducer-models.html#csukuangfj-sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20-bilingual-chinese-english

建议你先在 pc 机上测试。

跑通后，没问题，再去板子上跑。

去板子上跑的时候，请不要犯低级错误，记得使用正确的文件。

**Comment by csukuangfj** [comment]
> > 我又看了下代码，你是不是编译的时候，使用了
> > ```
> > -DCMAKE_BUILD_TYPE=Debug
> > ```
> 
> 还有，这个问题，你也没有回答我。
> 
> 请回答上面提出的每一个问题，谢谢配合。

再次重复一下，请回答这个。

**Comment by stelldogone** [comment]
好的，我正在查找，当时交叉编译看的文档，当时的文档被我关闭了，我找找看

**Comment by stelldogone** [comment]
![image](https://github.com/user-attachments/assets/0da9f0b1-59d4-4916-b094-0f70874db79b)
https://k2-fsa.github.io/sherpa/onnx/install/aarch64-embedded-linux.html
我是使用的交叉编译的工具链，安装完工具链后，使用的写好的脚本直接执行编译的，并没有debug这个参数

**Comment by csukuangfj** [comment]
你的 error log
![image](https://github.com/user-attachments/assets/20236d5e-de62-4ab3-8dbc-a82be64820e0)

显示，是下面的代码出现的错误

https://github.com/k2-fsa/sherpa-onnx/blob/77dd5f73fc1fffab5f65b360e879a0bfd86a4e14/sherpa-onnx/csrc/symbol-table.cc#L54

这个行代码，用了 `assert`, 只有在 debug 模式，才会被编译。

---

你还是去找找为什么你的 tokens.txt 两次哈希值不一样吧。

还有，请先在 pc 机上测试。

**Comment by stelldogone** [comment]
![image](https://github.com/user-attachments/assets/22147ce7-a958-471b-802a-35a53eda2255)
![image](https://github.com/user-attachments/assets/d255f3a7-9540-47d2-b188-3666b6468c2a)
大哥，你好
应我们部门主管要求，想先测试这个中文流式模型在板子上用api运行的效果
按照文档，我应该是修改这份makefile，以及其中给出的示例c文件，编译后即可使用吧
我比较疑惑的是，makefile中有链接许多库，存放的位置不一
但是实际我的的编译文件中的install目录下（如图）是有将所有需要的库放置进去的，我如果使用动态库，是否是只需要链接动态和h文件就可以了

**Comment by csukuangfj** [comment]
这个是文档，你看一下这个文档？
https://k2-fsa.github.io/sherpa/onnx/c-api/index.html

可以删掉 cargs.h 和libcargs.so, 你用不到的。

切记，按照文档来，不然，你又会出错。

举个例子，这么多 .a 文件，如何确定它们的链接顺序？

---

我现在比较关系的是，你是否成功运行了 sensevoice 模型？

**Comment by stelldogone** [comment]
主管催的比较急，要我先进行这个模型的c-api部署，后续我也会尝试sensevoice的，谢谢大哥
还有，动态库和静态库不是一个就够了吗，我必须要使用这个静态库吗？

**Comment by csukuangfj** [comment]
> 主管催的比较急，要我先进行这个模型的c-api部署，后续我也会尝试sensevoice的，谢谢大哥 还有，动态库和静态库不是一个就够了吗，我必须要使用这个静态库吗？

不是必须。

我们都支持，由你自己选择，用哪个。

它们的 优缺点，你自行 google.

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/sherpa-onnx/blob/77dd5f73fc1fffab5f65b360e879a0bfd86a4e14/CMakeLists.txt#L27

这个选项，默认是 OFF, 即编译静态库。

你打开它，就是编译动态库

请参考文档
https://k2-fsa.github.io/sherpa/onnx/install/aarch64-embedded-linux.html

---

总之一句话，就是多看文档。文档里可以找得到答案的，请自己解决。

**Comment by stelldogone** [comment]
好的，非常感谢大哥

**Comment by stelldogone** [comment]
![image](https://github.com/user-attachments/assets/cfde7dc0-9c21-4345-b258-d5ad4e5383fd)
![image](https://github.com/user-attachments/assets/9c07f3a5-604a-4684-8e5d-f3f136f55ced)
大哥，我已经成功编译一个c-api，且可以运行成功了，本来是想在这个基础上修改代码的
但是我最终目的还是麦克风拾音，然后实时识别，我如果基于这个c-api是不是还得加进去vad的模型
然后发现有个bin文件的vad-alsa，完全符合我的需求，因此想先测试这个bin文件，然后再根据这个api来完成后续代码
先测试了alsa这个bin文件
我的麦克风是card2，之前有用这个麦克风获取数据给讯飞的模型识别，是能保证麦克风没问题的，但是实际bin文件启动后并没有文字转出，想询问一下原因
![image](https://github.com/user-attachments/assets/d692ed56-c2d3-47ef-8634-81560892cb14)
按照这个教程，我图一的命令应该没有错误吧
还望您能抽空指点一下
再次感谢您

**Comment by csukuangfj** [comment]
你先用 arecord 命令行去录音，验证你的麦克风有没有问题。

如果没问题，请把你运行的 arecord 命令发过来。

**Comment by stelldogone** [comment]
录音应该是没问题，因为我之前跑过讯飞的模型，也用命令行录用音，听过，一整套链路都是正常的

**Comment by csukuangfj** [comment]
请回答问题。并把录音命令和录下来的音频文件，发过来了。我们来检查一下

**Comment by stelldogone** [comment]
好的

**Comment by stelldogone** [comment]
[录音.zip](https://github.com/user-attachments/files/17388244/default.zip)
![image](https://github.com/user-attachments/assets/2513f0d7-a9c6-40b6-82ec-6f72634ce3f2)
我们的麦克风是8通道，cll1是8通道合一的音频，所以能听到杂音
后面的是第7通道的音，回声消除后的正常音频
alsa命令行调用的音频可能是全部的音频给到模型，但是应该不影响吧，因为也是能听清人声的

**Comment by stelldogone** [comment]
额，刚刚发现ffmpeg转第7通道参数忘改了，转的是之前的其他音频，但是也差不多，您有要求，我可以在转一段

**Comment by csukuangfj** [comment]
首先，你这个是8通道的麦克风，那sherpa-onnx-alsa 录音的时候，用了几个通道录音，然后用哪一个通道去识别呢？

**Comment by stelldogone** [comment]
![image](https://github.com/user-attachments/assets/3d8ca55e-8b5c-4c1e-9a85-64472519d0ad)
![image](https://github.com/user-attachments/assets/9c95fe3b-ba99-46f0-aa15-91166faff525)
刚才闲着测试了一下sensevoice，跑起来了，还真是之前模型和tokens不匹配

**Comment by stelldogone** [comment]
sherpa-onnx-alsa是封装了的bin文件，我好像无法知道他里面具体的代码
我只知道他通过alsa这个库获取了我的麦克风信息

**Comment by csukuangfj** [comment]
关于录音这个问题，至少有两种解决方法：

1. 换一个单通道的麦克风。
2. 修改如下代码

https://github.com/k2-fsa/sherpa-onnx/blob/77dd5f73fc1fffab5f65b360e879a0bfd86a4e14/sherpa-onnx/csrc/alsa.cc#L76
改成
```
err = snd_pcm_hw_params_set_channels(capture_handle_, hw_params, 1); 
actual_channel_count_ = 8;
```

然后
https://github.com/k2-fsa/sherpa-onnx/blob/77dd5f73fc1fffab5f65b360e879a0bfd86a4e14/sherpa-onnx/csrc/alsa.cc#L21
改成
```
 (*out)[k] = in[i + 6] / 32768.; 
```

然后重新编译。

**Comment by stelldogone** [comment]
很抱歉上一个问题还没能答复您就又问不合理的问题
我还是想问问
sensevoice有办法做成流式吗
按照他这个转换时间0.42
如果非流式，我说话稍微长一些，岂不是就有很长的等待时间
我如果在vad内擅自按数据长度截断，是不是很容易造成识别不准？

**Comment by csukuangfj** [comment]
请用最新修改后的评论。

**Comment by csukuangfj** [comment]
》 sensevoice有办法做成流式吗

目前没有。

你可以用 vad + asr 的方式。

**Comment by csukuangfj** [comment]
> ![image](https://private-user-images.githubusercontent.com/107794988/376864288-3d8ca55e-8b5c-4c1e-9a85-64472519d0ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNDYwNjEsIm5iZiI6MTcyOTA0NTc2MSwicGF0aCI6Ii8xMDc3OTQ5ODgvMzc2ODY0Mjg4LTNkOGNhNTVlLThiNWMtNGMxZS05YTg1LTY0NDcyNTE5ZDBhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNlQwMjI5MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYWQ0NzY4OWQzN2IzMjA5NmM5MzY3YTlkNWQwNjMyNDExMWE4YTM4MGE5ZDNmNWQ0NmJmNDJmOGUxY2EwYWU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nYDrdL-DpBjlRDRKR2m8FQ4Av1n09M2kGzko1LCOcwc) ![image](https://private-user-images.githubusercontent.com/107794988/376864360-9c95fe3b-ba99-46f0-aa15-91166faff525.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNDYwNjEsIm5iZiI6MTcyOTA0NTc2MSwicGF0aCI6Ii8xMDc3OTQ5ODgvMzc2ODY0MzYwLTljOTVmZTNiLWJhOTktNDZmMC1hYTE1LTkxMTY2ZmFmZjUyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNlQwMjI5MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzEzNmE3Y2Q3NjEzMjJiODYyOGIwM2JmY2JkMjcxZGNkZWRmNmVhNDgwZWExNDY4OGEzM2JmNGFmOTdiMDI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xZrFZo296ALq84cQYaIwKsUZH7IPByoqkhhCMsyFXD0) 刚才闲着测试了一下sensevoice，跑起来了，还真是之前模型和tokens不匹配

太棒啦！

**Comment by stelldogone** [comment]
我不太明白您的意思，vad不是声音活动检测吗，asr不是语音识别吗？这怎么让sensevoice分段识别呢
还是说您的意思是使用其他asr模型？

**Comment by csukuangfj** [comment]
请自己看文档，和代码里现成的例子。

**Comment by stelldogone** [comment]
好的好的，打扰大哥了，非常感谢

**Comment by csukuangfj** [comment]
友情提示，实现成的代码如下:

https://github.com/k2-fsa/sherpa-onnx/blob/master/sherpa-onnx/csrc/sherpa-onnx-vad-microphone-offline-asr.cc

这里有现成的 apk, 你可以在手机上去体验。
https://k2-fsa.github.io/sherpa/onnx/vad/apk-asr-cn.html

![Screenshot 2024-10-16 at 10 40 31](https://github.com/user-attachments/assets/aeb35c95-90e0-47da-86b3-ee94d67afa70)

**Comment by stelldogone** [comment]
好的好的

**Comment by csukuangfj** [comment]
> 按照他这个转换时间0.42


请认真看 log, 去理解这个数，到底代表什么意思.


> 如果非流式，我说话稍微长一些，岂不是就有很长的等待时间

对的，不然就不叫做非流式了。

> 我如果在vad内擅自按数据长度截断，是不是很容易造成识别不准？

对的。但是如果你不擅自，那就不影响。

**Comment by csukuangfj** [comment]
https://k2-fsa.github.io/sherpa/onnx/pretrained_models/online-transducer/zipformer-transducer-models.html#csukuangfj-sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20-bilingual-chinese-english

推荐你使用这个流式模型，边说边识别。

**Comment by stelldogone** [comment]
好的，谢谢

**Comment by stelldogone** [comment]
![image](https://github.com/user-attachments/assets/58659f74-f2c0-445a-b59a-85b1f941ac98)
![image](https://github.com/user-attachments/assets/531042e5-6e20-4dc7-ae4c-b6e962a432a6)
我按照您给的参数修改了alsa.cc，然后更换了您推荐的流式模型，
但是使用bin的时候会出现如下情况，似乎说我的RTF大于1，
![image](https://github.com/user-attachments/assets/b92401d9-f536-411d-90e0-801d0e7cf10c)
但是实际测试单个文件的时候又是可以的
![image](https://github.com/user-attachments/assets/2c35be74-65b0-4bcd-bfd9-a60f7418d84c)

**Comment by csukuangfj** [comment]
额， 你为什么不用一样的模型文件去测试？

**Comment by stelldogone** [comment]
两个模型文件都是你信推荐的那个

**Comment by stelldogone** [comment]
你说的是int8吗

**Comment by stelldogone** [comment]
我看文档里alsa推荐用不是int8的。。我现在正在试int8的alsa效果，但是每次加载模型速度都很慢，感觉都要几分钟

**Comment by csukuangfj** [comment]
encoder, joiner, 用 int8
decoder 不用 int8

你已经会测试 rtf 了。

**Comment by csukuangfj** [comment]
> 我看文档里alsa推荐用不是int8的。。我现在正在试int8的alsa效果，但是每次加载模型速度都很慢，感觉都要几分钟

这个慢，是你自己环境的问题。

建议你先在 pc 机上测试没问题，再去板子上测试.

**Comment by stelldogone** [comment]
![image](https://github.com/user-attachments/assets/db65c9c6-03be-461f-85bb-b0f708b6df3b)
用int8出来效果了，但是速度好慢

**Comment by csukuangfj** [comment]
你的板子，是什么cpu?

你用的是文档里的哪个模型？

**Comment by csukuangfj** [comment]
> 用int8出来效果了，但是速度好慢

可否录一个视频，看看你说的慢，是有多慢？

**Comment by stelldogone** [comment]
速度好像不是很慢，但是我只有很靠近他，才能识别，而且不是很准
我怀疑是我的录音设备mic增益很低
![image](https://github.com/user-attachments/assets/69073448-7d7d-4c5a-a629-932abe8eef6a)
但是之前用讯飞的模型，他们是要付费的，里面有参数设置拾音的能量阈值，导致效果还不错，（嘈杂环境识别效果不行，所以才想更换）
![image](https://github.com/user-attachments/assets/46cd9726-f048-4703-a8f9-9fc2ce02d41a)
但是我录了个音，用识别文件的bin去识别，发现能识别出，感觉音频文件又是没问题的，output_channel7就是之前发您的录音文件，用机器录的，且用ffmpeg转的第7通道
稍后我录给视频给您

**Comment by stelldogone** [comment]
[Uploading 飞书20241016-135205.zip…]()

**Comment by stelldogone** [comment]
是因为这个流式的bin文件代码里，有设置vad吗，然后他的vad阈值比较高？

**Comment by csukuangfj** [comment]
不好意思，下载不了。

**Comment by stelldogone** [comment]
[Uploading 飞书20241016-135205.zip…]()

**Comment by stelldogone** [comment]
如果也不行的，我后面可以自己尝试看看，都麻烦您也不好意思

**Comment by stelldogone** [comment]
我先尽可能尝试我觉得可行的思路
已经是万分感谢了

**Comment by csukuangfj** [comment]
建议上传完后，再点击评论按钮。不然，下载不了的。

**Comment by stelldogone** [comment]
原来是我没上传完就发了。。。

**Comment by csukuangfj** [comment]
可不可以说话，边录视频？

现在看到的是，说话的时候，没有录到屏幕。等录到屏幕的时候，已经看到识别结果了。没有体现出来慢.

**Comment by stelldogone** [comment]
速度应该还可以，现在的问题是远距离说话识别不到，只有对着麦克风讲才有用

**Comment by csukuangfj** [comment]
> 速度应该还可以，现在的问题是远距离说话识别不到，只有对着麦克风讲才有用

那就是你麦克风收音的问题。

建议你修改代码，把采集到的音频保存下来。看看识别不到的时候，保存的音频是什么样子的。

**Comment by stelldogone** [comment]
好的

**Comment by stelldogone** [comment]
[sherpa_onnx_model.zip](https://github.com/user-attachments/files/17406627/sherpa_onnx_model.zip)
大哥，上面是我自己写的应用程序，运行的时候能加载模型，但是无法翻译
我想再找您咨询一下
我的主要逻辑是麦克风的进程按照100ms3200字节采集数据（pcm，原始数据），然后用管道发送出来，并且根据这个文件描述符触发io事件
在io事件的回调里面，获取数据，先判断vad
如果有语音活动，就把数据发送模型处理，直到没有语音活动为止。
具体逻辑我会自己处理，我想问大哥的问题是

1.我输入模型的音频必须是wav格式的吗？（wav其实就是pcm加了44字节的帧头数据，帧头内包含了数据长度）如果我是一边采集音频一边发送给模型，那我其实是不知道数据长度的，那哪来这个帧头呢？
2.所以，我可以直接把pcm数据喂给模型吗？
3.我使用讯飞的模型时，是每10ms320字节向模型输送数据，我也按照这个速率给我们的模型可以吗？
4.暂时不着急处理的问题：模型加载还是太慢了，感觉甚至要几分钟，有办法提高这个速度吗？

**Comment by csukuangfj** [comment]
不好意思，没时间看代码。

请贴 error log

**Comment by csukuangfj** [comment]
我们有提供给你 api, 如果你使用我们的 api 报错，我们可以帮你。

如何写代码，需要你自己去做。

**Comment by stelldogone** [comment]
![image](https://github.com/user-attachments/assets/aa304367-9a57-4be3-855d-d98fdbec9515)

![image](https://github.com/user-attachments/assets/f731cc04-d201-4aa4-8b7a-029fbc5aa44e)
模型能加载的，但是也没有报错，也没有回复

**Comment by stelldogone** [comment]
所以我在想，会不会是输入的音频的格式问题，也就是我上面提到的第1点

**Comment by csukuangfj** [comment]
这个不归我们管了，需要你自己去排查。

例子代码你能跑通，就证明没问题了。后续都是你自己需要解决的问题。

**Comment by stelldogone** [comment]
大哥，代码部分我跑通了，但是模型加载速度超级慢，我记了下时间。彻底加载完，平均要3分钟，这个有办法解决吗，比如固定永久加载在内存里，什么的

**Comment by csukuangfj** [comment]
只需加载一次，这个算在初始化时间里

**Comment by stelldogone** [comment]
确实是算在开机时间里面，但是我们是聊天机器人，每次开机要加载3-4分钟也太久了

**Comment by csukuangfj** [comment]
加载速度慢，和你板子有非常大的关系。你可以换个环境，去测试下加载速度

**Comment by stelldogone** [comment]
![image](https://github.com/user-attachments/assets/e976d02c-de44-49ea-882a-f0454d55ae55)
我在想会不会是路径有点问题，或者编译器的问题？
我的当时在虚拟机编译的动态库，当时文件路径是放在tmp这个路径下的，
编译好后移到板子里放的另外的路径

或者是编译器版本？我的板子是rk3568，虽然也是aarch64的，但是我有看过，你们文档推荐的编译器和我们的不一样，我是用的你们的

我同事之前也用过这个模型，部署在树莓派上的，加载只要10几秒，按说两边性能没差那么大的
大哥，如果您有思路麻烦提点一下
当然，我这个问题确实比较不好解决，还是非常感谢大哥的

**Comment by csukuangfj** [comment]
> 加载速度慢，和你板子有非常大的关系。你可以换个环境，去测试下加载速度

请看这里

**Comment by csukuangfj** [comment]
你可以写一个c++ 程序，去加载一个100M 的文件，加载到内存，看需要多长时间。

用不同的板子去测试

**Comment by stelldogone** [comment]
https://modelscope.cn/models/iic/speech_eres2net_base_sv_zh-cn_3dspeaker_16k
大哥，冒昧问一下，魔塔社区上有不少模型，都是onnx格式的，像这种模型要怎么使用呢？

**Comment by csukuangfj** [comment]
请看
https://github.com/k2-fsa/sherpa-onnx/blob/master/c-api-examples/offline-speaker-diarization-c-api.c#L27
