### ISSUE TITLE
Flutter is not functioning properly in the iOS simulator.(v1.10.28)

### ISSUE THREAD

**Issue by bing6** [k2-fsa/sherpa-onnx#1433]
Flutter is not functioning properly in the iOS simulator.
All versions after 1.10.24 are not working, and the issue in the latest version 1.10.28 is:

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol 'SherpaOnnxCreateOfflineSpeakerDiarization': dlsym(0x72c60, SherpaOnnxCreateOfflineSpeakerDiarization): symbol not found
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33:70)
#1      SherpaOnnxBindings.init (package:sherpa_onnx/src/sherpa_onnx_bindings.dart:1273:10)
#2      initBindings (package:sherpa_onnx/sherpa_onnx.dart:57:22)

Currently, the library I am using on the iOS simulator is compiled from build-ios-shared.sh. Is it possible that the related scripts have not been updated, resulting in the compiled library lacking the corresponding implementation?

**Comment by csukuangfj** [comment]
> the library I am using on the iOS simulator is compiled from build-ios-shared.sh

Please describe which commit you  are using to build the lib.

**Comment by bing6** [comment]
@csukuangfj 

The last commit is: 77dd5f73.

The issue was identified; it was necessary to delete the previous build results. After deleting the build-ios-shared directory and performing the build again, all issues were resolved.

**Comment by csukuangfj** [comment]
> it was necessary to delete the previous build results

Yes, that is due to the following statements:

https://github.com/k2-fsa/sherpa-onnx/blob/77dd5f73fc1fffab5f65b360e879a0bfd86a4e14/build-ios-shared.sh#L77

https://github.com/k2-fsa/sherpa-onnx/blob/77dd5f73fc1fffab5f65b360e879a0bfd86a4e14/build-ios-shared.sh#L46

**Comment by csukuangfj** [comment]
please try the latest release v1.10.31.

You don't need to change any code to support the iOS simulator with flutter. @bing6
