### ISSUE TITLE
go使用gpu推理是否需要重新编译

### ISSUE THREAD

**Issue by LucisXu** [k2-fsa/sherpa-onnx#1435]
- 平台：intel芯片的macos
- 语言：go
- 模型：sense-voice-model

1. 当指定参数provider为`cpu`时，一切正常，但是把参数改为`cuda`后出现以下提示：

`/Users/runner/work/sherpa-onnx/sherpa-onnx/sherpa-onnx/csrc/session.cc:GetSessionOptionsImpl:170 Please compile with -DSHERPA_ONNX_ENABLE_GPU=ON. Available providers: CoreMLExecutionProvider, CPUExecutionProvider, . Fallback to cpu!
`
是否意味着假如使用GPU进行推理需要重新使用指定参数编译某些库呢？

2. 当把参数改为`coreml`时，则出现了报错：
`Context leak detected, CoreAnalytics returned false
Context leak detected, CoreAnalytics returned false
Context leak detected, CoreAnalytics returned false
Context leak detected, CoreAnalytics returned false
Context leak detected, CoreAnalytics returned false
2024/10/16 18:15:14.945474 Recognizer created!
2024/10/16 18:15:14.945497 Start decoding!
2024/10/16 18:15:15.436138 Decoding done!
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1068b9b1e]
`

**Comment by csukuangfj** [comment]
你电脑上有nividia 的gpu卡么？

**Comment by csukuangfj** [comment]
这里的cuda，只支持linux x64和Windows x64，不支持其他的系统

**Comment by LucisXu** [comment]
原来如此，我用的macos所以不行，晚一些用linux试试，感谢🙏
