### ISSUE TITLE
Android 动态的设置vad 参数 threshold，minSilenceDuration等参数，出现libc崩溃

### ISSUE THREAD

**Issue by solocoder-tech** [k2-fsa/sherpa-onnx#1445]
你好，我这边想动态的设置threshold、minSilenceDuration 参数。做法是，用户输入后，我 先调用 vad.release后，再次重新加载模型initVadModel。此时有概率出现崩溃。请问，so库能支持这样的操作吗？

**Comment by csukuangfj** [comment]
支持的.


建议发送logcat的全部log，不然，没人能帮助你。
