### ISSUE TITLE
 Expected sample rate 16000. Given: 8000

### ISSUE THREAD

**Issue by fatihyasar** [k2-fsa/sherpa-onnx#1447]
First of all, thank you for providing this wonderful platform. 

In nodejs-addon-examples, If I give sampleRate : 8000 . It gives an error.
`...silero-vad-model.cc:Impl:30 Expected sample rate 16000. Given: 8000`

There is a code block in silero-vad-model.cc as follows.

```
if (sample_rate_ != 16000) {
SHERPA_ONNX_LOGE("Expected sample rate 16000. Given: %d",
config.sample_rate);
exit(-1);
}
```

In this case, I guess I can't use sampleRate 8000. Is that right?

**Comment by csukuangfj** [comment]
Yes, please use audios with 16000Hz.


You can resample them beforehand.

**Comment by chinarui-na** [comment]
> Yes, please use audios with 16000Hz.
> 
> You can resample them beforehand.

i see silero_vad support 8k, but same error.

**Comment by csukuangfj** [comment]
> > Yes, please use audios with 16000Hz.
> > 
> > You can resample them beforehand.
> 
> i see silero_vad support 8k, but same error.


Wr only support the  16000Hz silero vad.  Please resample your audio.before sending them to silero vad in sherpa-onnx.
