### ISSUE TITLE
流式或非流式 ASR 识别过程中，是否支持多并发？

### ISSUE THREAD

**Issue by wanganddi0918** [k2-fsa/sherpa-onnx#1450]
根据 sherpa-onnx.cc 文件中的说明，得知可以通过调整 num_threads 参数来实现多线程操作以加速模型的运算。根据经验得知，在一个并发系统中，可以通过实现多线程来提高程序的并行度和响应性。那么在 sherpa-onnx 中是否支持多并发（multiple concurrency）呢？如果支持，有没有相关的参考文档呀

**Comment by csukuangfj** [comment]
这个是基本的 c/c++ 多线程知识，和是否使用 sherpa-onnx 没关系。

我们提供的是 api。

Recongizer 是thread safe 的, stream 不是 thread safe 的.


----

> 得知可以通过调整 num_threads 

这是用多少个线程，去跑神经网络模型，由 onnxruntime 控制。

---

建议你看下我们提供的 websocket server ， 是如何支持多并发的.
