### ISSUE TITLE
关于go api 流式语音识别模型标点符号支持

### ISSUE THREAD

**Issue by LucisXu** [k2-fsa/sherpa-onnx#1453]
使用模型`sherpa-onnx-streaming-paraformer-bilingual-zh-en`
运行了demo`go-api-examples/streaming-decode-files/main.go`
看起来识别结果是没有标点符号的，流式的识别是不是不支持呢？

另外`sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20-bilingual-chinese-english`这个模型是否更值得推荐用作流式识别呢？

**Comment by csukuangfj** [comment]
1. 标点是标点
2. 识别是识别
3. 你可以对识别出来后的文字，通过一个标点模型，去加标点。

----

目前我们只支持 whisper 和 sense voice, 它们的输出结果，直接带标点。其他模型，输出不带标点，你需要单独加一个标点模型。
请参考 go api 里，标点模型的用法。

**Comment by LucisXu** [comment]
感谢，go api中看起来目前还没有 OfflinePunctuation 相关demo。不过在python api中找到了可以参考的demo。

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/sherpa-onnx/blob/bcaa91ed36a76b2735e9ea308228d9c7bd93a584/scripts/go/sherpa_onnx.go#L1324-L1367L

API 都有了，你自己写例子？

![78028f98cf1ae20495e502ef74e1ae35](https://github.com/user-attachments/assets/b98863eb-d94c-405c-9b00-13e3301ea219)

**Comment by csukuangfj** [comment]
> 感谢，go api中看起来目前还没有 OfflinePunctuation 相关demo。不过在python api中找到了可以参考的demo。

已经有了。请看
https://github.com/k2-fsa/sherpa-onnx/tree/master/go-api-examples/add-punctuation

@LucisXu
