### ISSUE TITLE
sherpa-onnx ,websocket server 对于endpoint，timestamp，tokens的支持

### ISSUE THREAD

**Issue by cooldoomsday** [k2-fsa/sherpa-onnx#148]
目前，sherpa-onnx ,websocket server 还没有支持endpoint，timestamp，tokens。希望能够支持

**Comment by csukuangfj** [comment]
已经支持了，请用最新的 master

下面是一个例子

<img width="1376" alt="Screenshot 2023-08-31 at 14 41 32" src="https://github.com/k2-fsa/sherpa-onnx/assets/5284924/da2ac859-1b7f-4386-9d7c-e42f133bdbb8">
