### ISSUE TITLE
Speak Diarization with ASR

### ISSUE THREAD

**Issue by CSLukkun** [k2-fsa/sherpa-onnx#1487]
你好，想请教一个问题。

我希望将一个音频中的说话人进行分离。每一段切分的子音频 有开始时间，持续时间，说话的内容，以及说话人的id。
我不清楚在这个仓库中是否提供这样的功能。

感谢

**Comment by csukuangfj** [comment]
支持的

**Comment by CSLukkun** [comment]
您能提供一些实例 或者 指导给我吗？非常感谢

On Oct 28, 2024, at 18:52, Fangjun Kuang ***@***.***> wrote:



支持的

**Comment by csukuangfj** [comment]
请自己看我们的提供的文档。

我们有提供 speaker diarization的例子

有提供 asr 的例子

你自己组合起来，就是你想要的。
