### ISSUE TITLE
Use CUDA in colab

### ISSUE THREAD

**Issue by we11as22** [k2-fsa/sherpa-onnx#1489]
I am trying to launch OfflineRecognizer with cuda as a python in colab:
=================================================
!pip install sherpa-onnx==1.10.30+cuda -f https://k2-fsa.github.io/sherpa/onnx/cuda.html 

from pathlib import Path
from typing import List, Optional

from _sherpa_onnx import (
    FeatureExtractorConfig,
    OfflineCtcFstDecoderConfig,
    OfflineLMConfig,
    OfflineModelConfig,
    OfflineMoonshineModelConfig,
    OfflineNemoEncDecCtcModelConfig,
    OfflineParaformerModelConfig,
)
from _sherpa_onnx import OfflineRecognizer as _Recognizer
from _sherpa_onnx import (
    OfflineRecognizerConfig,
    OfflineSenseVoiceModelConfig,
    OfflineStream,
    OfflineTdnnModelConfig,
    OfflineTransducerModelConfig,
    OfflineWenetCtcModelConfig,
    OfflineWhisperModelConfig,
    OfflineZipformerCtcModelConfig,
)

recognizer_config = OfflineRecognizerConfig(
    feat_config=FeatureExtractorConfig(sampling_rate=16000, feature_dim=80, low_freq=20, high_freq=-400, dither=0), 
    model_config=OfflineModelConfig(transducer=OfflineTransducerModelConfig(
        encoder_filename="/content/sherpa-onnx-nemo-transducer-giga-am-russian-2024-10-24/encoder.int8.onnx", 
        decoder_filename="/content/sherpa-onnx-nemo-transducer-giga-am-russian-2024-10-24/decoder.onnx", 
        joiner_filename="/content/sherpa-onnx-nemo-transducer-giga-am-russian-2024-10-24/joiner.onnx"), 
        paraformer=OfflineParaformerModelConfig(model=""), 
                                    nemo_ctc=OfflineNemoEncDecCtcModelConfig(model=""), 
                                    whisper=OfflineWhisperModelConfig(encoder="", decoder="", language="", task="transcribe", tail_paddings=-1), 
                                    tdnn=OfflineTdnnModelConfig(model=""), 
                                    zipformer_ctc=OfflineZipformerCtcModelConfig(model=""), 
                                    wenet_ctc=OfflineWenetCtcModelConfig(model=""), 
                                    sense_voice=OfflineSenseVoiceModelConfig(model="", language="auto", use_itn=False), 
                                    moonshine=OfflineMoonshineModelConfig(preprocessor="", encoder="", uncached_decoder="", cached_decoder=""), 
                                    telespeech_ctc="", 
                                    tokens="/content/sherpa-onnx-nemo-transducer-giga-am-russian-2024-10-24/tokens.txt", 
                                    num_threads=1, # was 2 
                                    debug=False, 
                                    provider="cuda", 
                                    model_type="nemo_transducer", 
                                    modeling_unit="cjkchar", bpe_vocab=""), 
    lm_config=OfflineLMConfig(model="", scale=0.5), 
    ctc_fst_decoder_config=OfflineCtcFstDecoderConfig(graph="", max_active=3000), 
    decoding_method="greedy_search",
    max_active_paths=4, 
    hotwords_file="", 
    hotwords_score=1.5, 
    blank_penalty=0, 
    rule_fsts="", 
    rule_fars="")

recognizer = _Recognizer(recognizer_config)

But I see
===========================================
----> 1 recognizer = _Recognizer(recognizer_config)

RuntimeError: /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1209 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory

Guys, how can I fix it?

**Comment by csukuangfj** [comment]
please see the colab below

https://github.com/k2-fsa/colab/blob/master/sherpa-onnx%2FRun_distil_whisper_with_sherpa_onnx_on_GPU_ipynb.ipynb

**Comment by we11as22** [comment]
I have seen colab repo, but I need to use model to transcribe multiple files and calling pre-compilled C scrypts is not sutable for me because of spending time to create recognizer for each file.  
Is it possible to use  cuda in Python class?

**Comment by csukuangfj** [comment]
By the way, the following colab guides you step by step
https://github.com/k2-fsa/colab/blob/master/sherpa-onnx/sherpa_onnx_whisper_large_v3.ipynb
