### ISSUE TITLE
No Joiner in Model File

### ISSUE THREAD

**Issue by bijanbina** [k2-fsa/sherpa-onnx#1495]
I've downloaded several whisper model file like [sherpa-onnx-whisper-large-v3.tar.bz2](https://objects.githubusercontent.com/github-production-release-asset-2e65be/531380835/16d64a0f-da4c-4bbe-8c68-f391d5cfb3e9?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20241029%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241029T083806Z&X-Amz-Expires=300&X-Amz-Signature=4c4f4627b0da2bf76a0a7c317488641250eeddfe6d997ad752168534eb1192a6&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dsherpa-onnx-whisper-large-v3.tar.bz2&response-content-type=application%2Foctet-stream) but No Joiner file exist in Model File

**Comment by csukuangfj** [comment]
That is expected. Please see our doc for usages.

Hint: 
https://k2-fsa.github.io/sherpa/onnx/pretrained_models/whisper/large-v3.html
