### ISSUE TITLE
Windows Line Separator(\n\r) seems will cause sherpa offline tts to crash

### ISSUE THREAD

**Issue by tenggyut** [k2-fsa/sherpa-onnx#1496]
I am using the OfflineTts with the vits-piper-en_US-lessac-low model on Windows. My git convert the line separator from \n to \n\r automaticly when I pull changes from the remote repo, and then my android crashes at the OfflineTts newFromFile native call.

after I change the line separator back to \n, all works fine again!

please check

**Comment by csukuangfj** [comment]
@tenggyut 

Could you try #1497  ?

**Comment by tenggyut** [comment]
certainly!
