### ISSUE TITLE
onnx whisper rus model

### ISSUE THREAD

**Issue by vks2** [k2-fsa/sherpa-onnx#1503]
is there any chance to have a prebuilt onnx whisper large model with russian language? thanks much

**Comment by csukuangfj** [comment]
Does the existing whisper large support Russian?

By the way, we support GigaAM，which is dedicated for Russian ASR.

**Comment by vks2** [comment]
GigaAm is a model for short command-like speech on russian so it doesn't perform well over direct real-time  speech and dialogs. large v1 (v2 and v3 too) whisper seems to work with the russian model with --language Russian key. is it fully converted in onnx? btw, following your guidelines, what joiner i should use? I've found encoder, tokens and decoder at hugging face. thanks much for quick replies!

**Comment by csukuangfj** [comment]
please read our doc for whisper.

you don't need joiner for whisper at all.

**Comment by vks2** [comment]
thanks much. yes, i've seen, you made a huge job to reformat whisper. (i read that https://k2-fsa.github.io/sherpa/onnx/spoken-language-identification/pretrained_models.html?highlight=whisper) . but i plan to use a recommended project [TMSpeech](https://github.com/jxlpzqc/TMSpeech) without deep digging into it's code. there's a straight-forward way to include a custom model in it - via encoders-decoders and joiners. ok, if there's now such a way, i'll try to reconfigure TMSpeech.Recognizer.SherpaOnnx SherpaOnnxConfig    class . it's hard coded against joiners https://github.com/jxlpzqc/TMSpeech/blob/master/src/Plugins/TMSpeech.Recognizer.SherpaOnnx/SherpaOnnxConfigEditor.cs

**Comment by csukuangfj** [comment]
You have not found the correct doc about whisper for ASR. Please retry.

**Comment by csukuangfj** [comment]
You have not found the correct doc about whisper for ASR. Please retry.

**Comment by vks2** [comment]
yes, but there's no Online Model Config for whisper ASR at the moment, so should go with offline one, right?

**Comment by csukuangfj** [comment]
there are no online whisper models.
