### ISSUE TITLE
build-ios-shared.sh报错，如何解决

### ISSUE THREAD

**Issue by pozi119** [k2-fsa/sherpa-onnx#1512]
mac下运行 `sh build-ios-shared.sh` 编译报错：
`
[100%] Linking CXX shared library ../../lib/libsherpa-onnx-c-api.dylib
ld: warning: duplicate -rpath '@loader_path' ignored
ld: warning: ignoring duplicate libraries: '-lm'
ld: library 'onnxruntime' not found
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [sherpa-onnx/c-api/CMakeFiles/sherpa-onnx-c-api.dir/build.make:107: lib/libsherpa-onnx-c-api.dylib] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1311: sherpa-onnx/c-api/CMakeFiles/sherpa-onnx-c-api.dir/all] Error 2
gmake: *** [Makefile:156: all] Error 2
`

**Comment by csukuangfj** [comment]
请贴所有的log。
还有，请不要用sh，直接用bash

**Comment by csukuangfj** [comment]
1. 请删掉 build-ios-shared 目录
2. 把
https://github.com/k2-fsa/sherpa-onnx/blob/86b1856c207761d999228c2f14f013908b5047c9/build-ios-shared.sh#L53
改成
```bash
 -S ..  -D CMAKE_VERBOSE_MAKEFILE=ON \ 
```
3. 重试。把重试的命令和 log, 请都发过来。

**Comment by csukuangfj** [comment]
@pozi119 

Please try #1522
