### ISSUE TITLE
The input tensor cannot be reshaped to the requested shape

### ISSUE THREAD

**Issue by isgat** [k2-fsa/sherpa-onnx#1519]
Hi!

**Model**: [sherpa-onnx-zipformer-ru-2024-09-18 (Russian, 俄语)](https://k2-fsa.github.io/sherpa/onnx/pretrained_models/offline-transducer/zipformer-transducer-models.html#sherpa-onnx-zipformer-ru-2024-09-18-russian)
**Wav File**: [Test.wav](https://drive.google.com/file/d/1uMuYmzVnL-uvwOKOV9AY1ao4ofgv5ffw/view?usp=sharing)

I get this error if the file is longer than about 20 seconds. 

**Error**:
```
[E:onnxruntime:, sequential_executor.cc:514 onnxruntime::ExecuteKernel] Non-zero status code returned while running Reshape node. Name:'/encoder/encoders.0/layers.0/self_attn_weights/Reshape_3' Status Message: C:\a\_work\1\s\onnxruntime\core\providers\cpu\tensor\reshape_helper.h:40 onnxruntime::ReshapeHelper::ReshapeHelper size != 0 && (input_shape_size % size) == 0 was false. The input tensor cannot be reshaped to the requested shape. Input shape:{1,1295,16}, requested shape:{-1,4589,4,4}
```

When decoding files provided as an example in the repository, everything is fine. I tried it with the compiled version on Windows and with C# API. I get the same errors.

Long files are not supported? What should I do?

**Comment by csukuangfj** [comment]
could you use a vad to segment your input file?

**Comment by isgat** [comment]
Thanks! It worked! I just didn't know about a vad. Made according to the example.
