### ISSUE TITLE
非回归 TTS 支持

### ISSUE THREAD

**Issue by endink** [k2-fsa/sherpa-onnx#1533]
是否有 plan 支持非回归的TTS支持计划？

F5-TTS
CosyVoice
ChatTTS
等等

**Comment by csukuangfj** [comment]
没计划。

建议你先看看它们在cpu上的速度有多快。就算支持了，你是否能接受它们的运行速度

**Comment by endink** [comment]
CPU 无法使用，主要是可以考虑用于桌面平台
