### ISSUE TITLE
cuda版本问题

### ISSUE THREAD

**Issue by MisakaMikoto-o** [k2-fsa/sherpa-onnx#1536]
我现有的环境只能使用cuda10.2，无法安升级为cuda11.8，请问有没有办法编译cuda10.2版本的sherpa-onnx cuda版本库，谢谢

**Comment by csukuangfj** [comment]
可以的，你去看哪个版本的onnxruntime支持cuda10.2


比如，你用onnxruntime 1.11 ，应该是可以的。

如果你用的是Linux arm64，那么，你不需要修改任何代码，直接可以用的

**Comment by MisakaMikoto-o** [comment]
> 可以的，你去看哪个版本的onnxruntime支持cuda10.2
> 
> 比如，你用onnxruntime 1.11 ，应该是可以的。
> 
> 如果你用的是Linux arm64，那么，你不需要修改任何代码，直接可以用的

我用的是Linux x64，请问在哪里修改onnxruntime版本

**Comment by MisakaMikoto-o** [comment]
在https://github.com/k2-fsa/sherpa-onnx/blob/master/cmake/onnxruntime-linux-x86_64-gpu.cmake这里我看见你们编译时默认的onnxruntime gpu版本是1.17.1，我是不是只需要在这里改成cuda10.2对应的onnxruntime gpu版本，再重新编译就行了，小白不是很懂(╥╯^╰╥)

**Comment by csukuangfj** [comment]
你说的非常对。就是改这个文件.

**Comment by MisakaMikoto-o** [comment]
> 你说的非常对。就是改这个文件.

但是我看了一下，我的cuda版本是10.2，cudnn版本是7.6.5，好像onnxruntime 1.11是不行的吧，根据这里https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements 的对应关系，我好像只能下载https://github.com/microsoft/onnxruntime/releases/download/v1.4.0/onnxruntime-linux-x64-gpu-1.4.0.tgz （？

**Comment by MisakaMikoto-o** [comment]
但是1.4.0版本的lib里好像没有libonnxruntime_providers相关的三个动态库，不知道是不是能直接用[・_・?]

**Comment by csukuangfj** [comment]
你试过1.6.0没

**Comment by MisakaMikoto-o** [comment]
> 你试过1.6.0没

刚刚试了一下，make -j的时候报错了：
```
error: ‘OrtCudnnConvAlgoSearchHeuristic’ was not declared in this scope; did you mean ‘OrtCudnnConvAlgoSearch’?
   17 |   int32_t cudnn_conv_algo_search = OrtCudnnConvAlgoSearchHeuristic;
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                    OrtCudnnConvAlgoSearch
```

**Comment by MisakaMikoto-o** [comment]
> 你试过1.6.0没

我用onnxruntime 1.13版本后来编译成功了（大概是成功了吧，虽然中间有报错，但是最后显示了[100%] Built target _sherpa_onnx），然后我应该怎么使用我自己编译的sherpa-onnx库呢，有没有生成whl能够直接通过pip安装呢，就像你们提供的那样

**Comment by csukuangfj** [comment]
有的，请看我们的Python安装文档。你看了，就知道如何做了

**Comment by MisakaMikoto-o** [comment]
> 有的，请看我们的Python安装文档。你看了，就知道如何做了

额，我看了下，文档里并没有写有生成whl啊，我在我的build目录下搜索也搜索不到whl后缀的文件

**Comment by csukuangfj** [comment]
请把你看的文档截图。写的蛮清楚了，不知道你为什么说没有

**Comment by MisakaMikoto-o** [comment]
> 请把你看的文档截图。写的蛮清楚了，不知道你为什么说没有

![image](https://github.com/user-attachments/assets/9357ff07-f883-45fa-a6d3-a71977f1b379)
我看的是这个

**Comment by csukuangfj** [comment]
对呀，method 3和4，都可以呀

**Comment by csukuangfj** [comment]
你想要whl文件，就把method 3的

python3 setup.py install

改成

python3 setup.py bdist_wheel


然后在dist目录下找到生成的.whl文件
(这个是python的基础知识，不属于sherpa-onnx的范畴)

**Comment by MisakaMikoto-o** [comment]
> > 你想要whl文件，就把method 3的
> > python3 setup.py install
> > 改成
> > python3 setup.py bdist_wheel
> > 然后在dist目录下找到生成的.whl文件 (这个是python的基础知识，不属于sherpa-onnx的范畴)
> 
> 对不起，我确实是纯小白，现在我运行python3 setup.py bdist_wheel，发现使用的onnxruntime版本和cmake指令变回了你们默认的，并且重新生成了一下，而不是使用我之前自己新建的build目录中构建的，这个应该修改哪里

**Comment by csukuangfj** [comment]
你以前是如何修改的？build目录是随时可以删掉的

**Comment by csukuangfj** [comment]
你现在运行了哪几条命令？你有没有设置method 3中的环境变量？

**Comment by MisakaMikoto-o** [comment]
> 你以前是如何修改的？build目录是随时可以删掉的

我之前修改了onnxruntime-linux-x86_64-gpu.cmake中的set(possible_file_locations，新增了我的1.13版本的onnxruntime zip包位置，然后cmake命令中新增了DCMAKE_PREFIX_PATH和DCMAKE_EXE_LINKER_FLAGS="-Wl,-rpath项用于搜索1.13onnxruntime依赖的tvm库，这样构建和生成都没问题了，二进制文件生成在了build/bin目录下，但是我现在运行python3 setup.py bdist_wheel会重新用默认配置给我生成一下，我该怎么使用我自己的配置生成并打包为whl

**Comment by csukuangfj** [comment]
请详细写出你执行的命令不要用文字描述。需要可以复制粘贴的那种命令

**Comment by MisakaMikoto-o** [comment]
> 请详细写出你执行的命令不要用文字描述。需要可以复制粘贴的那种命令

好的，我总结了一下，问题其实是在我运行python3 setup.py bdist_wheel时会执行这个cmake命令：
```
cmake -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=/root/anaconda3/envs/btvoice/bin/python -DCMAKE_INSTALL_PREFIX=/home/kwc/BTVoice/sherpa-onnx/build/lib.linux-x86_64-cpython-310/sherpa_onnx  -DBUILD_SHARED_LIBS=ON  -DBUILD_PIPER_PHONMIZE_EXE=OFF  -DBUILD_PIPER_PHONMIZE_TESTS=OFF  -DBUILD_ESPEAK_NG_EXE=OFF  -DBUILD_ESPEAK_NG_TESTS=OFF  -DSHERPA_ONNX_ENABLE_C_API=ON  -DSHERPA_ONNX_BUILD_C_API_EXAMPLES=OFF  -DSHERPA_ONNX_ENABLE_CHECK=OFF  -DSHERPA_ONNX_ENABLE_PYTHON=ON  -DSHERPA_ONNX_ENABLE_PORTAUDIO=ON  -DSHERPA_ONNX_ENABLE_WEBSOCKET=ON  /home/kwc/BTVoice/sherpa-onnx
```
而执行这个命令会使用你们默认的1.17版本onnxruntime库，而我自己编译时是在build目录下执行这个命令：
cmake \
  -DSHERPA_ONNX_ENABLE_PYTHON=ON \
  -DBUILD_SHARED_LIBS=ON \
  -DSHERPA_ONNX_ENABLE_CHECK=OFF \
  -DSHERPA_ONNX_ENABLE_PORTAUDIO=OFF \
  -DSHERPA_ONNX_ENABLE_C_API=OFF \
  -DSHERPA_ONNX_ENABLE_WEBSOCKET=OFF \
  -DSHERPA_ONNX_ENABLE_GPU=ON \
  -DCMAKE_PREFIX_PATH=/root/anaconda3/envs/btvoice/lib/python3.10/site-packages/tvm \
  -DCMAKE_EXE_LINKER_FLAGS="-Wl,-rpath,/root/anaconda3/envs/btvoice/lib/python3.10/site-packages/tvm" \
  ..
这个命令会正确的使用我在sherpa-onnx/cmake/onnxruntime-linux-x86_64-gpu.cmake中修改的1.13版本的onnxruntime库进行编译生成

**Comment by csukuangfj** [comment]
> 好的，我总结了一下，

我就问一句，你到底有没有运行 method 3 中的那条 export 语句.

(这是第二次问你了，希望你可以回答我们)

**Comment by MisakaMikoto-o** [comment]
> > 好的，我总结了一下，
> 
> 我就问一句，你到底有没有运行 method 3 中的那条 export 语句.
> 
> (这是第二次问你了，希望你可以回答我们)

啊我知道了，那估计问题出在这儿了，没有export用的是cpu版本的cmake配置，所以没有用我修改的1.13版本，对不起因为自己cmake的时候有加-DSHERPA_ONNX_ENABLE_GPU=ON选项，没意识到用setup.py实际上默认是没有这个选项的

**Comment by csukuangfj** [comment]
现在可以了没

**Comment by MisakaMikoto-o** [comment]
> 现在可以了没

生成whl文件了，但是pip安装上之后导入报错了
`/root/anaconda3/envs/btvoice/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /root/anaconda3/envs/btvoice/lib/python3.10/site-packages/_sherpa_onnx.cpython-310-x86_64-linux-gnu.so)`

**Comment by MisakaMikoto-o** [comment]
还是说是因为我gcc版本太低了的原因，我现在gcc版本是11.4，我看有说GLIBCXX_3.4.30 需要  GCC 12.1.0的

**Comment by csukuangfj** [comment]
你是不是编译和运行的电脑，不一样？

**Comment by MisakaMikoto-o** [comment]
> 你是不是编译和运行的电脑，不一样？

因为编译的时候需要从github下载一些东西，而我编译的环境没有联网，所以实际上我是现在一台有网的设备上先执行了一遍cmake，然后将整个文件夹拷贝到我编译的环境中，执行了make clean和rm -rf CMakeCache.txt CMakeFiles清除了之前的编译生成项，然后再cmake和make -j进行生成的，这样也会有影响吗

**Comment by csukuangfj** [comment]
请回答是不是一样。是，或者不是。

**Comment by csukuangfj** [comment]
还有，如果你提前下载好需要的文件到项目目录，即和setup.py放同一个目录，别解压，那么，运行cmake时，是不需要联网的。


还有，不建议你用conda

请用非conda的虚拟环境再试一次

**Comment by MisakaMikoto-o** [comment]
> 请回答是不是一样。是，或者不是。

是一样的，那我用非conda环境再试一下吧

**Comment by csukuangfj** [comment]
ok，那就极有可能是conda的问题

**Comment by csukuangfj** [comment]
建议你用method 4先试一下

**Comment by MisakaMikoto-o** [comment]
> ok，那就极有可能是conda的问题

确实是conda的问题，我用系统python就好了，但是现在报错
```
Failed to load model with error: /home/corex/sw_home/apps/onnxruntime/onnxruntime/core/graph/model_load_utils.h:47 void onnxruntime::model_load_utils::ValidateOpsetForDomain(const std::unordered_map<std::basic_string<char>, int>&, const onnxruntime::logging::Logger&, bool, const string&, int) ONNX Runtime only *guarantees* support for models stamped with official released onnx opset versions. Opset 19 is under development and support for this is limited. The operator schemas and or other functionality may change before next ONNX release and in this case ONNX Runtime will not guarantee backward compatibility. Current official support for domain com.ms.internal.nhwc is till opset 17.
```
你们提供的这两个onnx模型是不是用opset19导出的呀，我现在这个onnxruntime版本好像最多只支持opset17
```
wget https://github.com/k2-fsa/sherpa-onnx/releases/download/speaker-segmentation-models/sherpa-onnx-pyannote-segmentation-3-0.tar.bz2
```
```
wget https://github.com/k2-fsa/sherpa-onnx/releases/download/speaker-recongition-models/3dspeaker_speech_eres2net_base_sv_zh-cn_3dspeaker_16k.onnx
```

**Comment by MisakaMikoto-o** [comment]
但是奇怪的是我看https://github.com/k2-fsa/sherpa-onnx/blob/master/scripts/3dspeaker/export-onnx.py 和https://github.com/k2-fsa/sherpa-onnx/blob/master/scripts/pyannote/segmentation/export-onnx.py 导出onnx模型时设置的opset_version都是13，那不应该报错呀

**Comment by csukuangfj** [comment]
[for-you.zip](https://github.com/user-attachments/files/17770568/for-you.zip)

试试这个模型，替换 sherpa-onnx-pyannote-segmentation-3-0.tar.bz2 里面的 model.onnx

**Comment by csukuangfj** [comment]
测试了没？

**Comment by MisakaMikoto-o** [comment]
> 测试了没？

嗯嗯，刚刚试了一下，可以用，谢谢！

**Comment by csukuangfj** [comment]
> > 测试了没？
> 
> 嗯嗯，刚刚试了一下，可以用，谢谢！

太棒啦！

**Comment by csukuangfj** [comment]
> 但是奇怪的是我看https://github.com/k2-fsa/sherpa-onnx/blob/master/scripts/3dspeaker/export-onnx.py 和https://github.com/k2-fsa/sherpa-onnx/blob/master/scripts/pyannote/segmentation/export-onnx.py 导出onnx模型时设置的opset_version都是13，那不应该报错呀

你知道去找代码，这个很不错！

上面的附件，是直接用https://github.com/k2-fsa/sherpa-onnx/blob/master/scripts/pyannote/segmentation/export-onnx.py
导出来的。

我们提供的模型，使用了下面两行
https://github.com/k2-fsa/sherpa-onnx/blob/c34ab3559187a065f0e607c3d120ed203f1a4bcc/scripts/pyannote/segmentation/run.sh#L17-L18

应该是
https://github.com/k2-fsa/sherpa-onnx/blob/c34ab3559187a065f0e607c3d120ed203f1a4bcc/scripts/pyannote/segmentation/run.sh#L18
导致了你的问题。你可以去掉它，然后自己导出模型。

@MisakaMikoto-o 

这个 issue 可以关闭了么

**Comment by MisakaMikoto-o** [comment]
> > 但是奇怪的是我看https://github.com/k2-fsa/sherpa-onnx/blob/master/scripts/3dspeaker/export-onnx.py 和https://github.com/k2-fsa/sherpa-onnx/blob/master/scripts/pyannote/segmentation/export-onnx.py 导出onnx模型时设置的opset_version都是13，那不应该报错呀
> 
> 你知道去找代码，这个很不错！
> 
> 上面的附件，是直接用https://github.com/k2-fsa/sherpa-onnx/blob/master/scripts/pyannote/segmentation/export-onnx.py 导出来的。
> 
> 我们提供的模型，使用了下面两行
> 
> https://github.com/k2-fsa/sherpa-onnx/blob/c34ab3559187a065f0e607c3d120ed203f1a4bcc/scripts/pyannote/segmentation/run.sh#L17-L18
> 
> 应该是
> 
> https://github.com/k2-fsa/sherpa-onnx/blob/c34ab3559187a065f0e607c3d120ed203f1a4bcc/scripts/pyannote/segmentation/run.sh#L18
> 
> 
> 导致了你的问题。你可以去掉它，然后自己导出模型。
> @MisakaMikoto-o
> 
> 这个 issue 可以关闭了么

嗯嗯，可以关闭了，再次感谢你的耐心解答！
