### ISSUE TITLE
Add checksums to releases

### ISSUE THREAD

**Issue by thewh1teagle** [k2-fsa/sherpa-onnx#1542]
I need it to verify the integrity of the libraries in sherpa-rs
https://github.com/wangzuo/action-release-checksums

**Comment by thewh1teagle** [comment]
Any thoughts regarding this issue? I can try contribute it.
Do you prefer dedicated action file for that, which will fetch all assets and upload final checksum, or a script that each action will call it when upload asset?

**Comment by csukuangfj** [comment]
> Do you prefer dedicated action file for that, which will fetch all assets and upload final checksum

It is great if you can contribute. 

Yes, we prefer this option. We can let GitHub Actions run it periodically, e.g., at 1:00 AM daily. 

Also, we can enable it to run manually.

**Comment by thewh1teagle** [comment]
> It is great if you can contribute.
> 
> Yes, we prefer this option. We can let GitHub Actions run it periodically, e.g., at 1:00 AM daily.
> 
> Also, we can enable it to run manually.

I created https://github.com/thewh1teagle/checksum
Any thoughts? we can easily add it

**Comment by csukuangfj** [comment]
Is it possible to specify a tag to compute checksum for?

For instance, our current ASR models are saved in 
https://github.com/k2-fsa/sherpa-onnx/releases/tag/asr-models

Also, is the resulting `checksum.txt` uploaded to the specified tag?

**Comment by csukuangfj** [comment]
Also, can you remove the assets from the disk after computing the checksum?

There are many model files and I am afraid if they are not deleted after download, the disk would be full.

**Comment by thewh1teagle** [comment]
> Also, can you remove the assets from the disk after computing the checksum?

I already did
https://github.com/thewh1teagle/checksum/blob/main/index.ts#L109



> Is it possible to specify a tag to compute checksum for?

I'll add optional tag input

**Comment by thewh1teagle** [comment]
> Also, is the resulting `checksum.txt` uploaded to the specified tag?

Yes
