### ISSUE TITLE
Cannot run go api examples under Windows 10

### ISSUE THREAD

**Issue by simiwe** [k2-fsa/sherpa-onnx#1554]
Operation steps:
1. Clone https://github.com/k2-fsa/sherpa-onnx.git.
2. Enter the go-api-examples/add-punctuation directory.
3. Download https://github.com/k2-fsa/sherpa-onnx/releases/download/punctuation-models/sherpa-onnx-punct-ct-transformer-zh-en-vocab272727-2024-04-12.tar.bz2
After decompression, put it in the current directory.
4. Modify `config.Model.CtTransformer`
 in `main.go`:

```
config.Model.CtTransformer = ".\\sherpa-onnx-punct-ct-transformer-zh-en-vocab272727-2024-04-12\\model.onnx"
```
5. After running  `go run .\main.go` output:

```
exit status 0xc0000135
```

go version

```
go version go1.23.3 windows/amd64
```

go.mod
```
module add-punctuation

go 1.12

require (
    github.com/k2-fsa/sherpa-onnx-go v1.8.14
    github.com/k2-fsa/sherpa-onnx-go-linux v1.10.31 // indirect 
    github.com/k2-fsa/sherpa-onnx-go-macos v1.10.31 // indirect 
    github.com/k2-fsa/sherpa-onnx-go-windows v1.10.31 // indirect
)
```

**Comment by csukuangfj** [comment]
You need to copy the DLLs from the downloaded package.

**Comment by simiwe** [comment]
> You need to copy the DLLs from the downloaded package.

I develop on Mac, using "github.com/k2-fsa/sherpa-onnx-go/sherpa_onnx", and it works well.

Can I directly cross-compile to generate a windows executable file?

Or do I need to configure the development environment on Windows before compiling?

**Comment by csukuangfj** [comment]
> You need to copy the DLLs from the downloaded package.

Have you tried it?

**Comment by simiwe** [comment]
> > You need to copy the DLLs from the downloaded package.
> 
> Have you tried it?

After downloading the DLLs as described in the [document](https://k2-fsa.github.io/sherpa/onnx/go-api/index.html), it still doesn't work properly.

![image](https://github.com/user-attachments/assets/58569dac-71f0-4b6a-a1e3-145707f606e7)

**Comment by BadDeveloper2022** [comment]
这个问题 最终咋解决了？

**Comment by csukuangfj** [comment]
> 这个问题 最终咋解决了？

请详细描述你的问题 @BadDeveloper2022
