### ISSUE TITLE
Add SSML 

### ISSUE THREAD

**Issue by wukonggeo** [k2-fsa/sherpa-onnx#1560]
In tts model, such as vctk, how to Increase pause interval?
such as:
Text = "Hello, this  is  a <    break time="0.5s"/    > test"

**Comment by wangxuefei-25** [comment]
> 在 tts 模型中，例如 vctk，如何增加暂停间隔？例如：Text = “您好，这是一个<休息时间=”0.5s“/ >测试”

请问这个问题解决了吗，我尝试了增加暂停间隔，但是没有成功

**Comment by wukonggeo** [comment]
没有支持。
