### ISSUE TITLE
In flutter, when uploading an iOS program to the app store, an error message appears: Invalid Bundle. The bundle Runner.app/Frameworks/sherpa_onnx.frmework does not support the minimum OS Version specified in the Info.plist

### ISSUE THREAD

**Issue by homelee** [k2-fsa/sherpa-onnx#1562]
In flutter, when uploading an iOS program to the app store, an error message appears: Invalid Bundle. The bundle Runner.app/Frameworks/sherpa_onnx.frmework does not support the minimum OS Version specified in the Info.plist

My fix: modify Info.plist, add
......
<key>SupportedArchitectures</key>
<array>
<string>arm64</string>
</array>
<key>SupportedPlatform</key>
<string>ios</string>
<key>MinimumOSVersion</key>
<string>13.0</string>
........
Also modify sherpa_onnx_ios.podspec
s.platform = :ios, "13.0"

Hopefully fixed in the release version

**Comment by csukuangfj** [comment]
Thanks! Please see https://github.com/k2-fsa/sherpa-onnx/pull/1563

We are releasing v1.10.32.

Could you test the new release after 
https://github.com/csukuangfj/sherpa-onnx/actions/runs/12012222667/job/33482941789
finishes?

**Comment by homelee** [comment]
thanks
