### ISSUE TITLE
Ubuntu编译安卓库报错：build-android-arm64-v8a.sh-->

### ISSUE THREAD

**Issue by aceip** [k2-fsa/sherpa-onnx#1567]
/sherpa-onnx/sherpa-onnx/csrc/online-transducer-model.cc:209:5: error: unknown type name 'Manager'
  209 |     Manager *mgr, const OnlineModelConfig &config);
 sherpa-onnx/sherpa-onnx/csrc/online-transducer-model.cc:186:17: error: no matching function for call to 'ReadFile'
  186 |   auto buffer = ReadFile(mgr, config.transducer.encoder);

**Comment by csukuangfj** [comment]
请用最新的代码

**Comment by aceip** [comment]
我试试

**Comment by csukuangfj** [comment]
> 我试试

稍等5分钟，我上传一下

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/sherpa-onnx/pull/1568 解决了这个问题。

请用最新的 master

**Comment by aceip** [comment]
好的好的

**Comment by aceip** [comment]
问题已解决 牛人点个赞！
![0013E439](https://github.com/user-attachments/assets/8a04644e-4554-423b-9821-a55fe2698cc2)
