### ISSUE TITLE
Confusing file names

### ISSUE THREAD

**Issue by dnhkng** [k2-fsa/sherpa-onnx#1569]
I really appreciate the work you have done in generating onnx models!

I would like to try a few, based on the rankings from the Huggingface ASR leaderboard:
https://huggingface.co/spaces/hf-audio/open_asr_leaderboard

However, I am having trouble identifying which sherpa-onnx model corresponds to the entries on the leaderboard. I know this is mostly a Nvidia issue, as they have released a lot of models with very similar names.

Could you please help with table of the top models?
|**HF Leaderboard Name**	| **Sherpa-ONNX Name**|
| -------- | ------- |
|nvidia/canary-1b		|  x|
|nyrahealth/CrisperWhisper	|  not available ?
|nvidia/parakeet-tdt-1.1b	|  x|
|nvidia/parakeet-rnnt-1.1b	|  x|
|nvidia/parakeet-ctc-1.1b	| x|
|nvidia/parakeet-tdt_ctc-110m	| sherpa-onnx-nemo-parakeet_tdt_ctc_110m-en-36000.tar.bz2 |
|nvidia/parakeet-rnnt-0.6b	| x|
|distil-whisper/distil-large-v3	| x (but we have distil-large-v2, you can add v3 if you like)|
|nvidia/parakeet-ctc-0.6b	| x|
|openai/whisper-large-v2	|  sherpa-onnx-whisper-distil-large-v2.tar.bz2|
|openai/whisper-large-v3-turbo	| sherpa-onnx-whisper-turbo.tar.bz2|
|distil-whisper/distil-large-v2	| sherpa-onnx-whisper-distil-large-v2.tar.bz2|

The release page has quite a few Nemo models, but I want to use a good one!
sherpa-onnx-nemo-ctc-en-citrinet-512.tar.bz2
sherpa-onnx-nemo-ctc-en-conformer-small.tar.bz2
sherpa-onnx-nemo-ctc-en-conformer-medium.tar.bz2
sherpa-onnx-nemo-ctc-en-conformer-large.tar.bz2
sherpa-onnx-nemo-streaming-fast-conformer-transducer-en-80ms.tar.bz2
sherpa-onnx-nemo-streaming-fast-conformer-ctc-en-80ms.tar.bz2
sherpa-onnx-nemo-streaming-fast-conformer-transducer-en-480ms.tar.bz2
sherpa-onnx-nemo-streaming-fast-conformer-ctc-en-480ms.tar.bz2
sherpa-onnx-nemo-streaming-fast-conformer-transducer-en-1040ms.tar.bz2
sherpa-onnx-nemo-streaming-fast-conformer-ctc-en-1040ms.tar.bz2
sherpa-onnx-nemo-parakeet_tdt_transducer_110m-en-36000.tar.bz2
sherpa-onnx-nemo-fast-conformer-transducer-es-1424.tar.bz2
sherpa-onnx-nemo-parakeet_tdt_ctc_110m-en-36000.tar.bz2
sherpa-onnx-nemo-fast-conformer-transducer-en-de-es-fr-14288.tar.bz2
sherpa-onnx-nemo-fast-conformer-ctc-es-1424.tar.bz2
sherpa-onnx-nemo-fast-conformer-transducer-en-24500.tar.bz2
sherpa-onnx-nemo-fast-conformer-ctc-en-de-es-fr-14288.tar.bz2
sherpa-onnx-nemo-fast-conformer-transducer-be-de-en-es-fr-hr-it-pl-ru-uk-20k.tar.bz2
sherpa-onnx-nemo-fast-conformer-ctc-en-24500.tar.bz2
sherpa-onnx-nemo-fast-conformer-ctc-be-de-en-es-fr-hr-it-pl-ru-uk-20k.tar.bz2
sherpa-onnx-nemo-transducer-giga-am-russian-2024-10-24.tar.bz2
sherpa-onnx-nemo-ctc-giga-am-russian-2024-10-24.tar.bz2

**Comment by csukuangfj** [comment]
Please see the updated table.

By the way, we don't convert very large models to sherpa-onnx, but  it is feasible.

**Comment by csukuangfj** [comment]
Please search in the `scripts` folder for model conversion/export code.

**Comment by csukuangfj** [comment]
Not sure what you mean by `best`?

For any model, you need to evaluate it on your specific test dataset.

There is no model that performs best on any dataset.

**Comment by dnhkng** [comment]
Very true! A single best does not exist.  Maybe Pareto Curve optimal on performance vs model size?

Anyway, I have selected Parakeet, as it scored very high on the HuggingFace ASR leaderboard on many datasets.
