### ISSUE TITLE
Go项目 C API 升级到 v1.10.31 之后出现报错：Rule fst 'greedy_search' does not exist.

### ISSUE THREAD

**Issue by iAInNet** [k2-fsa/sherpa-onnx#1570]
在 macos 系统上执行，debug 模式打开，模型内容输出如下，一切正常。

`
/Users/runner/work/sherpa-onnx/sherpa-onnx/sherpa-onnx/c-api/c-api.cc:convertConfig:490 OfflineRecognizerConfig(feat_config=FeatureExtractorConfig(sampling_rate=16000, feature_dim=80, low_freq=20, high_freq=-400, dither=0), model_config=OfflineModelConfig(transducer=OfflineTransducerModelConfig(encoder_filename="", decoder_filename="", joiner_filename=""), paraformer=OfflineParaformerModelConfig(model=""), nemo_ctc=OfflineNemoEncDecCtcModelConfig(model=""), whisper=OfflineWhisperModelConfig(encoder="", decoder="", language="", task="transcribe", tail_paddings=-1), tdnn=OfflineTdnnModelConfig(model=""), zipformer_ctc=OfflineZipformerCtcModelConfig(model=""), wenet_ctc=OfflineWenetCtcModelConfig(model=""), sense_voice=OfflineSenseVoiceModelConfig(model="/opt/models/stt/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17/model.onnx", language="zh", use_itn=False), moonshine=OfflineMoonshineModelConfig(preprocessor="", encoder="", uncached_decoder="", cached_decoder=""), telespeech_ctc="", tokens="/opt/models/stt/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17/tokens.txt", num_threads=3, debug=True, provider="cpu", model_type="", modeling_unit="cjkchar", bpe_vocab=""), lm_config=OfflineLMConfig(model="", scale=1), ctc_fst_decoder_config=OfflineCtcFstDecoderConfig(graph="", max_active=3000), decoding_method="greedy_search", max_active_paths=4, hotwords_file="", hotwords_score=1.5, blank_penalty=0, rule_fsts="", rule_fars="")
`

但是在 linux aarch64 架构的板载设备上运行，同样的配置，debug 模式打开， 模型内容输出如下，**启动异常**：

`
/project/sherpa-onnx/c-api/c-api.cc:convertConfig:461 OfflineRecognizerConfig(feat_config=FeatureExtractorConfig(sampling_rate=16000, feature_dim=80, low_freq=20, high_freq=-400, dither=0), model_config=OfflineModelConfig(transducer=OfflineTransducerModelConfig(encoder_filename="", decoder_filename="", joiner_filename=""), paraformer=OfflineParaformerModelConfig(model=""), nemo_ctc=OfflineNemoEncDecCtcModelConfig(model=""), whisper=OfflineWhisperModelConfig(encoder="", decoder="", language="", task="transcribe", tail_paddings=-1), tdnn=OfflineTdnnModelConfig(model=""), zipformer_ctc=OfflineZipformerCtcModelConfig(model=""), wenet_ctc=OfflineWenetCtcModelConfig(model=""), sense_voice=OfflineSenseVoiceModelConfig(model="/root/cache/models/stt/senseVoice/model.int8.onnx", language="zh", use_itn=False), telespeech_ctc="", tokens="/root/cache/models/stt/senseVoice/tokens.txt", num_threads=3, debug=True, provider="cpu", model_type="", modeling_unit="cjkchar", bpe_vocab=""), lm_config=OfflineLMConfig(model="", scale=3.05312e-05), ctc_fst_decoder_config=OfflineCtcFstDecoderConfig(graph="", max_active=3000), decoding_method="greedy_search", max_active_paths=939527904, hotwords_file="", hotwords_score=1.5, blank_penalty=3.05326e-05, rule_fsts="greedy_search", rule_fars="")
/project/sherpa-onnx/csrc/offline-recognizer.cc:Validate:96 Rule fst 'greedy_search' does not exist.
/project/sherpa-onnx/c-api/c-api.cc:SherpaOnnxCreateOfflineRecognizer:343 Errors in config
SIGSEGV: segmentation violation
PC=0x7f9c411790 m=8 sigcode=1
signal arrived during cgo execution
`

从模型输出的基本信息，可以看出，问题是从 max_active_paths 开始：

**max_active_paths=939527904, hotwords_file="", hotwords_score=1.5, blank_penalty=3.05326e-05, rule_fsts="greedy_search", rule_fars=""**

按照源码的实现，max_active_paths 默认应该是 4 ，blank_penalty 是 0，rule_fsts 是空字符串 "" 才对，但是这几个字段都出现了奇怪的数值。这几个字段在我自己的工程配置文件里是没有配置的，在 macos 工具包里就走了默认值，但是在 linux aarch64 架构的设备就出现了奇怪的数值。

最终因为 rule_fsts 不为空，Validate 方法那里验证不通过： “Rule fst 'greedy_search' does not exist.”，导致模型启动失败了。

**Comment by csukuangfj** [comment]
请描述复现步骤。

最关键的，你是否自己编译了 sherpa-onnx 的 go package?

**Comment by csukuangfj** [comment]
CI （macos) 是没问题的。
https://github.com/k2-fsa/sherpa-onnx/actions/runs/12034338828

**Comment by iAInNet** [comment]
> 请描述复现步骤。
> 
> 最关键的，你是否自己编译了 sherpa-onnx 的 go package?

没有自己编译 lib 库，而是直接下载了 github 工程里自带的 lib 目录。
- macos： https://github.com/k2-fsa/sherpa-onnx-go-macos
- linux： https://github.com/k2-fsa/sherpa-onnx-go-linux

最主要是上面几个字段的数值，并不是固定的，linux aarch64 设备上每次启动都会不一样。比如：

**max_active_paths=805310576, blank_penalty=4.65913e-10, rule_fsts="greedy_search", rule_fars=""**

就感觉这几个字段访问到未定义的内存地址一样。

**Comment by csukuangfj** [comment]
你这个应该是 c-api.h 不对。


你的 c-api.h 是不是配套的？

**Comment by csukuangfj** [comment]
你直接跑我们提供的例子代码，是否有问题？

（不要自己去下载 .so 文件）

**Comment by iAInNet** [comment]
> 你直接跑我们提供的例子代码，是否有问题？
> 
> （不要自己去下载 .so 文件）

可以，我明早做两个变更，再给你答复
- 直接引入 github 工程包
- 在板载设备上运行 go-api-examples 样例验证（macos 是没问题）

**Comment by iAInNet** [comment]
> 你直接跑我们提供的例子代码，是否有问题？
> 
> （不要自己去下载 .so 文件）

在板载设备上直接运行 go-api-examples 样例是能成功的，**说明 C  API  和 lib 库是没问题的**。再确认 c-api.h 是完全一致后，定位到了问题：板载设备上 `/lib` 路径下的库文件并没有更新，板载的所有库文件都是单独打包推送写入设备来升级， 跟直接运行样例的方式不一样。**我手动升级库文件之后，运行正常了**。

问题解决了。

**Comment by csukuangfj** [comment]
太棒啦
