### ISSUE TITLE
Could you make separate offline tts C module, please?

### ISSUE THREAD

**Issue by JohnClaw** [k2-fsa/sherpa-onnx#1585]
It is difficult to deal with such huge amount of code.

**Comment by csukuangfj** [comment]
could you be more specific?

**Comment by JohnClaw** [comment]
> could you be more specific?

Separate github repo for sherpa-onnx-tts.

**Comment by csukuangfj** [comment]
no， there is no such a plan. 

please see our doc for  c API.

you only need two files
 - 1. c-api.h
 - 2. libsherpa-onnx-c-api.so
