### ISSUE TITLE
Pruned_transducer_stateless3 model onnx export issue 

### ISSUE THREAD

**Issue by s-mousmita** [k2-fsa/sherpa-onnx#1602]
Hello everyone,
I am trying to test the hotword feature with one of my pruned_transducer_stateless3 model. I exported the model using this script https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless3/export-onnx.py. But unfortunately, I encountered an error:
csrc/online-conformer-transducer-model.cc:InitEncoder:98 num_encoder_layers does not exist in the metadata.

I attempted to modify the export script to include the necessary metadata, but that led to additional errors during decoding.
Could anyone point me toward the correct recipe for exporting the model? Your help would be greatly appreciated. 

Thank you!

**Comment by csukuangfj** [comment]
Please don't use  an online recognizer with a non-streaming model.

**Comment by s-mousmita** [comment]
Hi Fangjun, Thanks for the reply.
But I trained the model using  --dynamic-chunk-training "True" --causal-convolution "True". So is not it a streaming model ?
Secondly when I export the model to torchscript model (--jit "True")  and  run online-recognizer at  k2-fsa/sherpa  , it works well.

**Comment by csukuangfj** [comment]
Are you also exporting a streaming model?

Would be great if you.can share the complete export command.

**Comment by s-mousmita** [comment]
I think I am exporting a streaming model. Here is the command:

python3 pruned_transducer_stateless3/export-onnx.py \
    --exp-dir exp/pruned_transducer_stateless3/v17_bpe500_vp/ \
    --iter 1624000 \
    --avg 103 \
    --causal-convolution True \
    --dynamic-chunk-training True \
    --tokens data/lang_bpe_500/tokens.txt

Is this correct ?

**Comment by csukuangfj** [comment]
The export-onnx.py you are using only supports exporting non-streaming models.


Please have a look at export-onnx-streaming.py from pruned_transducer_stateless5 from librispeech.

**Comment by s-mousmita** [comment]
export-onnx-streaming.py from pruned_transducer_stateless5 worked.  Thanks.
