### ISSUE TITLE
ASR使用whisper强制中文，app崩溃

### ISSUE THREAD

**Issue by wanghongwei123** [k2-fsa/sherpa-onnx#1604]
12-06 17:08:26.338 D/DigestGenerator( 3909): digest=============com.k2fsa.sherpa.onnxAbort message: 'JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-: illegal continuation byte 

whisper 采用的是 bpe 建模，具体到汉字，一个汉字, utf8 编码， 3个字节。

识别的时候，有可能是几个字节组合在一起，是一个非法的 utf8 sequence, 所以 jvm 报这个错误了。
[log.txt](https://github.com/user-attachments/files/18055487/log.txt)

**Comment by csukuangfj** [comment]
@wanghongwei123  Please test it with the latest master. It should be fixed now.
