### ISSUE TITLE
鸿蒙语音转文字demo中，模型还未加载就crash，请麻烦帮忙看下

### ISSUE THREAD

**Issue by JonYou03** [k2-fsa/sherpa-onnx#1605]
crash信息：
![image](https://github.com/user-attachments/assets/3b265ae1-933d-46c0-8963-105d7a1e6025)

crash位置
![image](https://github.com/user-attachments/assets/10283575-f950-440c-98c7-78454c8c9f03)

**Comment by csukuangfj** [comment]
你没有按照文档来呀！

你的 silero_vad.onnx 在哪里？

**Comment by csukuangfj** [comment]
![Screenshot 2024-12-09 at 11 21 51](https://github.com/user-attachments/assets/271fa182-ebaf-4327-98fd-b8298bee9523)


文档写的蛮详细了，你可以花点时间去看看么？

**Comment by JonYou03** [comment]
不好意思，是我看漏了

**Comment by csukuangfj** [comment]
> 不好意思，是我看漏了

可以跑了没？

你可以试试文档里的那个 sense voice 模型， 支持中英粤日韩， 5种语言呢。

**Comment by JonYou03** [comment]
可以的，太溜了
