### ISSUE TITLE
web语音合成、麒麟服务器

### ISSUE THREAD

**Issue by 20246688** [k2-fsa/sherpa-onnx#1623]
大佬们好，我发现在Linux服务器运行自己改写的语音合成demo合成速度和Windows单机的合成速度差不多。但是在麒麟上合成速度慢了大约六倍左右，请问是系统原因吗？我改写的是文档里面python demo

**Comment by csukuangfj** [comment]
麒麟是什么CPU?

**Comment by csukuangfj** [comment]
麒麟是什么CPU?

**Comment by 20246688** [comment]
> 麒麟是什么CPU？

x86的

**Comment by csukuangfj** [comment]
太笼统了，帮不到你

**Comment by 20246688** [comment]
请问还需要什么信息吗？我可以去收集一下

**Comment by csukuangfj** [comment]
1如何编译的，需要完整的命令和命令行输出。注意，关键词是完整的

2.具体cpu型号。请不要只说x86

**Comment by 20246688** [comment]
好的感谢指正，我明天整理好给您

**Comment by 20246688** [comment]
好的，感谢指正。我先做一些排查准备和信息收集，然后回复您。

**Comment by 20246688** [comment]
> 1如何编译的，需要完整的命令和命令行输出。注意，关键词是完整的
> 
> 2.具体cpu型号。请不要只说x86

你好，cpu型号是Hygon C86 7380 32-Core Processor，cpu cores和siblings都是16，cpu主频2199，clflush size是64.请问还需要什么信息吗？我可以尝试提供给您

**Comment by csukuangfj** [comment]
上面说了两点，你只回复了第2点。麻烦补充第一点。

> 1如何编译的，需要完整的命令和命令行输出。注意，关键词是完整的

**Comment by 20246688** [comment]
> 上面说了两点，你只回复了第2点。麻烦补充第一点。
> 
> > 1如何编译的，需要完整的命令和命令行输出。注意，关键词是完整的

好的稍等

**Comment by 20246688** [comment]
你好，久等了。
1、我先是参考sherpa-onnx\python-api-examples\offline-tts.py固定了传入参数，这样方便打包，就不用在服务器配置python环境了。

2、调整后的详细代码如下：
import os
import time
import sherpa_onnx
import soundfile as sf

# 设置输出文件夹路径
output_folder = 'Combined-WAV'
os.makedirs(output_folder, exist_ok=True)  # 确保文件夹存在，如果不存在则创建

# 设置输出文件名
output_filename = "vits-c-16.wav"

# 输入文本文件路径
text_file_path = '文本.txt'

with open(text_file_path, 'r', encoding='utf-8') as text_file:
    text = text_file.read().strip()

# 构建完整的输出文件路径
output_filepath = os.path.join(output_folder, output_filename)

# 固定配置参数
vits_model = './sherpa-onnx/vits-zh-hf-fanchen-C/vits-zh-hf-fanchen-C.onnx'
vits_lexicon = './sherpa-onnx/vits-zh-hf-fanchen-C/lexicon.txt'
vits_tokens = './sherpa-onnx/vits-zh-hf-fanchen-C/tokens.txt'
vits_dict_dir = './sherpa-onnx/vits-zh-hf-fanchen-C/dict'
tts_rule_fsts = './sherpa-onnx/vits-zh-hf-fanchen-C/phone.fst,./sherpa-onnx/vits-zh-hf-fanchen-C/date.fst,./sherpa-onnx/vits-zh-hf-fanchen-C/number.fst'
sid = 16
speed = 1.0
provider = 'cpu'
num_threads = 1
max_num_sentences = 2
debug = True

# 配置TTS
tts_config = sherpa_onnx.OfflineTtsConfig(
    model=sherpa_onnx.OfflineTtsModelConfig(
        vits=sherpa_onnx.OfflineTtsVitsModelConfig(
            model=vits_model,
            lexicon=vits_lexicon,
            data_dir="",
            dict_dir=vits_dict_dir,
            tokens=vits_tokens,
        ),
        provider=provider,
        debug=debug,
        num_threads=num_threads,
    ),
    rule_fsts=tts_rule_fsts,
    max_num_sentences=max_num_sentences,
)

# 验证配置
if not tts_config.validate():
    raise ValueError("Please check your config")

# 创建TTS对象
tts = sherpa_onnx.OfflineTts(tts_config)

# 生成语音
start = time.time()
audio = tts.generate(text, sid=sid, speed=speed)
end = time.time()

# 检查音频数据
if len(audio.samples) == 0:
    print("Error in generating audios. Please read previous error messages.")
else:
    # 计算耗时与实时因子
    elapsed_seconds = end - start
    audio_duration = len(audio.samples) / audio.sample_rate
    real_time_factor = elapsed_seconds / audio_duration

    # 保存音频文件
    sf.write(output_filepath, audio.samples, samplerate=audio.sample_rate, subtype="PCM_16")
    print(f"Saved to {output_filepath}")
    print(f"The text is '{text}'")
    print(f"Elapsed seconds: {elapsed_seconds:.3f}")
    print(f"Audio duration in seconds: {audio_duration:.3f}")
    print(f"RTF: {elapsed_seconds:.3f}/{audio_duration:.3f} = {real_time_factor:.3f}")

3、程序执行后不同环境下的输出情况：

1）win10系统单机demo：
Saved to Combined-WAV\vits-c-16.wav
The text is '你好，这是清华幼儿园广播频道，欢迎收听元旦晚会节目播报'
Elapsed seconds: 2.983
Audio duration in seconds: 6.208
RTF: 2.983/6.208 = 0.481

2）第二步中示例程序打包后在新服务器运行：
[root@localhost test-tts]#./gf
Saved to Combined-WAV/vits-c-16. wav
The text is‘你好，这是清华幼儿园广播频道，欢迎收听元旦晚会节目播报
Elapsed seconds: 12.079
Audio duration in secondst,5.920
RTF: 12.079/5.920=2.040   注：此demo是在交流中型号为Hygon C86 7380 32-Core Processor的cpu服务器运行的

**Comment by 20246688** [comment]
我发现第二个demo的rtf始终还是很高，所以主要是服务器cpu的原因吧？

**Comment by csukuangfj** [comment]
试试把num_threads用大一点？你现在是1，试试2，3，4，等几个值，看看rtf如何变化

**Comment by 20246688** [comment]
> 试试把num_threads用大一点？你现在是1，试试2,3,4，等几个值，看看rtf如何变化

团队老师您好，我通过修改线程数测试了一下我改写的demo；发现设置线程数大概在10到20之间的话，推理速度会快很多，同样的一句话，rtf大概在0.22左右。想再次请教一下团队老师这次问题的主要原因是什么呢？主要是因为cpu型号的影响么？类似的推理速度缓慢是不是都可以尝试通过调整线程数目来进行优化呢？

**Comment by csukuangfj** [comment]
你的服务器，单个cpu能力不行，但是，你服务器cpu多，设置number of threads，可以使用多个cpu一起算，所以速度快。

你自己需要去测试，看用什么数量的threads，速度最快

**Comment by 20246688** [comment]
> 你的服务器，单个cpu能力不行，但是，你服务器cpu多，设置number of threads，可以使用多个cpu一起算，所以速度快。
> 
> 你自己需要去测试，看用什么数量的threads，速度最快

好的！非常感谢！
