### ISSUE TITLE
用自己应用包名 app 奔溃

### ISSUE THREAD

**Issue by XTaoWang** [k2-fsa/sherpa-onnx#1626]
com.k2fsa.sherpa.onnx 这是 测试demo 的包名，如何替换自己的包名。可以跑，改包名运行奔溃

**Comment by csukuangfj** [comment]
方法是不改包名，直接 import.

---

如果你非得要改包名（不知道你这么做的动机是什么），你需要改 sherpa-onnx/jni/ 下面的 .cc 文件，需要你熟悉 jni. 不然，这个难度对你很大。

（提示，这个是完全开源的代码，用的 apacha 2.0 license, 对商用非常友好)

**Comment by XTaoWang** [comment]
1.想测试下，只需要改 sherpa-onnx/jni/ 下面的 .cc 文件就好了吧 ，（com_2fsa_sherpa_onnx 文件中的方法改成->自己的包名）
2.尝试下来还是 还是直接使用 package com.k2fsa.sherpa.onnx 原来包效率更高。感谢

**Comment by csukuangfj** [comment]
> 1.想测试下，只需要改 sherpa-onnx/jni/ 下面的 .cc 文件就好了吧 ，（com_2fsa_sherpa_onnx 文件中的方法改成->自己的包名）
> 2.尝试下来还是 还是直接使用 package com.k2fsa.sherpa.onnx 原来包效率更高。感谢
> 

1.对的。更细节的地方，需要你自己看代码，和对jni的理解


2。 对的。直接import 就可以。

我们还支持maven。你可以看SherpaOnnxJavaDemo里是如何使用的。我们的文档还没更新

**Comment by XTaoWang** [comment]
好的 谢谢
