### ISSUE TITLE
Add release for android C API

### ISSUE THREAD

**Issue by thewh1teagle** [k2-fsa/sherpa-onnx#1634]
It will be useful if sherpa-onnx release `aarch64-linux-android` and `armv7-linux-androideabi` C API libraries to releases.
I think that it should built with NDK

Related: https://github.com/thewh1teagle/sherpa-rs/issues/29

**Comment by thewh1teagle** [comment]
I guess I can use the `.so` files from https://github.com/k2-fsa/sherpa-onnx/releases/download/v1.10.35/sherpa-onnx-v1.10.35-android.tar.bz2 but there's no headers so I'll need to fetch it from the source

**Comment by csukuangfj** [comment]
Please turn on the option.in the build shell script to build C API.

**Comment by thewh1teagle** [comment]
> Please turn on the option.in the build shell script to build C API.

Could you also share the URL of the file?

Additionally, would it be possible to add this release by default to sherpa-onnx, or is there a specific reason not to?

**Comment by csukuangfj** [comment]
Could you change
https://github.com/k2-fsa/sherpa-onnx/blob/b76cd9033a521ac3b5b664c5765a9696aa494835/.github/workflows/android.yaml#L65
to
```
            export SHERPA_ONNX_ENABLE_C_API=ON
           ./build-android-arm64-v8a.sh 
```

Also, similarly, could you change
https://github.com/k2-fsa/sherpa-onnx/blob/b76cd9033a521ac3b5b664c5765a9696aa494835/.github/workflows/android.yaml#L77
https://github.com/k2-fsa/sherpa-onnx/blob/b76cd9033a521ac3b5b664c5765a9696aa494835/.github/workflows/android.yaml#L89

https://github.com/k2-fsa/sherpa-onnx/blob/b76cd9033a521ac3b5b664c5765a9696aa494835/.github/workflows/android.yaml#L101

Then the next release will contain C API `.so` for Android.
