### ISSUE TITLE
SherpaOnnxKeywordSpotterConfig 如何设置模型类型

### ISSUE THREAD

**Issue by endink** [k2-fsa/sherpa-onnx#1636]
C++ 使用 `SherpaOnnxKeywordSpotterConfig` 如何确定 `model_config.model_type`， 看了源码貌似可以自动从 encoder 文件中读取类型，会失败？   
使用的这个模型：

https://github.com/k2-fsa/sherpa-onnx/releases/download/kws-models/sherpa-onnx-kws-zipformer-wenetspeech-3.3M-2024-01-01.tar.bz2

是不是源码和模型不匹配啊

```
Please make sure you are using the latest export-onnx.py from icefall to export your transducer models
F:\Works\sherpa-onnx\sherpa-onnx\csrc\online-transducer-model.cc:Create:116 Unknown model type in online transducer!
```

**Comment by csukuangfj** [comment]
请贴完整的命令和log，请大方一点。

**Comment by endink** [comment]
我的问题，encoder/decoder 文件传反了
