### ISSUE TITLE
Problem with piper-tts models

### ISSUE THREAD

**Issue by mah92** [k2-fsa/sherpa-onnx#1637]
Hi
I am trying to test SherpaOnnxTts on android. 
Onnx lessac model from [pretrained_models](https://k2-fsa.github.io/sherpa/onnx/tts/pretrained_models/vits.html#en-us-lessac-medium-english-single-speaker) works but models from piper-voices repository like [lessac](https://huggingface.co/rhasspy/piper-voices/blob/main/en/en_US/lessac/medium/en_US-lessac-medium.onnx) not works (the program just hangs on startup). What conversion do you perform on piper models to work?
I use static libonnx(sherpa-onnx-static-link-onnxruntime-1.10.35.aar), can it be the problem source?

**Comment by mah92** [comment]
When converting a piper ckpt file, what steps are recommended? Then how can I add a voice to sherpa repo? Should I add an issue or change somewhere and add a pull request?

**Comment by csukuangfj** [comment]
Have you ever read the sherpa-onnx doc for converting models from piper?

Also, when you encounter errors, please describe in detail how to reproduce them and post the complete logs. Otherwise, we cannot help you.

**Comment by mablue** [comment]
https://k2-fsa.github.io/sherpa/onnx/tts/piper.html

**Comment by mah92** [comment]
Thank you. It was the problem. I still have one question, which I did not found in the documents.
How can I add a voice to sherpa repo? Should I add an issue or change somewhere and add a pull request?

**Comment by csukuangfj** [comment]
> Thank you. It was the problem. I still have one question(which I did not find in the documents)
> How can I add a voice to sherpa repo? Should I add an issue or change somewhere and add a pull request?

Do you mean to add a new piper tts model?

**Comment by mah92** [comment]
Yes I do

**Comment by csukuangfj** [comment]
> And also what conditions should I check before trying to add a piper model in your repo? Is there a checklist?

The next time you want to add a new model to sherpa-onnx from piper,please post the following links directly.
- https://huggingface.co/rhasspy/piper-voices/discussions/22
- https://huggingface.co/mah92/persian-english-piper-tts-model/

---

You don't need to do anything to add it to sherpa-onnx. Just post the links.

**Comment by csukuangfj** [comment]
You can download the model from
https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-fa_en-rezahedayatfar-ibrahimwalk-medium.tar.bz2

Or try it online at
https://huggingface.co/spaces/k2-fsa/text-to-speech?logs=container

<img width="1293" alt="Screenshot 2024-12-24 at 15 13 58" src="https://github.com/user-attachments/assets/7b637503-4cfc-4839-b0a0-4df47954f11f" />
