### ISSUE TITLE
Does it support whisper with timestamp?

### ISSUE THREAD

**Issue by NBStarry** [k2-fsa/sherpa-onnx#1650]
I've tired a simple case and get the ouput: {"lang": "", "emotion": "", "event": "", "text": " After early nightfall, the yellow lamps would light up here and there the squalid quarter of the brothels.", "timestamps": [], "tokens":[" After", " early", " night", "fall", ",", " the", " yellow", " lamps", " would", " light", " up", " here", " and", " there", " the", " squ", "alid", " quarter", " of", " the", " bro", "the", "ls", "."], "words": []}. 

How to get the timestamp?

**Comment by csukuangfj** [comment]
Please switch to another model.

You can find which model supports timestamps by looking at our doc.

There is an example output for each model in the doc.
