### ISSUE TITLE
增加 Flutter 库的 OnlineRecognizer.direct() 等构造函数

### ISSUE THREAD

**Issue by w-rui** [k2-fsa/sherpa-onnx#1660]
目前的 `OnlineRecognizer` 只有 `OnlineRecognizer._({required this.ptr, required this.config});` 和 `factory OnlineRecognizer(OnlineRecognizerConfig config)`。

由于 Flutter 的 factory 函数在主线程运行时，会在性能不佳的机器上，卡住主线程挺长时间。所以我们需要使用 `ReceivePort` 放到 Isolate 去初始化，以及做语音解析，但是子线程的 factory 返回的 OnlineRecognizer 无法传给主线程，因为 OnlineRecognizer 无法使用 ptr 和 config 直接初始化。

所以，我们需要一个额外的初始化方法（可以简单的讲 _ 构造函数重命名，或者新增）：
`OnlineRecognizer.direct({required this.ptr, required this.config});`

同理，TTS 也需要增加一个类似的构造函数： 
`OfflineTts.direct({required this.ptr, required this.config});`。

由于代码非常简单，就不 Pull Request 了，两行代码即可。

**Comment by csukuangfj** [comment]
能否帮忙提一个 pull request?

不管简单与否，只要对大家有帮助，我们都欢迎 pull request,

**Comment by csukuangfj** [comment]
Fixed by #1667
