### ISSUE TITLE
Different hypothesis key generations between sherpa and sherpa-onnx

### ISSUE THREAD

**Issue by jingzhaoou** [k2-fsa/sherpa-onnx#225]
For `sherpa`, the hypothesis key is generated using `torch::Join`

https://github.com/k2-fsa/sherpa/blob/8e3728bf61f54af6a90cd6f9ab37b288f82b9b15/sherpa/csrc/hypothesis.h#L55

Thus, for `[0, 4]`, the key is `0-4`. 

However, for `sherpa-onnx`, the hypothesis key has an extra `-` at the end:

https://github.com/k2-fsa/sherpa-onnx/blob/a12252a01dd74ef10aaae52f1b8ef4415d33242f/sherpa-onnx/csrc/hypothesis.h#L60-L69

Thus, for `[0, 4]`, the key is `0-4-`. 

I wonder if we should change `sherpa-onnx` to match `sherpa`. Please advice.

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/sherpa-onnx/blob/a12252a01dd74ef10aaae52f1b8ef4415d33242f/sherpa-onnx/csrc/hypothesis.h#L63

should be
```cpp
 std::string sep = ""; 
```

> I wonder if we should change sherpa-onnx to match sherpa. Please advice.

Yes, please make a pull-request to fix it.

**Comment by jingzhaoou** [comment]
@csukuangfj  thanks! I just created a PR https://github.com/k2-fsa/sherpa-onnx/pull/226 for this change.
