### ISSUE TITLE
Hello,w hen will stream Chinese support/?

### ISSUE THREAD

**Issue by jinfagang** [k2-fsa/sherpa-onnx#23]
Hello,w hen will stream Chinese support/?

**Comment by csukuangfj** [comment]
tomorrow.

**Comment by csukuangfj** [comment]
Please see
https://k2-fsa.github.io/sherpa/onnx/pretrained_models/lstm-transducer-models.html#csukuangfj-sherpa-onnx-lstm-zh-2023-02-20-chinese

We are adding more pre-trained models in addition to LSTM transducer.
