### ISSUE TITLE
RuntimeError when running sherpa-onnx - Dimension Mismatch

### ISSUE THREAD

**Issue by lightfate** [k2-fsa/sherpa-onnx#235]
Hello,

I'm trying to use the sherpa-onnx Python API to transcribe audio files with the zipformer model. However, I'm encountering an error indicating a dimension mismatch between the input data and the model's expectations.

Here is the command I'm running:

python offline-decode-files.py \
  --tokens=./sherpa-onnx-zipformer-en-2023-04-01/tokens.txt \
  --encoder=./sherpa-onnx-zipformer-en-2023-04-01/encoder-epoch-99-avg-1.onnx \
  --decoder=./sherpa-onnx-zipformer-en-2023-04-01/decoder-epoch-99-avg-1.onnx \
  --joiner=./sherpa-onnx-zipformer-en-2023-04-01/joiner-epoch-99-avg-1.onnx \
  ./sherpa-onnx-zipformer-en-2023-04-01/test_wavs/0.wav \
  ./sherpa-onnx-zipformer-en-2023-04-01/test_wavs/1.wav \
  ./sherpa-onnx-zipformer-en-2023-04-01/test_wavs/8k.wav

And here is the error message I'm getting:
Started!
D:\a\sherpa-onnx\sherpa-onnx\sherpa-onnx\csrc\offline-stream.cc:AcceptWaveformImpl:108 Creating a resampler:
   in_sample_rate: 8000
   output_sample_rate: 16000
Traceback (most recent call last):
  File "offline-decode-files.py", line 340, in <module>
    main()
  File "offline-decode-files.py", line 319, in main
    recognizer.decode_streams(streams)
  File "D:\004-Workspace\pycharm\sherpa\venv\lib\site-packages\sherpa_onnx\offline_recognizer.py", line 242, in decode_streams
    self.recognizer.decode_streams(ss)
RuntimeError: Got invalid dimensions for input: x for the following indices
 index: 1 Got: 1764 Expected: 39
 Please fix either the inputs or the model.

From the error message, it seems like the input data's dimensions don't match what the model is expecting. However, I'm not sure why this is the case, as I'm using the provided offline-decode-files.py script and the test WAV files and your models

I would greatly appreciate any insights or advice on how to resolve this issue. Thank you in advance for your help!

here is my env:
python ==3.8
(venv) PS D:\004-Workspace\pycharm\sherpa> pip list
Package       Version
------------- -------
numpy         1.24.4
pip           22.3.1
sentencepiece 0.1.96
setuptools    65.5.1
sherpa-onnx   1.5.5
wheel         0.38.4

**Comment by csukuangfj** [comment]
Could you pass the option
```
--debug=true
```
when you invoke
```
python offline-decode-files.py
```
and show the output?

**Comment by csukuangfj** [comment]
Here is the output on my side when using `--debug=true`:
```
/Users/runner/work/sherpa-onnx/sherpa-onnx/sherpa-onnx/csrc/offline-transducer-model.cc:InitEncoder:141 ---encoder---
model_author=k2-fsa
model_type=zipformer
version=1
comment=stateless7


/Users/runner/work/sherpa-onnx/sherpa-onnx/sherpa-onnx/csrc/offline-transducer-model.cc:InitDecoder:161 ---decoder---
vocab_size=500
context_size=2


/Users/runner/work/sherpa-onnx/sherpa-onnx/sherpa-onnx/csrc/offline-transducer-model.cc:InitJoiner:185 ---joiner---
joiner_dim=512


Started!
/Users/runner/work/sherpa-onnx/sherpa-onnx/sherpa-onnx/csrc/offline-stream.cc:AcceptWaveformImpl:108 Creating a resampler:
   in_sample_rate: 8000
   output_sample_rate: 16000
```

Please make sure you are using the correct model.

Please show the sha256sum of your model files.

**Comment by csukuangfj** [comment]
```
(py38) fangjuns-MacBook-Pro:sherpa-onnx-zipformer-en-2023-04-01 fangjun$ shasum -a 256 encoder-epoch-99-avg-1.onnx
7d495012dd5b7ba008143f0c9cb52f3fd97ab0f208923d6a03be0e7db0cd4a4d  encoder-epoch-99-avg-1.onnx
(py38) fangjuns-MacBook-Pro:sherpa-onnx-zipformer-en-2023-04-01 fangjun$ ls -lh encoder-epoch-99-avg-1.onnx
-rw-r--r--  1 fangjun  staff   337M Apr  2 17:43 encoder-epoch-99-avg-1.onnx
(py38) fangjuns-MacBook-Pro:sherpa-onnx-zipformer-en-2023-04-01 fangjun$ ls -l encoder-epoch-99-avg-1.onnx
-rw-r--r--  1 fangjun  staff  353667745 Apr  2 17:43 encoder-epoch-99-avg-1.onnx
```

Please make sure your output matches the above output.

**Comment by csukuangfj** [comment]
I suspect that you are using a streaming zipformer but somehow for some unknown reason you put them incorrectly in the folder `sherpa-onnx-zipformer-en-2023-04-01/`.

**Comment by lightfate** [comment]
(venv) PS D:\004-Workspace\pycharm\sherpa> CertUtil -hashfile ./sherpa-onnx-zipformer-en-2023-04-01/encoder-epoch-99-avg-1.onnx SHA256 
SHA256 的 ./sherpa-onnx-zipformer-en-2023-04-01/encoder-epoch-99-avg-1.onnx 哈希:
709f0ed53a734b7942f170127e7547b566cb29c4afc5e67719f314c3d63ccb10

I use the model：
csukuangfj/sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20 (Bilingual, Chinese + English)[](https://k2-fsa.github.io/sherpa/onnx/pretrained_models/online-transducer/zipformer-transducer-models.html#csukuangfj-sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20-bilingual-chinese-english)
can i use the bilingual-chinese-english model in offline-decode-files.py

**Comment by lightfate** [comment]
ok，thank you so much~

**Comment by lonngxiang** [comment]
AssertionError: sample-rate=16000 does not exist!

输入语音文件只能16000采样吗

**Comment by csukuangfj** [comment]
> AssertionError: sample-rate=16000 does not exist!
> 
> 输入语音文件只能16000采样吗

你把你使用的完整命令，贴出来。

**Comment by lonngxiang** [comment]
这边保存文件是这个采样
Frame rate: 48000

运行转录文本报错：
```
python    offline-decode-files.py  --tokens=C:\Users\loong\Downloads\sherpa-onnx-paraformer-trilingual-zh-cantonese-en\sherpa-onnx-paraformer-trilingual-zh-cantonese-en\tokens.txt --paraformer=C:\Users\loong\Downloads\sherpa-onnx-paraformer-trilingual-zh-cantonese-en\sherpa-onnx-paraformer-trilingual-zh-cantonese-en\model.onnx --num-threads=2 --decoding-method=greedy_search --debug=True sample-rate=16000 feature-dim=80 audio.wav

```

**Comment by csukuangfj** [comment]
请帖完整的 error log

**Comment by lonngxiang** [comment]
> 请帖完整的 error log

需要提前wav文件转换采样率才能用吗
```

Started!
Traceback (most recent call last):
  File "D:\project\MeloTTS\offline-decode-files.py", line 472, in <module>
    main()
  File "D:\project\MeloTTS\offline-decode-files.py", line 442, in main
    assert_file_exists(wave_filename)
  File "D:\project\MeloTTS\offline-decode-files.py", line 290, in assert_file_exists
    assert Path(filename).is_file(), (
AssertionError: sample-rate=16000 does not exist!
Please refer to https://k2-fsa.github.io/sherpa/onnx/pretrained_models/index.html to download it 
```

**Comment by csukuangfj** [comment]
```
sample-rate=16000 feature-dim=80 audio.wav
```

是你自己命令输错了

你把
```
--sample-rate
```

改成了
```
sample-rate
```

你漏掉了 `--`.

**Comment by lonngxiang** [comment]
> ```
> sample-rate=16000 feature-dim=80 audio.wav
> ```
> 
> 是你自己命令输错了
> 
> 你把
> 
> ```
> --sample-rate
> ```
> 
> 改成了
> 
> ```
> sample-rate
> ```
> 
> 你漏掉了 `--`.

嗯是漏了，但填上怎么没有识别结果输出？

这些都没有打印
```
results = [s.result.text for s in streams]
    end_time = time.time()
    print(results)
    print("Done!")

    for wave_filename, result in zip(args.sound_files, results):
        print(f"{wave_filename}\n{result}")
        print("-" * 10)
```
![image](https://github.com/k2-fsa/sherpa-onnx/assets/40717349/34374152-e7cd-4712-b292-86c01fd53c59)

**Comment by lonngxiang** [comment]
还有这种情况保存，换个wav文件

```

Started!
Traceback (most recent call last):
  File "D:\project\MeloTTS\offline-decode-files.py", line 473, in <module>
    main()
  File "D:\project\MeloTTS\offline-decode-files.py", line 443, in main
    samples, sample_rate = read_wave(wave_filename)
  File "D:\project\MeloTTS\offline-decode-files.py", line 312, in read_wave
    assert f.getsampwidth() == 2, f.getsampwidth()  # it is in bytes
AssertionError: 4
```

**Comment by csukuangfj** [comment]
我们只支持 wave 格式。请自己阅读 python 代码，自己调试。

**Comment by csukuangfj** [comment]
如果你用的是我们的测试音频，没有结果输出，我们可以看。

如果是你自己调用的问题，或者使用错误的音频格式，这个需要你自己解决。

**Comment by lonngxiang** [comment]
> 如果你用的是我们的测试音频，没有结果输出，我们可以看。
> 
> 如果是你自己调用的问题，或者使用错误的音频格式，这个需要你自己解决。

嗯嗯好的

**Comment by lonngxiang** [comment]
> > ```
> > sample-rate=16000 feature-dim=80 audio.wav
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 是你自己命令输错了
> > 你把
> > ```
> > --sample-rate
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 改成了
> > ```
> > sample-rate
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 你漏掉了 `--`.
> 
> 嗯是漏了，但填上怎么没有识别结果输出？
> 
> 这些都没有打印
> 
> ```
> results = [s.result.text for s in streams]
>     end_time = time.time()
>     print(results)
>     print("Done!")
> 
>     for wave_filename, result in zip(args.sound_files, results):
>         print(f"{wave_filename}\n{result}")
>         print("-" * 10)
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/40717349/316720848-228b9293-80ce-4496-a76d-5c3c922a2655.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MjUzMTksIm5iZiI6MTcxMTQyNTAxOSwicGF0aCI6Ii80MDcxNzM0OS8zMTY3MjA4NDgtMjI4YjkyOTMtODBjZS00NDk2LWE3NmQtNWMzYzkyMmEyNjU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDAzNTAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMWY3ZmVhNTFjYmUyNGM1MTlhNmZlNWZiMzg1YzE3NTJlODFhMWU4MzRmNWZjMTJmYzFiNDc0MjI1ODlmNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qb_zBCmNZ1DLH_MpMXvRwa4cmsMz3lfBCB0wpVcdA9k)

但这个正常音频文件没有报错信息能帮看下原因吗，怎么发出来wav看看？

**Comment by lonngxiang** [comment]
这是音频压缩zip

[ezyzip.zip](https://github.com/k2-fsa/sherpa-onnx/files/14752381/ezyzip.zip)

**Comment by csukuangfj** [comment]
请把你调用的命令发出来

**Comment by lonngxiang** [comment]
这个模型 comment=speech_seaco_paraformer_large_asr_nat-zh-cantonese-en-16k-common-vocab11666-pytorch       
```
python    offline-decode-files.py  --tokens=C:\Users\loong\Downloads\sherpa-onnx-paraformer-trilingual-zh-cantonese-en\sherpa-onnx-paraformer-trilingual-zh-cantonese-en\tokens.txt --paraformer=C:\Users\loong\Downloads\sherpa-onnx-paraformer-trilingual-zh-cantonese-en\sherpa-onnx-paraformer-trilingual-zh-cantonese-en\model.onnx --num-threads=2 --decoding-method=greedy_search --debug=True --sample-rate=16000 --feature-dim=80 audio123.wav 
```

**Comment by lonngxiang** [comment]
@csukuangfj  另外这两个wav按照1个频道，16000采样还是识别不了，没有报错，开始start后就没有后续直接结束了程序；这边测试了下其他工具可以识别

[ezyzip1.zip](https://github.com/k2-fsa/sherpa-onnx/files/14766265/ezyzip1.zip)
![image](https://github.com/k2-fsa/sherpa-onnx/assets/40717349/503f7f6d-d0b9-4450-b8a1-ff73d2a33d6d)

![image](https://github.com/k2-fsa/sherpa-onnx/assets/40717349/a318ebed-044c-483c-aaa0-7a2ccbbaf0ce)

**Comment by csukuangfj** [comment]
<img width="1353" alt="Screenshot 2024-03-27 at 10 07 18" src="https://github.com/k2-fsa/sherpa-onnx/assets/5284924/cde5169a-49c1-4fea-aa65-50b86585aae8">

我这里是可以的。你那里识别不出来，我就不知道了。

---

https://huggingface.co/spaces/k2-fsa/automatic-speech-recognition
这个 huggingface space, 也能识别出来。你找找你自己的原因吧。

<img width="1086" alt="Screenshot 2024-03-27 at 10 08 58" src="https://github.com/k2-fsa/sherpa-onnx/assets/5284924/9b0dbaa7-a54b-47f7-890a-2fe2bf4e3b00">

**Comment by lonngxiang** [comment]
> <img alt="Screenshot 2024-03-27 at 10 07 18" width="1353" src="https://private-user-images.githubusercontent.com/5284924/317096975-cde5169a-49c1-4fea-aa65-50b86585aae8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MDU2ODgsIm5iZiI6MTcxMTUwNTM4OCwicGF0aCI6Ii81Mjg0OTI0LzMxNzA5Njk3NS1jZGU1MTY5YS00OWMxLTRmZWEtYWE2NS01MGI4NjU4NWFhZTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjdUMDIwOTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGUwY2E2MzIyZGNiNGY0OGYxYmEwZGVlM2RjMTQzZDVlMTA5ZjhhNTBkOGJhOGJmNDUyYWNiMTczMTk3ZDFhZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ICPHlCb8c1hviEPfrz6_AKkqhep_zGkZAjgxtMIL9Ak">
> 我这里是可以的。你那里识别不出来，我就不知道了。
> 
> https://huggingface.co/spaces/k2-fsa/automatic-speech-recognition 这个 huggingface space, 也能识别出来。你找找你自己的原因吧。
> 
> <img alt="Screenshot 2024-03-27 at 10 08 58" width="1086" src="https://private-user-images.githubusercontent.com/5284924/317097196-9b0dbaa7-a54b-47f7-890a-2fe2bf4e3b00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MDU2ODgsIm5iZiI6MTcxMTUwNTM4OCwicGF0aCI6Ii81Mjg0OTI0LzMxNzA5NzE5Ni05YjBkYmFhNy1hNTRiLTQ3ZjctODkwYS0yZmUyYmY0ZTNiMDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjdUMDIwOTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTliZjFhZjIwNWYwNmIyY2RhNjI5OGMzNmUwZDQ5ZWJiNGM5ODdjMTU3Mjk4NWYzNTM0ZTNiZDg1M2YzMDdmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rKGuOHgD5suudd6DhTV0Go14s3D8V0Eej753LoDd2PI">

嗯，这么奇怪，我再看看，多谢

**Comment by lonngxiang** [comment]
debug出来，大概是到这个函数出错，但这个函数就是没有报错信息，也不好进去查看具体实现细节，现在版本升级到最新版也不行
![image](https://github.com/k2-fsa/sherpa-onnx/assets/40717349/4b3ddf09-5f19-43ce-8060-3b6e5e98c289)

**Comment by lonngxiang** [comment]
在安装的包里没有找到_sherpa_onnx相关文件
```
from _sherpa_onnx import (
    OfflineRecognizerConfig,
    OfflineStream,
```

![image](https://github.com/k2-fsa/sherpa-onnx/assets/40717349/127ba47f-8cda-4679-8001-42df4d1078d8)

**Comment by lonngxiang** [comment]
在linux上运行，直接报段错误
![image](https://github.com/k2-fsa/sherpa-onnx/assets/40717349/bf62e02c-3055-4672-928c-70233a1ff745)

**Comment by csukuangfj** [comment]
你的 offline_file.py 如何得到的？

你用我们提供的代码，不做任何修改，是否有问题？

**Comment by lonngxiang** [comment]
> 你的 offline_file.py 如何得到的？
> 
> 你用我们提供的代码，不做任何修改，是否有问题？

完全用的官方代码，https://github.com/k2-fsa/sherpa-onnx/blob/master/python-api-examples/offline-decode-files.py

现在不知道是安装包，环境冲突还是，暂时没发现具体产生问题

**Comment by csukuangfj** [comment]
你用 c++ 编译出来的二进制 `sherpa-onnx-offline` 去试试？
