### ISSUE TITLE
go-api-examples/real-time-speech-recognition-from-microphone line 59 code error

### ISSUE THREAD

**Issue by ghjdegithub** [k2-fsa/sherpa-onnx#255]
code dir: go-api-examples/real-time-speech-recognition-from-microphone
API call error in line 59 of the code。
It should be call DeleteOnlineStream, but call NewOnlineStream. go build failed

**Comment by csukuangfj** [comment]
Thanks for pointing it out. Could you please create a pull-request to fix it?
