### ISSUE TITLE
Identifying web socket streams when dealing with multiple clients

### ISSUE THREAD

**Issue by Caet-pip** [k2-fsa/sherpa-onnx#279]
Hello, I am using streaming_server.py file as the server, is there any way to identify the individual clients that connect to my server to differentiate their streams and possibly give them a unique id.

Thanks.

**Comment by csukuangfj** [comment]
Yes, please see
https://github.com/k2-fsa/sherpa-onnx/blob/e31f9e48c2932385c62d31f8d77829574b222909/python-api-examples/streaming_server.py#L605

You can get the client IP and port from `socket`.

Please refer to the documentation of `websockets` about how to do that.

**Comment by Caet-pip** [comment]
Hello, thanks for the reply.

> Please refer to the documentation of `websockets` about how to do that.

This refers to websockets official documentation or websocket section in sherpa-onnx documentation

**Comment by csukuangfj** [comment]
Please refer to the python package `websockets`.
