### ISSUE TITLE
Endpointing not working with zipformer models

### ISSUE THREAD

**Issue by uni-sagar-raikar** [k2-fsa/sherpa-onnx#282]
Hi @csukuangfj ,

Even though there are endpointing flags and configs with sherpa-onnx-websocket-server, we are finding only single segment in outputs without any segmentation. 

I see that, here https://github.com/k2-fsa/sherpa-onnx/blob/eb22b4845a048014d67ec2624ebcf48e5df8d0a0/sherpa-onnx/csrc/online-recognizer-transducer-impl.h#L188 there is no endpointing logic as sherpa. Is this incomplete? or am I missing something?

Thanks

**Comment by csukuangfj** [comment]
There is pull-request for that.
https://github.com/k2-fsa/sherpa-onnx/pull/175

I have been planning to refactor the endpointing logic in sherpa-onnx so that PR has not been merged yet.

**Comment by uni-sagar-raikar** [comment]
Checking this PR commit right now. Any ETA on when this merge will happen? I think latest refactoring has more changes compared to this PR codebase.

**Comment by csukuangfj** [comment]
> Checking this PR commit right now. Any ETA on when this merge will happen? I think latest refactoring has more changes compared to this PR codebase.

Probably in the coming month. We are quite busy this month.

**Comment by csukuangfj** [comment]
I think it is supported now. Please use the latest master.
