### ISSUE TITLE
terminate called after throwing an instance of 'nlohmann::json_abi_v3_11_2::detail::type_error'

### ISSUE THREAD

**Issue by wangpy1204** [k2-fsa/sherpa-onnx#288]
How can I fix the error that occurs when I use the Whisper model for Chinese speech recognition?
![image](https://github.com/k2-fsa/sherpa-onnx/assets/35224733/5604062f-3fe2-4052-83df-4728badff774)

**Comment by csukuangfj** [comment]
Please change
https://github.com/k2-fsa/sherpa-onnx/blob/49ec7e8f57f71115dcc758eaec68132c42c0e74b/sherpa-onnx/csrc/sherpa-onnx-offline.cc#L146
to
```
 ss[i - 1]->GetResult().text.c_str()); 
```

We will replace the json serialization library to fix this issue.

Or you can switch to
https://github.com/k2-fsa/sherpa-onnx/blob/master/python-api-examples/offline-decode-files.py
