### ISSUE TITLE
Explanation behind segment 

### ISSUE THREAD

**Issue by Caet-pip** [k2-fsa/sherpa-onnx#290]
Hello,

Can you please explain how the logic behind the segment output. I am trying to create an application with multiple speakers which displays turn by turn transcript.

Sometimes when one speaker is talking and another starts talking, their segment does not increment with the new transcript, is there any way to modify the segment logic, any help with this is appreciated. Thanks.

**Comment by danpovey** [comment]
The segments are just separated by a certain length of silence, right now there is nothing that is intended to detect a change of speaker.

**Comment by csukuangfj** [comment]
By the way, the principle for endpointing is described in the following documentation:
https://k2-fsa.github.io/sherpa/ncnn/endpoint.html

**Comment by Caet-pip** [comment]
Thanks for the response!
