### ISSUE TITLE
When will c-api be supported on windows?

### ISSUE THREAD

**Issue by NEUzht** [k2-fsa/sherpa-onnx#297]
When will c-api be supported on windows?

**Comment by csukuangfj** [comment]
It is already supported. We even have MFC examples that use the c-api to build a single exe.

Could you tell us the difficulties you have?

**Comment by NEUzht** [comment]
I have followed our project documentation and generated the exe file. Now I want to build the project in vs and use the static library files generated during the installation process, now I have a little problem.
![image](https://github.com/k2-fsa/sherpa-onnx/assets/75012618/9b2cab67-faec-4e6b-88da-653d698e7183)

**Comment by csukuangfj** [comment]
Please describe the problem you have.

**Comment by csukuangfj** [comment]
Please describe what you have done.

The more information you provide, the quicker we can help you fix it.

**Comment by NEUzht** [comment]
![image](https://github.com/k2-fsa/sherpa-onnx/assets/75012618/7258549b-9080-4add-8ab2-4fbb5493ea68)

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/sherpa-onnx/tree/master/mfc-examples

The above folder contains examples of using the C API in visual studio with MFC.

![Screenshot 2023-09-03 at 14 10 44](https://github.com/k2-fsa/sherpa-onnx/assets/5284924/781d59bd-d93e-453c-8b81-87120de885bd)

**Comment by csukuangfj** [comment]
> https://github.com/k2-fsa/sherpa-onnx/tree/master/mfc-examples

Sorry, please also use text to describe your issue.

**Comment by NEUzht** [comment]
I have added these above static libraries as well as header files in Visual Studio 2022 and now there is no way to run it with the above LNK200 error.

**Comment by csukuangfj** [comment]
> I have added these above static libraries as well as header files

Please describe in detail how you add them and preferably also add screenshots.


Please upload the file ending with `.vcxproj`.

**Comment by csukuangfj** [comment]
vs has settings for release and debug separately, and it also has settings for win32 and x64. please make sure you have added it correctly.

**Comment by NEUzht** [comment]
I'm using the same version as when I compiled the static libraries, release and x64.
![image](https://github.com/k2-fsa/sherpa-onnx/assets/75012618/d9ea6d0c-2f55-4b2d-a8e3-ea9ce700f604)
And I've added the library's include directory to the project's configuration properties.

![image](https://github.com/k2-fsa/sherpa-onnx/assets/75012618/e53234e2-cb13-4ea8-bbcb-7d5329307e3d)

**Comment by NEUzht** [comment]
https://k2-fsa.github.io/sherpa/onnx/install/windows.html#bit-windows-x64
where lib is generated with the following command
git clone https://github.com/k2-fsa/sherpa-onnx
cd sherpa-onnx
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ...
cmake --build . --config Release

**Comment by NEUzht** [comment]
[sherpa_1.zip](https://github.com/k2-fsa/sherpa-onnx/files/12505320/sherpa_1.zip)

**Comment by NEUzht** [comment]
How do I fix this?

**Comment by csukuangfj** [comment]
> ![image](https://user-images.githubusercontent.com/75012618/265244354-9b2cab67-faec-4e6b-88da-653d698e7183.png)

We can find several mistakes that you have made from the above screenshots.

First, you are asking the C API issue, so I assume you only need to include the header
https://github.com/k2-fsa/sherpa-onnx/blob/master/sherpa-onnx/c-api/c-api.h

You can find that `c-api.h` does not depend on any other header files from sherpa-onnx. In other words,  `endpoint.h` and `hypothesis.h` should not be included in your project.

Second, you have not included the lib for onnxruntime that is why it complains some symbols from onnxruntime are not found.

---

From the file [sherpa_1.zip](https://github.com/k2-fsa/sherpa-onnx/files/12505320/sherpa_1.zip) you posted, we can see that you include the wrong path:
```
  <AdditionalIncludeDirectories>C:\Users\zht\Desktop\github\sherpa-onnx\sherpa-onnx\csrc;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
```

The `c-api.h` is inside `sherpa-onnx/c-api`, not in `sherpa-onnx/csrc`.

Also, if you are using
```
#include "sherpa-onnx/c-api/c-api.h"
```

You should use
```
  <AdditionalIncludeDirectories>C:\Users\zht\Desktop\github\sherpa-onnx;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
```

**Comment by csukuangfj** [comment]
> How do I fix this?

From the screenshots you have posted, we assume you don't have much experience about using an external pre-built project in vs, we suggest that you use
https://github.com/k2-fsa/sherpa-onnx/tree/master/mfc-examples
as a starting point. We have setup everything for you.

All you need is to run
```
cd C:\Users\zht\Desktop\github\sherpa-onnx
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=.\install ...
cmake --build . --config Release --target install
```
and then you can double click the following file
https://github.com/k2-fsa/sherpa-onnx/blob/master/mfc-examples/mfc-examples.sln


You can remove things from `mfc-examples` that you don't need.

**Comment by NEUzht** [comment]
ok,i will try it

**Comment by NEUzht** [comment]
Thanks for giving me the solution, it's really my first time to build a c++ project, I don't have much experience, I think I'm just missing the onnxruntinme lib, there's a problem with the path you mentioned above, that's the Debug version, I didn't correct it in time!

**Comment by NEUzht** [comment]
Thanks again for the solution, I've got it solved now
![image](https://github.com/k2-fsa/sherpa-onnx/assets/75012618/00b8b311-3559-498c-85ee-33f783064fe3)
