### ISSUE TITLE
What is the difference between offline vs online model?

### ISSUE THREAD

**Issue by debasish-mihup** [k2-fsa/sherpa-onnx#302]
What is the difference between offline vs online in streaming mode? I am trying to run the Zipformer2 model locally directly with audio buffer data.

**Comment by csukuangfj** [comment]
> What is the difference between offline vs online in streaming mode?

For online models, i.e., streaming models, you can get recognition results as you speak.
For offline models, i.e., non-streaming models, you must send all the audio data at once for recognition.

If you want real-time speech recognition, please use an online model.

In general, offline models have better recognition accuracy than online models.

Online/Offline here has nothing to do with computer networks.
