### ISSUE TITLE
speaker diarization

### ISSUE THREAD

**Issue by matbee-eth** [k2-fsa/sherpa-onnx#325]
Has there been any effort or plans to include speaker diarization in Sherpa?

**Comment by csukuangfj** [comment]
Sorry, currently there is no such a plan.

**Comment by csukuangfj** [comment]
By the way, we support speaker identification/verification now.

Please find Android APKs at
https://k2-fsa.github.io/sherpa/onnx/speaker-identification/apk.html

**Comment by thewh1teagle** [comment]
> By the way, we support speaker identification/verification now.

What about segmentation? do you support it? I think that's the only missing part currently to implement diarization on top of sherpa

**Comment by csukuangfj** [comment]
We support silero vad.

**Comment by csukuangfj** [comment]
@matbee-eth By the way, we have supported speaker diarization.
