### ISSUE TITLE
[Bug] Online websocket server response empty for first few sends after connected.

### ISSUE THREAD

**Issue by samx81** [k2-fsa/sherpa-onnx#327]
In my case, the client would connect to the online websocket server, speak a few word and `Done` to get the result, the audio duration is usually between 3~10 seconds so the server should response right away after connected to server.
After commit aa48b76, I need to wait/speak much longer to get response. It feels like I have to wait 1 or 2 endpoints so the server can start working.

I guess the problem is caused by setting `0` to `-1` in these line but I don't really sure what it does, but changing them back to `0` does fix the problem:
https://github.com/k2-fsa/sherpa-onnx/blob/aa48b76d4b6781266d140f0b4f83c449a07cd579/sherpa-onnx/csrc/online-transducer-greedy-search-decoder.cc#L58-L59

Is this normal or should I set some params to avoid getting empty response at the beginning?

**Comment by csukuangfj** [comment]
Which model are you using? If you use your own model, what code are you using to train the model?

**Comment by samx81** [comment]
> Which model are you using? If you use your own model, what code are you using to train the model?

I'm using [sherpa-onnx-streaming-zipformer-en-2023-06-21](https://k2-fsa.github.io/sherpa/onnx/pretrained_models/online-transducer/zipformer-transducer-models.html#csukuangfj-sherpa-onnx-streaming-zipformer-en-2023-06-21-english) since it has trained on multiple corpus

**Comment by samx81** [comment]
Thanks! The updated `decoder.onnx` works just like before!
Does it means I have to re-export my own models if I want to use them after this commit?

**Comment by csukuangfj** [comment]
> Thanks! The updated `decoder.onnx` works just like before! Does it means I have to re-export my own models if I want to use them after this commit?

Yes, please use
https://github.com/k2-fsa/icefall/pull/1264
to re-export your own model.
