### ISSUE TITLE
Any plans to bring flashlight decoder to the sherpa inference framework?

### ISSUE THREAD

**Issue by kafan1986** [k2-fsa/sherpa-onnx#343]
Some times the use case requires the output being limited to the training vocab. Is it possible now? Flashlight decoder implementation allows this. Any plans of bringing this functionality to this framework?

**Comment by csukuangfj** [comment]
Could you describe what your issue is?

**Comment by kafan1986** [comment]
> Could you describe what your issue is?

Updated the description and other details.

**Comment by csukuangfj** [comment]
We are trying
https://github.com/k2-fsa/icefall/pull/1244

With the above PR, you can use HL or HLG decoding for models trained using CTC loss.

If you introduce L into the search, only words in the lexicon can be decoded.

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/sherpa-onnx/pull/349

@kafan1986 

Please see the above PR, you can use HL or HLG decoding. Only words present in L can be decoded.
