### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by rouseabout** [k2-fsa/sherpa-onnx#393]
https://k2-fsa.github.io/sherpa/onnx/tts/pretrained_models/vits.html

> Since there are 109 speakers available, we can choose a speaker from 0 to 198. The default speaker ID is 0.

s/198/108/

**Comment by csukuangfj** [comment]
Thanks! Will fix it.

**Comment by csukuangfj** [comment]
Closing as it has been fixed.
