### ISSUE TITLE
Is the sherpa-onnx tts support the sample rate 16k?

### ISSUE THREAD

**Issue by OswaldoBornemann** [k2-fsa/sherpa-onnx#405]
Is the sherpa-onnx tts support the sample rate 16k?

**Comment by csukuangfj** [comment]
You can use `resample.{h,cc}` to resample the output audio samples or you can use a third party resampler.

**Comment by OswaldoBornemann** [comment]
@csukuangfj Thank you very much. Do we have the Android source code demo like ASR that we can compile the Android SDK from the source? I have noticed that the Android demo in sherpa-onnx is built for the need of ASR, from which the front-end code is not compatible with the need of TTS. Thanks.

**Comment by csukuangfj** [comment]
We have android demo for tts, please see
https://github.com/k2-fsa/sherpa-onnx/tree/master/android/SherpaOnnxTts

(The build process is identical to that of ASR)

**Comment by csukuangfj** [comment]
You can find a list of APKs for TTS at
https://k2-fsa.github.io/sherpa/onnx/tts/apk.html

<img width="955" alt="Screenshot 2023-11-01 at 11 30 52" src="https://github.com/k2-fsa/sherpa-onnx/assets/5284924/8c9a714e-7726-4317-a4d7-f1fbac055e7b">

**Comment by OswaldoBornemann** [comment]
Yeah i found it as well. But what if I want to change the TTS model then how do I achieve that? Thanks.

**Comment by OswaldoBornemann** [comment]
> We have android demo for tts, please see https://github.com/k2-fsa/sherpa-onnx/tree/master/android/SherpaOnnxTts
> 
> (The build process is identical to that of ASR)

Oh I see. Thank you very much

**Comment by OswaldoBornemann** [comment]
@csukuangfj So do i need to run the command `./build-android-arm64-v8a.sh` as well to build the `SherpaOnnxTts` project?
``

**Comment by OswaldoBornemann** [comment]
@csukuangfj Oh i got your meaning. I will try myself first. Thank you very much.

**Comment by csukuangfj** [comment]
> So do i need to run the command ./build-android-arm64-v8a.sh

Yes, you are correct. You need to build the C++ code to get shared libraries that can be used by android studio.

Please see our build for android documentation, though it is written for ASR, it is applicable also to TTS.

**Comment by csukuangfj** [comment]
>  But what if I want to change the TTS model then how do I achieve that? 

Please read the TTS kotlin code first. Once read, I believe you know how to change it. 
(You only need to change two variables to specify the model directory and model name)
