### ISSUE TITLE
VAD might not output last segment

### ISSUE THREAD

**Issue by chiiyeh** [k2-fsa/sherpa-onnx#415]
I might be mistaken, but it seems like the segments is only push out when no speech is detected. However the audio might be cut off say in between a speech, so the last segment does not hit the nospeech decision and is not added to be popped out.

**Comment by csukuangfj** [comment]
Could you point to the related code?

**Comment by chiiyeh** [comment]
Hmmm.. I think there is nothing wrong with the code here: 
https://github.com/k2-fsa/sherpa-onnx/blob/master/sherpa-onnx/csrc/voice-activity-detector.cc#L48-L69
But more of it missing a function to kind of flush out the last segment when the audio ends and there is speech remaining that is not yet returned as a segment.

**Comment by csukuangfj** [comment]
> But more of it missing a function to kind of flush out the last segment 

Oh, I see your point. The issue is we need to know when the last segment comes.

**Comment by chiiyeh** [comment]
Maybe will need a seperate function `vad.flush()` which will append any dangling segment?
Once we know the audio has ended we can run this function. Like for the code here: https://github.com/k2-fsa/sherpa-onnx/blob/master/python-api-examples/generate-subtitles.py#L345-L378
Can be change to:
```python
    sample_remains = True
    while sample_remains:
        # *2 because int16_t has two bytes
        data = process.stdout.read(frames_per_read * 2)
        if not data:
            sample_remains = False
            vad.flush()

        samples = np.frombuffer(data, dtype=np.int16)
        samples = samples.astype(np.float32) / 32768

        buffer = np.concatenate([buffer, samples])
        while len(buffer) > window_size:
            vad.accept_waveform(buffer[:window_size])
            buffer = buffer[window_size:]

        streams = []
        segments = []
        while not vad.empty():
            segment = Segment(
                start=vad.front.start / args.sample_rate,
                duration=len(vad.front.samples) / args.sample_rate,
            )
            segments.append(segment)

            stream = recognizer.create_stream()
            stream.accept_waveform(args.sample_rate, vad.front.samples)

            streams.append(stream)

            vad.pop()
 ```

**Comment by chiiyeh** [comment]
Fixed by https://github.com/k2-fsa/sherpa-onnx/pull/1099
