### ISSUE TITLE
build static libraries or shared libraries for windows

### ISSUE THREAD

**Issue by obitodaitu** [k2-fsa/sherpa-onnx#424]
How to build static libraries or shared libraries for windows?

**Comment by csukuangfj** [comment]
![Screenshot 2023-11-14 at 23 55 40](https://github.com/k2-fsa/sherpa-onnx/assets/5284924/5ed8d67f-9a0e-4f96-9eb7-52c779177964)

https://k2-fsa.github.io/sherpa/onnx/install/windows.html

Please see our documentation.

You need at least vs >= 2019 to build static libraries.

**Comment by obitodaitu** [comment]
thanks

**Comment by csukuangfj** [comment]
Does it fix your issue?

**Comment by obitodaitu** [comment]
yes, succeed a few times for 1.8.9 version 。1.8.10 version has not been successful yet。

**Comment by csukuangfj** [comment]
> yes, succeed a few times for 1.8.9 version 。1.8.10 version has not been successful yet。

could you post the error logs?
