### ISSUE TITLE
'onnxruntime_cxx_api.h' file not found

### ISSUE THREAD

**Issue by summerHearts** [k2-fsa/sherpa-onnx#429]
环境：
 mac m1

`Building for simulator (x86_64)
SHERPA_ONNXRUNTIME_LIB_DIR: /Users/yaoyajie/open-source/sherpa-onnx/build-ios/ios-onnxruntime/onnxruntime.xcframework/ios-arm64_x86_64-simulator
`
error msg:

open-source/sherpa-onnx/sherpa-onnx/csrc/cat.h:9:10: fatal error: 'onnxruntime_cxx_api.h' file not found
#include "onnxruntime_cxx_api.h"  // NOLINT

<img width="1172" alt="image" src="https://github.com/k2-fsa/sherpa-onnx/assets/10678821/b3fdf0df-5d83-4ebd-98c2-b9cf6f7fe0cb">

该怎么解决呢，多人多台设备尝试均是此错误

**Comment by csukuangfj** [comment]
Please see https://github.com/k2-fsa/sherpa-onnx/pull/430

It has been merged and please use the latest master.

**Comment by summerHearts** [comment]
thanks,  The project can run normally, but without the TTS related Api interface, I am unable to perform it. it only contain SherpaOnnxRecognizer

**Comment by csukuangfj** [comment]
> thanks, The project can run normally, but without the TTS related Api interface, I am unable to perform it. it only contain SherpaOnnxRecognizer

Will add tts API for iOS before Sunday. Please wait for a while.

**Comment by summerHearts** [comment]
@csukuangfj thanks, 
![image](https://github.com/k2-fsa/sherpa-onnx/assets/10678821/0d6f6e42-16c6-4304-ab28-1ea2ac570cb6) the model is large for iOS app, The probability of crashing is increasing - oom . Is there any way to solve this problem?

**Comment by csukuangfj** [comment]
Which model is large for iOS?

**Comment by csukuangfj** [comment]
You can always  use the `.int8.onnx` model.

**Comment by summerHearts** [comment]
> You can always use the `.int8.onnx` model.

> OK ,thanks, I will try!

**Comment by summerHearts** [comment]
Sorry, do you have any plans to provide TTSDemo for testing? I will provide a detailed test report

**Comment by csukuangfj** [comment]
出ios demo 的，正在写

**Comment by summerHearts** [comment]
Thank you very much to the author. The TTS voice broadcasting sound is very good. The only concern currently is that the mobile end integrates onnxruntime. xcframework, which also has 60M in a release environment. Additionally, with vits-aishell3. int8. onnx 39M, the resource file size is nearly 100M, which is not acceptable on the mobile end. How can we reduce the package size？

**Comment by csukuangfj** [comment]
> The only concern currently is that the mobile end integrates onnxruntime. xcframework, which also has 60M in a release environment.

It is a static library and the final executable can be further stripped. Have you tried that?

**Comment by csukuangfj** [comment]
![Screenshot 2023-11-24 at 11 48 38](https://github.com/k2-fsa/sherpa-onnx/assets/5284924/356771b1-011f-4589-a3e9-b3b17647b740)


The above is the archive file size (without model files).

**Comment by csukuangfj** [comment]
<img width="1239" alt="image" src="https://github.com/k2-fsa/sherpa-onnx/assets/5284924/67c49675-d8f1-462d-9516-02c629db0c24">


Here is the file size of the final IPA, not including model files.

You can see that it is only 5.3MB.

**Comment by summerHearts** [comment]
thanks, i will Integrate into project summary for packaging testing, thank you
