### ISSUE TITLE
don't make connections

### ISSUE THREAD

**Issue by MXC48** [k2-fsa/sherpa-onnx#435]
the TTS is great but when he speaks in French he doesn't make the connections between words.

**Comment by csukuangfj** [comment]
> the TTS is great but when he speaks in French he doesn't make the connections between words.

which model are you using?

Could you explain what "connections" means? would be great if you can post an example audio with the corresponding text.

**Comment by MXC48** [comment]
I use the UMPC medium model, but it works for all of them.
In French, a liaison (connection) is the last letter of a word that can influence the next one.

A video that explains :
https://www.youtube.com/watch?v=yRCD8vgohZo

**Comment by csukuangfj** [comment]
> https://www.youtube.com/watch?v=yRCD8vgohZo

Thanks for the link. The video is very informative.

I think we have fixed the issue by #453 

The following is a sample wav generated by the following command
```bash
python3 ./python-api-examples/offline-tts.py \
  --vits-model=./vits-piper-fr_FR-siwis-low/fr_FR-siwis-low.onnx \
  --vits-tokens=./vits-piper-fr_FR-siwis-low/tokens.txt \
  --vits-data-dir=./vits-piper-fr_FR-siwis-low/espeak-ng-data \
  --debug=1 \
  --output-filename=./siwis-fr.wav \
  "les oranges"
```

https://github.com/k2-fsa/sherpa-onnx/assets/5284924/cbe511be-3296-46ac-9c2d-24bb51a4488b



---

You can find the models at
https://github.com/k2-fsa/sherpa-onnx/releases/tag/tts-models

![Screenshot 2023-11-29 at 17 30 47](https://github.com/k2-fsa/sherpa-onnx/assets/5284924/ecd7277f-5fdc-4b6f-b710-53576642a9c1)

**Comment by csukuangfj** [comment]
@MXC48 

Please try it using our huggingface space.
https://huggingface.co/spaces/k2-fsa/text-to-speech

**Comment by MXC48** [comment]
> @MXC48 
> 
> Please try it using our huggingface space.
> https://huggingface.co/spaces/k2-fsa/text-to-speech

yes that's much better thank you very much !

**Comment by csukuangfj** [comment]
Shall I mark it as fixed now?

**Comment by MXC48** [comment]
> Shall I mark it as fixed now?

Yes you can !
