### ISSUE TITLE
[Help Needed]Export whisper large-v2 to onnx

### ISSUE THREAD

**Issue by LazycatChaos** [k2-fsa/sherpa-onnx#464]
### I'm following the instruction to export large-v2 to onnx 
[https://k2-fsa.github.io/sherpa/onnx/pretrained_models/whisper/export-onnx.html](url)
### after this command
`python3 export_onnx.py --model large-v2`
### the log is 
![image](https://github.com/k2-fsa/sherpa-onnx/assets/151980474/6a70810b-c07e-4cd3-9b31-2954ac06e029)
### then i got 1267 files include the encoder decoder and tokens files
![image](https://github.com/k2-fsa/sherpa-onnx/assets/151980474/ead97ba1-8abb-4ec9-b127-4b53f3d8bad5)

![image](https://github.com/k2-fsa/sherpa-onnx/assets/151980474/62b6e867-6604-4d22-8bea-96aecaee9816)

![image](https://github.com/k2-fsa/sherpa-onnx/assets/151980474/39a7df0a-f191-42dc-a879-2b8dac82b2b1)

![image](https://github.com/k2-fsa/sherpa-onnx/assets/151980474/fbf8aac4-9cbf-4f6d-a9ff-3bbb7d46ec8d)
### then I use the test.py to check the onnx model
`python3 test.py --encoder ./ckpt/large-v2-encoder.onnx --decoder ./ckpt/large-v2-decoder.onnx --tokens=./ckpt/large-v2-tokens.txt ./0.wav`
### But got the error
![image](https://github.com/k2-fsa/sherpa-onnx/assets/151980474/c4cd53df-505b-4054-b527-261b30db6048)
#### ps:by the way if you could provide the model, I would greatly appreciate it :-)

**Comment by csukuangfj** [comment]
which version of onnx and onnxruntime are you using?

**Comment by csukuangfj** [comment]
Please change
```
python3 test.py --encoder ./ckpt/large-v2-encoder.onnx --decoder ./ckpt/large-v2-decoder.onnx --tokens=./ckpt/large-v2-tokens.txt ./0.wav
```
to
```
cd ckpt
python3 ../test.py --encoder ./large-v2-encoder.onnx --decoder ./large-v2-decoder.onnx --tokens=./large-v2-tokens.txt ../0.wav
```

and see if it works.

**Comment by csukuangfj** [comment]
@LazycatChaos 

I find that you have already successfully exported the model.

The issue is that the model is so large that it exceeds 2GB and PyTorch saves it to external data files.
When the model is loaded in onnxruntime, it throws. I have not found a way to fix it.

**Comment by LazycatChaos** [comment]
ok, thanks anyway.
