### ISSUE TITLE
aishell3、huayan模型使用异常

### ISSUE THREAD

**Issue by 906051999** [k2-fsa/sherpa-onnx#468]
- 使用[[tts-models](https://github.com/k2-fsa/sherpa-onnx/releases/tag/tts-models)](https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/sherpa-onnx-non-streaming-tts-v1.8.11.exe) 组件
- 异常1：生成的音频长度异常 --》  [vits-zh-aishell3.tar.bz2](https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-zh-aishell3.tar.bz2)

![PixPin_2023-12-05_21-07-00](https://github.com/k2-fsa/sherpa-onnx/assets/34464024/b3993aa3-af67-4625-b33c-7c0ec24a17f2)
![image](https://github.com/k2-fsa/sherpa-onnx/assets/34464024/04456ca4-e1e6-4600-a833-13f537c9916b)

- 异常2：生成音频内容异常，测试的中文文本发音不明 --》https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-zh_CN-huayan-medium.tar.bz2
![image](https://github.com/k2-fsa/sherpa-onnx/assets/34464024/22bfe579-bc5d-4c0d-90d5-510ec8e63d24)

**Comment by csukuangfj** [comment]
大概率是你的系统不是utf8编码。

最简单的验证方法是使用一个英文模型去测试。

如果英文模型正常，请参考我们文档里面的FAQ,把你的系统设置成utf8编码

**Comment by csukuangfj** [comment]
担心你找不到文档，我把链接发给你
https://k2-fsa.github.io/sherpa/onnx/tts/faq.html#how-to-enable-utf-8-on-windows

**Comment by csukuangfj** [comment]
现在正常了，对吧？

**Comment by 906051999** [comment]
> 现在正常了，对吧？

模型使用正常了，但是各种界面弹窗都乱码了，哈哈
