### ISSUE TITLE
编译成wasm版本

### ISSUE THREAD

**Issue by deepsadness** [k2-fsa/sherpa-onnx#480]
你好. 我们的仓库很棒. 想请教一下. 我们可以支持编译成wasm的版本吗?

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/sherpa-ncnn 支持，还没试过 sherpa-onnx

即使把 sherpa-onnx 编译成了 wasm 的库，还是需要写 javascript 代码去用它的。

有计划支持 wasm, 但要明年去了。社区可以贡献的话，就最好不过了。

**Comment by deepsadness** [comment]
你好. 那方便发一下 https://github.com/k2-fsa/sherpa-ncnn 转成wasm的代码地址. 或者实现方式的地址吗?
我在仓库里面找了一下. 还没发现

看ncnn官方也有点奇怪. 他表明是支持32位的CPU .不支持其它的.
所以两个仓库对比下. 我就来这里问了

**Comment by csukuangfj** [comment]
> 你好. 那方便发一下 https://github.com/k2-fsa/sherpa-ncnn 转成wasm的代码地址. 或者实现方式的地址吗? 我在仓库里面找了一下. 还没发现
> 
> 看ncnn官方也有点奇怪. 他表明是支持32位的CPU .不支持其它的. 所以两个仓库对比下. 我就来这里问了

请看

https://github.com/k2-fsa/sherpa-ncnn/issues/289

**Comment by csukuangfj** [comment]
@deepsadness 

已经支持了。既支持在浏览器中使用 WebAssembly, 又支持在 NodeJS 里面用 WebAssembly. 我们现在提供的 NPM 包，里面就是 WebAssemlby module.
