### ISSUE TITLE
What's the difference between `sherpa-onnx` and `sherpa-ncnn`

### ISSUE THREAD

**Issue by OswaldoBornemann** [k2-fsa/sherpa-onnx#483]
What's the difference between `sherpa-onnx` and `sherpa-ncnn`?

**Comment by csukuangfj** [comment]
Please see our documentation
https://k2-fsa.github.io/sherpa/intro.html

**Comment by csukuangfj** [comment]
![Screenshot 2023-12-14 at 11 21 11](https://github.com/k2-fsa/sherpa-onnx/assets/5284924/0e730511-2f56-443b-b893-787c60a9ad0f)

**Comment by OswaldoBornemann** [comment]
Thank you very much.

**Comment by OswaldoBornemann** [comment]
Is there any reason why we all use onnxruntime and ncnn for mobile deployment? For example, does onnxruntime have an advantage over NCNN in terms of CPU or memory usage?

**Comment by csukuangfj** [comment]
> Is there any reason why we all use onnxruntime and ncnn for mobile deployment? For example, does onnxruntime have an advantage over NCNN in terms of CPU or memory usage?

Please see our documentation.

ncnn is much smaller in library file size than onnxruntime.

**Comment by OswaldoBornemann** [comment]
I see. Thank you.

**Comment by OswaldoBornemann** [comment]
Will we consider opening the original checkpoint of sherpa-onnx-streaming-zipformer-multi-zh-hans-2023-12-12 (Chinese)? This may help us convert the model into a PNNX model and apply it to the sherpa-ncnn.

**Comment by csukuangfj** [comment]
> Will we consider opening the original checkpoint of sherpa-onnx-streaming-zipformer-multi-zh-hans-2023-12-12 (Chinese)? 

Yes, it is open-sourced. Everything from us, the next-generation Kaldi team, is open-sourced.

Please see
https://huggingface.co/zrjin/icefall-asr-multi-zh-hans-zipformer-ctc-streaming-2023-11-05/tree/main

**Comment by OswaldoBornemann** [comment]
I see. Really appreciated. I see that there is already file named `export-onnx-streaming.sh` to export the model to onnx. Is it possible to prepare a file named `export-ncnn.sh` as we saw in `sherpa-ncnn-streaming-zipformer-zh-14M-2023-02-23`? Thanks.

**Comment by csukuangfj** [comment]
Please read our documentation for exporting models to ncnn
https://k2-fsa.github.io/icefall/model-export/export-ncnn.html

Models not listed in the doc are not supported.

**Comment by OswaldoBornemann** [comment]
> Please read our documentation for exporting models to ncnn https://k2-fsa.github.io/icefall/model-export/export-ncnn.html
> 
> Models not listed in the doc are not supported.

You mean this model (https://huggingface.co/zrjin/icefall-asr-multi-zh-hans-zipformer-ctc-streaming-2023-11-05/tree/main) can not be exported to ncnn version?

**Comment by csukuangfj** [comment]
> > Please read our documentation for exporting models to ncnn https://k2-fsa.github.io/icefall/model-export/export-ncnn.html
> > Models not listed in the doc are not supported.
> 
> You mean this model (https://huggingface.co/zrjin/icefall-asr-multi-zh-hans-zipformer-ctc-streaming-2023-11-05/tree/main) can not be exported to ncnn version?

You are right. It cannot.

**Comment by OswaldoBornemann** [comment]
What about this one? https://huggingface.co/pkufool/icefall-asr-zipformer-wenetspeech-20230615

**Comment by csukuangfj** [comment]
There are zipformer v1 and zipformer v2.

The only reason is that we have not supported it. You need to spend a lot of, a lot of, time on converting a model to ncnn.

**Comment by OswaldoBornemann** [comment]
> There are zipformer v1 and zipformer v2.
> 
> The only reason is that we have not supported it. You need to spend a lot of, a lot of, time on converting a model to ncnn.

So you mean https://huggingface.co/pkufool/icefall-asr-zipformer-wenetspeech-20230615 is zipformer v1 and https://huggingface.co/zrjin/icefall-asr-multi-zh-hans-zipformer-ctc-streaming-2023-11-05/tree/main is zipformer v2?

**Comment by csukuangfj** [comment]
pruned_transducer_stateless7_streaming is zipformer v1

the ./zipformer folder is zipformer v2

**Comment by OswaldoBornemann** [comment]
> pruned_transducer_stateless7_streaming is zipformer v1
> 
> the ./zipformer folder is zipformer v2

One more question, so now sherpa-ncnn only support zipformer v1, right?

**Comment by OswaldoBornemann** [comment]
Oh, i got your meaning. Thank you.
