### ISSUE TITLE
Support Android system: Google Text-to-speech Engine App Alternative 

### ISSUE THREAD

**Issue by Pantyhose-X** [k2-fsa/sherpa-onnx#488]
https://k2-fsa.github.io/sherpa/onnx/tts/apk.html  Not a replacement for **Google Text-to-speech Engine App** Doesn't feel very useful

**Comment by christiankaye** [comment]
I downloaded the apk and it works fine as a stand-alone application. It does not appear to replace the built-in TTS. I was hoping that Sherpa-Onnx was similar to Google TTS, RHVoice, eSpeak or picoTTS which provide drop-in replacements for mobile TTS.

**Comment by csukuangfj** [comment]
I am working on it.

**Comment by csukuangfj** [comment]
FYI: I just managed to implement
https://developer.android.com/reference/kotlin/android/speech/tts/TextToSpeechService
and you can use it to replace the system TTS engine.

I will create a PR over the weekend.
