### ISSUE TITLE
[Help wanted] Support modified_beam_search

### ISSUE THREAD

**Issue by csukuangfj** [k2-fsa/sherpa-onnx#49]
# TODO

- [ ] Use https://github.com/k2-fsa/sherpa-ncnn/blob/master/sherpa-ncnn/csrc/modified-beam-search-decoder.h as a reference

**Comment by pingfengluo** [comment]
I will give a hand

**Comment by csukuangfj** [comment]
> I will give a hand

Thanks!

**Comment by pingfengluo** [comment]
close with PR #69
