### ISSUE TITLE
Have a error to with build sherpa-onnx with gpu

### ISSUE THREAD

**Issue by erquren** [k2-fsa/sherpa-onnx#491]
i try to install sherpa-onnx with gpu 
i am use this command

`git clone https://github.com/k2-fsa/sherpa-onnx
cd sherpa-onnx
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DSHERPA_ONNX_ENABLE_GPU=ON ..
make -j6`

maybe important info is 
[100%] Linking C executable ../bin/offline-tts-c-api
[100%] Linking C executable ../bin/decode-file-c-api
/usr/bin/ld: warning: ../../_deps/onnxruntime-src/lib/libonnxruntime_providers_cuda.so, needed by ../lib/libsherpa-onnx-c-api.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: ../../_deps/onnxruntime-src/lib/libonnxruntime_providers_cuda.so, needed by ../lib/libsherpa-onnx-c-api.so, not found (try using -rpath or -rpath-link)
[100%] Built target decode-file-c-api
[100%] Built target offline-tts-c-api

when i run with 

`sherpa-onnx \
  --tokens=/home/team/devel/sherpa-onnx/sherpa-onnx-streaming-zipformer-multi-zh-hans-2023-12-12/tokens.txt \
  --encoder=/home/team/devel/sherpa-onnx/sherpa-onnx-streaming-zipformer-multi-zh-hans-2023-12-12/encoder-epoch-20-avg-1-chunk-16-left-128.onnx \
  --decoder=/home/team/devel/sherpa-onnx/sherpa-onnx-streaming-zipformer-multi-zh-hans-2023-12-12/decoder-epoch-20-avg-1-chunk-16-left-128.onnx \
  --joiner=/home/team/devel/sherpa-onnx/sherpa-onnx-streaming-zipformer-multi-zh-hans-2023-12-12/joiner-epoch-20-avg-1-chunk-16-left-128.onnx \
  /home/team/devel/sherpa-onnx/sherpa-onnx-streaming-zipformer-multi-zh-hans-2023-12-12/test_wavs/DEV_T0000000000.wav`

have a error with this
./sherpa-onnx: error while loading shared libraries: ../../_deps/onnxruntime-src/lib/libonnxruntime_providers_cuda.so: cannot open shared object file: No such file or directory

but this so lib is in this path,i cant understand why cant link this
i try to export this lib in my env ,but not good

**Comment by erquren** [comment]
this error is in fedora33 cuda11.4

when i use ubuntu22 cuda12.2 ,it is success,maybe it have cuda version limit?

**Comment by csukuangfj** [comment]
Please have a look at
https://github.com/k2-fsa/sherpa-onnx/issues/392#issuecomment-1833929387

**Comment by erquren** [comment]
> Please have a look at [#392 (comment)](https://github.com/k2-fsa/sherpa-onnx/issues/392#issuecomment-1833929387)

i see this issue ,i download onnxruntime-linux-x64-gpu-1.16.3.tgz,and export the lib and include to my env
build success and make success

when i ldd the build bin ,such as sherpa-onnx ,all lib have found.

but when i run the application with this code 

`
./build/bin/sherpa-onnx \
  --tokens=./sherpa-onnx-streaming-zipformer-multi-zh-hans-2023-12-12/tokens.txt \
  --encoder=./sherpa-onnx-streaming-zipformer-multi-zh-hans-2023-12-12/encoder-epoch-20-avg-1-chunk-16-left-128.onnx \
  --decoder=./sherpa-onnx-streaming-zipformer-multi-zh-hans-2023-12-12/decoder-epoch-20-avg-1-chunk-16-left-128.onnx \
  --joiner=./sherpa-onnx-streaming-zipformer-multi-zh-hans-2023-12-12/joiner-epoch-20-avg-1-chunk-16-left-128.onnx \
  ./sherpa-onnx-streaming-zipformer-multi-zh-hans-2023-12-12/test_wavs/DEV_T0000000000.wav
`

[66601.119165] sherpa-onnx-mic[1195037]: segfault at 0 ip 00007ff188cf7755 sp 00007ffda6ea1b60 error 4 in libonnxruntime_providers_cuda.so[7ff188ca3000+7d2000]
[66601.119174] Code: 08 e8 6f c7 fa ff 48 8b 3d b0 08 94 14 4c 89 e2 48 89 ee e8 bd c0 fa ff e8 18 c6 fa ff 48 89 c7 48 8d 05 46 f6 4f 16 48 89 38 <48> 8b 07 ff 90 b8 10 00 00 48 8d 15 2b f6 4f 16 48 8d 3d e4 9e 2a
[66613.857671] sherpa-onnx[1195346]: segfault at 0 ip 00007f0898c07755 sp 00007ffde05c4120 error 4 in libonnxruntime_providers_cuda.so[7f0898bb3000+7d2000]
[66613.857681] Code: 08 e8 6f c7 fa ff 48 8b 3d b0 08 94 14 4c 89 e2 48 89 ee e8 bd c0 fa ff e8 18 c6 fa ff 48 89 c7 48 8d 05 46 f6 4f 16 48 89 38 <48> 8b 07 ff 90 b8 10 00 00 48 8d 15 2b f6 4f 16 48 8d 3d e4 9e 2a
[66630.688052] sherpa-onnx[1195755]: segfault at 0 ip 00007fc59ce2f755 sp 00007fff18b02d50 error 4 in libonnxruntime_providers_cuda.so[7fc59cddb000+7d2000]
[66630.688059] Code: 08 e8 6f c7 fa ff 48 8b 3d b0 08 94 14 4c 89 e2 48 89 ee e8 bd c0 fa ff e8 18 c6 fa ff 48 89 c7 48 8d 05 46 f6 4f 16 48 89 38 <48> 8b 07 ff 90 b8 10 00 00 48 8d 15 2b f6 4f 16 48 8d 3d e4 9e 2a

**Comment by csukuangfj** [comment]
> > Please have a look at [#392 (comment)](https://github.com/k2-fsa/sherpa-onnx/issues/392#issuecomment-1833929387)
> 
> i see this issue ,i download onnxruntime-linux-x64-gpu-1.16.3.tgz,and export the lib and include to my env build success and make success
> 
> when i ldd the build bin ,such as sherpa-onnx ,all lib have found.
> 
> but when i run the application with this code
> 
> `./build/bin/sherpa-onnx \ --tokens=./sherpa-onnx-streaming-zipformer-multi-zh-hans-2023-12-12/tokens.txt \ --encoder=./sherpa-onnx-streaming-zipformer-multi-zh-hans-2023-12-12/encoder-epoch-20-avg-1-chunk-16-left-128.onnx \ --decoder=./sherpa-onnx-streaming-zipformer-multi-zh-hans-2023-12-12/decoder-epoch-20-avg-1-chunk-16-left-128.onnx \ --joiner=./sherpa-onnx-streaming-zipformer-multi-zh-hans-2023-12-12/joiner-epoch-20-avg-1-chunk-16-left-128.onnx \ ./sherpa-onnx-streaming-zipformer-multi-zh-hans-2023-12-12/test_wavs/DEV_T0000000000.wav`
> 
> [66601.119165] sherpa-onnx-mic[1195037]: segfault at 0 ip 00007ff188cf7755 sp 00007ffda6ea1b60 error 4 in libonnxruntime_providers_cuda.so[7ff188ca3000+7d2000] [66601.119174] Code: 08 e8 6f c7 fa ff 48 8b 3d b0 08 94 14 4c 89 e2 48 89 ee e8 bd c0 fa ff e8 18 c6 fa ff 48 89 c7 48 8d 05 46 f6 4f 16 48 89 38 <48> 8b 07 ff 90 b8 10 00 00 48 8d 15 2b f6 4f 16 48 8d 3d e4 9e 2a [66613.857671] sherpa-onnx[1195346]: segfault at 0 ip 00007f0898c07755 sp 00007ffde05c4120 error 4 in libonnxruntime_providers_cuda.so[7f0898bb3000+7d2000] [66613.857681] Code: 08 e8 6f c7 fa ff 48 8b 3d b0 08 94 14 4c 89 e2 48 89 ee e8 bd c0 fa ff e8 18 c6 fa ff 48 89 c7 48 8d 05 46 f6 4f 16 48 89 38 <48> 8b 07 ff 90 b8 10 00 00 48 8d 15 2b f6 4f 16 48 8d 3d e4 9e 2a [66630.688052] sherpa-onnx[1195755]: segfault at 0 ip 00007fc59ce2f755 sp 00007fff18b02d50 error 4 in libonnxruntime_providers_cuda.so[7fc59cddb000+7d2000] [66630.688059] Code: 08 e8 6f c7 fa ff 48 8b 3d b0 08 94 14 4c 89 e2 48 89 ee e8 bd c0 fa ff e8 18 c6 fa ff 48 89 c7 48 8d 05 46 f6 4f 16 48 89 38 <48> 8b 07 ff 90 b8 10 00 00 48 8d 15 2b f6 4f 16 48 8d 3d e4 9e 2a

What is the output of
```
nvcc --version
```
and
```
nvidia-smi
```
?

**Comment by erquren** [comment]
![image](https://github.com/k2-fsa/sherpa-onnx/assets/39297833/9ff06451-ae56-4f65-915d-6e90529ba4b1)
 nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_Sep_13_19:13:29_PDT_2021
Cuda compilation tools, release 11.5, V11.5.50
Build cuda_11.5.r11.5/compiler.30411180_0

**Comment by erquren** [comment]
the onnxruntime_gpu only support cuda11.X ,if use cuda12.X need build from onnxruntime

**Comment by MrRace** [comment]
> the onnxruntime_gpu only support cuda11.X ,if use cuda12.X need build from onnxruntime

@erquren 
After build onnxruntime from source, how to modify the [cmake file: onnxruntime-linux-x86_64-gpu.cmake](https://github.com/k2-fsa/sherpa-onnx/blob/master/cmake/onnxruntime-linux-x86_64-gpu.cmake) ?  It seems that there are some other dependencies that need to be modified accordingly. Is it sufficient to only modify the onnxruntime-linux-x86_64-gpu.cmake file? Thanks a lot!

**Comment by csukuangfj** [comment]
>  It seems that there are some other dependencies that need to be modified accordingly

Could you be more specific about "some other"?
