### ISSUE TITLE
Loading ONNX Model in PyQt5 Subthread

### ISSUE THREAD

**Issue by Tiny1213** [k2-fsa/sherpa-onnx#492]
I attempted to use Sherpa-ONNX TTS in a PyQt5 application. However, I encountered an issue where loading an ONNX model in a subthread seems to block the main thread of the PyQt application. Is this behavior expected, and what would be the recommended solution to address this issue?

**Comment by csukuangfj** [comment]
Could you share your code ?

**Comment by Tiny1213** [comment]
def star_load_model(self,text, model, speed, volume_level):
        thread = threading.Thread(target=self._do_load_model, name='load model thread',
                                  args=(model, speed, volume_level))
        thread.start()
    
    def _do_load_model(self,*arg):
        print('start loading model...')
        model=arg[0]
        speed=arg[1]
        volume_level=arg[2]
        text='hello,sherpa'
        sherpaXX = SherpaGenerator()
        sherpaXX.load_model(**{'model_id': model['model_id'],
                                  'model_path': os.path.abspath(
                                      os.path.join(root_dir, MODELS_DIRECTORY, model['model_path'])),
                                  'model_name': model['model_name'],
                                  'sid': int(model['sid']),
                                  'speed': speed})
        print('complete loading model...')

this is my code.

**Comment by Tiny1213** [comment]
> Are you using the latest sherpa-onnx? And how do you wrap sherpa-onnx?
> 
> If you don't release the GIL in your c++ code, then multithreading in Python is actually single threaded.

yeah，I believe the GIL is the reason.

**Comment by csukuangfj** [comment]
We can help you If you are using sherpa-onnx and If you post all of your related code.

**Comment by Tiny1213** [comment]
> We can help you If you are using sherpa-onnx and If you post all of your related code.

Thank you, you've been very helpful. I will move Sherpa-ONNX to a subprocess so that the main application thread won't be blocked

**Comment by csukuangfj** [comment]
@Tiny1213 

Please try #493 

It should fix your issue.

Note that using a thread is more lightweight than that of a process.

**Comment by Tiny1213** [comment]
> @Tiny1213
> 
> Please try #493
> 
> It should fix your issue.
> 
> Note that using a thread is more lightweight than that of a process.

I will give it a try, thank you.

**Comment by csukuangfj** [comment]
> > @Tiny1213
> > Please try #493
> > It should fix your issue.
> > Note that using a thread is more lightweight than that of a process.
> 
> I will give it a try, thank you.

 Note that you need to build it from source.

**Comment by Tiny1213** [comment]
> > > @Tiny1213
> > > Please try #493
> > > It should fix your issue.
> > > Note that using a thread is more lightweight than that of a process.
> > 
> > 
> > I will give it a try, thank you.
> 
> Note that you need to build it from source.

ok，i got it

**Comment by csukuangfj** [comment]
Does it work for you?

**Comment by Tiny1213** [comment]
I tried to build the it from source on Windows, but it failed.Do I have to install Visual Studio?

**Comment by csukuangfj** [comment]
@Tiny1213 

We have built Python wheels for you.

Please visit https://github.com/csukuangfj/sherpa-onnx/actions/runs/7271561019
to download them.

![Screenshot 2023-12-20 at 14 25 06](https://github.com/k2-fsa/sherpa-onnx/assets/5284924/8a3f2e49-695b-4f87-ac93-792a3e7a0c1c)

**Comment by Tiny1213** [comment]
It works！Thank you.By the way, will this PR be merged into the master?

**Comment by csukuangfj** [comment]
> It works！Thank you.By the way, will this PR be merged into the master?

Thanks for testing!

Yes, merging it now.
