### ISSUE TITLE
中文tts只支持文档中的模型吗

### ISSUE THREAD

**Issue by Tiny1213** [k2-fsa/sherpa-onnx#495]
我想用 sherpa-onnx tts播报中文，尝试了 https://k2-fsa.github.io/sherpa/onnx/tts/apk.html 里面的模型。
请问只有列出的这些模型可以用吗？其他的模型export为onnx后，能运行吗？

**Comment by csukuangfj** [comment]
> 其他的模型export为onnx后

如果是纯 vits, 就可以。注意是 纯 vits.

像 bert +vits  或者 so vits 等，都不可以，因为不是纯 vits.

**Comment by Tiny1213** [comment]
魔塔社区的那些模型，能用吗？

**Comment by csukuangfj** [comment]
> 魔塔社区的那些模型，能用吗？

请看我上面的回答。

**Comment by Tiny1213** [comment]
好吧，我去看了，没有纯vits的
