### ISSUE TITLE
Conditional inclusion of TTS

### ISSUE THREAD

**Issue by rkjaran** [k2-fsa/sherpa-onnx#498]
Can a build option be added to disable the building of TTS related parts of sherpa-onnx? Something like `SHERPA_ONNX_ENABLE_TTS`? I'm building on sherpa-onnx as a library for speech recognition and would prefer to not have to maintain a divergent fork. What's especially problematic for me is the usage and linking to `espeak-ng`, which I believe is under a GPLv3 license and thus somewhat incompatible with the license of this project.

I can create a PR for this.

**Comment by csukuangfj** [comment]
> I can create a PR for this.

Thanks! That sounds great! Looking forward to your PR.
