### ISSUE TITLE
How to set the sampling rate recognition of 48000

### ISSUE THREAD

**Issue by FZ985** [k2-fsa/sherpa-onnx#502]
hello，
How to identify audio with a sampling rate of 48000. The audio cannot be identified after setting 48000. Do other parameters need to be changed?

**Comment by csukuangfj** [comment]
You don't need to specify  the sampling rate if you use our pretrained models.


Please post all of your output logs if you still have issues.

**Comment by FZ985** [comment]
Because we used the audio stream obtained by a third-party SDK, the SDK output sampling rate is 48000, two-channel, and there is no external sampling rate configuration, so we ran the iOS demo to change 16000 to 48000, and found that the recognition results were inaccurate. Occasionally, the recognition is empty. Only the sampling rate has been changed. Have other parameter configurations been modified? Because we do not understand the configuration of parameter names very well.

**Comment by csukuangfj** [comment]
could you describe how you change the code? I assume  you only change the sample rate argument of the accept waveform function and leave other code unchanged.

Also, it supports only a single channel.

**Comment by 743848887** [comment]
`      let outputFormat = AVAudioFormat(
            commonFormat: .pcmFormatFloat32,
            sampleRate: 48000, channels: 1,
            interleaved: false)!
`

**Comment by csukuangfj** [comment]
For the sample rate, please don't change feature  config, which is specific for a selected model.

In your case, please change only accept waveform.  I think it is clearly documented.

**Comment by 743848887** [comment]
I get data is uint8_t * bytes,So How do I process the data?

**Comment by csukuangfj** [comment]
> I get data is uint8_t * bytes,So How do I process the data?
> 

You need to first figure out what is the format of your samples. As you know everything in the computer is represented by bytes and can be saved in uint8_t*.


The accept waveform function only accepts samples in the range [-1,1].

It is your responsibility to convert your samples to the desired format.

**Comment by 743848887** [comment]
When I convert it to [float], the data obtained is always the same string
           
```
    func convertAudioDataToFloatArray(audioData: Data) -> [Float] {
        let format = AVAudioFormat(
            commonFormat: .pcmFormatFloat32,
            sampleRate: 16000, channels: 1,
            interleaved: false)!
        guard let pcmBuffer = AVAudioPCMBuffer(pcmFormat: format, frameCapacity: AVAudioFrameCount(audioData.count / MemoryLayout<Int16>.stride)) else {
            fatalError("Failed to create AVAudioPCMBuffer")
        }
        
        let data = NSData(data: audioData)
        pcmBuffer.frameLength = AVAudioFrameCount(audioData.count / MemoryLayout<Int16>.stride)
        let buffer = pcmBuffer.audioBufferList.pointee.mBuffers
        data.getBytes(UnsafeMutableRawPointer(buffer.mData!), length: audioData.count)
        let floatArray = Array(UnsafeBufferPointer(start: pcmBuffer.floatChannelData![0], count: Int(pcmBuffer.frameLength)))
        let scaledArray = floatArray.map { $0 / Float(Int16.max) }
        
        return scaledArray
    }
```
log like this 
 
![WX20231226-171205@2x](https://github.com/k2-fsa/sherpa-onnx/assets/13196303/93fc92e4-ba13-49de-9874-a86ec97c6818)

**Comment by csukuangfj** [comment]
Could you describe how you  obtain audioData?

**Comment by 743848887** [comment]
Thanks .
I get uint8_t * bytes through the audio stream, which is 48000 sampleRate dual channel. Then convert it to mono data

**Comment by csukuangfj** [comment]
Do you have detailed config  for the audio stream, e.g., the sample format?

**Comment by 743848887** [comment]
```
@property (assign, nonatomic) uint8_t * bytes;
 
@property (assign, nonatomic) int32_t length;
 
@property (assign, nonatomic) int32_t channels;
 
@property (assign, nonatomic) int32_t sampleRate;
 
@property (assign, nonatomic) int32_t bytesPerSample;
 
@property (assign, nonatomic) int32_t samples;
 
@property (assign, nonatomic) uint64_t renderTimeMs;
```

**Comment by csukuangfj** [comment]
Could you also show their values?

**Comment by 743848887** [comment]
```
(lldb) po frame.bytes
"\xc4\xfd\xc4\xfd%\xfd%\xfd\xb3\xfc\xb3\xfc\x86\xfc\x86\xfcp\xfcp\xfc3\xfc3\xfc\xd9\xfb\xd9\xfb\xb1\xfb\xb1\xfb\xf0\xfb\xf0\xfbs\xfcs\xfc\xed\xfc\xed\xfc=\xfd=\xfdw\xfdw\xfd\xaf\xfd\xaf\xfd\xdd\xfd\xdd\xfd\xfb\xfd\xfb\xfd\U00000014\xfe\U00000014\xfe8\xfe8\xfe^\xfe^\xfew\xfew\xfe\x82\xfe\x82\xfe\x90\xfe\x90\xfe\xb0\xfe\xb0\xfe\xdf\xfe\xdf\xfe\U00000015\xff\U00000015\xffE\xffE\xff[\xff[\xffC\xffC\xff\U00000002\xff\U00000002\xff\xbf\xfe\xbf\xfe\xa3\xfe\xa3\xfe\xa7\xfe\xa7\xfe\xa0\xfe\xa0\xfev\xfev\xfeD\xfeD\xfe2\xfe2\xfe@\xfe@\xfeQ\xfeQ\xfeT\xfeT\xfeH\xfeH\xfe*\xfe*\xfe\xf5\xfd\xf5\xfd\xae\xfd\xae\xfdo\xfdo\xfdL\xfdL\xfdJ\xfdJ\xfd`\xfd`\xfd\x83\xfd\x83\xfd\xa7\xfd\xa7\xfd\xc9\xfd\xc9\xfd\xed\xfd\xed\xfd\U00000016\xfe\U00000016\xfeD\xfeD\xfeh\xfeh\xfel\xfel\xfeD\xfeD\xfe\U00000005\xfe\U00000005\xfe\xd9\xfd\xd9\xfd\xd1\xfd\xd1\xfd\xd6\xfd\xd6\xfd\xc2\xfd\xc2\xfd\x8b\xfd\x8b\xfdM\xfdM\xfd'\xfd'\xfd\U0000001b\xfd\U0000001b\xfd\U00000012\xfd\U00000012\xfd\U00000001\xfd\U00000001\xfd\xef\xfc\xef\xfc\xde\xfc\xde\xfc\xc3\xfc\xc3\xfc\x93\xfc\x93\xfc]\xfc]\xfc8\xfc8\xfc.\xfc.\xfc6\xfc6\xfcA\xfcA\xfcG\xfcG\xfcO\xfcO\xfcc\xfcc\xfc\x85\xfc\x85\xfc\xaa\xfc\xaa\xfc\xc6\xfc\xc6\xfc\xd5\xfc\xd5\xfc\xdf\xfc\xdf\xfc\xf1\xfc\xf1\xfc\U00000015\xfd\U00000015\xfdE\xfdE\xfdp\xfdp\xfd\x8c\xfd\x8c\xfd\xa2\xfd\xa2\xfd\xc4\xfd\xc4\xfd\xf4\xfd\xf4\xfd,\xfe,\xfef\xfef\xfe\x9c\xfe\x9c\xfe\xca\xfe\xca\xfe\xe5\xfe\xe5\xfe\xed\xfe\xed\xfe\xed\xfe\xed\xfe\xfa\xfe\xfa\xfe&\xff&\xffr\xffr\xff\xd1\xff\xd1\xff5"

(lldb) po frame.sampleRate
48000

(lldb) po frame.length
2048

(lldb) po frame.channels
2

(lldb) po frame.samples
512

(lldb) po frame.renderTimeMs
<nil>

(lldb) po frame.bytesPerSample
4

```

**Comment by csukuangfj** [comment]
@743848887 

Thank you for sharing the information.

The last two questions are:
- Since there are two channels, how samples of each channel are arranged? Is it interleaved, like
```
sample0_channel0 sample0_channel1 sample1_channel0 sample1_channel1 ...
```

- `po frame.bytesPerSample` is 4, so are you samples of int32_t or float format?

> Because we used the audio stream obtained by a third-party SDK, the SDK output sampling rate is 48000, two-channel,

Please give more detail about the audio stream, e.g., the sample format.

**Comment by 743848887** [comment]
![WX20231227-193932@2x](https://github.com/k2-fsa/sherpa-onnx/assets/13196303/7555e4c3-6b60-4c41-b32c-73a4e03147c6)
Thank you very much for your reply. Is it possible to replace the annotation with other methods? I don’t know what effect this has.

**Comment by csukuangfj** [comment]
> @743848887 
> 
> Thank you for sharing the information.
> 
> The last two questions are:
> - Since there are two channels, how samples of each channel are arranged? Is it interleaved, like
> ```
> sample0_channel0 sample0_channel1 sample1_channel0 sample1_channel1 ...
> ```
> 
> - `po frame.bytesPerSample` is 4, so are you samples of int32_t or float format?
> 
> > Because we used the audio stream obtained by a third-party SDK, the SDK output sampling rate is 48000, two-channel,
> 
> Please give more detail about the audio stream, e.g., the sample format. 
> 

could you answer this question?

**Comment by 743848887** [comment]
The channel sorting SDK cannot provide it, so I switched the buffer's callback。

       `UInt32 inNumberFrames, AudioBufferList * _Nonnull ioData, const AudioTimeStamp * _Nonnull inTimeStamp, const AudioStreamBasicDescription asbd`

**Comment by csukuangfj** [comment]
Sorry, the information you provided is too limited and I cannot provide code to make it working.

My suggestion is that you change your code so that for the following code
```
self.recognizer.acceptWaveform(samples:bufferlist.mBuffers.array())
```

you pass 48000 to the above function `self.recognizer.acceptWaveform`.
And the samples you passed to it are normalized to [-1, 1]. 


Note that `acceptWaveform` accepts two arguments, one of them is the sample rate, which in your case should be 48000.

**Comment by 743848887** [comment]
How to convert bufferlist to [-1,1] . This is my approach and this didn't work. Can you provide me with instructions on how to convert it? 

```
+ (void)normalizeSamplesInAudioBufferList:(AudioBufferList *)inputBufferList inputFormat:(AudioStreamBasicDescription)inputFormat{
     Float32 *audioData = (Float32 *)inputBufferList->mBuffers[0].mData;
     UInt32 numSamples = inputBufferList->mBuffers[0].mDataByteSize / sizeof(Float32);
     Float32 maxAbsValue = 0.0;
    for (UInt32 i = 0; i < numSamples; i++) {
        Float32 absValue = fabs(audioData[i]);
        if (absValue > maxAbsValue) {
            maxAbsValue = absValue;
        }
    }
     if (maxAbsValue > 1.0) {
        for (UInt32 i = 0; i < numSamples; i++) {
            audioData[i] /= maxAbsValue;
        }
    }
}
```

**Comment by csukuangfj** [comment]
> @743848887
> 
> Thank you for sharing the information.
> 
> The last two questions are:
> 
> * Since there are two channels, how samples of each channel are arranged? Is it interleaved, like
> 
> ```
> sample0_channel0 sample0_channel1 sample1_channel0 sample1_channel1 ...
> ```
> 
> * `po frame.bytesPerSample` is 4, so are you samples of int32_t or float format?
> 
> > Because we used the audio stream obtained by a third-party SDK, the SDK output sampling rate is 48000, two-channel,
> 
> Please give more detail about the audio stream, e.g., the sample format.

I have asked you these two questions but you have not provided any information about it. Sorry that I cannot help you since I have no idea what `inputBufferList->mBuffers[0].mData` contains.

**Comment by 743848887** [comment]
I have changed the method provided by the system

**Comment by csukuangfj** [comment]
Fixed via the next-gen Kaldi QQ group.
