### ISSUE TITLE
Can python version output the timestamp information?

### ISSUE THREAD

**Issue by OswaldoBornemann** [k2-fsa/sherpa-onnx#506]
Can python version output the timestamp information?

**Comment by csukuangfj** [comment]
Yes, it is definitely possible.

**Comment by OswaldoBornemann** [comment]
Is there any related document to implement it?

**Comment by OswaldoBornemann** [comment]
Oh i see. I have seen the `timestamps` function in recognizer.

**Comment by OswaldoBornemann** [comment]
Can the other pretrained models, such as paraformer, support the timestamp function? It seems that when I use paraformer, the timestamp output is empty.

**Comment by csukuangfj** [comment]
>  It seems that when I use paraformer, the timestamp output is empty.

Not all paraformer models support timestamps.

If you use the following one, you should be able to get timestamp information, as you can see from the doc.
https://k2-fsa.github.io/sherpa/onnx/pretrained_models/offline-paraformer/paraformer-models.html#csukuangfj-sherpa-onnx-paraformer-zh-2023-09-14-chinese

![Screenshot 2023-12-29 at 11 24 35](https://github.com/k2-fsa/sherpa-onnx/assets/5284924/aa4fe0f8-a07f-4993-8166-6d471151e865)

**Comment by OswaldoBornemann** [comment]
Thank you very much.
