### ISSUE TITLE
Mismatch in fbank computation parameters causing deletion errors

### ISSUE THREAD

**Issue by ipmedenn** [k2-fsa/sherpa-onnx#514]
Hello,

I found that there is a mismatch in fbank computation parameters.
Icefall models are trained with parameter high_freq = -400 (class FbankConfig in lhotse/features/kaldi/extractors.py), but in kaldi-native-fbank(sherpa-onnx) default high_freq value is 0.
In my experiments, for some audio files this causes a large amount of deletion errors in sherpa-onnx.
Also, similar mismatch in kaldifeat affects zipformer/streaming_decode.py in icefall.

**Comment by csukuangfj** [comment]
Thanks for pointing it out! We have never realized the mismatch. 

I just checked the code and find that lhotse is using -400 as the default value for high_freq.

Could you help make PRs to sherpa to hardcode the value of high_freq to -400?

**Comment by nshmyrev** [comment]
Hi @ipmedenn 

This is a great catch, thank you! I am actually fighting for some time with high number of deletions in streaming longform recognition too.

Do you see that the proposed change completely fixed the problem? I quickly tested with -400, actually I don't see much difference, it sometimes gets even worse. Maybe problem is somewhere else too. Do you see the deletions issue in offline mode or in streaming mode?

One thing I noticed that it helps to reset encoder state, but not well tested

https://github.com/alphacep/sherpa-onnx/commit/d6ae83063929cf838aea8ac52090c6cdfd2c5400

**Comment by csukuangfj** [comment]
Fixed in
- https://github.com/k2-fsa/sherpa-onnx/pull/515
- https://github.com/k2-fsa/sherpa-ncnn/pull/294
- https://github.com/k2-fsa/sherpa/pull/528
- https://github.com/k2-fsa/icefall/pull/1447

Great thanks to @ipmedenn !

**Comment by ipmedenn** [comment]
> Hi @ipmedenn
> 
> This is a great catch, thank you! I am actually fighting for some time with high number of deletions in streaming longform recognition too.
> 
> Do you see that the proposed change completely fixed the problem? I quickly tested with -400, actually I don't see much difference, it sometimes gets even worse. Maybe problem is somewhere else too. Do you see the deletions issue in offline mode or in streaming mode?
> 
> One thing I noticed that it helps to reset encoder state, but not well tested

Hi @nshmyrev,
I see deletions issue in streaming mode, and -400 completely solves this issue.

**Comment by nshmyrev** [comment]
@ipmedenn Great, thanks for the information!
