### ISSUE TITLE
从funasr来的，这个paraformer项目源码有么？我这边弄了好像不行，然后有ncnn那个库对funasr的支持的么

### ISSUE THREAD

**Issue by gsn516** [k2-fsa/sherpa-onnx#521]
![微信图片_20240110164306](https://github.com/k2-fsa/sherpa-onnx/assets/5070270/717aab54-4e49-45fb-8eb2-bacd5f3fd39f)
![微信图片_20240110164455](https://github.com/k2-fsa/sherpa-onnx/assets/5070270/e25d8b2c-c6a1-4fea-929c-e410864aeb92)

**Comment by csukuangfj** [comment]
画红框框的源码在
https://github.com/k2-fsa/sherpa-onnx/tree/master/android/SherpaOnnx2Pass

我看你已经找到代码了。

请贴完整的 error log ，文本形式的那种

**Comment by csukuangfj** [comment]
目前，sherpa-ncnn 只支持来自 icefall 的流式模型。注意上面一句有一个 `只`.

**Comment by gsn516** [comment]
大哥，你回复好快
[log.txt](https://github.com/k2-fsa/sherpa-onnx/files/13885341/log.txt)

**Comment by gsn516** [comment]
> 目前，sherpa-ncnn 只支持来自 icefall 的流式模型。注意上面一句有一个 `只`.

大哥，回复上面了

**Comment by csukuangfj** [comment]
@gsn516 
你的 .so 文件是从哪里来的？请说详细点。

**Comment by gsn516** [comment]
> @gsn516 你的 .so 文件是从哪里来的？请说详细点。

昨天试了不行，我拿你的apk解压拿出来so文件试了不行，然后今天我自己编译的，今天下午拉的最新的sherpa-onnx工程，
![DINGTALK_IM_3686079920 JPG](https://github.com/k2-fsa/sherpa-onnx/assets/5070270/5175a5d5-4c41-4480-b643-ab3a20e0178f)
![DINGTALK_IM_1280445663 JPG](https://github.com/k2-fsa/sherpa-onnx/assets/5070270/01722944-bdad-469e-bb7c-c41bc8c0580b)

**Comment by gsn516** [comment]
我编译也是成功的，没看到有编译的错误

> @gsn516 你的 .so 文件是从哪里来的？请说详细点。

下面这个是编译时候的日志：
[ndk.txt](https://github.com/k2-fsa/sherpa-onnx/files/13886930/ndk.txt)

**Comment by csukuangfj** [comment]
你试试 1.9.4 的 apk? 

https://github.com/k2-fsa/sherpa-onnx/releases/tag/v1.9.4

1.9.7 的有问题。 master 上修复了，但不知道你为什么还报错。
你把 git log 的输出，和你 jniLibs 下面的 .so 的 哈希值，和你 build 时生成的 .so 的哈希值发过来看看，看看你用的是不是最新的代码编译成的 .so.

**Comment by gsn516** [comment]
> 你试试 1.9.4 的 apk?
> 
> https://github.com/k2-fsa/sherpa-onnx/releases/tag/v1.9.4
> 
> 1.9.7 的有问题。 master 上修复了，但不知道你为什么还报错。 你把 git log 的输出，和你 jniLibs 下面的 .so 的 哈希值，和你 build 时生成的 .so 的哈希值发过来看看，看看你用的是不是最新的代码编译成的 .so.

老哥，我下载了你的v1.9.4的apk，把里面的so拿出来，放到我的工程里，跑起来没问题。。。，那就是最新版的有问题了，我git拉下来的代码肯定是最新的，你的修复的是master分支吧？那应该是master分支还是有问题

**Comment by csukuangfj** [comment]
我修复的就是 master 分支。

所以我上面说
> 你把 git log 的输出，和你 jniLibs 下面的 .so 的 哈希值，和你 build 时生成的 .so 的哈希值发过来看看，看看你用的是不是最新的代码编译成的 .so.

**Comment by gsn516** [comment]
> 我修复的就是 master 分支。
> 
> 所以我上面说
> 
> > 你把 git log 的输出，和你 jniLibs 下面的 .so 的 哈希值，和你 build 时生成的 .so 的哈希值发过来看看，看看你用的是不是最新的代码编译成的 .so.

主要是你说的hash值我不知道咋弄。。。

**Comment by gsn516** [comment]
> 我修复的就是 master 分支。
> 
> 所以我上面说
> 
> > 你把 git log 的输出，和你 jniLibs 下面的 .so 的 哈希值，和你 build 时生成的 .so 的哈希值发过来看看，看看你用的是不是最新的代码编译成的 .so.

还有，你发出来的v1.9.7的那个apk包，在我的手机上一样奔溃

**Comment by csukuangfj** [comment]
> > 我修复的就是 master 分支。
> > 所以我上面说
> > > 你把 git log 的输出，和你 jniLibs 下面的 .so 的 哈希值，和你 build 时生成的 .so 的哈希值发过来看看，看看你用的是不是最新的代码编译成的 .so.
> 
> 还有，你发出来的v1.9.7的那个apk包，在我的手机上一样奔溃

就是 1.9.7 有问题的。你不用 two pass 的 apk, 也会有问题么？ 1.9.7， 只有 two pass apk 有问题.

**Comment by csukuangfj** [comment]
发 1.9.8 之前，我在手机上试一下，没问题了，我再发版

**Comment by gsn516** [comment]
> 发 1.9.8 之前，我在手机上试一下，没问题了，我再发版

ok，感谢老哥
