### ISSUE TITLE
Add Persian language apk for android

### ISSUE THREAD

**Issue by karim23657** [k2-fsa/sherpa-onnx#524]
@csukuangfj 
Here are metadata added onnx models for vits Piper,for persian:
https://huggingface.co/karim23657/persian-tts-vits/tree/main/mimic3-haaniye_low

Please add tts engine pre-built Persian language apk for android to releases

**Comment by csukuangfj** [comment]
@karim23657 

Is the above hugging face repo indeed from piper?

Its `generator.onnx.json` is different from other models from piper.

**Comment by karim23657** [comment]
@csukuangfj  Actually it wasn't for piper , I got it from https://github.com/MycroftAI/mimic3-voices
Then added metedata to work with piper , an i tested it ,it works finely without any error,
I recommend you to add pre-built apk for all mimic3-voices onnx models, they are compatible with piper.

**Comment by csukuangfj** [comment]
> Then added metedata to work with piper , an i tested it ,it works finely without any error,

Could you share the code to show how you test it?

**Comment by csukuangfj** [comment]
please try it at
https://huggingface.co/spaces/k2-fsa/text-to-speech

![Screenshot 2024-01-14 at 16 01 40](https://github.com/k2-fsa/sherpa-onnx/assets/5284924/e6c357d4-90f6-4a10-9e51-c87fef514118)

You can download the model at
https://github.com/k2-fsa/sherpa-onnx/releases/tag/tts-models

https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-fa-haaniye_low.tar.bz2

**Comment by csukuangfj** [comment]
Added!

Please see
- https://k2-fsa.github.io/sherpa/onnx/tts/apk-engine.html
- https://k2-fsa.github.io/sherpa/onnx/tts/apk.html

|standalone tts|tts engine|
|---|---|
|![Screenshot 2024-01-14 at 19 30 07](https://github.com/k2-fsa/sherpa-onnx/assets/5284924/1067570f-7f62-475b-8611-8bdcc9797dff)|![Screenshot 2024-01-14 at 19 31 00](https://github.com/k2-fsa/sherpa-onnx/assets/5284924/f20c3b77-5cc9-4d25-9fc5-04b66625280f)|

**Comment by gyroing** [comment]
@csukuangfj  @karim23657                           
 The Mimic3 tts engine  uses Persian NLP Toolkit "hazm" which plays an important role in POSTagger and Tokenize of Persian language. This job has been done in the Mimic3 tts engine.
https://github.com/MycroftAI/mimic3/blob/be72c185e471e3ef939147679df9e1d00262c513/mimic3_tts/voice.py#L12”

Saying that we just convert the model is not enough for the Persian language and the prepositions in the text are not read. We should pay attention to this important issue.”

**Comment by gyroing** [comment]
This engine Works but it reads the sentences Word by Word 😐 for this issue there is no persian language for piper yet. Becuase piper dosn't use hazm

**Comment by karim23657** [comment]
@csukuangfj , thank you for adding , please Also add prebuilt apk for vits-piper-fa_IR-amir-medium .
And also please add https://huggingface.co/facebook/mms-tts-fas to models with prebuilt apk .

**Comment by csukuangfj** [comment]
> And also please add https://huggingface.co/facebook/mms-tts-fas to models with prebuilt apk .

Could you follow
https://k2-fsa.github.io/sherpa/onnx/tts/mms.html
to add it by yourself?

This is an open-source project and we need your contribution.

**Comment by csukuangfj** [comment]
> @csukuangfj @karim23657 The Mimic3 tts engine uses Persian NLP Toolkit "Hazm" https://github.com/roshan-research/hazm which plays an important role in POSTagger and Tokenize of Persian language(pre-processing). This job has been done in the Mimic3 tts engine. https://github.com/MycroftAI/mimic3/blob/be72c185e471e3ef939147679df9e1d00262c513/mimic3_tts/voice.py#L602
> 
> Saying that we just convert the model is not enough for the Persian language and the Adducts(ترکیب اضافی) in the text are not read correctly. We should pay attention to this important issue.”
> 
> Here is the modeled solution from mimic3 Github page with a minor changes, I hope it will be used. https://huggingface.co/spaces/gyroing/PersianTextCorrection_Hazm

Since `hazm` is a Python package, it is not possible to use it in C++. Hope that users familiar with Persian can contribute based on what we have provided.

**Comment by gyroing** [comment]
Hi
new Persian Piper model  is ready to convert to android apk: 
[Persian TTS model for piper](https://huggingface.co/gyroing/Persian-Piper-Model-gyro
Persian Piper TTS spapce : 
)[ Persian Piper TTS space](https://huggingface.co/spaces/gyroing/Persian_Piper_TTS_HAZM) based on [persian-tts-dataset-male dataset](https://www.kaggle.com/datasets/magnoliasis/persian-tts-dataset-male)
voice model training is under progress  for finetune

**Comment by csukuangfj** [comment]
> Hi new Persian Piper model is ready to convert to android apk: [Persian TTS model for piper](https://huggingface.co/gyroing/Persian-Piper-Model-gyro Persian Piper TTS spapce : )[ Persian Piper TTS space](https://huggingface.co/spaces/gyroing/Persian_Piper_TTS_HAZM) based on [persian-tts-dataset-male dataset](https://www.kaggle.com/datasets/magnoliasis/persian-tts-dataset-male) voice model training is under progress for finetune

@gyroing 

Added!

Please see https://github.com/k2-fsa/sherpa-onnx/pull/555

**Comment by gyroing** [comment]
Hi 
Model has been updated:
[Persian-Piper-Model-gyro](https://huggingface.co/gyroing/Persian-Piper-Model-gyro)
