### ISSUE TITLE
Broken TTS engine apks 

### ISSUE THREAD

**Issue by Dmole** [k2-fsa/sherpa-onnx#528]
Using a current Google Pixel

and https://librera.mobi/

The engine apks install but crash the settings, and make no sound.

**Comment by csukuangfj** [comment]
Are you leaving the app running while configuring the settings?

**Comment by Dmole** [comment]
No; I went so far as to restart the phone to be sure.

**Comment by csukuangfj** [comment]
please also have a look at 
https://huggingface.co/csukuangfj/sherpa-onnx-apk/discussions/1#65977065092b4516b87640a1

> I enter the app, if I close it and go to settings to change the tts it crashes, but if I left it open(in the background) and go to settings it doesn't crash. Is it normal?
I'm not a root user, but I used a playstore app to show some logs:

**Comment by Dmole** [comment]
Yes I see it only works when the app is open.

That is not normal.

Maybe the app is missing a hook, or is not using one properly...

**Comment by csukuangfj** [comment]
> Yes I see it only works when the app is open.
> 
> That is not normal.
> 
> Maybe the app is missing a hook, or is not using one properly...

Do you have any suggestions to fix it?

I am new to Android programming and have never written an Android service before.

**Comment by csukuangfj** [comment]
> Yes I see it only works when the app is open.

> That is not normal.


That should have been fixed in the latest release.
