### ISSUE TITLE
UTF encoding of tokens in python

### ISSUE THREAD

**Issue by vesis84** [k2-fsa/sherpa-onnx#535]
Hello,
I use latest `master` of sherpa-onnx with pybind11 (v1.9.7).

The output from `OnlineRecognizerResult.text`  is with correct encoding:
(e.g.: `"Kdyť autobusu , já bych chtěl nahlásit o dovolená voda a požár zarážek ."`)

But the content of `OnlineRecognizerResult.tokens` is wrong:
(e.g.: `[' K', '<0x64>', '<0x79>', 'ť', ' a', '<0x75>', 'to', 'bu', '<0x73>', '<0x75>', ' ,', ' já', ' bych', ' chtěl', ' na', '<0x68>', 'lá', '<0x73>', '<0x69>', '<0x74>', ' o', ' dovol', 'en', 'á', ' v', '<0x6F>', 'da', ' a', ' po', 'ž', 'á', '<0x72>', ' za', 'rá', 'že', '<0x6B>', ' .']`)

For some reason, the single-char strings in range `[a-z]` come out as hexa-decimal codes.
This is what comes directly from the pybind11 property [OnlineRecognizerResult.tokens](https://github.com/k2-fsa/sherpa-onnx/blob/bf1dd3daf6f19f5abfbeeb3a0e5d66db997c29e7/sherpa-onnx/python/csrc/online-recognizer.cc#L23)

In the previous version `db41778e995277c6aee898ac75ff90fd05a6e837` (v1.8.11), it was still okay (~end of november).

I tried to reimplement `OnlineRecognizerResult.tokens` with: 
`PyUnicode_DecodeUTF8` as it is done in `OnlineRecognizerResult.text`. But that did not solve the issue.

Would you have an idea what might be possibly causing it ?
Best regards,
Karel

**Comment by csukuangfj** [comment]
Are you using a transducer or a CTC model?

**Comment by vesis84** [comment]
it is a transducer model

**Comment by vesis84** [comment]
Well, should it be the other way round ?
`if (sym.size() == 1 && sym[0] != ' ' && sym[0] >= 0x80) {`
Otherwise the 1char BPE tokens like 'a' 'b' 'c' will still be converted to hex-code...

**Comment by vesis84** [comment]
Yes, it solves it, should i open PR with it, would is also be in CTC ?
Does it break the 'byte output', that someone else needed ?

**Comment by csukuangfj** [comment]
>  should i open PR with it, would is also be in CTC

Yes, please.

---

> Does it break the 'byte output', that someone else needed ?

No, I don't think it will break byte-bpe.

---

Please change the following code:
https://github.com/k2-fsa/sherpa-onnx/blob/b6c020901a0be61f038ff7735b73b8e176796728/sherpa-onnx/csrc/offline-recognizer-transducer-impl.h#L49

https://github.com/k2-fsa/sherpa-onnx/blob/b6c020901a0be61f038ff7735b73b8e176796728/sherpa-onnx/csrc/online-recognizer-transducer-impl.h#L53

https://github.com/k2-fsa/sherpa-onnx/blob/b6c020901a0be61f038ff7735b73b8e176796728/sherpa-onnx/csrc/online-recognizer-ctc-impl.h#L41

https://github.com/k2-fsa/sherpa-onnx/blob/b6c020901a0be61f038ff7735b73b8e176796728/sherpa-onnx/csrc/offline-recognizer-ctc-impl.h#L48

**Comment by vesis84** [comment]
OK, the PR #550 is opened . 
Finally, a range of printable characters <128, is extempt from rewriting 1-char tokens as hexa-chars.

**Comment by csukuangfj** [comment]
Closing via #550
