### ISSUE TITLE
windows上运行speaker-identification-with-vad.py，提示sherpa_onnx没有SpeakerEmbeddingExtractor成员

### ISSUE THREAD

**Issue by zhoulei007** [k2-fsa/sherpa-onnx#537]
(py3_8) PS D:\gamefiles\Kaldi\cp2\sherpa-onnx> .\go.bat

D:\gamefiles\Kaldi\cp2\sherpa-onnx>python D:\gamefiles\Kaldi\cp2\sherpa-onnx\python-api-examples\speaker-identification-with-vad.py --silero-vad-model=D:\gamefiles\Kaldi\silero_vad.onnx --speaker-file speaker.txt --model wespeaker_zh_cnceleb_resnet34.onnx
Traceback (most recent call last):
  File "D:\gamefiles\Kaldi\cp2\sherpa-onnx\python-api-examples\speaker-identification-with-vad.py", line 169, in <module>
    extractor: sherpa_onnx.SpeakerEmbeddingExtractor,
AttributeError: module 'sherpa_onnx' has no attribute 'SpeakerEmbeddingExtractor'

D:\gamefiles\Kaldi\cp2\sherpa-onnx>pause
请按任意键继续. . .

**Comment by csukuangfj** [comment]
https://k2-fsa.github.io/sherpa/onnx/python/install.html#
请从源码编译。还没有发布新版本

等把说话人识别的安卓demo写好了，再发布新版本

**Comment by zhoulei007** [comment]
好，静候佳音

**Comment by csukuangfj** [comment]
已发布新版本。
请使用
```
pip install -U sherpa-onnx
```
