### ISSUE TITLE
bug: crashes instantly when id is different from a number

### ISSUE THREAD

**Issue by Ar57m** [k2-fsa/sherpa-onnx#547]
Notice a bug now, If I unintentionally write anything different than a number in the voice id, the app crashes instantly on android.

**Comment by csukuangfj** [comment]
could you describe the filename of the app you are running?

**Comment by Ar57m** [comment]
> could you describe the filename of the app you are running?

sherpa-onnx-1.9.8-arm64-v8a-en-tts-engine-vits-piper-en_GB-vctk-medium.apk

sherpa-onnx-1.9.8-arm64-v8a-en-tts-engine-vits-piper-en_US-libritts-high.apk

I think that should happen with others with more than one voice too

**Comment by csukuangfj** [comment]
Thanks for reporting.  We will fix it today.

**Comment by Ar57m** [comment]
one unrelated question, is there any plans to support silero tts models or xtts, if possible?

**Comment by Ar57m** [comment]
> > Are there ONNX models for them?
> 
> I think for silero yes https://github.com/snakers4/silero-models?tab=readme-ov-file#onnx

wrong one that's the stt, my bad, I couldn't find the tts onnx

**Comment by Ar57m** [comment]
thanks for the updates, on 1.9.9 seems much better 👏 that it can run in the background, but one minor thing I notice that the app doesn't remember the selected voice after closed.

**Comment by csukuangfj** [comment]
>  but one minor thing I notice that the app doesn't remember the selected voice after closed.

One solution is to serialize the config using sqlite. However, I am not familiar with that.

Help from the community is appreciated.

**Comment by Ar57m** [comment]
I am not familiar with that too, no problem. Is there any difference in the new 1.9.10 from 1.9.9 on android?
