### ISSUE TITLE
Support creating new stream with hotwords

### ISSUE THREAD

**Issue by w11wo** [k2-fsa/sherpa-onnx#551]
Hi, this is more of a feature request than an issue report. Apologies if this is not the proper place.

Currently, the context graph of a stream is initialized only once, and the path to the hotwords file is dependent on its value in config. This config is then used during model initialization, where the context graph is thus initialized.

Is it possible to support a frontend API (Python, mobile, etc) where we can update the list of hotwords multiple times, with only 1 instantiation of a model? This is motivated by the fact that it takes a while for the model to initialize on mobile phones, hence it might be convenient, if possible, to initialize the model once, but support replacing the hotword-boosted stream multiple times.

Thank you!

**Comment by csukuangfj** [comment]
Yes, I think it is possible.
https://github.com/k2-fsa/sherpa-onnx/blob/3f2a17ef47c9ccba8491bc2abad3bf70acedfdc7/sherpa-onnx/csrc/online-recognizer.h#L140

We already have C++ APIs for that.  You can check whether it is wrapped to Python/C/Kotlin etc. If it is not, could you help contribute by adding it?

**Comment by ductranminh** [comment]
Hi there, I just create this pull request #568 to support hot words on android/ios frontend

**Comment by w11wo** [comment]
Closing after successful merge
