### ISSUE TITLE
how can I train a persian stt?

### ISSUE THREAD

**Issue by mablue** [k2-fsa/sherpa-onnx#559]
whats the plan about stt engine for Iranian deaf people? can you share a persian version? I can help about big resources of text and voices connected together or any kind of help

**Comment by csukuangfj** [comment]
If you have data and GPU, then you can use
https://github.com/k2-fsa/icefall
to train a speech-to-text model and use it with sherpa-onnx.

You can find the doc for icefall at
https://k2-fsa.github.io/icefall/
