### ISSUE TITLE
Can I run the ConvEmformer model on Android ?

### ISSUE THREAD

**Issue by Hmialia** [k2-fsa/sherpa-onnx#562]
It seems that the onnx model exported from [convemformer](https://huggingface.co/Zengwei/icefall-asr-librispeech-conv-emformer-transducer-stateless2-2022-07-05) is not be supported by onnx on Android, although It can work with the script "onnx_pretrained.py" of Icefall. Here is my logcat info when the app trying to load convemformer model: 
![image](https://github.com/k2-fsa/sherpa-onnx/assets/118377714/178035c2-2f89-461b-8e91-2a4a4ce6df6a)
I am not sure if I need to provide more information of it, so I will continue to pay attention and add information. I would appreciate it if you could point out what went wrong.

**Comment by csukuangfj** [comment]
Sorry, you cannot.

The reason is that the following issue has not been fixed yet.
https://github.com/k2-fsa/sherpa-onnx/issues/42


---

Is there a reason to not use zipformer?

**Comment by csukuangfj** [comment]
Would be great if someone can help to fix #42

**Comment by Hmialia** [comment]
> Sorry, you cannot.
> 
> The reason is that the following issue has not been fixed yet. #42
> 
> Is there a reason to not use zipformer?

Thank you for your help. This [zipformer](https://huggingface.co/Zengwei/icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29) model can run on Android with onnx. I have no idea about other zipformer modles because I haven't use them.
