### ISSUE TITLE
Android crash java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "OrtGetApiBase" 

### ISSUE THREAD

**Issue by ductranit** [k2-fsa/sherpa-onnx#566]
Hi there,
I got this crash on initialize my custom model on android latest `master` branch (it works fine on iOS)
```
E/AndroidRuntime(12835): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "OrtGetApiBase" referenced by "/data/app/~~E5nv_HE51iLiRwWLA_Bz1A==/com.ccc-EyyC04IWDsMVtu1qBAE5lg==/base.apk!/lib/arm64-v8a/libsherpa-onnx-jni.so"...
E/AndroidRuntime(12835): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
E/AndroidRuntime(12835): 	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
E/AndroidRuntime(12835): 	at java.lang.System.loadLibrary(System.java:1661)
E/AndroidRuntime(12835): 	at com.k2fsa.sherpa.onnx.SherpaOnnx.<clinit>(SherpaOnnx.kt:122)
E/AndroidRuntime(12835): 	at com.ccc.service.SpeechServiceImpl.initModelMap(SpeechServiceImpl.kt:197)
E/AndroidRuntime(12835): 	at com.ccc.service.SpeechServiceImpl.initModel(SpeechServiceImpl.kt:185)
E/AndroidRuntime(12835): 	at com.ccc.service.SpeechServiceImpl.initSpeech(SpeechServiceImpl.kt:65)
E/AndroidRuntime(12835): 	at com.ccc.SpeechController.initSpeech$lambda$14(SpeechController.kt:482)
E/AndroidRuntime(12835): 	at com.ccc.SpeechController.$r8$lambda$i1zrzkJnm6mxbVj5vK745WXJdcw(Unknown Source:0)
E/AndroidRuntime(12835): 	at com.ccc.SpeechController$$ExternalSyntheticLambda0.run(Unknown Source:6)
E/AndroidRuntime(12835): 	at java.lang.Thread.run(Thread.java:1012)
```
And [this line](https://github.com/k2-fsa/sherpa-onnx/blob/master/android/SherpaOnnx/app/src/main/java/com/k2fsa/sherpa/onnx/SherpaOnnx.kt#L117)
```
System.loadLibrary("sherpa-onnx-jni")
```

Is there any suggestion to fix it?

**Comment by csukuangfj** [comment]
Which version of Android Studio are you using? Update it may solve the issue.

**Comment by ductranit** [comment]
@csukuangfj I'm using the latest Android Studio.
But I think it's native code issue from library instead of Android Studio

**Comment by csukuangfj** [comment]
Could you describe how you get the `.so` files?

**Comment by csukuangfj** [comment]
<img width="552" alt="00566b7819b514cc0a6df2a437d589c2" src="https://github.com/k2-fsa/sherpa-onnx/assets/5284924/4d53d193-ef72-408d-be9b-c129cfff1db4">

Does the above command work for you? Also, please make sure you are using libonnxruntime.so for arm64-v8a
if you are running the app on your phone.

---

One user had the same issue before but fixed it by updating Android Studio. 
<img width="559" alt="Screenshot 2024-02-01 at 09 53 48" src="https://github.com/k2-fsa/sherpa-onnx/assets/5284924/f3690c7a-3468-47cb-bf8d-c6d697efa77d">

<img width="554" alt="Screenshot 2024-02-01 at 09 55 27" src="https://github.com/k2-fsa/sherpa-onnx/assets/5284924/39f91fab-61ff-452d-ab40-9832f66e4ccc">

**Comment by ductranit** [comment]
I found the cause. It's onnxruntime version mismatch (I'm using another onnxruntime library in another lib).
So I just fix this issue by update the same onnxruntime version

**Comment by jinheena** [comment]
I faced the same issue suddenly. But  how do i know the version of onnxruntime from sherpa-onnx? 
I tried v1.9.14 and v1.9.17 but they got the same crash when i add 
`implementation("com.microsoft.onnxruntime:onnxruntime:latest.release")`
to the build.gradle(:app) to run another onnx model.
Changing the android studio version could not solve the issue either.

**Comment by csukuangfj** [comment]
Please describe in detail how you use sherpa-onnx.

We are using onnxruntime 1.17.1 as of now in sherpa-onnx.

**Comment by jinheena** [comment]
v1.9.17 with onnx version 1.17.1 solved the issue. Thank you for your help.
