### ISSUE TITLE
How should copyright be indicated for deployment?

### ISSUE THREAD

**Issue by shenck0** [k2-fsa/sherpa-onnx#570]
> https://github.com/k2-fsa/sherpa-onnx
> Copyright (C) 2022-2023, sherpa development team
> Licensed under the Apache License, Version 2.0 (the "License"); http://www.apache.org/licenses/LICENSE-2.0
> 
Is the above acceptable?

**Comment by csukuangfj** [comment]
Yes, that is fine with us.

(Please replace 2022-2023 with 2022-2024)

**Comment by shenck0** [comment]
Nice work, thanks!
