### ISSUE TITLE
准确率有相关的对比数据吗？

### ISSUE THREAD

**Issue by Hynsn** [k2-fsa/sherpa-onnx#573]
你好！请问sherpa-onnx、sherpa-ncnn和苹果siri、谷歌语音准确率方面有做过相关的数据对比吗，我这边在做这语音识别方面的调研 需要你们的帮助。

**Comment by csukuangfj** [comment]
sherpa-onnx、sherpa-ncnn 里面的模型，都是来自 icefall。
对于同一个模型，sherpa-onnx 和 sherpa-ncnn 的准确率，理论上来说，是一样的.

---

一般说的准确率，是在一个特定的数据集上。 icefall 里面, 每个 recipe 的 results.md 有详细的数据。

----

> 苹果siri、谷歌语音准确率方面有做过相关的数据对比

 我们没做过。我也没见过有其他开源框架做过这种对比。

这种对比的意义大么？你真要对比，就准备你使用场景的数据，然后用不同的模型去测试，看看准确率。

**Comment by Hynsn** [comment]
我这边需要，那只能自己测试了
