### ISSUE TITLE
sample_rate does not exist in the metadata

### ISSUE THREAD

**Issue by Soebb** [k2-fsa/sherpa-onnx#574]
project/sherpa-onnx/csrc/offline-tts-vits-model.cc:Init:83 sample_rate does not exist in the metadata

**Comment by csukuangfj** [comment]
could you describe which model you are using and how you download it?

**Comment by heyjoeway** [comment]
I ran into this issue when trying to use SherpaOnnxTTSEngine with a custom-trained Piper voice. It's not an issue with SherpaOnnx, rather Piper's `export_onnx` script does not attach the required metadata. I was able to fix it manually with the following snippet:
```python
import onnx

mdl = onnx.load("model.onnx")

a = mdl.metadata_props.add()
a.key = "sample_rate"
a.value = "22050"

a = mdl.metadata_props.add()
a.key = "n_speakers"
a.value = "1"

a = mdl.metadata_props.add()
a.key = "model_type"
a.value = "vits"

a = mdl.metadata_props.add()
a.key = "comment"
a.value = "piper"

a = mdl.metadata_props.add()
a.key = "language"
a.value = "English"

a = mdl.metadata_props.add()
a.key = "voice"
a.value = "en-us"

a = mdl.metadata_props.add()
a.key = "has_espeak"
a.value = "1"

onnx.save(mdl, "model_with_meta.onnx")
```

**Comment by siship** [comment]
Thank @heyjoeway. I have used the following code to update the onnx model.

```
model_path = "/icefall-tts-ljspeech-vits-2024-02-28/exp/vits-epoch-1000.onnx"
# Load the model
mdl = onnx.load(model_path)

# Add the metadata props Sherpa‑ONNX expects
for key, value in {
    "sample_rate": 22050,    # LJSpeech uses 22.05 kHz
    "n_speakers": 1,         # mono speaker
    "model_type": "vits",
    "comment": "piper",
    "language": "English",
    "voice": "en-us",
    "has_espeak": 1
}.items():
    meta = mdl.metadata_props.add()
    meta.key = key
    meta.value = str(value)

onnx.save(mdl, model_path)

sess = ort.InferenceSession(model_path, providers=["CPUExecutionProvider"])
print(sess.get_modelmeta().custom_metadata_map)
```
But when I run this:

```
sherpa-onnx-offline-tts \
  --vits-model=./icefall-tts-ljspeech-vits-2024-02-28/exp/vits-epoch-1000.onnx \
  --vits-tokens=./tokens.txt \
  --vits-lexicon=./lexicon.txt \
  --num-threads=1 \
  --output-filename=./high.wav \
  "Ask not what your country can do for you; ask what you can do for your country."
```

I got this error:

`terminate called after throwing an instance of 'Ort::Exception'
  what():  Got invalid dimensions for input: noise_scale for the following indices
 index: 0 Got: 3 Expected: 1
 Please fix either the inputs/outputs or the model.
`
There is no error with:  `/vits-ljs/vits-ljs.onnx` model

Does anyone know the issue? Anything needs to be done in the Python binding?

**Comment by siship** [comment]
Thank [@heyjoeway](https://github.com/heyjoeway). I have used the following code to update the onnx model.
# --model-type=high: https://huggingface.co/Zengwei/icefall-tts-ljspeech-vits-2024-02-28
model_path = "/icefall-tts-ljspeech-vits-2024-02-28/exp/vits-epoch-1000.onnx"
# Load the model
mdl = onnx.load(model_path)

# Add the metadata props Sherpa‑ONNX expects
for key, value in {
    "sample_rate": 22050,    # LJSpeech uses 22.05 kHz
    "n_speakers": 1,         # mono speaker
    "model_type": "vits",
    "comment": "piper",
    "language": "English",
    "voice": "en-us",
    "has_espeak": 1
}.items():
    meta = mdl.metadata_props.add()
    meta.key = key
    meta.value = str(value)

onnx.save(mdl, model_path)

sess = ort.InferenceSession(model_path, providers=["CPUExecutionProvider"])
print(sess.get_modelmeta().custom_metadata_map)
But when I run this:
```
python3 /home/self/workspace/k2/sherpa-onnx/python-api-examples/offline-tts.py \
 --vits-model=./icefall-tts-ljspeech-vits-2024-02-28/exp/vits-epoch-1000-update.onnx \
 --vits-lexicon=./vits-ljs/lexicon.txt \
 --vits-tokens=./vits-ljs/tokens.txt \
 --output-filename=./high-py.wav \
 "Ask not what your country can do for you; ask what you can do for your country."
```
OR
```
sherpa-onnx-offline-tts \
  --vits-model=icefall-tts-ljspeech-vits-2024-02-28/exp/vits-epoch-1000-update.onnx \
  --vits-tokens=icefall-tts-ljspeech-vits-2024-02-28/data/tokens.txt \
  --vits-data-dir=espeak-ng-data \
  --num-threads=1 \
  --output-filename=out.wav \
  "Ask not what your country can do for you; ask what you can do for your country."
```
I got this error:
`Got invalid dimensions for input: noise_scale for the following indices index: 0 Got: 3 Expected: 1 Please fix either the inputs/outputs or the model.` 

Btw, there is no error with: /vits-ljs/vits-ljs.onnx model. https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-ljs.tar.bz2

Does anyone know the issue?

And what is the difference between https://huggingface.co/Zengwei/icefall-tts-ljspeech-vits-2024-02-28 and https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-ljs.tar.bz2 models? @csukuangfj

**Comment by csukuangfj** [comment]
vits-ljs is from the original vits repo.

icefall-tts-ljspeech-vits-2024-02-28 is trained using icefall.

Although they are both VITS, they are from different frameworks. Thus, you need to use different scripts to add meta data.

Please first tell us where you get your vits model.

@siship

**Comment by siship** [comment]
@csukuangfj Thanks for your response. 

We started VITs model training using the icefall script, since training is still going on, we planned to do inferecing with the pretrained models shared in Icefall/sherpa page with sherpa-onnx.

The following models we tried:
https://huggingface.co/Zengwei/icefall-tts-ljspeech-vits-2024-02-28 - high 
https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-ljs.tar.bz2

And we used the same `sherpa-onnx-offline-tts` for testing.

sherpa-onnx-offline-tts \
  --vits-model=icefall-tts-ljspeech-vits-2024-02-28/exp/vits-epoch-1000.onnx \
  --vits-tokens=icefall-tts-ljspeech-vits-2024-02-28/data/tokens.txt \
  --vits-data-dir=espeak-ng-data \
  --num-threads=1 \
  --output-filename=out.wav \
  "Ask not what your country can do for you; ask what you can do for your country."

Can you tell me which scripts to add meta data for `icefall-tts-ljspeech-vits-2024-02-28/exp/vits-epoch-1000.onnx` this model? And how to run sherpa-onnx-offline-tts for this model?

Also, I have another confusion: 

To export to onnx for this model: `icefall-tts-ljspeech-vits-2024-02-28/exp/epoch-1000.pt (an icefall model)` we need to use: https://github.com/k2-fsa/icefall/blob/master/egs/ljspeech/TTS/vits/export-onnx.py, am I correct?

And this `https://github.com/k2-fsa/sherpa-onnx/blob/master/scripts/vits/export-onnx-ljs.py` is for this implementation: https://github.com/jaywalnut310/vits ?

**Comment by csukuangfj** [comment]
> Can you tell me which scripts to add meta data for icefall-tts-ljspeech-vits-2024-02-28/exp/vits-epoch-1000.onnx this model?

Does it already have meta data?

Every tts onnx model from icefall has already contained meta data.


---

> To export to onnx for this model: icefall-tts-ljspeech-vits-2024-02-28/exp/epoch-1000.pt (an icefall model) we need to use: https://github.com/k2-fsa/icefall/blob/master/egs/ljspeech/TTS/vits/export-onnx.py, am I correct?

Yes, you are right.

---

> And this https://github.com/k2-fsa/sherpa-onnx/blob/master/scripts/vits/export-onnx-ljs.py is for this implementation: https://github.com/jaywalnut310/vits ?

Yes, you are right.

**Comment by siship** [comment]
> > Can you tell me which scripts to add meta data for icefall-tts-ljspeech-vits-2024-02-28/exp/vits-epoch-1000.onnx this model?
> 
> Does it already have meta data?
> 
> Every tts onnx model from icefall has already contained meta data.
I used following script - this is working after adding the `sample_rate` in metadata
`./vits/test_onnx.py --model-filename icefall-tts-ljspeech-vits-2024-02-28/exp/vits-epoch-1000-update.onnx --tokens icefall-tts-ljspeech-vits-2024-02-28/data/tokens.txt`

{'noise_scale_w': '0.8', 'noise_scale': '0.667', 'has_espeak': '1', 'voice': 'en-us', 'n_speakers': '1', 'language': 'English', 'sample_rate': '22050', 'comment': 'piper', 'version': '1', 'model_author': 'k2-fsa', 'model_type': 'vits'}

But, this same model is not working `icefall-tts-ljspeech-vits-2024-02-28/exp/vits-epoch-1000-update.onnx` is not working with:  `sherpa-onnx-offline-tts` binary

**Comment by csukuangfj** [comment]
Please compare the number of inputs/outputs of the two onnx models.

The ealerier one may not be exported using the latest export-onnx.py

**Comment by siship** [comment]
@csukuangfj Thanks, we tried to export our intermediate vits model. It is working without any issues. 

Also, I export the pretrained `icefall-tts-ljspeech-vits-2024-02-28/exp/epoch-1000.pt` using the latest export-onnx.py - it's working without any issues.

Thanks for the help.

Can you tell me, how to convert to int8 - `export-onnx.py` does not have that? However, `https://github.com/k2-fsa/sherpa-onnx/blob/master/scripts/vits/export-onnx-ljs.py` it has - `quantize_dynamic`. I tried, but got some inconsistency error.

**Comment by csukuangfj** [comment]
> I tried, but got some inconsistency error.

Please post your quantization code and your error logs.

**Comment by siship** [comment]
> > I tried, but got some inconsistency error.
> 
> Please post your quantization code and your error logs.

Hi, it's done. There was some other issues, i faced. Fixed it. Thanks.
I have quantized all the pretrained models.

**Comment by csukuangfj** [comment]
Please.use 

OfflineMatchaTtsModelConfig
,

NOT OfflineTtsVitsModelConfig.

**Comment by avalanche15** [comment]
> Please.use
> 
> OfflineMatchaTtsModelConfig ,
> 
> NOT OfflineTtsVitsModelConfig.

![Image](https://github.com/user-attachments/assets/d93ffb4d-bb86-4fc8-89a4-5fdea4f55ea4)你好这些model 和我的/data/matcha-icefall-zh-baker/model-steps-3.onnx"适配吗区别是什么呢

**Comment by csukuangfj** [comment]
建议去看matcha tts的文档。文档里都有。

**Comment by silmes** [comment]
> 建议去看matcha tts的文档。文档里都有。

你好，我在使用java-api初始化模型时，出现错误：D:\a\sherpa-onnx\sherpa-onnx\sherpa-onnx\csrc\offline-tts-matcha-model.cc:Init:162 'jieba' does not exist in the metadata，然后程序异常中止，并且没有捕获到 Java 层面的异常

模型为：matcha-icefall-zh-en

模型下载地址为：https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/matcha-icefall-zh-en.tar.bz2

代码为：
 public static void main(String[] args) {

        // 1. 绝对路径
        String modelPath = "D:/tts/sherpa-onnx";
        String dataDir = modelPath + "/matcha-icefall-zh-en/espeak-ng-data";

        try {
            // 2. 构建配置
            String model = modelPath + "/matcha-icefall-zh-en/model-steps-3.onnx";
            String voCoder = modelPath + "/vocos-16khz-univ.onnx";
            String tokens = modelPath + "/matcha-icefall-zh-en/tokens.txt";
            String lexicon = modelPath + "/matcha-icefall-zh-en/lexicon.txt";

            OfflineTtsMatchaModelConfig matchaModelConfig = OfflineTtsMatchaModelConfig.builder()
                    .setAcousticModel(model)
                    .setVocoder(voCoder)
                    .setTokens(tokens)
                    .setDataDir(dataDir) 
                    .setLexicon(lexicon)
                    .build();

            OfflineTtsModelConfig modelConfig = OfflineTtsModelConfig.builder()
                    .setMatcha(matchaModelConfig)
                    .setNumThreads(1) // 先用 1 个线程排查，排除多线程冲突
                    .setDebug(true)
                    .build();

            OfflineTtsConfig config = OfflineTtsConfig.builder()
                    .setModel(modelConfig)
                    .build();

            System.out.println("即将执行 new OfflineTts(config)，如果这里卡住或闪退，说明就是初始化崩溃...");
            new OfflineTts(config);
            System.out.println("恭喜！TTS 初始化成功！");

        } catch (Throwable t) {
            System.err.println("捕获到 Java 层面的异常：");
            t.printStackTrace();
        }
    }


完整报错：
D:\a\sherpa-onnx\sherpa-onnx\sherpa-onnx\jni\offline-tts.cc:operator ():271 config:
OfflineTtsConfig(model=OfflineTtsModelConfig(vits=OfflineTtsVitsModelConfig(model="", lexicon="", tokens="", data_dir="", dict_dir="", noise_scale=0.667, noise_scale_w=0.8, length_scale=1), matcha=OfflineTtsMatchaModelConfig(acoustic_model="D:/tts/sherpa-onnx/matcha-icefall-zh-en/model-steps-3.onnx", vocoder="D:/tts/sherpa-onnx/vocos-16khz-univ.onnx", lexicon="D:/tts/sherpa-onnx/matcha-icefall-zh-en/lexicon.txt", tokens="D:/tts/sherpa-onnx/matcha-icefall-zh-en/tokens.txt", data_dir="D:/tts/sherpa-onnx/matcha-icefall-zh-en/espeak-ng-data", dict_dir="", noise_scale=1, length_scale=1), kokoro=OfflineTtsKokoroModelConfig(model="", voices="", tokens="", lexicon="", data_dir="", dict_dir="", length_scale=1, lang=""), kitten=OfflineTtsKittenModelConfig(model="", voices="", tokens="", data_dir="", length_scale=1), num_threads=1, debug=True, provider="cpu"), rule_fsts="", rule_fars="", max_num_sentences=1, silence_scale=0.2)
D:\a\sherpa-onnx\sherpa-onnx\sherpa-onnx\csrc\offline-tts-matcha-model.cc:Init:154 ---matcha model---
version=1
model_type=matcha-tts
language=chinese English
voice=zh en-us
model_author=dengcunqin
n_speakers=1
pad_id=0
sample_rate=16000
use_eos_bos=1
modelscope_url=https://modelscope.cn/models/dengcunqin/matcha_tts_zh_en_20251010
demo_url=https://www.tulingyun.com/tts.html
num_ode_steps=3
----------input names----------
0 x
1 x_length
2 noise_scale
3 length_scale
----------output names----------
0 mel


D:\a\sherpa-onnx\sherpa-onnx\sherpa-onnx\csrc\offline-tts-matcha-model.cc:Init:162 'jieba' does not exist in the metadata

**Comment by csukuangfj** [comment]
@silmes 

你好！请去提一个 issue, 记得严格按照 issue template 里的步骤来.

**Comment by csukuangfj** [comment]
@silmes 

友情提示，文档都是适配最新的代码的。你没告诉我们你用的什么版本代码，假设你用的最新的.

**Comment by silmes** [comment]
> [@silmes](https://github.com/silmes)
> 
> 友情提示，文档都是适配最新的代码的。你没告诉我们你用的什么版本代码，假设你用的最新的.
谢谢你，确实是版本的问题
我之前使用的是sherpa-onnx-v1.12.10.jar版本，更新为最新版本之后已经可以正常使用了
