### ISSUE TITLE
sherpa-onnx-alsa Failed to set number of channels to 1 or Failed to set sample rate to 16000 

### ISSUE THREAD

**Issue by Abandon-ht** [k2-fsa/sherpa-onnx#578]
When u are using sherpa-onnx-alsa & encounter issues with using the microphone as input, u can try changing hw:0,0 to plughw:0,0
![issure](https://github.com/k2-fsa/sherpa-onnx/assets/64671747/9b9efed6-6452-4d04-a4c1-9adccc1927b1)
Note: Please use the arecord -l command to check your sound card devices & replace plughw:0,0 with you own. This command will display a list of available sound card devices
![issure2](https://github.com/k2-fsa/sherpa-onnx/assets/64671747/71301159-c5cc-447d-a5de-b926de9b25b3)

**Comment by csukuangfj** [comment]
Thanks! We have updated the code and doc to use `plughw`.
