### ISSUE TITLE
Can't generate lexicon

### ISSUE THREAD

**Issue by Ahmed-Hossam-Aldeen** [k2-fsa/sherpa-onnx#582]
I converted my Arabic vits model to onnx and generated tokens successfly using the script in the repo, I want to integrate it in a mobile application but I can't find the lexicon.txt file for Arabic? And do I need a lexicon file if I have my custom Arabic cleaner in the model config?

**Comment by csukuangfj** [comment]
could you describe how you convert words to tokens?

If you use espeak-ng like piper, then you don't need a lexicon.txt at all.

**Comment by Ahmed-Hossam-Aldeen** [comment]
I replaced English cleaners with a function that maps Arabic characters to English without using phonemizer library, then I use text_to_sequence normally just like the normal code

**Comment by csukuangfj** [comment]
https://huggingface.co/csukuangfj/vits-ljs

you  can find how we generate lexicon for English in the above link.
