### ISSUE TITLE
sherpa_onnx.OnlineRecognizer( TypeError: OnlineRecognizer() takes no arguments

### ISSUE THREAD

**Issue by lonngxiang** [k2-fsa/sherpa-onnx#594]
运行speech-recognition-from-microphone-onnx 报错

![image](https://github.com/k2-fsa/sherpa-onnx/assets/40717349/ecb0a737-ff50-4436-9b23-245e0b988d6f)

**Comment by csukuangfj** [comment]
你是不是 sherpa-onnx 和 sherpa-ncnn 弄混了？

有运行

pip install sherpa-onnx

么

**Comment by lonngxiang** [comment]
> 你是不是 sherpa-onnx 和 sherpa-ncnn 弄混了？
> 
> 有运行
> 
> pip install sherpa-onnx
> 
> 么

有安装的：Installing collected packages: sherpa-onnx
Successfully installed sherpa-onnx-1.9.10；

windows运行： python .\speech-recognition-from-microphone-onnx.py  --tokens=sherpa-onnx-streaming-zipformer-multi-zh-hans-2023-12-12/tokens.txt --encoder=sherpa-onnx-streaming-zipformer-multi-zh-hans-2023-12-12/encoder-epoch-20-avg-1-chunk-16-left-128.onnx   --decoder=sherpa-onnx-streaming-zipformer-multi-zh-hans-2023-12-12/decoder-epoch-20-avg-1-chunk-16-left-128.onnx --joiner=sherpa-onnx-streaming-zipformer-multi-zh-hans-2023-12-12/joiner-epoch-20-avg-1-chunk-16-left-128.onnx

`#!/usr/bin/env python3

# Real-time speech recognition from a microphone with sherpa-onnx Python API
#
# Please refer to
# https://k2-fsa.github.io/sherpa/onnx/pretrained_models/index.html
# to download pre-trained models

import argparse
import sys
from pathlib import Path

try:
    import sounddevice as sd
except ImportError:
    print("Please install sounddevice first. You can use")
    print()
    print("  pip install sounddevice")
    print()
    print("to install it")
    sys.exit(-1)

import sherpa_onnx




def assert_file_exists(filename: str):
    assert Path(filename).is_file(), (
        f"{filename} does not exist!\n"
        "Please refer to "
        "https://k2-fsa.github.io/sherpa/onnx/pretrained_models/index.html to download it"
    )


def get_args():
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )

    parser.add_argument(
        "--tokens",
        type=str,
        help="Path to tokens.txt",
    )

    parser.add_argument(
        "--encoder",
        type=str,
        help="Path to the encoder model",
    )

    parser.add_argument(
        "--decoder",
        type=str,
        help="Path to the decoder model",
    )

    parser.add_argument(
        "--joiner",
        type=str,
        help="Path to the joiner model",
    )

    parser.add_argument(
        "--decoding-method",
        type=str,
        default="greedy_search",
        help="Valid values are greedy_search and modified_beam_search",
    )

    return parser.parse_args()


def create_recognizer():
    args = get_args()
    assert_file_exists(args.encoder)
    assert_file_exists(args.decoder)
    assert_file_exists(args.joiner)
    assert_file_exists(args.tokens)
    # Please replace the model files if needed.
    # See https://k2-fsa.github.io/sherpa/onnx/pretrained_models/index.html
    # for download links.
    print(args.tokens,
        args.encoder,
        args.decoder,
        args.joiner)
    recognizer = sherpa_onnx.OnlineRecognizer(
        tokens=args.tokens,
        encoder=args.encoder,
        decoder=args.decoder,
        joiner=args.joiner,
        num_threads=1,
        sample_rate=16000,
        feature_dim=80,
        decoding_method=args.decoding_method,
    )
    return recognizer


def main():
    recognizer = create_recognizer()
    print("Started! Please speak")

    # The model is using 16 kHz, we use 48 kHz here to demonstrate that
    # sherpa-onnx will do resampling inside.
    sample_rate = 48000
    samples_per_read = int(0.1 * sample_rate)  # 0.1 second = 100 ms
    last_result = ""
    stream = recognizer.create_stream()
    # last_result = ""
    i=0
    with sd.InputStream(channels=1, dtype="float32", samplerate=sample_rate) as s:
        while True:
            samples, _ = s.read(samples_per_read)  # a blocking read
            samples = samples.reshape(-1)
            stream.accept_waveform(sample_rate, samples)
            while recognizer.is_ready(stream):
                recognizer.decode_stream(stream)
            result = recognizer.get_result(stream)
            # if last_result != result:
            #     last_result = result
            #     print("\r{}".format(result), end="", flush=True)

            if last_result != result:
                if i==0:
                    print("{}".format(result),end='')
                    last_result = result
                    i=i+1
                else:
                    last_result_len=len(last_result)
                    
                    new_word = result[last_result_len:]
                    # print(last_result,result,new_word)
                    print("{}".format(new_word),end='', flush=True)
                    last_result = result


if __name__ == "__main__":
    devices = sd.query_devices()
    print(devices)
    default_input_device_idx = sd.default.device[0]
    print(f'Use default device: {devices[default_input_device_idx]["name"]}')

    try:
        main()
    except KeyboardInterrupt:
        print("\nCaught Ctrl + C. Exiting")`

**Comment by csukuangfj** [comment]
```python3
import sherpa_onnx
print(sherpa_onnx.__file__)
print(help(sherpa_onnx.OnlineRecognizer))
```

这几行，输出什么呢？

**Comment by lonngxiang** [comment]
> ```python
> ```python
> print(help(sherpa_onnx.OnlineRecognizer))
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

```
import sherpa_onnx
>>> print(sherpa_onnx.__file__)
C:\Users\loong\.conda\envs\nlp\Lib\site-packages\sherpa_onnx\__init__.py
>>> print(help(sherpa_onnx.OnlineRecognizer))
Help on class OnlineRecognizer in module sherpa_onnx.online_recognizer:

class OnlineRecognizer(builtins.object)
 |  A class for streaming speech recognition.
 |
 |  Please refer to the following files for usages
 |   - https://github.com/k2-fsa/sherpa-onnx/blob/master/sherpa-onnx/python/tests/test_online_recognizer.py
 |   - https://github.com/k2-fsa/sherpa-onnx/blob/master/python-api-examples/online-decode-files.py
 |
 |  Methods defined here:
 |
 |  create_stream(self, hotwords: Optional[str] = None)
 |
 |  decode_stream(self, s: _sherpa_onnx.OnlineStream)
 |
 |  decode_streams(self, ss: List[_sherpa_onnx.OnlineStream])
 |
 |  get_result(self, s: _sherpa_onnx.OnlineStream) -> str
 |
 |  is_endpoint(self, s: _sherpa_onnx.OnlineStream) -> bool
 |
 |  is_ready(self, s: _sherpa_onnx.OnlineStream) -> bool
 |
 |  reset(self, s: _sherpa_onnx.OnlineStream) -> bool
 |
 |  timestamps(self, s: _sherpa_onnx.OnlineStream) -> List[float]
 |
 |  tokens(self, s: _sherpa_onnx.OnlineStream) -> List[str]
 |
 |  ----------------------------------------------------------------------
 |  Class methods defined here:
 |
 |  from_paraformer(tokens: str, encoder: str, decoder: str, num_threads: int = 2, sample_rate: float = 16000, feature_dim: int = 80, enable_endpoint_detection: bool = False, rule1_min_trailing_silence: float = 2.4, rule2_min_trailing_silence: float = 1.2, rule3_min_utterance_length: float = 20.0, decoding_method: str = 'greedy_search', provider: str = 'cpu') from builtins.type
 |      Please refer to
 |      `<https://k2-fsa.github.io/sherpa/onnx/pretrained_models/index.html>`_
 |      to download pre-trained models for different languages, e.g., Chinese,
 |      English, etc.
 |
 |      Args:
 |        tokens:
 |          Path to ``tokens.txt``. Each line in ``tokens.txt`` contains two
 |          columns::
 |
 |              symbol integer_id
 |
 |        encoder:
 |          Path to ``encoder.onnx``.
 |        decoder:
 |          Path to ``decoder.onnx``.
 |        num_threads:
 |          Number of threads for neural network computation.
 |        sample_rate:
 |          Sample rate of the training data used to train the model.
 |        feature_dim:
 |          Dimension of the feature used to train the model.
 |        enable_endpoint_detection:
 |          True to enable endpoint detection. False to disable endpoint
 |          detection.
 |        rule1_min_trailing_silence:
 |          Used only when enable_endpoint_detection is True. If the duration
 |          of trailing silence in seconds is larger than this value, we assume
 |          an endpoint is detected.
 |        rule2_min_trailing_silence:
 |          Used only when enable_endpoint_detection is True. If we have decoded
 |          something that is nonsilence and if the duration of trailing silence
 |          in seconds is larger than this value, we assume an endpoint is
 |          detected.
 |        rule3_min_utterance_length:
 |          Used only when enable_endpoint_detection is True. If the utterance
 |          length in seconds is larger than this value, we assume an endpoint
 |          is detected.
 |        decoding_method:
 |          The only valid value is greedy_search.
 |        provider:
 |          onnxruntime execution providers. Valid values are: cpu, cuda, coreml.
 |
 |  from_transducer(tokens: str, encoder: str, decoder: str, joiner: str, num_threads: int = 2, sample_rate: float = 16000, feature_dim: int = 80, enable_endpoint_detection: bool = False, rule1_min_trailing_silence: float = 2.4, rule2_min_trailing_silence: float = 1.2, rule3_min_utterance_length: float = 20.0, decoding_method: str = 'greedy_search', max_active_paths: int = 4, hotwords_score: float = 1.5, blank_penalty: float = 0.0, hotwords_file: str = '', provider: str = 'cpu', model_type: str = '', lm: str = '', lm_scale: float = 0.1) from builtins.type
 |      Please refer to
 |      `<https://k2-fsa.github.io/sherpa/onnx/pretrained_models/index.html>`_
 |      to download pre-trained models for different languages, e.g., Chinese,
 |      English, etc.
 |
 |      Args:
 |        tokens:
 |          Path to ``tokens.txt``. Each line in ``tokens.txt`` contains two
 |          columns::
 |
 |              symbol integer_id
 |
 |        encoder:
 |          Path to ``encoder.onnx``.
 |        decoder:
 |          Path to ``decoder.onnx``.
 |        joiner:
 |          Path to ``joiner.onnx``.
 |        num_threads:
 |          Number of threads for neural network computation.
 |        sample_rate:
 |          Sample rate of the training data used to train the model.
 |        feature_dim:
 |          Dimension of the feature used to train the model.
 |        enable_endpoint_detection:
 |          True to enable endpoint detection. False to disable endpoint
 |          detection.
 |        rule1_min_trailing_silence:
 |          Used only when enable_endpoint_detection is True. If the duration
 |          of trailing silence in seconds is larger than this value, we assume
 |          an endpoint is detected.
 |        rule2_min_trailing_silence:
 |          Used only when enable_endpoint_detection is True. If we have decoded
 |          something that is nonsilence and if the duration of trailing silence
 |          in seconds is larger than this value, we assume an endpoint is
 |          detected.
 |        rule3_min_utterance_length:
 |          Used only when enable_endpoint_detection is True. If the utterance
 |          length in seconds is larger than this value, we assume an endpoint
 |          is detected.
 |        decoding_method:
 |          Valid values are greedy_search, modified_beam_search.
 |        max_active_paths:
 |          Use only when decoding_method is modified_beam_search. It specifies
 |          the maximum number of active paths during beam search.
 |        blank_penalty:
 |          The penalty applied on blank symbol during decoding.
 |        hotwords_file:
 |          The file containing hotwords, one words/phrases per line, and for each
 |          phrase the bpe/cjkchar are separated by a space.
 |        hotwords_score:
 |          The hotword score of each token for biasing word/phrase. Used only if
 |          hotwords_file is given with modified_beam_search as decoding method.
 |        provider:
 |          onnxruntime execution providers. Valid values are: cpu, cuda, coreml.
 |        model_type:
 |          Online transducer model type. Valid values are: conformer, lstm,
 |          zipformer, zipformer2. All other values lead to loading the model twice.
 |
 |  from_wenet_ctc(tokens: str, model: str, chunk_size: int = 16, num_left_chunks: int = 4, num_threads: int = 2, sample_rate: float = 16000, feature_dim: int = 80, enable_endpoint_detection: bool = False, rule1_min_trailing_silence: float = 2.4, rule2_min_trailing_silence: float = 1.2, rule3_min_utterance_length: float = 20.0, decoding_method: str = 'greedy_search', provider: str = 'cpu') from builtins.type
 |      Please refer to
 |      `<https://k2-fsa.github.io/sherpa/onnx/pretrained_models/wenet/index.html>`_
 |      to download pre-trained models for different languages, e.g., Chinese,
 |      English, etc.
 |
 |      Args:
 |        tokens:
 |          Path to ``tokens.txt``. Each line in ``tokens.txt`` contains two
 |          columns::
 |
 |              symbol integer_id
 |
 |        model:
 |          Path to ``model.onnx``.
 |        chunk_size:
 |          The --chunk-size parameter from WeNet.
 |        num_left_chunks:
 |          The --num-left-chunks parameter from WeNet.
 |        num_threads:
 |          Number of threads for neural network computation.
 |        sample_rate:
 |          Sample rate of the training data used to train the model.
 |        feature_dim:
 |          Dimension of the feature used to train the model.
 |        enable_endpoint_detection:

```

**Comment by csukuangfj** [comment]
你写的代码
```
    recognizer = sherpa_onnx.OnlineRecognizer(
        tokens=args.tokens,
        encoder=args.encoder,
        decoder=args.decoder,
        joiner=args.joiner,
        num_threads=1,
        sample_rate=16000,
        feature_dim=80,
        decoding_method=args.decoding_method,
    )
    return recognizer
```
这个是从哪里来的？

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/sherpa-onnx/blob/master/python-api-examples/speech-recognition-from-microphone.py

最新的代码是这个

**Comment by lonngxiang** [comment]
> 你写的代码
> 
> ```python
>     recognizer = sherpa_onnx.OnlineRecognizer(
>         tokens=args.tokens,
>         encoder=args.encoder,
>         decoder=args.decoder,
>         joiner=args.joiner,
>         num_threads=1,
>         sample_rate=16000,
>         feature_dim=80,
>         decoding_method=args.decoding_method,
>     )
>     return recognizer
> ```
> 
> 这个是从哪里来的？

嗯，我用新的测试喜爱，这份代码可能是去年的

**Comment by lonngxiang** [comment]
> https://github.com/k2-fsa/sherpa-onnx/blob/master/python-api-examples/speech-recognition-from-microphone.py
> 
> 最新的代码是这个

好像还是报错
```
recognizer = sherpa_onnx.OnlineRecognizer.from_transducer(
  File "C:\Users\loong\.conda\envs\nlp\Lib\site-packages\sherpa_onnx\online_recognizer.py", line 181, in from_transducer
    self.recognizer = _Recognizer(recognizer_config)
RuntimeError: Failed to load model because protobuf parsing failed.

```

**Comment by csukuangfj** [comment]
你模型文件路径，是不是不对？

https://k2-fsa.github.io/sherpa/onnx/python/real-time-speech-recongition-from-a-microphone.html

这个是具体的文档，你去看看？

请确保
1. 你有下载模型
2. 你有正确的给定模型文件路径

**Comment by lonngxiang** [comment]
> ####
> Comment
> Write
> Preview
> 
> 
> Add your comment here...
> 
> [ Markdown is supported ](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) 
> Paste, drop, or click to add files
>  Close with comment
> Comment
> Remember, contributions to this repository should follow our [GitHub Community Guidelines](https://docs.github.com/articles/github-community-guidelines).
> Assignees
> No one assigned
> Labels
> None yet
> Projects
> None yet
> Milestone
> No milestone
> Development
> No branches or pull requests
> 
> Notifications
> Customize
> 
> Unsubscribe
> You’re receiving notifications because you authored the thread.
> 
> 2 participants
> [ <img alt="@csukuangfj" width="26" height="26" src="https://avatars.githubusercontent.com/u/5284924?s=52&amp;v=4"> ](/csukuangfj) [ <img alt="@lonngxiang" width="26" height="26" src="https://avatars.githubusercontent.com/u/40717349?s=52&amp;v=4"> ](/lonngxiang)
> ## Footer
> [ ](https://github.com)
> © 2024 GitHub, Inc.
> ### Footer navigation
> * [Terms](https://docs.github.com/site-policy/github-terms/github-terms-of-service)
> * [Privacy](https://docs.github.com/site-policy/privacy-policies/github-privacy-statement)
> * [Secu](/security)

嗯，应该是文件损坏，我用的huggingface-cli下载，好像下载的文件有一定问题

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/sherpa-onnx/releases/tag/asr-models

这边可以下载，你去看看？直接 wget 就好
<img width="1077" alt="Screenshot 2024-02-21 at 12 08 38" src="https://github.com/k2-fsa/sherpa-onnx/assets/5284924/38e2559a-9808-4731-8751-a3035478a191">

**Comment by lonngxiang** [comment]
> https://github.com/k2-fsa/sherpa-onnx/releases/tag/asr-models
> 
> 这边可以下载，你去看看？直接 wget 就好 <img alt="Screenshot 2024-02-21 at 12 08 38" width="1077" src="https://private-user-images.githubusercontent.com/5284924/306491921-38e2559a-9808-4731-8751-a3035478a191.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0ODg4NDUsIm5iZiI6MTcwODQ4ODU0NSwicGF0aCI6Ii81Mjg0OTI0LzMwNjQ5MTkyMS0zOGUyNTU5YS05ODA4LTQ3MzEtODc1MS1hMzAzNTQ3OGExOTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjFUMDQwOTA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGU3Y2E0MDlkN2JjNGVmOTc2M2Y3OGZjODQwYWY1ZWQ1MzJhMjAwNmJiOGZhYjVlZGY1NzcwZmNjZjVkZjBkNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.amo-XmOSbyAWUQ67GL8Mtq90Aki5kx4r1TCMZQ2qDrU">

好的收到，谢谢

**Comment by chenzf11** [comment]
我报的错是
![image](https://github.com/k2-fsa/sherpa-onnx/assets/61148900/7c659678-848f-4183-a5fc-398ed30cff4e)
把这两个注释掉就好了
![image](https://github.com/k2-fsa/sherpa-onnx/assets/61148900/b0294003-4bbd-4045-af97-d5c6b2b81fb2)
但是我识别实例的文件正常，识别自己的文件没有识别结果

**Comment by csukuangfj** [comment]
因为还没发布新版本。 现在就发新版本。

**Comment by chenzf11** [comment]
> 我报的错是 ![image](https://private-user-images.githubusercontent.com/61148900/335143135-7c659678-848f-4183-a5fc-398ed30cff4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjUxNTYsIm5iZiI6MTcxNzA2NDg1NiwicGF0aCI6Ii82MTE0ODkwMC8zMzUxNDMxMzUtN2M2NTk2NzgtODQ4Zi00MTgzLWE1ZmMtMzk4ZWQzMGNmZjRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDEwMjczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MDAyN2YwZTg4MjgzMTM4YmY2MzVjMDVhMzJjOWI1ZmY1MGIwYzhhNTVlYmYzZmEyMjE4MjhjM2Q2YzY5YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h3jp13JJEAyEZaYQqM8PKz1hlkhdSWkoue34gj3Z6BY) 把这两个注释掉就好了 ![image](https://private-user-images.githubusercontent.com/61148900/335143319-b0294003-4bbd-4045-af97-d5c6b2b81fb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjUxNTYsIm5iZiI6MTcxNzA2NDg1NiwicGF0aCI6Ii82MTE0ODkwMC8zMzUxNDMzMTktYjAyOTQwMDMtNGJiZC00MDQ1LWFmOTctZDVjNmIyYjgxZmIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDEwMjczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlODdhMDUzNjg2NGMxZGY0NTE3YjY2MWM3NDNiY2JlODBlMGY1MzZiYmU2NmNjM2JmM2NlZWNjZjI0ODc5ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dtYlDn5Fj-Whewmdi-4oeNZakYTXaXvRdmDxAg7v3Rk) 但是我识别实例的文件正常，识别自己的文件没有识别结果

是因为我自己的文件时全英文吗，格式都对，单通道16位

**Comment by csukuangfj** [comment]
你自己的文件，请发过来看看？

**Comment by chenzf11** [comment]
[test-wav.zip](https://github.com/k2-fsa/sherpa-onnx/files/15497629/test-wav.zip)
谢谢谢谢

**Comment by chenzf11** [comment]
> [test-wav.zip](https://github.com/k2-fsa/sherpa-onnx/files/15497629/test-wav.zip) 谢谢谢谢

嗷嗷用的https://github.com/k2-fsa/sherpa-onnx/blob/master/python-api-examples/online-decode-files.py这份代码测的

**Comment by csukuangfj** [comment]
<img width="1356" alt="Screenshot 2024-05-30 at 18 41 00" src="https://github.com/k2-fsa/sherpa-onnx/assets/5284924/932daec2-a780-4888-8f5b-3baa7016ee04">


我这里，用 whisper tiny.en 跑，没有任何的问题。

**Comment by csukuangfj** [comment]
你的 .wav 文件没问题。请换个英语模型跑。

**Comment by chenzf11** [comment]
> 你的 .wav 文件没问题。请换个英语模型跑。

现在用的/mnt/trash/new_kaldi/sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20
改成sherpa-onnx-streaming-zipformer-en-2023-06-26这个模型可以吗

**Comment by csukuangfj** [comment]
可以的。你试试？

**Comment by csukuangfj** [comment]
linux 发布新版本了。

```
pip install -U sherpa-onnx
```

升级下 sherpa-onnx, 你就不需要改代码了
