### ISSUE TITLE
how to solve the channel problem and bit rate problem?

### ISSUE THREAD

**Issue by deyiluobo** [k2-fsa/sherpa-onnx#602]
I refer to the following documents to compile the project and put it on the development board to run.[https://k2-fsa.github.io/sherpa/onnx/install/aarch64-embedded-linux.html](https://k2-fsa.github.io/sherpa/onnx/install/aarch64-embedded-linux.html)
command is:
`./sherpa-onnx-alsa  --tokens=./sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20/tokens.txt  --encoder=./sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20/encoder-epoch-99-avg-1.onnx --decoder=./sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20/decoder-epoch-99-avg-1.onnx --joiner=./sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20/joiner-epoch-99-avg-1.onnx hw:3,0`

An error occurred

```
Failed to set number of channels to 1. Invalid argument
Channel count is set to 2. Will use only 1 channel of it.
Failed to set sample rate to 16000
Current sample rate is 48000
Creating a resampler:
   in_sample_rate: 48000
   output_sample_rate: 16000
Recording started!
Use recording device: hw:3,0
```
The program is running, but the microphone cannot pick up the sound
Can you tell me how to solve the channel problem and bit rate problem?

**Comment by csukuangfj** [comment]
Could you replace 

hw:3,0

with

plughw:3,0

and re-try?

---

Also, the program seems to.be running successfully, right?

**Comment by deyiluobo** [comment]
> Could you replace
> 
> hw:3,0
> 
> with
> 
> plughw:3,0
> 
> and re-try?
> 
> Also, the program seems to.be running successfully, right?

It can run normally after using `plughw`, thank you very much!
