### ISSUE TITLE
这边项目也支持语音唤醒吗？

### ISSUE THREAD

**Issue by lonngxiang** [k2-fsa/sherpa-onnx#607]
这边看到这里好像是；但看命令行这要怎么安装使用呢
https://k2-fsa.github.io/sherpa/onnx/kws/index.html
![image](https://github.com/k2-fsa/sherpa-onnx/assets/40717349/7ab4d892-1879-4a24-ba97-76f42575b3f4)

**Comment by csukuangfj** [comment]
pip install sherpa-onnx后，就有的

**Comment by lonngxiang** [comment]
> pip install sherpa-onnx后，就有的
我这好像不行，import sherpa_onnx可以，但是命令行sherpa-onnx-cli不行

![image](https://github.com/k2-fsa/sherpa-onnx/assets/40717349/19f8f96d-7910-4a15-83d5-1cc472d69e21)
![image](https://github.com/k2-fsa/sherpa-onnx/assets/40717349/00a2e9bf-4d50-402b-80a8-542ae590065b)

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/sherpa-onnx/blob/master/sherpa-onnx/python/sherpa_onnx/cli.py

就是这个文件。

你手动下载，然后跑它

**Comment by lonngxiang** [comment]
> pip install sherpa-onnx

嗯谢谢，这边重新安装后可以了；然后问下这语音唤醒有python使用案例吗

**Comment by lonngxiang** [comment]
z这里是不是写错了，这里不是热词是唤醒词案例；案例不知道有python使用调用的代码不

![image](https://github.com/k2-fsa/sherpa-onnx/assets/40717349/2bd2a050-af73-4778-9432-8a8333ca7aa1)

**Comment by csukuangfj** [comment]
> z这里是不是写错了，这里不是热词是唤醒词案例

你说得对.

---

> 案例不知道有python使用调用的代码不

这个要问 @pkufool 

我看了下，没找到 python 的例子.

**Comment by lonngxiang** [comment]
> > > > z这里是不是写错了，这里不是热词是唤醒词案例
> > > 
> > > 
> > > 你说得对.
> > > > 案例不知道有python使用调用的代码不
> > > 
> > > 
> > > 这个要问 @pkufool
> > > 我看了下，没找到 python 的例子.
> > 
> > 
> > 嗯嗯，期待@pkufool 看到帮忙回复下
> 
> 在加，我写个测试就合并

tks， 非常期待

**Comment by lonngxiang** [comment]
@csukuangfj  @pkufool  
麻烦问下这个版本是不是还没有发布呢？https://github.com/k2-fsa/sherpa-onnx/blob/master/python-api-examples/keyword-spotter-from-microphone.py
![image](https://github.com/k2-fsa/sherpa-onnx/assets/40717349/e11ee55b-44bc-422f-b774-500a80cbbd30)

**Comment by csukuangfj** [comment]
你的是哪个版本？

```
pip install sherpa-onnx>=1.9.11
```

**Comment by lonngxiang** [comment]
> 你的是哪个版本？
> 
> ```
> pip install sherpa-onnx>=1.9.11
> ```

sherpa-onnx   1.9.10
