### ISSUE TITLE
Requred File?

### ISSUE THREAD

**Issue by studionexus-lk** [k2-fsa/sherpa-onnx#611]
is that 

vits-piper-en_GB.sh
vits-piper-en_GB.py
tokens.txt

requred to be added on assets files on android?

**Comment by csukuangfj** [comment]
```
vits-piper-en_GB.sh
vits-piper-en_GB.py
```
are not required. Their sole purpose is to show you have the model is converted from piper.

---

`tokens.txt` is required.
