### ISSUE TITLE
热词影响onnx端点识别问题

### ISSUE THREAD

**Issue by 20246688** [k2-fsa/sherpa-onnx#619]
设置的热词表，用于onnx流式识别时，出现识别到热词就停止识别的情况，请问如何解决？

**Comment by csukuangfj** [comment]
请 @pkufool 帮忙看下

**Comment by 20246688** [comment]
老师们好，我看见ncnn那边好像有个关于热词尾部删除bug的，因为看不明白，不知道是不是可以解决这个识别问题的，如果可以的话，恳请老师录个相关视频吧

**Comment by pkufool** [comment]
这个问题，这两天会修，录什么视频？

**Comment by 20246688** [comment]
因为我看pull很吃力

**Comment by pkufool** [comment]
@20246688  https://github.com/k2-fsa/sherpa-onnx/pull/638 这个 PR 修了。 你可以再测一下
