### ISSUE TITLE
单词写错需要修改

### ISSUE THREAD

**Issue by lonngxiang** [k2-fsa/sherpa-onnx#621]
应该是：num_trailing_blanks=args.num_trailing_blanks,

https://github.com/k2-fsa/sherpa-onnx/blob/f9db33c9268b20e7bc50c24637fb04bf3fa83e65/python-api-examples/keyword-spotter-from-microphone.py#L166

**Comment by csukuangfj** [comment]
能帮忙提个 pull-request 吗？

建议在本地跑了没问题后，再提交。可以避免出现类似的问题。

**Comment by lonngxiang** [comment]
> 能帮忙提个 pull-request 吗？
> 
> 建议在本地跑了没问题后，再提交。可以避免出现类似的问题。

嗯好的
