### ISSUE TITLE
麻烦问下endpoint识别与vad识别有什么区别吗？

### ISSUE THREAD

**Issue by lonngxiang** [k2-fsa/sherpa-onnx#627]
https://github.com/k2-fsa/sherpa-onnx/blob/master/python-api-examples/speech-recognition-from-microphone-with-endpoint-detection.py

https://github.com/k2-fsa/sherpa-onnx/blob/master/python-api-examples/vad-with-non-streaming-asr.py

**Comment by csukuangfj** [comment]
![image](https://github.com/k2-fsa/sherpa-onnx/assets/5284924/b0207f13-2228-460d-bf79-c68d3a6fadc1)

**Comment by lonngxiang** [comment]
嗯，两个的应用方向有啥区别呢

**Comment by csukuangfj** [comment]
> [speech-recognition-from-microphone-with-endpoint-detection.py](https://github.com/k2-fsa/sherpa-onnx/blob/master/python-api-examples/speech-recognition-from-microphone-with-endpoint-detection.py)
这个是流式 ASR

---

> [/vad-with-non-streaming-asr.py](https://github.com/k2-fsa/sherpa-onnx/blob/master/python-api-examples/vad-with-non-streaming-asr.py)

这个是非流式 ASR

**Comment by lonngxiang** [comment]
> > [speech-recognition-from-microphone-with-endpoint-detection.py](https://github.com/k2-fsa/sherpa-onnx/blob/master/python-api-examples/speech-recognition-from-microphone-with-endpoint-detection.py)
> > 这个是流式 ASR
> 
> > [/vad-with-non-streaming-asr.py](https://github.com/k2-fsa/sherpa-onnx/blob/master/python-api-examples/vad-with-non-streaming-asr.py)
> 
> 这个是非流式 ASR

VAD能应用到流式吗

**Comment by csukuangfj** [comment]
我们没用过
