### ISSUE TITLE
设置keywords后，例如小新小新这样的识别就很高，如果是“学习管家”这样的就基本很难识别到，老哥指导下怎么优化？

### ISSUE THREAD

**Issue by gsn516** [k2-fsa/sherpa-onnx#634]

**Comment by csukuangfj** [comment]
请 @pkufool  帮忙看看

**Comment by gsn516** [comment]
> 关键词怎么配的？ keywords_score 和 keywords_threshold 设置的多少？

就用的默认的1.5和0.25，这个有相关配置的介绍么？

**Comment by gsn516** [comment]
> 关键词怎么配的？ keywords_score 和 keywords_threshold 设置的多少？

关键词用你们的命令生成的

**Comment by pkufool** [comment]
> > 关键词怎么配的？ keywords_score 和 keywords_threshold 设置的多少？
> 
> 就用的默认的1.5和0.25，这个有相关配置的介绍么？

文档里有简单的介绍他们的用途。 你可以试试 增大 keywords_score, 减小 keywords_threshold

**Comment by gsn516** [comment]
> > > 关键词怎么配的？ keywords_score 和 keywords_threshold 设置的多少？
> > 
> > 
> > 就用的默认的1.5和0.25，这个有相关配置的介绍么？
> 
> 文档里有简单的介绍他们的用途。 你可以试试 增大 keywords_score, 减小 keywords_threshold

好像改动后基本没效果，还是识别不出，我用了一共两行关键词，小新小新识别率就很高，还有其他优化途径么？学习管家基本识别不出来

**Comment by pkufool** [comment]
你可以录些 学习管家 的音频进行 finetune。

**Comment by pkufool** [comment]
你的 keywords 文件发出来看一下

**Comment by gsn516** [comment]
> 你的 keywords 文件发出来看一下

你用这个试下，w ǎng d iǎn g uǎn j iā @网点管家

**Comment by gsn516** [comment]
> 你可以录些 学习管家 的音频进行 finetune。

这个有相关教程链接么？帮忙发下，我试下

**Comment by pkufool** [comment]
https://github.com/k2-fsa/icefall/tree/master/egs/wenetspeech/KWS 从 run.sh 开始看

**Comment by gsn516** [comment]
> finetune

感谢，我试试

**Comment by pkufool** [comment]
![cb381054a912b594d51c27c18e075a2](https://github.com/k2-fsa/sherpa-onnx/assets/11765074/5da9deb8-d97d-434e-b5e5-b606bbba77bb)

我试了一下，“网点管家” 的触发率确实比较低，你可以把前鼻音那个配置也加进去，后鼻音用这个参数。再测一下

**Comment by gsn516** [comment]
> ![cb381054a912b594d51c27c18e075a2](https://private-user-images.githubusercontent.com/11765074/310019142-5da9deb8-d97d-434e-b5e5-b606bbba77bb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjM1NDAsIm5iZiI6MTcwOTYyMzI0MCwicGF0aCI6Ii8xMTc2NTA3NC8zMTAwMTkxNDItNWRhOWRlYjgtZDk3ZC00MzRlLWI1ZTUtYjYwNmJiYmE3N2JiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA3MjA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2OTU4NmZiNWMxMDg1NDdhYjYzNTE5YzQ5NTc0MjZkZjY2YmQ2YTNiMTM1MDQyYTk3MDJkNTViZmMyMjllMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xG1rz06paIAG2d8wXSqEdK0YPy7LQf6YibMBX3OoXmU)
> 
> 我试了一下，“网点管家” 的触发率确实比较低，你可以把前鼻音那个配置也加进去，后鼻音用这个参数。再测一下

好像确实触发率高了很多，但是感觉和小新小新这个还是有点差距，按您说的录些 网点管家 的音频进行 finetune。是否会有一个相对不错的提升？

**Comment by pkufool** [comment]
你录些数据finetune，提升效果肯定会好很多，你可以看 recipe 里面的结果。

**Comment by gsn516** [comment]
> 你录些数据finetune，提升效果肯定会好很多，你可以看 recipe 里面的结果。

嗯，感谢老哥，按你说的去试试

**Comment by jzdcf** [comment]
是不是辅音是 u 的识别效果都不好，我都是“取消”识别不到
