### ISSUE TITLE
Issue with Decoding Audio Stream from Genesys Client

### ISSUE THREAD

**Issue by tempops** [k2-fsa/sherpa-onnx#645]
Hello, I am running an implementation which consumed an audio stream from third party client and sends it to streaming server through socket connection. I receive the audio (which is PCMU with 8000Hz sample rate)  but I do not see any result even when I print it to check in the terminal, I think the stream data is going to "while self.recognizer.is_ready(stream)" and not going t next step.

I have printed the length of samples to check the output when audio is coming into the server.

In recv_audio_samples() I print length of message when it is received from socket.recv() for which I get 1600

I also print the length of output  from np.frombuffer(message, dtype=np.float.32) for which I get 400

samples = await self.recv_audio_samples(socket)
            if samples is None:
                break

            # TODO(fangjun): At present, we assume the sampling rate
            # of the received audio samples equal to --sample-rate
            stream.accept_waveform(sample_rate=self.sample_rate, waveform=samples)
            print(samples) ==> "output is a tensor"
            print(len(samples)) ==> "result is 400"
 
            while self.recognizer.is_ready(stream):
                await self.compute_and_decode(stream)
                result = self.recognizer.get_result(stream)
                print(result) ==> "result is empty"
 

I also changed the sample rate to 8000 here:  stream.accept_waveform(sample_rate=8000, waveform=samples)

**Comment by csukuangfj** [comment]
> which is PCMU with 8000Hz sample rate

We require PCM, not PCMU.

Please use PCM.

If you still have issues, please save the received data to a wave file and check whether there are any issues with the data.
(You can also post the saved file and we can have a look.)

**Comment by tempops** [comment]
Thank you for the response,

Is there any way to convert the audio livestream to PCM format before sending to streaming_server?

For offline file transcription I can convert the wav file format to be readable by sherpa-onnx using ffmpeg for wav file, but I do not know how to do it for streaming audio data.

**Comment by csukuangfj** [comment]
> Is there any way to convert the audio livestream to PCM format

Sorry, we don't have experience with that. Please search for it with Google.

**Comment by tempops** [comment]
Sure, thank you.
