### ISSUE TITLE
tts piper中文模型能否增加支持多音字？

### ISSUE THREAD

**Issue by longshiming** [k2-fsa/sherpa-onnx#649]
目前sherpa-onnx中tts使用piper中文模型不能区分多音字，能否增加中文多音字区分的支持

**Comment by csukuangfj** [comment]
piper 里的中文模型，目前应该只有一个，它用的是 espeak-ng，目前不知道如何加多音字的支持。

非 piper 的中文模型，自己可以在 lexicon.txt 里，加入多音字的支持。需要什么发音，可以自己加。我们也加了一部分多音字。
但多音字太多了，我们无法一一列举。只有用户自己碰到需要的，自己加了。
