### ISSUE TITLE
Is the latest ios-build script working?

### ISSUE THREAD

**Issue by l3utterfly** [k2-fsa/sherpa-onnx#651]
I'm trying to build for onnxruntime 1.17.1. It appears this is not found: `wget https://github.com/csukuangfj/onnxruntime-libs/releases/download/v${onnxruntime_version}/onnxruntime.xcframework-${onnxruntime_version}.tar.bz2`

I noticed in the releases page the xcframework stopped being released after 1.16.3, is that intentional?

**Comment by csukuangfj** [comment]
Because I have not managed to build onnxruntime 1.17.x for iOS, so the script is still using onnxruntime 1.16.3

**Comment by csukuangfj** [comment]
The script is still working. You can try it. I just tried it.

**Comment by l3utterfly** [comment]
Oh ok, any problems with building for iOS? Perhaps I can help?

**Comment by csukuangfj** [comment]
> Oh ok, any problems with building for iOS? Perhaps I can help?

Thanks! I will try to compile it one more time tomorrow. If it still fails, I will post the error logs here.

**Comment by csukuangfj** [comment]
Please see #654
