### ISSUE TITLE
The command line tool named 'sherpa-onnx-cli' for converting hotwords to tokens was not found.

### ISSUE THREAD

**Issue by rbt2000** [k2-fsa/sherpa-onnx#656]

**Comment by rbt2000** [comment]
Thank you to the entire team for your hard work and dedication. Your contributions have made a significant impact on this project. Your work has been immensely beneficial to me.

**Comment by NS-ice** [comment]
Did you solve it? I have the same problem.
`berry@berry:~/sherpa-onnx/build/bin $ sherpa-onnx-keyword-spotter --help
-bash: sherpa-onnx-keyword-spotter: command not found
berry@berry:~/sherpa-onnx/build/bin $ sherpa-onnx-cli text2token --help
-bash: sherpa-onnx-cli: command not found
`
 these command tools can be found.

**Comment by NS-ice** [comment]
It looks like you need to **install Python package**. [https://k2-fsa.github.io/sherpa/onnx/python/install.html#check-your-installation](url)

```shell
Extracting sherpa_onnx-1.10.27-py3.11-linux-aarch64.egg to /usr/local/lib/python3.11/dist-packages
Adding sherpa-onnx 1.10.27 to easy-install.pth file
**Installing sherpa-onnx-cli script to /usr/local/bin**

Installed /usr/local/lib/python3.11/dist-packages/sherpa_onnx-1.10.27-py3.11-linux-aarch64.egg
Processing dependencies for sherpa-onnx==1.10.27
Finished processing dependencies for sherpa-onnx==1.10.27
berry@berry:~/sherpa-onnx $ sherpa-onnx-cli
Usage: sherpa-onnx-cli [OPTIONS] COMMAND [ARGS]...

  The shell entry point to sherpa-onnx.

Options:
  --help  Show this message and exit.

```

**Comment by csukuangfj** [comment]
pip install sherpa-onnx

should fix the issue.
