### ISSUE TITLE
Convenience Request: Please Add Support for Using hotwords.txt in .NET Environment, Thank You!

### ISSUE THREAD

**Issue by rbt2000** [k2-fsa/sherpa-onnx#658]
I'm writing to request a feature that would greatly enhance the accuracy of speech recognition in task-specific scenarios within the .NET environment. Specifically, I would like to see support for utilizing a hotwords.txt file in the SpeechRecognitionFromMicrophone component.

The integration of hotword detection can significantly improve the performance of speech recognition systems by reducing the amount of irrelevant audio data that needs to be processed. This, in turn, leads to faster and more accurate recognition results, which is crucial for applications where voice commands play a central role.

I believe that adding the ability to use hotwords.txt in the .NET implementation would be a valuable addition to the project, and I'm sure it would be appreciated by other users as well.

Thank you for considering this request. I'm looking forward to any updates or suggestions you might have.

Best regards,
rbt2000

**Comment by csukuangfj** [comment]
Fixed in #689
