### ISSUE TITLE
Not able to run ios-swiftui sample project

### ISSUE THREAD

**Issue by DeepanshCUHK** [k2-fsa/sherpa-onnx#659]
I am not able to run the ios tts sample project. It is giving error that "No XCFramework found". How to fix that?

**Comment by csukuangfj** [comment]
https://k2-fsa.github.io/sherpa/onnx/ios/build-sherpa-onnx-swift.html

Please follow our doc.

If you still have issues after reading the doc, please ask it again.

**Comment by DeepanshCUHK** [comment]
Great, following the doc works. I have another questions:
1. Where can i find more pre-trained models like this: https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_US-amy-low.tar.bz2
2. How can I train my own model using my voice?

**Comment by csukuangfj** [comment]
> Where can i find more pre-trained models like this

Please see
https://github.com/k2-fsa/sherpa-onnx/releases/tag/tts-models

There are, a lot of, pre-trained TTS models on the above page.

---

> How can I train my own model using my voice?

You can either use [piper](https://github.com/rhasspy/piper)
or [icefall](https://github.com/k2-fsa/icefall).

By the way, `icefall` is maintained by us so you can get first-time support if you have any issues.

**Comment by DeepanshCUHK** [comment]
Ok, I will check that out. Thanks!

Another question I had: 
I already have .pth files (from Realtime voice cloning), is there any way I convert them to the required format for your model?

**Comment by csukuangfj** [comment]
Note that `.pth` file is just an extension. Everything can be renamed to have a `.pth` extension.

The point is what is saved in your file. We support only VITS model at present. If your model is VITS, then it is very likely that we have already supported it.

**Comment by DeepanshCUHK** [comment]
do you have any example of loading a custom vits model into the project? I have been trying to do it but it is not working.

I tried the following:
1. Load "onnx" and "onnx.json" just like given in sample project.
2. Change the model name

It is showing me an error that "sample_rate does not exist in the metadata"

<img width="409" alt="Screenshot 2024-03-15 at 12 34 05 PM" src="https://github.com/k2-fsa/sherpa-onnx/assets/32092609/4b08b51b-d522-48f1-afd2-9442aa5e0fe2">
<img width="574" alt="Screenshot 2024-03-15 at 12 35 48 PM" src="https://github.com/k2-fsa/sherpa-onnx/assets/32092609/70f77936-1819-4e6b-ba4c-22e8585a953c">

**Comment by csukuangfj** [comment]
please download the model from
https://github.com/k2-fsa/sherpa-onnx/releases/tag/tts-models

Files not downloaded from the above URL are not supported.

**Comment by DeepanshCUHK** [comment]
Got it!

> You can either use [piper](https://github.com/rhasspy/piper)
> or [icefall](https://github.com/k2-fsa/icefall).

Any example code on how to convert the VITS custom voice model generated from piper or icefall into the required format that I can run with sherpa-onnx?

**Comment by csukuangfj** [comment]
> Any example code on how to convert the VITS custom voice model trained from piper 

Yes, please see
https://github.com/csukuangfj/models/blob/small-fixes/.github/scripts/vits-piper.sh

---

> icefall into the required format that I can run with sherpa-onnx?

Yes, please see
https://k2-fsa.github.io/icefall/recipes/TTS/ljspeech/vits.html#export-models

---

By the way, if your piper model is open-sourced, we can convert it to sherpa-onnx for you.

**Comment by DeepanshCUHK** [comment]
Thanks for the resources, I will take a look! 

Is it also possible to clone custom voice model using Coqui-TTS and convert to sherpa-onnx? Any resources for that?

**Comment by csukuangfj** [comment]
As described above, we support only vits models.

**Comment by DeepanshCUHK** [comment]
Yes right. So, if I train a VITS model using Coqui TTS (like this: https://www.youtube.com/watch?v=8v18u8PQXgs&t=160s), can I convert that to sherpa-onnx?

**Comment by csukuangfj** [comment]
Yes. Please use `characters` or `espeak-ng` as the frontend.
