### ISSUE TITLE
C#版本：OnlineRecognizerResult字段返回过少

### ISSUE THREAD

**Issue by dengyh2018** [k2-fsa/sherpa-onnx#660]
C#版本：OnlineRecognizerResult只返回text字段，建议返回一下其他字段：tokens, timestamps, start_time等等。
<img width="350" alt="tapd_68600772_base64_1710087170_564" src="https://github.com/k2-fsa/sherpa-onnx/assets/43289616/97e46514-48e1-4529-9e78-954b66d3f4ae">
![tapd_68600772_base64_1710087288_484](https://github.com/k2-fsa/sherpa-onnx/assets/43289616/5eebd445-13fd-40b9-9ee5-89cf17777b70)

**Comment by dengyh2018** [comment]
您好：
  　你的邮件已收到，稍后回复。
                                  －－邓奕宏

**Comment by wxbool** [comment]
希望 go 的sdk 一起安排下，感谢大佬

**Comment by csukuangfj** [comment]
Closed by #690
