### ISSUE TITLE
Bytes input to FFmpeg in speech-recognition-from-url.py

### ISSUE THREAD

**Issue by tempops** [k2-fsa/sherpa-onnx#663]
Hello,

I am getting raw audio bytes in this format which I want to convert to a format that is accessible by Sherpa ONNX

raw input audio bytes:
b'\x00\x00@\xbb\x00\x00\x80\xba\x00\x00\xe0\xba\x00\x00\xd4\xbb\x00\x00\x80\xb9\x00\x00\x00\xbb\x00\x00P\xbb\x00\x00\xe0\xba\x00\x00\xe0\xba\x00\x00\xc0\xba\x00\x00 \xbb\x00\x000\xbb\x00\x00P\xbb\x00\x00`\xbb\x00\x00p\xbb\x00\x00 \xbb\x00\x00

I try providing this as input to FFmpeg code in speech-recognition-from-url.py:

    recognizer = create_recognizer(args)
 
    byte = await websocket.recv()
 
    ffmpeg_cmd = [
        "ffmpeg",
        "-i",
        byte,
        "-f",
        "s16le",
        "-acodec",
        "pcm_s16le",
        "-ac",
        "1",
        "-ar",
        "16000",
        "-",
    ]

I receive no output when I try this method. Is there any way to stream audio bytes to ffmpeg?

**Comment by csukuangfj** [comment]
> I am getting raw audio bytes

Everything in the computer is represented in bytes.

Given that you did not describe any metadata about the bytes, it is not possible to tell you how to do with your bytes, since
the bytes can represent any thing.

**Comment by tempops** [comment]
These bytes are from an audio stream, I am sending the bytes to be decoded by ffmpeg and then read by Sherpa_ONNX. The audio stream is from online-websocket-client-microphone.py which is sending the microphone bytes to the websocket I had given above:

recognizer = create_recognizer(args)

byte = await websocket.recv()

ffmpeg_cmd = [
    "ffmpeg",
    "-i",
    byte,
    "-f",
    "s16le",
    "-acodec",
    "pcm_s16le",
    "-ac",
    "1",
    "-ar",
    "16000",
    "-",
]


However ffmpeg does not give any output in stdout and it is stuck at the first frame

data = process.stdout.read(frames_per_read * 2)
        if not data:
            break

do we need to send a specific chunk of bytes as input to ffmpeg? currently it is receiving byte length of 3200

**Comment by csukuangfj** [comment]
I suggest that you save the output of ffmpeg to a file and check the file.

**Comment by tempops** [comment]
Hello,
I had to provide pipe:0 input to ffmpeg to ingest bytes on the fly and provide metadata about the bytes beforehand to make it work.

Thanks!
