### ISSUE TITLE
NUGET PACKAGE FOR sherpa-onnx

### ISSUE THREAD

**Issue by studionexus-lk** [k2-fsa/sherpa-onnx#680]
org.k2fsa.sherpa.onnx  nuget package wont support x86?

![Screenshot 2024-03-20 083834](https://github.com/k2-fsa/sherpa-onnx/assets/105704203/2e99b077-69c9-4351-84a0-01c7d4792faa)

**Comment by csukuangfj** [comment]
Do you need windows 32-bit x86?

**Comment by csukuangfj** [comment]
will.add it. please wait for a moment.
