### ISSUE TITLE
ASR Storage Audio and text Files

### ISSUE THREAD

**Issue by Pantyhose-X** [k2-fsa/sherpa-onnx#681]
ASR Speech to text while preserving audio and text
For example, at a company meeting, a school teacher can save the audio and text of a speech for later review and reflection. This is a very good feature. 

A large number of ASR models
https://github.com/facebookresearch/seamless_communication

**Comment by csukuangfj** [comment]
Sorry, it is not in the plan. The models are sooooo large.
