### ISSUE TITLE
sherpa-onnx 与 sherpa-ncnn 功能对比

### ISSUE THREAD

**Issue by zw76859420** [k2-fsa/sherpa-onnx#685]
Hello,
  请问下管理员有对比过 sherpa-onnx 与 sherpa-ncnn 在速度上的对比吗？（CPU and GPU）

Best

**Comment by csukuangfj** [comment]
树莓派4B cpu上，我们的模型， onnxruntime 比 ncnn 略快。

**Comment by zw76859420** [comment]
> 树莓派4B cpu上，我们的模型， onnxruntime 比 ncnn 略快。

请问有在GPU上进行对比吗？

**Comment by csukuangfj** [comment]
木有

**Comment by csukuangfj** [comment]
gpu， 请用 k2-fsa/sherpa

**Comment by zw76859420** [comment]
> gpu， 请用 k2-fsa/sherpa

明白了，多谢
