### ISSUE TITLE
中文识别乱码

### ISSUE THREAD

**Issue by yunbiaolin** [k2-fsa/sherpa-onnx#700]
在windows上编译运行sherpa-onnx-offline.exe， 中文是乱码如下。 英文的结果是对的。  按理说模型是支持中英文的， 请问哪里配置不对？
下面是我运行的命令行：
sherpa-onnx-offline.exe --tokens=C:/Users/Test/Downloads/sherpa-onnx-paraformer-zh-2024-03-09.tar/sherpa-onnx-paraformer-zh-2024-03-09/tokens.txt   --paraformer=C:/Users/Test/Downloads/sherpa-onnx-paraformer-zh-2024-03-09.tar/sherpa-onnx-paraformer-zh-2024-03-09/model.onnx   C:/sherpa-onnx/build/bin/Release/sherpa-onnx-paraformer-trilingual-zh-cantonese-en/test_wavs/3-sichuan.wav

运行的结果：
{"text": "Φç¬σ╖▒σ░▒µÿ»σ£¿ΘéúΣ╕¬σ£¿ΘéúΣ╕¬σ░▒µÿ»σ£¿µâàΦèéΘçîΘ¥óσ░▒µÿ»µäƒΦºëµÿ»µ╝öτÜäτë╣σê½σÑ╜σ░▒µÿ»σÑ╜σâÅσ╛êτ£ƒσ«₧Σ╕Çµá╖Σ╜áτƒÑΘüôσÉº", "timestamps": [], "tokens":["Φç¬", "σ╖▒", "σ░▒", "µÿ»", "σ£¿", "Θéú", "Σ╕¬", "σ£¿", "Θéú", "Σ╕¬", "σ░▒", "µÿ»", "σ£¿", "µâà", "Φèé", "Θçî", "Θ¥ó", "σ░▒", "µÿ»", "µäƒ", "Φºë", "µÿ»", "µ╝ö", "τÜä", "τë╣", "σê½", "σÑ╜", "σ░▒", "µÿ»", "σÑ╜", "σâÅ", "σ╛ê", "τ£ƒ", "σ«₧", "Σ╕Ç", "µá╖", "Σ╜á", "τƒÑ", "Θüô", "σÉº"]}

**Comment by csukuangfj** [comment]
你下载模型的那个文档，有说明，如何解决

**Comment by csukuangfj** [comment]
命令行运行

CHCP 65001

**Comment by yunbiaolin** [comment]
@csukuangfj  谢谢。 我原来的系统是英文系统， 后来换成中文系统解决了。 不过你的方法更简单。
