### ISSUE TITLE
Unable to make apk

### ISSUE THREAD

**Issue by carapatounfor** [k2-fsa/sherpa-onnx#701]
im sorry for mi incomptence but im a newby, im trying but im unable to make the apk run, i followed all steps but im not able to get out of the UnsatisfiedLinkError. what am i doing wrong? i have the libraries in mi jniLibs file. u chosed only one librari arm64-v8. i downloaded de libraries from here: https://github.com/k2-fsa/sherpa-onnx/releases/download/v1.9.0/sherpa-onnx-v1.9.0-android.tar.bz2. i have the code exactly like the sample app i am using the model [vits-coqui-de-css10.tar.bz2](https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-coqui-de-css10.tar.bz2):

import android.content.Context
import android.content.res.AssetManager
import android.media.AudioAttributes
import android.media.AudioFormat
import android.media.AudioTrack
import android.media.AudioManager
import android.media.MediaPlayer

data class OfflineTtsVitsModelConfig(
    var model: String,
    var lexicon: String = "",
    var tokens: String,
    var dataDir: String = "",
    var noiseScale: Float = 0.667f,
    var noiseScaleW: Float = 0.8f,
    var lengthScale: Float = 1.0f,
)

data class OfflineTtsModelConfig(
    var vits: OfflineTtsVitsModelConfig,
    var numThreads: Int = 1,
    var debug: Boolean = false,
    var provider: String = "cpu",
)

data class OfflineTtsConfig(
    var model: OfflineTtsModelConfig,
    var ruleFsts: String = "",
    var maxNumSentences: Int = 1,
)

class GeneratedAudio(
    val samples: FloatArray,
    val sampleRate: Int,
) {
    fun save(filename: String) =
        saveImpl(filename = filename, samples = samples, sampleRate = sampleRate)

    private external fun saveImpl(
        filename: String,
        samples: FloatArray,
        sampleRate: Int
    ): Boolean
}

class OfflineTts(
    assetManager: AssetManager? = null,
    var config: OfflineTtsConfig,
) {
    private var ptr: Long

    init {
        if (assetManager != null) {
            ptr = new(assetManager, config)
        } else {
            ptr = newFromFile(config)
        }
    }

    fun sampleRate() = getSampleRate(ptr)

    fun numSpeakers() = getNumSpeakers(ptr)

    fun generate(
        text: String,
        sid: Int = 0,
        speed: Float = 1.0f
    ): GeneratedAudio {
        var objArray = generateImpl(ptr, text = text, sid = sid, speed = speed)
        return GeneratedAudio(
            samples = objArray[0] as FloatArray,
            sampleRate = objArray[1] as Int
        )
    }

    fun allocate(assetManager: AssetManager? = null) {
        if (ptr == 0L) {
            if (assetManager != null) {
                ptr = new(assetManager, config)
            } else {
                ptr = newFromFile(config)
            }
        }
    }

    fun generateWithCallback(
        text: String,
        sid: Int = 0,
        speed: Float = 1.0f,
        callback: (samples: FloatArray) -> Unit
    ): GeneratedAudio {
        var objArray = generateWithCallbackImpl(ptr, text = text, sid = sid, speed = speed, callback=callback)
        return GeneratedAudio(
            samples = objArray[0] as FloatArray,
            sampleRate = objArray[1] as Int
        )
    }

    fun free() {
        if (ptr != 0L) {
            delete(ptr)
            ptr = 0
        }
    }

    protected fun finalize() {
        delete(ptr)
    }

    private external fun new(
        assetManager: AssetManager,
        config: OfflineTtsConfig,
    ): Long

    private external fun newFromFile(
        config: OfflineTtsConfig,
    ): Long

    private external fun delete(ptr: Long)
    private external fun getSampleRate(ptr: Long): Int
    private external fun getNumSpeakers(ptr: Long): Int

    // The returned array has two entries:
    //  - the first entry is an 1-D float array containing audio samples.
    //    Each sample is normalized to the range [-1, 1]
    //  - the second entry is the sample rate
    external fun generateImpl(
        ptr: Long,
        text: String,
        sid: Int = 0,
        speed: Float = 1.0f
    ): Array<Any>

    external fun generateWithCallbackImpl(
        ptr: Long,
        text: String,
        sid: Int = 0,
        speed: Float = 1.0f,
        callback: (samples: FloatArray) -> Unit
    ): Array<Any>

    fun getOfflineTtsConfig(
        modelDir: String,
        modelName: String,
        lexicon: String,
        dataDir: String,
        ruleFsts: String
    ): OfflineTtsConfig? {
        return OfflineTtsConfig(
            model = OfflineTtsModelConfig(
                vits = OfflineTtsVitsModelConfig(
                    model = "model.onnx", // Nombre de tu archivo de modelo
                    tokens = "tokens.txt", // Ubicación de tus tokens
                    lexicon = "", // Lexicon vacío, ya que no lo necesitas
                    dataDir = "", //
                ),
                numThreads = 2,
                debug = true,
                provider = "cpu",
            ),
            ruleFsts = "ruleFsts",
        )
    }
    companion object {
        init {
            System.loadLibrary("sherpa-onnx-jni")
        }
    }
}

 this is my last logcat:

 03-26 00:09:41.932  2088  2273 I DeviceStateService: event is too short, not process app: com.carapato.reading mediacodec action.
03-26 00:09:41.933  2088  2273 I DeviceStateService: event is too short, not process app: com.carapato.reading mediacodec action.
03-26 00:09:41.935 12809 12846 D BufferPoolAccessor: buffer invalidation added bp:0 1
03-26 00:09:41.935 12809 12850 D BufferPoolAccessor: buffer invalidation deleted bp:0
03-26 00:09:41.936   851  2245 D BufferPoolAccessor: buffer invalidation added bp:125 1
03-26 00:09:41.936   851  1226 D BufferPoolAccessor: buffer invalidation deleted bp:125
03-26 00:09:41.945 12809 12809 E arapato.readin: No implementation found for long com.carapato.reading.OfflineTts.new(android.content.res.AssetManager, com.carapato.reading.OfflineTtsConfig) (tried Java_com_carapato_reading_OfflineTts_new and Java_com_carapato_reading_OfflineTts_new__Landroid_content_res_AssetManager_2Lcom_carapato_reading_OfflineTtsConfig_2)
03-26 00:09:41.946 12809 12809 D AndroidRuntime: Shutting down VM
03-26 00:09:41.946 12809 12809 I QarthLog: [PatchStore] createDisableExceptionQarthFile

**Comment by csukuangfj** [comment]
Please don't change the package name of our code. That is the reason for the error.

You can use any package name for your own code.

**Comment by csukuangfj** [comment]
I suggest that you run our sample code as it is. Only after you have successfully run the sample app can you try to change it.

**Comment by carapatounfor** [comment]
thank you for your help. i am trying to do that but im a little bit confuse with the config of the model, expecially with this part : <

private fun initTts() {
        var modelDir: String?
        var modelName: String?
        var ruleFsts: String?
        var lexicon: String?
        var dataDir: String?
        var assets: AssetManager? = application.assets

        // The purpose of such a design is to make the CI test easier
        // Please see
        // https://github.com/k2-fsa/sherpa-onnx/blob/master/scripts/apk/generate-tts-apk-script.py
        modelDir = null
        modelName = null
        ruleFsts = null
        lexicon = null
        dataDir = null

        // Example 1:
        // modelDir = "vits-vctk"
        // modelName = "vits-vctk.onnx"
        // lexicon = "lexicon.txt"

        // Example 2:
        // https://github.com/k2-fsa/sherpa-onnx/releases/tag/tts-models
        // https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-en_US-amy-low.tar.bz2
        // modelDir = "vits-piper-en_US-amy-low"
        // modelName = "en_US-amy-low.onnx"
        // dataDir = "vits-piper-en_US-amy-low/espeak-ng-data"

        // Example 3:
        // modelDir = "vits-zh-aishell3"
        // modelName = "vits-aishell3.onnx"
        // ruleFsts = "vits-zh-aishell3/rule.fst"
        // lexicon = "lexicon.txt"

        if (dataDir != null) {
            val newDir = copyDataDir(modelDir)
            modelDir = newDir + "/" + modelDir
            dataDir = newDir + "/" + dataDir
            assets = null
        }

        val config = getOfflineTtsConfig(
            modelDir = modelDir!!, modelName = modelName!!, lexicon = lexicon ?: "",
            dataDir = dataDir ?: "",
            ruleFsts = ruleFsts ?: ""
        )!!

        tts = OfflineTts(assetManager = assets, config = config)
    }
> and also with this: 

fun getOfflineTtsConfig(
    modelDir: String,
    modelName: String,
    lexicon: String,
    dataDir: String,
    ruleFsts: String
): OfflineTtsConfig? {
    return OfflineTtsConfig(
        model = OfflineTtsModelConfig(
            vits = OfflineTtsVitsModelConfig(
                model = "$modelDir/$modelName",
                lexicon = "$modelDir/$lexicon",
                tokens = "$modelDir/tokens.txt",
                dataDir = "$dataDir"
            ),
            numThreads = 2,
            debug = true,
            provider = "cpu",
        ),
        ruleFsts = ruleFsts,
    )
}

**Comment by csukuangfj** [comment]
Please describe the issues you have in text.

We have documented clearly via several examples. All you need to do is to choose one example, uncomment it, and update it with your own model.

**Comment by carapatounfor** [comment]
thank you for your kindness. i know you have a lot of documentation and believe me, i`ve read it all, im trying this for 3 days but im not clear with some things. i downloaded: https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-coqui-de-css10.tar.bz2 . in this file i have tokens.txt, config.json vits-coqui.py etc... but there's no ruleFsts or lexicon.txt. i assume i have to put all this files in assets. i assume also, i have to leave ruleFsts and lexicon null, or i have to put tokens.txt in lexicon? thank you for your patience.

**Comment by csukuangfj** [comment]
Please use
```
        modelDir = "vits-coqui-de-css10"
        modelName = "model.onnx"
        lang = "deu"
```

in your selected model.

**Comment by carapatounfor** [comment]
im using the code of the app. without any change, with the same package, with the libs on assets/jniLibs, only one, as you said in https://k2-fsa.github.io/sherpa/onnx/android/build-sherpa-onnx.html i followed every step, but i still cant make it work:
 // java.lang.UnsatisfiedLinkError: No implementation found for int com.k2fsa.sherpa.onnx.OfflineTts.getSampleRate(long) (tried Java_com_k2fsa_sherpa_onnx_OfflineTts_getSampleRate and Java_com_k2fsa_sherpa_onnx_OfflineTts_getSampleRate__J)
at com.k2fsa.sherpa.onnx.OfflineTts.getSampleRate(Native Method)
at com.k2fsa.sherpa.onnx.OfflineTts.sampleRate(Tts.kt:57)
i feel like im missing something but i did all you said in your repository.

**Comment by csukuangfj** [comment]
> i downloaded de libraries from here: https://github.com/k2-fsa/sherpa-onnx/releases/download/v1.9.0/sherpa-onnx-v1.9.0-android.tar.bz2

I don't know why you choose `v1.9.0`.

Our latest release is `v1.9.14`. Have you ever tried our latest release or tried to compile the .so by yourself with the latest master?

**Comment by csukuangfj** [comment]
![Screenshot 2024-03-26 at 11 40 14](https://github.com/k2-fsa/sherpa-onnx/assets/5284924/b7261fbf-a2dc-4a51-96df-cf948014d926)


As documented, please always use the latest release.

**Comment by carapatounfor** [comment]
**FIXED**, thank you very much for your patience and knowledge, i downloaded the old version of the library, as it was in the github building sample. now i managed to put the tts running, buti have an issue, the tts speaks everything twice, and the dot pauses are incredibly long, is there any way to fix this?

**Comment by csukuangfj** [comment]
> the tts speaks everything twice

Is it reproducible with our provided APK?

**Comment by carapatounfor** [comment]
yep, i think its because of the TTS config

**Comment by csukuangfj** [comment]
Does it work as expected now?

**Comment by carapatounfor** [comment]
I'm working on it Im trying css10/es/vits model. I will try s couple of them and see if it's the model or the code. But I didn't change the code only the config I set 0.87 for speed is the only thing I changed. I will post the results.

**Comment by csukuangfj** [comment]
Note that es is for Spanish while de is for German.

You.need to set lang to
spa
if you use es.

**Comment by csukuangfj** [comment]
I have tested both the German and the Spanish model from coqui and everything works perfectly fine.

I am not sure why you get repeated voices.

You can download the pre-built APKs for Spanish and German using the following address:

- https://huggingface.co/csukuangfj/sherpa-onnx-apk/resolve/main/tts-engine/sherpa-onnx-1.9.14-armeabi-v7a-es-tts-engine-vits-coqui-es-css10.apk

- https://huggingface.co/csukuangfj/sherpa-onnx-apk/resolve/main/tts-engine/sherpa-onnx-1.9.14-armeabi-v7a-de-tts-engine-vits-coqui-de-css10.apk
