### ISSUE TITLE
[feature request] apk signing

### ISSUE THREAD

**Issue by gilcu3** [k2-fsa/sherpa-onnx#705]
I am not sure if this is the correct place to ask.

I have been using the builds from (https://k2-fsa.github.io/sherpa/onnx/tts/apk-engine.html) as a tts engine in my android phone for a while, and it is working great. One nuisance though, is that the signature used to compile apks changes with every update, which forces me to uninstall the previous version every time. Could you (or whoever compiled the apks) use the same key every time, even if it is just a debug key?

**Comment by csukuangfj** [comment]
I am using github acitons to build the APK.

Could you refer me to any doc about the signing?

**Comment by gilcu3** [comment]
> I am using github acitons to build the APK.
> 
> Could you refer me to any doc about the signing?

Thanks for the fast reply. Just by chance I know it was done recently for another project, and seems to be relatively trivial to implement. See this [commit](https://github.com/theimpulson/ReLabs/commit/da69e29281891175a09b2815e15cc9a2c7706e79).

**Comment by csukuangfj** [comment]
Thank you! I will test it tomorrow.

**Comment by csukuangfj** [comment]
Please see #710 

All TTS (engine) APKS, starting from 1.9.14 (inclusive), should be signed with the same key.

Also, they are built in `Release` mode, instead of `Debug` mode.
