### ISSUE TITLE
Huggingface demos are broken: Module.lengthBytesUTF8 is not a function

### ISSUE THREAD

**Issue by iSuslov** [k2-fsa/sherpa-onnx#721]
> Uncaught TypeError: Module.lengthBytesUTF8 is not a function
>     at initSherpaOnnxOfflineTtsVitsModelConfig (sherpa-onnx-tts.js:16:27)
>     at initSherpaOnnxOfflineTtsModelConfig (sherpa-onnx-tts.js:64:27)
>     at initSherpaOnnxOfflineTtsConfig (sherpa-onnx-tts.js:92:7)
>     at new OfflineTts (sherpa-onnx-tts.js:116:20)
>     at createOfflineTts (sherpa-onnx-tts.js:200:10)
>     at Module.onRuntimeInitialized (app-tts.js:25:9)
>     at doRun (sherpa-onnx-wasm-main-tts.js:1:118186)
>     at run (sherpa-onnx-wasm-main-tts.js:1:118346)
>     at runCaller (sherpa-onnx-wasm-main-tts.js:1:117880)
>     at Object.removeRunDependency (sherpa-onnx-wasm-main-tts.js:1:38514)

<img width="1393" alt="Screenshot 2024-03-30 at 2 02 40 AM" src="https://github.com/k2-fsa/sherpa-onnx/assets/7628774/fdaab908-743c-440f-aefb-d0107d5fa7c8">

**Comment by datkat21** [comment]
Saw this a couple weeks ago but didn't make a comment on it. This issue appears to have been introduced with a recent commit at the on the demo repository.

**Comment by csukuangfj** [comment]
Fixed in #720.

Please try it again.

**Comment by iSuslov** [comment]
@csukuangfj works well
