### ISSUE TITLE
Getting an error in this Python script: python-api-examples/online-zipformer-ctc-hlg-decode-file.py

### ISSUE THREAD

**Issue by kerolos** [k2-fsa/sherpa-onnx#736]
[python-api-examples](https://github.com/k2-fsa/sherpa-onnx/tree/master/python-api-examples)
/online-zipformer-ctc-hlg-decode-file.py

**Error:** 
python-api-examples\online-zipformer-ctc-hlg-decode-file.py", line 130, in main
    recognizer = sherpa_onnx.OnlineRecognizer.from_zipformer2_ctc(
TypeError: from_zipformer2_ctc() got an unexpected keyword argument 'ctc_graph'

**Comment by csukuangfj** [comment]
You need to use the latest master or wait until we release v1.9.16
