### ISSUE TITLE
openharmony上交叉编译onnxruntime库报错

### ISSUE THREAD

**Issue by jackwenshann** [k2-fsa/sherpa-onnx#757]
![image](https://github.com/k2-fsa/sherpa-onnx/assets/90788900/4f3ee693-0b44-4d5d-8756-54cd5de6bb70)
能否提供openharmony对应的onnxruntime 32位和64位的库

**Comment by csukuangfj** [comment]
请提供详细的log

**Comment by csukuangfj** [comment]
@jackwenshann 请问你用的 gcc 版本是什么？如何编译的 sherpa-onnx?

**Comment by csukuangfj** [comment]
请问解决了吗？
