### ISSUE TITLE
使用sherpa-onnx遇到一个奇怪的问题

### ISSUE THREAD

**Issue by AHPUymhd** [k2-fsa/sherpa-onnx#760]
![image](https://github.com/k2-fsa/sherpa-onnx/assets/72792297/c3351551-f615-4c07-9939-5f5b0d534957)
我的代码里面是将   你好军哥   转化成  n ǐ h ǎo j ūn g ē @你好军哥，但是应该在keyword_spotter = sherpa_onnx.KeywordSpotter这行代码的时候出现了错误，导致不能运行，请问这是哪里出来问题，非常期待您的回复！！！我的代码如下：
![image](https://github.com/k2-fsa/sherpa-onnx/assets/72792297/3508dadf-9706-44d3-b294-0a4155d239ed)
![image](https://github.com/k2-fsa/sherpa-onnx/assets/72792297/84986a89-db3d-42db-af2c-d81a494f5e0a)
![image](https://github.com/k2-fsa/sherpa-onnx/assets/72792297/a9a9bd45-01b2-449b-a882-3f134fd693d4)
![image](https://github.com/k2-fsa/sherpa-onnx/assets/72792297/32fe1034-4738-4893-9953-5fe114f8a391)
![image](https://github.com/k2-fsa/sherpa-onnx/assets/72792297/e9ad6526-9940-4a4a-b06e-e053d3aa7910)
![image](https://github.com/k2-fsa/sherpa-onnx/assets/72792297/02abf9a8-c020-48d4-a965-82fc02600bc7)
![image](https://github.com/k2-fsa/sherpa-onnx/assets/72792297/e62749c4-a577-42d7-a2a8-9825a98c616d)
![image](https://github.com/k2-fsa/sherpa-onnx/assets/72792297/ccf5ce7d-b629-4308-af77-cbe14414fb12)
![image](https://github.com/k2-fsa/sherpa-onnx/assets/72792297/7ec60674-6e19-4d46-bd17-40acc70e1af2)
![image](https://github.com/k2-fsa/sherpa-onnx/assets/72792297/15f7b820-5e07-4182-9258-a1060797c583)
![image](https://github.com/k2-fsa/sherpa-onnx/assets/72792297/10daf950-0a14-45d2-ac61-73130b858c41)

**Comment by AHPUymhd** [comment]
@pkufool @csukuangfj 可以麻烦您们帮我解答一下疑问吗

**Comment by AHPUymhd** [comment]
![image](https://github.com/k2-fsa/sherpa-onnx/assets/72792297/2b808bc4-7a12-4e4b-82e3-9f5a5e20f919)

**Comment by csukuangfj** [comment]
请直接贴文字代码

**Comment by csukuangfj** [comment]
```
key_file = "C:/Users/X/Documents/Tencent Files/1848795229/FileRecv/sherpa-onnx-kws-zipformer-wenetspeech-3.3M-2024-01-01/keywords_raw.txt"

```

这个文件，包含什么？请把这个文件发过来。

**Comment by csukuangfj** [comment]
你是不是应该要传 keywords.txt 而不是 keywords_raw.txt ?

**Comment by AHPUymhd** [comment]
> 你是不是应该要传 keywords.txt 而不是 keywords_raw.txt ?

结果都一样的错误

**Comment by AHPUymhd** [comment]
![image](https://github.com/k2-fsa/sherpa-onnx/assets/72792297/9d38b0c9-8828-4878-9e74-9abcd02766a9)
jiu's就是这个

> 你是不是应该要传 keywords.txt 而不是 keywords_raw.txt ?

**Comment by csukuangfj** [comment]
> > 你是不是应该要传 keywords.txt 而不是 keywords_raw.txt ?
> 
> 结果都一样的错误

不应该，请贴使用 keywords.txt 的 error log

**Comment by csukuangfj** [comment]
> ![image](https://private-user-images.githubusercontent.com/72792297/322021580-9d38b0c9-8828-4878-9e74-9abcd02766a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MzMxMTQsIm5iZiI6MTcxMjkzMjgxNCwicGF0aCI6Ii83Mjc5MjI5Ny8zMjIwMjE1ODAtOWQzOGIwYzktODgyOC00ODc4LTllNzQtOWFiY2QwMjc2NmE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDE0NDAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzZjgwNzgyZTI2YThiMDZlMDM3NjM5ZmY5ZTUyOWQwZWRkZDAzYzc2NTliODU3OTVlYjZmN2VkNGVkOWQzY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PbCvUs1K9ItcRFDLlbRlzNFPSqAymi24dhkiWT-GAb4) jiu's就是这个
> 
> > 你是不是应该要传 keywords.txt 而不是 keywords_raw.txt ?

你这个错了。不要把这个给这个 python脚本，你要用 keywords.txt, 不要用keywords_raw.txt, 我应该表述清楚了吧？

**Comment by AHPUymhd** [comment]
![image](https://github.com/k2-fsa/sherpa-onnx/assets/72792297/efc001bb-ff22-4a71-ba24-561b96327ce0)
改成了之后是这个错误

**Comment by AHPUymhd** [comment]
请问是模型没下载对吗

**Comment by csukuangfj** [comment]
你看，现在是文件名不对。不是刚次那个错误了。这种低级错误，你自己解决？

**Comment by AHPUymhd** [comment]
> 你看，现在是文件名不对。不是刚次那个错误了。这种低级错误，你自己解决？

好滴，非常谢谢您

**Comment by csukuangfj** [comment]
解决了没有呢？

**Comment by AHPUymhd** [comment]
> 解决了没有呢？

实在不好意思哈，已经解决了，非常感谢您的帮助。
