### ISSUE TITLE
Android tts, java 11, gradle 7

### ISSUE THREAD

**Issue by paps96** [k2-fsa/sherpa-onnx#767]
Hello, I would like to use this library, specifically the TTS (Text-to-Speech), in an Android project built with Java. However, since the project is configured with Java 11 and Gradle version 7 (it's a somewhat exotic project), I need the .c file to link the methods and be able to use them. Could you please assist me in constructing this file?

**Comment by csukuangfj** [comment]
Could you explain why you need a `.c` file?
We provide a `jni.cc`.

Have you followed our Android doc to build `sherpa-onnx` for Android?

**Comment by paps96** [comment]
Yes I have, and I succesfuly link the .so files (I could try tts app) , however when I tried to add the library into my project in jni.cc file there are many issues related with headers files,  Are there more documentation to link libraries (.so) files with android files (.java, .kt files) through jni.cpp file?

**Comment by csukuangfj** [comment]
If you want to use the source code from sherpa-onnx in your own project, please use
only a single header file
https://github.com/k2-fsa/sherpa-onnx/blob/master/sherpa-onnx/c-api/c-api.h

If you use any header file other than `c-api.h`, then your approach is not correct.

**Comment by paps96** [comment]
Hello, I understand how to make it work. I just needed to put 'package com.k2fsa.sherpa.onnx' at the top of Tts.kt and TtsEngine.kt. Additionally, I couldn't install it on my project with Java 11 and Gradle 7; I had to upgrade to Java 17 and Gradle 8.2. In the end, I was able to use this project with Java through Kotlin interoperability.  Thanks for your support.
