### ISSUE TITLE
output scores for speaker identification

### ISSUE THREAD

**Issue by chiiyeh** [k2-fsa/sherpa-onnx#769]
Hi! I tried the speaker identification using the python code and it works great! Am wondering if it can be modified to output the match scores as well or the highest score. This can help with debugging why some speakers are not identified and aid with setting a suitable threshold for use as well.

**Comment by csukuangfj** [comment]
Yes, it is possible. Would you mind contributing?

**Comment by chiiyeh** [comment]
Hi, I don't mind contributing. No very familiar with it though, can I just change the output to a tuple instead of string which it is outputting now?

**Comment by csukuangfj** [comment]
You can find the PR that added speaker recognition functions to sherpa-onnx at
https://github.com/k2-fsa/sherpa-onnx/pull/516


>  can I just change the output to a tuple instead of string 

Yes, it is doable. I suggest that you keep the current API unchanged and add a new API for your need.
