### ISSUE TITLE
is there any plan to support offline zipformer in sherpa-onnx?

### ISSUE THREAD

**Issue by beyond-boy** [k2-fsa/sherpa-onnx#79]

**Comment by csukuangfj** [comment]
Yes, that is in the plan.

Would you like to make contributions?

**Comment by beyond-boy** [comment]
> 
Is there any example for reference to do this?

>

**Comment by EmreOzkose** [comment]
I think zipformer models can be replaced with conformer model. It should work without any effort.

**Comment by EmreOzkose** [comment]
[Zipformer input/outputs](https://github.com/k2-fsa/icefall/blob/8aaa9761e46c6d71e63096160ddee0197f64a5ff/egs/librispeech/ASR/pruned_transducer_stateless7/export-onnx.py#L278) and [Conformer input/outputs](https://github.com/k2-fsa/icefall/blob/8aaa9761e46c6d71e63096160ddee0197f64a5ff/egs/librispeech/ASR/pruned_transducer_stateless3/export-onnx.py#L260) are same. So, only changing path should work.

**Comment by beyond-boy** [comment]
> [Zipformer input/outputs](https://github.com/k2-fsa/icefall/blob/8aaa9761e46c6d71e63096160ddee0197f64a5ff/egs/librispeech/ASR/pruned_transducer_stateless7/export-onnx.py#L278) and [Conformer input/outputs](https://github.com/k2-fsa/icefall/blob/8aaa9761e46c6d71e63096160ddee0197f64a5ff/egs/librispeech/ASR/pruned_transducer_stateless3/export-onnx.py#L260) are same. So, only changing path should work.
not the export work, this is easy and have already done in the open source icefall repo,
my question is to do offline decode use c++ in sherpa-onnx?

**Comment by beyond-boy** [comment]
not the export work, this is easy and have already done in the open source icefall repo,
my question is how to do offline decode use c++ in sherpa-onnx?  Is there any example for reference to do this?

**Comment by csukuangfj** [comment]
The reference implementation is in `k2-fsa/sherpa`.

If you have read the code, you can see that the streaming decoding code of `k2-fsa/sherpa-onnx` is very similar to that from `k2-fsa/sherpa`.
