### ISSUE TITLE
Lowercase transformation sherpa-onnx-microphone is not compatible with UTF-8

### ISSUE THREAD

**Issue by daniel-dona** [k2-fsa/sherpa-onnx#791]
I'm training a Spanish model and looks like `sherpa-onnx-microphone` (maybe other executables too) prints words in lowercase, but It does not work correctly for some Spanish letters (Ñ, Á, É, Í, Ó, Ú, Ü).

```
$ ./sherpa-onnx-microphone --encoder=[...]

Num devices: 16
Use default device: 15
  Name: default
  Max input channels: 32
Started
0:  toman el nÚmero uno y doplica lo obtienen dos
```

Ex: `nÚmero` should be `número`

I think the problem is here:
https://github.com/k2-fsa/sherpa-onnx/blob/d97a283dbb124b97f7560026f5db8490baa76f04/sherpa-onnx/csrc/sherpa-onnx-microphone.cc#L164C1-L164C62

Tried setting the locale, but I see no change.

```
$ locale
LANG=es_ES.UTF-8
LANGUAGE=es_ES
LC_CTYPE="es_ES.UTF-8"
LC_NUMERIC="es_ES.UTF-8"
LC_TIME="es_ES.UTF-8"
LC_COLLATE="es_ES.UTF-8"
LC_MONETARY="es_ES.UTF-8"
LC_MESSAGES="es_ES.UTF-8"
LC_PAPER="es_ES.UTF-8"
LC_NAME="es_ES.UTF-8"
LC_ADDRESS="es_ES.UTF-8"
LC_TELEPHONE="es_ES.UTF-8"
LC_MEASUREMENT="es_ES.UTF-8"
LC_IDENTIFICATION="es_ES.UTF-8"
LC_ALL=es_ES.UTF-8
```

**Comment by csukuangfj** [comment]
Could you change them in your tokens.txt?

You can convert them in advance in your tokens.txt to lowercase

**Comment by daniel-dona** [comment]
> Could you change them in your tokens.txt?
> 
> You can convert them in advance in your tokens.txt to lowercase

Sure, I mean is not really a problem for me, just looked a bit strange... I can also try to make the change to handle UTF-8 transformation and create a PR if you're interested

**Comment by csukuangfj** [comment]
>  I can also try to make the change to handle UTF-8 transformation and create a PR if you're interested

Thanks! That would be great. I think we need such a function.
