### ISSUE TITLE
hello, how to export the projection onnx?

### ISSUE THREAD

**Issue by jinfagang** [k2-fsa/sherpa-onnx#8]
From the export, I didn't find how to export the projection onnx as well?

**Comment by EmreOzkose** [comment]
PR is [here](https://github.com/k2-fsa/icefall/pull/584), but not been merged yet since I didn't have time to do some changes (about testing and inference scripts). However, you can use the [export script](https://github.com/EmreOzkose/icefall/blob/onnx_proj_exports/egs/librispeech/ASR/pruned_transducer_stateless3/export.py) for now.

**Comment by jinfagang** [comment]
@EmreOzkose Hi, I only found these onnx were exported, didn't find encoder_proj.onnx or decoder_proj.onnx.

<img width="187" alt="image" src="https://user-images.githubusercontent.com/21303438/192673922-e9a7762b-09f3-4d8d-aa51-9d92f22ebb4a.png">

which needed by your onnx c++ inference code.

<img width="343" alt="image" src="https://user-images.githubusercontent.com/21303438/192673994-9434aaab-df40-4afb-8983-20c7844a8da5.png">


I have 2 questions:

1. the export didn't aligned with your inference code, how to resolve it?
2. you have a all_in_one model, in my opinion, this is useless, since we using encoder and decoder to inference, how didi u using it?

**Comment by csukuangfj** [comment]
What have you done and what are the  error messages?

**Comment by EmreOzkose** [comment]
Hi @jinfagang , I am updating PR now. You can use [export script](https://github.com/EmreOzkose/icefall/blob/onnx_proj_exports/egs/librispeech/ASR/pruned_transducer_stateless3/export.py)

> 1. the export didn't aligned with your inference code, how to resolve it?

Export script is updated.

> 2. you have a all_in_one model, in my opinion, this is useless, since we using encoder and decoder to inference, how didi u using it?

Initially, the aim was to combine all parts into one .onnx like model.pt. There is [a branch which uses only all-in-one.onnx to decode](https://github.com/EmreOzkose/sherpa/tree/onnx/sherpa/bin/pruned_transducer_statelessX). It is written in Python. This repo uses Onnxruntime without dependency on Libtorch and I couldn't extract each model (encoder, decoder, etc..) internally. Hence models are given separately for now.

**Comment by jinfagang** [comment]
@EmreOzkose thanks. now i can get proj model as well.

the all in on infefrence, from I can see: https://github.com/EmreOzkose/sherpa/blob/887ddd0924cf5c4216a8671c39b04e8e8371356d/sherpa/bin/pruned_transducer_statelessX/offline_asr.py#L298 

this still using model's decoder when greedysearch. This is not convenient on onnxruntime.

**Comment by jinfagang** [comment]
Oh, I get it. Will this also port to c++ as well?

**Comment by EmreOzkose** [comment]
This repo contains the first working version, but I have to do refactoring (adding OfflineASR, OfflineRecognizer, etc..). I am planning to do it in a few days.

**Comment by csukuangfj** [comment]
Please use
https://github.com/k2-fsa/icefall/blob/master/egs/wenetspeech/ASR/pruned_transducer_stateless2/export.py
to export Chinese models.
