### ISSUE TITLE
Encrypt/decrypt sherpa-onnx models

### ISSUE THREAD

**Issue by anita-smith1** [k2-fsa/sherpa-onnx#808]
We built an android tts sherpa onnx model for a client and they want me to encrypt the model, so the voice (celebrity of some sort) which was used to fine tune the model won't be used to cause harm. How can I encrypt and decrypt sherpa onnx models. During conversion from standard onnx to sherpa onnx, there is no mechanism for encryption. Can you add this feature? if there is can you point me in the direction?

**Comment by csukuangfj** [comment]
We use srandard onnx models.

Please search with Google for that.

**Comment by anita-smith1** [comment]
Okay thanks
