### ISSUE TITLE
VS2022 使用静态库编译MFC例程成功，使用动态库编译失败

### ISSUE THREAD

**Issue by kyn817046** [k2-fsa/sherpa-onnx#839]
包含目录和库目录填写正确；
附加依赖库填写正确；
运行库选择多线程DLL

运行报错：
严重性	代码	说明	项目	文件	行	禁止显示状态	详细信息
错误	LNK1107	文件无效或损坏: 无法在 0x2F0 处读取	speech_recognition	E:\workspace\kaldi_mc\speech_rec\sherpa-onnx-v1.9.23-win-x64-shared\lib\cargs.dll	1		
![image](https://github.com/k2-fsa/sherpa-onnx/assets/121105502/9027841d-b351-4e65-ab41-b9da3bffc7cd)

**Comment by kyn817046** [comment]
![image](https://github.com/k2-fsa/sherpa-onnx/assets/121105502/306effa4-6201-40b8-b22c-911e37014543)
不管哪个放前面，最前面的dll都会报错无法读取

**Comment by csukuangfj** [comment]
> 无法在 0x2F0 处读取 speech_recognition E:\workspace\kaldi_mc\speech_rec\sherpa-onnx-v1.9.23-win-x64-shared\lib\cargs.dll 1

不需要 cargs.dll

请删掉这个依赖，然后重试

**Comment by kyn817046** [comment]
![image](https://github.com/k2-fsa/sherpa-onnx/assets/121105502/3b0180a1-401a-4187-8a50-b1a7f07c5314)
还是报错：
严重性	代码	说明	项目	文件	行	禁止显示状态	详细信息
错误	LNK1107	文件无效或损坏: 无法在 0x308 处读取	speech_recognition	E:\workspace\kaldi_mc\speech_rec\sherpa-onnx-v1.9.23-win-x64-shared\lib\sherpa-onnx-portaudio.dll	1

**Comment by kyn817046** [comment]
> ![image](https://private-user-images.githubusercontent.com/121105502/328364556-306effa4-6201-40b8-b22c-911e37014543.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNTE0MTksIm5iZiI6MTcxNTA1MTExOSwicGF0aCI6Ii8xMjExMDU1MDIvMzI4MzY0NTU2LTMwNmVmZmE0LTYyMDEtNDBiOC1iMjJjLTkxMWUzNzAxNDU0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QwMzA1MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzU3NTM2Yjk4NDU5ZjIzM2NmNTA5Mjc0NDYzNmM1NTJhNDBlMTlkMTAwNmNhMTg2NjUxYjY3OTkzNzdkMjBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AMcSLIs2KfXH2aAqmZZAGsAksp8qV7DJr0MQq6am6LY) 不管哪个放前面，最前面的dll都会报错无法读取

不管哪个dll放最前面，都会报错最前面这个dll无法读取

**Comment by kyn817046** [comment]
不管哪个dll放在最前面，都会报错最前面这个dll无法读取

**Comment by csukuangfj** [comment]
你电脑上，有这个 dll 文件吗？截个图我看看？

**Comment by kyn817046** [comment]
> 你电脑上，有这个 dll 文件吗？截个图我看看？

![image](https://github.com/k2-fsa/sherpa-onnx/assets/121105502/684c47ac-f7d7-4403-95f3-180d6bd63d0d)
链接到这里的

**Comment by csukuangfj** [comment]
如何在 vs 里添加的 dll 文件？

**Comment by kyn817046** [comment]
> 如何在 vs 里添加的 dll 文件？
![image](https://github.com/k2-fsa/sherpa-onnx/assets/121105502/bd326a75-49d5-44c3-bf6c-c06ba722f74f)

**Comment by csukuangfj** [comment]
为什么两个截图里的 dll, 所在的位置不一样

**Comment by kyn817046** [comment]
重新解压了再放进来好了，之前解压可能哪有问题
