### ISSUE TITLE
TTS WebAssembly for other languages not work

### ISSUE THREAD

**Issue by kmpartner** [k2-fsa/sherpa-onnx#846]
I tried to follow the instruction to build text-to-speech with WebAssembly.
https://k2-fsa.github.io/sherpa/onnx/tts/wasm/index.html
When I used English language as in instruction. It worked well.

But when I tried to use some models for different languages.
https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-de_DE-mls-medium.tar.bz2

It did not generate correct audio voices.
(in the case of single speaker model, it seems to work, but for multiple speakers not work well)

How can I solve this problem?

**Comment by csukuangfj** [comment]
Please tell us what you have done with the German tts model.

For "not work well", could you describe in detail what it means?

**Comment by kmpartner** [comment]
Thank you for reply.
I just followed documentation page (https://k2-fsa.github.io/sherpa/onnx/tts/wasm/build.html) by changing wget URL and moving, copy file name according to downloaded file.

Page was successfully displayed, but when I tried to create German voice, it create strange voice in all Speaker ID I tested (5~6 different ID).

**Comment by csukuangfj** [comment]
> by changing URL for wget

Could you describe it in detail what you have done?

**Comment by kmpartner** [comment]
I tried wget and manually download from models list.
wget -q https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-de_DE-mls-medium.tar.bz2

extract downloaded folder
copy .onnx, tokens, and espeak-ng-data to asset folder
and change .onnx file name to model.onnx.

delete old contents in build-wasm-simd-tts folder

run 
build-wasm-simd-tts.sh

test page

generated voice length is very long (~20 second) and strange from "Heute ist ein guter Tag. Gestern war ein guter Tag.".

**Comment by csukuangfj** [comment]
Could you switch to another German model?

I just tested it and found that the model cannot produce correct speech. I am deleting it.

**Comment by csukuangfj** [comment]
By the way, you can try all German tts models at
https://huggingface.co/spaces/k2-fsa/text-to-speech

<img width="1048" alt="Screenshot 2024-05-12 at 12 06 57" src="https://github.com/k2-fsa/sherpa-onnx/assets/5284924/bb6a5b90-29ff-4f22-988f-24174a303c65">

**Comment by kmpartner** [comment]
That is no problem. I am testing it. 
But I want to know why in English case multi-speakers model works, and not works in other languages (I tested French multi-speakers model as well, and it generates strange voices).  Which files are wrong to produce strange voices?

**Comment by csukuangfj** [comment]
> I tested French multi-speakers model as well, and it generates strange voices

Please tell us the exact model you are using.

please first test the model at
https://huggingface.co/spaces/k2-fsa/text-to-speech

**Comment by kmpartner** [comment]
I don't remember well, but I think model was
https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-piper-fr_FR-mls-medium.tar.bz2

It is possible that vits-piper models that contain "mls(-medium)" not work well in different languages as well.

**Comment by csukuangfj** [comment]
I suggest that you don't use any model including `mls` in its name. I am deleting this model from sherpa-onnx.

**Comment by woheller69** [comment]
I also tried ```mls``` for Dutch and German. They work, but only for the first generation. When the input is modified they return nonsense

**Comment by csukuangfj** [comment]
we have deleted models containing mls in the name.
