### ISSUE TITLE
Export Time Info.

### ISSUE THREAD

**Issue by wukonggeo** [k2-fsa/sherpa-onnx#863]
When I use python to run  the democode, how to output the time range corresponding to each sentence when outputting audio?
@csukuangfj

**Comment by csukuangfj** [comment]
Please see
https://github.com/k2-fsa/sherpa-onnx/blob/master/python-api-examples/generate-subtitles.py

You can generate subtitles, which contain both time and text.

**Comment by wukonggeo** [comment]
Thank you very much for your reply. This code is too complex for simple text-speech-generation. I decided to split the text into several sentences and used pydub to calculate time length.
