### ISSUE TITLE
说话人识别繁体字问题

### ISSUE THREAD

**Issue by 20246688** [k2-fsa/sherpa-onnx#869]
配置：win10
bat文件：
@echo off
CHCP 65001
set PYTHONIOENCODING=utf-8
python test.py ^
  --silero-vad-model=./sherpa-onnx/silero_vad.onnx ^
  --threshold=0.2 ^
  --model=./sherpa-onnx/3dspeaker_speech_eres2net_large_sv_zh-cn_3dspeaker_16k.onnx ^
  --speaker-file=./speaker.txt
echo ok
pause

speaker.txt
Jack ./wav-library/ai-jack-1.wav
Jack ./wav-library/ai-jack-2.wav
Jack ./wav-library/ai-jack-3.wav
lulu ./wav-library/ai-lulu-1.wav
lulu ./wav-library/ai-lulu-2.wav
lulu ./wav-library/ai-lulu-3.wav
中文 ./wav-library/ce-1.wav
中文 ./wav-library/ce-2.wav
中文 ./wav-library/ce-3.wav

请问输出的时候为什么是繁体字

**Comment by 20246688** [comment]
def load_speaker_file(args) -> Dict[str, List[str]]:
    if not Path(args.speaker_file).is_file():
        raise ValueError(f"--speaker-file {args.speaker_file} does not exist")

    ans = defaultdict(list)
    with open(args.speaker_file, encoding='utf-8') as f:   已解决，谢谢！

**Comment by csukuangfj** [comment]
请截个图，哪里有繁体字？

**Comment by 20246688** [comment]
非常抱歉，我目前已修改了代码，复现不了之前的问题了，但问题可以通过修改sherpa-onnx\python-api-examples\speaker-identification-with-vad.py里面的def load_speaker_file(args) -> Dict[str, List[str]]:里的with open(args.speaker_file, encoding='utf-8') as f，应该是Win10操作系统或者bat文件的读编码习惯的问题，演示视频应该是在Linux使用的。

**Comment by csukuangfj** [comment]
ok, 那这个 issue, 可以关了么

**Comment by 20246688** [comment]
嗯嗯
