### ISSUE TITLE
What is the difference between running silero-vad with sherpa-onnx compared to the original onnxruntime 

### ISSUE THREAD

**Issue by tkyin17** [k2-fsa/sherpa-onnx#884]
* What are the key differences between running models and processes with sherpa-onnx compared to the toriginal onnxruntime?
* Specifically for silero-vad, are there any differences as well?

**Comment by csukuangfj** [comment]
We provide an easier interface to silero-vad.

We support running silero-vad on Android, iOS, Linux, macOS, Windows, Raspberry Pi, etc.

We also provide C++, C, Python, C#, Java, JavaScript, Kotlin, Swift, Go APIs for it.

Furthermore, we also show how to uses it with ASR.

**Comment by tkyin17** [comment]
@csukuangfj Thank you for your explanation. What should I do if I want to ask questions about different areas? I think opening many issues just for questions is probably not a good idea.

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/sherpa-onnx/tree/master/ios-swiftui%2FSherpaOnnxSubtitle
