### ISSUE TITLE
如何安装cpp-api

### ISSUE THREAD

**Issue by Mactarvish** [k2-fsa/sherpa-onnx#891]
执行install之后得到的是c-api，但是我想要cpp风格的api  如何安装cpp-api

**Comment by csukuangfj** [comment]
目前没有单独的 cpp-api.h

如果你想用 cpp-api.h, 你需要参考我们的 sherpa-onnx.cc 如何写的，用我们的 CMakeLists.txt, 把你的代码加进来。

---

欢迎贡献 cpp-api.h 和 cpp-api.cc

**Comment by Mactarvish** [comment]
好，有时间整一套
