### ISSUE TITLE
Unable to run the SherpaOnnx2Pass android example project

### ISSUE THREAD

**Issue by l3utterfly** [k2-fsa/sherpa-onnx#892]
I've downloaded the necessary models and configured the path for the 2pass example. I get this error in logcat: `Read binary file: Load /data/user/0/com.k2fsa.sherpa.onnx/files/sherpa-onnx-streaming-zipformer-en-2023-06-26/encoder-epoch-99-avg-1-chunk-16-left-128.int8.onnx failed`

Where should I copy the file to? I've copied the file to the app's private directory and still get this error. How should I modify the "modelDir"?

**Comment by csukuangfj** [comment]
please copy the model dir to your assets dir inside Android Studio

**Comment by l3utterfly** [comment]
Is it possible to load the model from my storage instead of the asset directory?

**Comment by csukuangfj** [comment]
> Is it possible to load the model from my storage instead of the asset directory?

yes, you need to read the code to find out how to do that.

**Comment by l3utterfly** [comment]
I have figured it out, thank you!
