### ISSUE TITLE
Obtaining Encoder Features

### ISSUE THREAD

**Issue by magacc1** [k2-fsa/sherpa-onnx#893]
I'm looking to use some of the pretrained speech recognizers and compute their encoder output features in real-time.

When I'm looking at the API of _Recognizer / _sherpa_onnx.OnlineRecognizer as defined [here](https://github.com/k2-fsa/sherpa-onnx/blob/8af2af84664d3285ba452bf453bb928a3eb6e978/sherpa-onnx/python/sherpa_onnx/online_recognizer.py#L12)

I see only the following methods, and cannot find a way to get access to specifically compute the encoder outputs:
 'create_stream',
 'decode_stream',
 'decode_streams',
 'get_result',
 'is_endpoint',
 'is_ready',
 'reset'
 
Can anyone help provide pointers on how to get the encoder features, or find the code underneath decode_stream and break it down to compute the encoder results?

Thanks!

**Comment by csukuangfj** [comment]
We don't provide such an API as general users don't need it.

> Can anyone help provide pointers on how to get the encoder features

For the online transducers, you can take a look at
https://github.com/k2-fsa/sherpa-onnx/blob/8af2af84664d3285ba452bf453bb928a3eb6e978/sherpa-onnx/csrc/online-recognizer-transducer-impl.h#L224-L225

**Comment by magacc1** [comment]
Thanks Fangjun!
