### ISSUE TITLE
How to use android NNAPI?

### ISSUE THREAD

**Issue by l3utterfly** [k2-fsa/sherpa-onnx#895]
I see in the build arm64_v8a script it has: `# Please use -DANDROID_PLATFORM=android-27 if you want to use Android NNAPI`

Do the ASR and TTS APIs use the Android NNAPI by default if it's compiled with android-27? Or do I need to pass in some config/flag to enable this?

**Comment by csukuangfj** [comment]
> Do the ASR and TTS APIs use the Android NNAPI by default if it's compiled with android-27?

No.

> Or do I need to pass in some config/flag to enable this?

Yes.

---

The steps are:

1. Change
https://github.com/k2-fsa/sherpa-onnx/blob/49ee458bfb8dbd68a48c8a78b5cef9a893e65e22/build-android-arm64-v8a.sh#L87

You need to replace `21` with `27` or greater.

2. For ASR, you need to change
https://github.com/k2-fsa/sherpa-onnx/blob/49ee458bfb8dbd68a48c8a78b5cef9a893e65e22/sherpa-onnx/kotlin-api/OnlineRecognizer.kt#L44

by replacing `cpu` with `nnapi`.

For TTS and other tasks you need to do the same thing as ASR. (I think you have got the ideas.)
