### ISSUE TITLE
whisper offline subscribe error "Name:'/Expand' Status Message: invalid expand shape"

### ISSUE THREAD

**Issue by clockfly** [k2-fsa/sherpa-onnx#896]
Using model: sherpa-onnx-whisper-tiny.tar.bz2
Using example:  https://github.com/k2-fsa/sherpa-onnx/blob/master/go-api-examples/non-streaming-decode-files/main.go

Error:
```
/Users/runner/work/sherpa-onnx/sherpa-onnx/sherpa-onnx/csrc/offline-recognizer-whisper-impl.h:DecodeStream:113 Only waves less than 30 seconds are supported. We process only the first 30 seconds and discard the remaining data
/Users/runner/work/sherpa-onnx/sherpa-onnx/sherpa-onnx/csrc/offline-recognizer-whisper-impl.h:DecodeStream:160 

Caught exception:

Non-zero status code returned while running Expand node. Name:'/Expand' Status Message: invalid expand shape

Return an empty result. Number of input frames: 2950, Current tail paddings: 1000. If you see a lot of such exceptions, please consider using a larger --whisper-tail-paddings
2024/05/21 10:02:16 Decoding done!

```

Audio is attached.
[videoplayback.mp4.2048806673.wav.zip](https://github.com/k2-fsa/sherpa-onnx/files/15383494/videoplayback.mp4.2048806673.wav.zip)

**Comment by csukuangfj** [comment]
please tell us what you have done after reading the logs.

**Comment by clockfly** [comment]
PS: FP16 model works fine. INT8 onnx model not working.

**Comment by csukuangfj** [comment]
please tell us what you have done after reading the logs.

**Comment by clockfly** [comment]
Nothing. Bascially following the example: https://github.com/k2-fsa/sherpa-onnx/blob/master/go-api-examples/non-streaming-decode-files/main.go

nothing more.

**Comment by csukuangfj** [comment]
please read the log carefully:

Return an empty result. Number of input frames: 2950, Current tail paddings: 1000. If you see a lot of such exceptions, please consider using a larger --whisper-tail-paddings

**Comment by csukuangfj** [comment]
Please see
https://github.com/k2-fsa/sherpa-onnx/blob/fdcae56a1463695a68cec05349a10036f0622b21/go-api-examples/non-streaming-decode-files/main.go#L34

You need to update your sherpa-onnx-go.

**Comment by clockfly** [comment]
Thanks.

**Comment by taox142** [comment]
@clockfly Hello, have you sovled this issue? I came cross the same issue. But I am using python.

**Comment by csukuangfj** [comment]
> [@clockfly](https://github.com/clockfly) Hello, have you sovled this issue? I came cross the same issue. But I am using python.

Can you share commands and test wave for reproducing?
