### ISSUE TITLE
请问sherpa-onnx和sherpa-ncnn分别有哪些优劣势？

### ISSUE THREAD

**Issue by zhanweiw** [k2-fsa/sherpa-onnx#912]
请问sherpa-onnx和sherpa-ncnn分别有哪些优劣势？
这两个项目有没有稍详细的区别介绍？比如性能对比什么的。
我们应该如何选择？

**Comment by csukuangfj** [comment]
请看
https://k2-fsa.github.io/sherpa/intro.html

**Comment by zhanweiw** [comment]
非常感谢！这个连接里边的内容我是看过的。想了解一下在Windows上使用的话，性能和精度，这两者有什么区别？应该如何选择。

**Comment by csukuangfj** [comment]
模型都是来自 icefall, 理论上，精度都是一样的。

都是我们维护的。我们都建议用。你想用哪个，就用哪个。
