### ISSUE TITLE
请问microphone-offline和microphone有什么区别？

### ISSUE THREAD

**Issue by zhanweiw** [k2-fsa/sherpa-onnx#913]
请问如下两个程序从结果上来说，有什么区别？也就是说，offline和online有什么区别？
sherpa-onnx-microphone-offline.exe
sherpa-onnx-microphone.exe

**Comment by csukuangfj** [comment]
加 offline 的，只能和 非流式模型用。

没加的，只能和流式模型用.

不能混用，否则会报错。

请看这里
https://k2-fsa.github.io/sherpa/onnx/faqs/index.html#id1

**Comment by zhanweiw** [comment]
明白。谢谢！
