### ISSUE TITLE
请问如果想通过语音下发命令，应该怎么做？

### ISSUE THREAD

**Issue by zhanweiw** [k2-fsa/sherpa-onnx#918]
比如我想通过语音下发命令给机器人：要求一句话说完后，能够及时检测到，并把这个句子作为一个命令。问题是怎么知道一句话说完了(检测到声音中间的停顿)？
不知道是否可以做到这一点？如何做？
谢谢啦！

**Comment by csukuangfj** [comment]
请看我们 B 站的视频。给每一句话的前面加标号, 0, 1, 2, 等等。

文档里有 endpointing.

建议你先看文档，按照文档，去跑流式模型。 如果你有去跑过，你应该就知道了。

**Comment by zhanweiw** [comment]
感谢这么晚还给回复。我继续研究看看。

**Comment by csukuangfj** [comment]
> 感谢这么晚还给回复。我继续研究看看。

请动手去跑。不想动手的话，可以去看我们b站的演示视频

**Comment by zhanweiw** [comment]
@csukuangfj 还有个问题请教：流式模型的识别率是不是没有非流式的识别率高？有什么办法既能断句，又能有非流式模型的高识别率吗？

**Comment by csukuangfj** [comment]
其实，我们视频里有的，你前面加个vad就好了。

**Comment by zhanweiw** [comment]
昨天早些时候试过下边的脚本，效果似乎不太好，我今天再试试看：
python sherpa-onnx\python-api-examples\vad-with-non-streaming-asr.py --tokens=./sherpa-onnx-paraformer-zh-2024-03-09/tokens.txt --paraformer=./sherpa-onnx-paraformer-zh-2024-03-09/model.onnx --silero-vad-model=silero_vad.onnx

**Comment by zhanweiw** [comment]
@csukuangfj 刚才又试了一下，效果还可以，但遇到和昨天一样的问题，问几个问题后会卡死，再问问题就没反应了。

**Comment by csukuangfj** [comment]
请详细描述你的测试环境，完整的测试命令及测试结果

**Comment by csukuangfj** [comment]
已通过qq群解决。
