### ISSUE TITLE
请问Sherpa_ONNX框架下的ASR模型的output是如何与tokens.txt中的文字对应起来的呢？

### ISSUE THREAD

**Issue by zihanyue** [k2-fsa/sherpa-onnx#922]
新手提问，在Sherpa_ONNX框架下，ASR模型的output应该是一个二维数组（如果没错的话），那么这个output是如何与tokens.txt中的文字对应起来的呢？谢谢！

我现在用的模型是sherpa-onnx-paraformer-zh-small-2024-03-09

**Comment by zihanyue** [comment]
我现在用的模型是sherpa-onnx-paraformer-zh-small-2024-03-09

**Comment by csukuangfj** [comment]
请自行查看解码的代码。最后是一个1-d 的数组。
