### ISSUE TITLE
Words are being ignored with message `ConvertTextToTokenIdsNotChinese`

### ISSUE THREAD

**Issue by corani** [k2-fsa/sherpa-onnx#929]
I'm trying the `go-api-examples/non-streaming-tts` example with some of my own texts, and its dropping a number of words with the message:

`/project/sherpa-onnx/csrc/lexicon.cc:ConvertTextToTokenIdsNotChinese:333 OOV {some word}. Ignore it!`

Using the same models (vits-ljs and vits-vctk) with https://github.com/coqui-ai/TTS works fine, so I don't think it's a problem with the model.

**Comment by csukuangfj** [comment]
which model are you using and what words do you give to the model?

**Comment by wukonggeo** [comment]
@csukuangfj 
when l use vits-vctk model, the same error appeared,  the error log in the following img.
![Uploading error_log.png…]()

**Comment by csukuangfj** [comment]
都乱码了。请参考文档里的FAQs,设置utf8编码。或者，别用Windows

**Comment by wukonggeo** [comment]
@csukuangfj , It's not the system encoding issue。
Some test sentence, the bold words was missing.
1.Or change planning **frameworks** to set road.      
2. we must take action in the post-**2020**. 
3. Order the books in your **timeframes**.
![error_log2](https://github.com/k2-fsa/sherpa-onnx/assets/140490295/f9a43554-f78e-4789-9c6a-b53c352e0919)

**Comment by csukuangfj** [comment]
I suggest that you use a tts model from piper that uses espeak-ng as the phonemizer
or
use a character-based tts model
or
add the OOV to your lexicon.txt

(Think that there are many many many English words. If a lexicon.txt is used, only words in the lexicon.txt can be recognized)

**Comment by wukonggeo** [comment]
Thank you for your reply，these missing words are not in the model dictionary, so it can't decode.

**Comment by csukuangfj** [comment]
Closing as the behavior is expected.

The lexicon.txt is impossible to include every word.

Please see the comment at https://github.com/k2-fsa/sherpa-onnx/issues/929?notification_referrer_id=NT_kwDOAFCkPLMxMDg0MDQ5NTMxMzo1Mjg0OTI0#issuecomment-2160376990

**Comment by csukuangfj** [comment]
By the way, we support more than 100 tts models from piper.
please see
https://github.com/k2-fsa/sherpa-onnx/releases/tag/tts-models

If you use piper, you won't have OOV issues any more.

**Comment by wukonggeo** [comment]
Thank you very much, I will try these model in Piper.

**Comment by corani** [comment]
Thanks, using [vits-coqui-en-vctk.tar.bz2](https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-coqui-en-vctk.tar.bz2) instead of [vits-vctk.tar.bz2](https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-vctk.tar.bz2) indeed works fine (piper models work as well).

**Comment by wukonggeo** [comment]
@corani Thank you very much,I will try it.
