### ISSUE TITLE
sherpa_onnx.Display have some bug in windows11

### ISSUE THREAD

**Issue by dongqianzhuan** [k2-fsa/sherpa-onnx#93]
when i run python example in windows x64 with vscode

the terminal output is not nornal work

i think sherpa_onnx.Display have some bug

i add the output with print

'
                print("print:： "+ last_result)
                display.print(-1, result)
'
it is normal work

the python code is download from 

https://github.com/k2-fsa/sherpa-onnx/blob/master/python-api-examples/speech-recognition-from-microphone.py

the package is from  pip install sherpa-onnx

print:： 你
浣
print:： 你好
浣犲ソ
print:： 你好啊
浣犲ソ鍟
print:： 你好啊今天天
浣犲ソ鍟婁粖澶╁ぉ
print:： 你好啊今天天气
浣犲ソ鍟婁粖澶╁ぉ姘
print:： 你好啊今天天气真不错
浣犲ソ鍟婁粖澶╁ぉ姘旂湡涓嶉敊
print:： 你好啊今天天气真不错 HELLO
浣犲ソ鍟婁粖澶╁ぉ姘旂湡涓嶉敊 HELLO
print:： 你好啊今天天气真不错 HELLO WHATS YOUR
浣犲ソ鍟婁粖澶╁ぉ姘旂湡涓嶉敊 HELLO WHATS YOUR
print:： 你好啊今天天气真不错 HELLO WHATS YOUR NAME
浣犲ソ鍟婁粖澶╁ぉ姘旂湡涓嶉敊 HELLO WHATS YOUR NAME

**Comment by csukuangfj** [comment]
Could you please have a look at the doc

https://k2-fsa.github.io/sherpa/onnx/pretrained_models/zipformer-transducer-models.html#id2

Basically, you have to run the following command in your terminal 

CHCP 65001

**Comment by dongqianzhuan** [comment]
thank you~ it is useful!
