### ISSUE TITLE
Does not support long audio inference？

### ISSUE THREAD

**Issue by MrRace** [k2-fsa/sherpa-onnx#931]
I used the [whisper/test.py](https://github.com/k2-fsa/sherpa-onnx/blob/master/scripts/whisper/test.py) script to test model inference, but I found that audio longer than 30 seconds is being truncated. Is there a plan to improve this part of the code to support evaluation of long audio? Thanks a lot!

**Comment by csukuangfj** [comment]
Whisper supports at most 30 seconds.

To support longer audios, we have to break then into chunks, each of which should be less than 30 seconds long.

We provide VAD + ASR.
You can try silero VAD + Whisper tiny.en Android APK provided by us.
Please see https://k2-fsa.github.io/sherpa/onnx/vad/apk-asr-cn.html

(Specifically, the APK for whisper is https://hf-mirror.com/csukuangfj/sherpa-onnx-apk/blob/main/vad-asr/sherpa-onnx-1.9.25-x86_64-vad_asr-en-whisper_tiny.apk)

Currently, we have no plan to make test.py support longer audios.

**Comment by MrRace** [comment]
> Whisper supports at most 30 seconds.
> 
> To support longer audios, we have to break then into chunks, each of which should be less than 30 seconds long.
> 
> We provide VAD + ASR. You can try silero VAD + Whisper tiny.en Android APK provided by us. Please see https://k2-fsa.github.io/sherpa/onnx/vad/apk-asr-cn.html
> 
> (Specifically, the APK for whisper is https://hf-mirror.com/csukuangfj/sherpa-onnx-apk/blob/main/vad-asr/sherpa-onnx-1.9.25-x86_64-vad_asr-en-whisper_tiny.apk)
> 
> Currently, we have no plan to make test.py support longer audios.
@csukuangfj 
Wow, the provided APK looks great. Is there a detailed guide available for compiling these APKs? I may need to fine-tune my own model.  Thanks a lot!

**Comment by MrRace** [comment]
@csukuangfj  
If I want to deploy Whisper in an online mode to a mobile phone, it seems that the current [guide ](https://k2-fsa.github.io/sherpa/onnx/pretrained_models/whisper/index.html ) only supports offline mode? 
So, if I want to deploy the Whisper model with online mode to a mobile phone, how should I modify the [code](https://github.com/k2-fsa/sherpa-onnx/blob/master/sherpa-onnx/kotlin-api/OnlineRecognizer.kt#L185) that I can add a new model?  Thanks! Additionally, I noticed that some models in the [download list](https://github.com/k2-fsa/sherpa-onnx/releases/tag/asr-models) have "stream" in their names while others do not. Does this mean that if I want to deploy the same model both online and offline, I need to export two separate model files?

**Comment by csukuangfj** [comment]
> If I want to deploy Whisper in online mode to a mobile phone, it seems that the current [guide ](https://k2-fsa.github.io/sherpa/onnx/pretrained_models/whisper/index.html)only supports offline mode?
So, if I want to deploy the Whisper model with online mode to a mobile phone, how should I modify the [code](https://github.com/k2-fsa/sherpa-onnx/blob/master/sherpa-onnx/kotlin-api/OnlineRecognizer.kt#L185) that I can add a new model?

We also want to do that. Please tell us if you find a framework supporting that.


---

> Does this mean that if I want to deploy the same model both online and offline, I need to export two separate model files?

Yes.

**Comment by MrRace** [comment]
> > Does this mean that if I want to deploy the same model both online and offline, I need to export two separate model files?
> 
> Yes.

@csukuangfj  Is there a corresponding guide for exporting the model separately for online and offline models? Thank you very much for your response.

**Comment by csukuangfj** [comment]
> > > Does this mean that if I want to deploy the same model both online and offline, I need to export two separate model files?
> > 
> > 
> > Yes.
> 
> @csukuangfj Is there a corresponding guide for exporting the model separately for online and offline models? Thank you very much for your response.

Please see our icefall doc for model exporting.
