### ISSUE TITLE
Audio Not properly configured in swift examples

### ISSUE THREAD

**Issue by Web3Kev** [k2-fsa/sherpa-onnx#938]
I had a few issues with the following pojects : iOS-swift/SherpaOnnx and iOS-swiftui/sherpaonnx2pass
I am on Xcode 15.4 and it kept on crashing at initialization with error : Thread 1: "required condition is false: IsFormatSampleRateAndChannelCountValid(format)"

I fixed it by creating the following method:
```
func configureAudioSession() {
 do {
      let audioSession = AVAudioSession.sharedInstance()
      try audioSession.setCategory(.playAndRecord, mode: .default, options: [])
      try audioSession.setActive(true)
      print("setup successful")
 } catch {
       print("Audio setup error: \(error)")
 }
 } 
```

and calling it in  iOS-swift/SherpaOnnx's ViewController

```
override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        configureAudioSession()
        resultLabel.text = "ASR with Next-gen Kaldi\n\nSee https://github.com/k2-fsa/sherpa-onnx\n\nPress the Start button to run!"
        recordBtn.setTitle("Start", for: .normal)
        initRecognizer()
        initRecorder()
    }

    
```

and in  iOS-swiftui/sherpaonnx2pass's SherpaOnnxViewModel

```
init() {
        configureAudioSession()
        initRecognizer()
        initOfflineRecognizer()
        initRecorder()
    }
```

**Comment by csukuangfj** [comment]
Are you using the latest code?

Please update the `Info.plist` file to allow accessing the microphone.

**Comment by Web3Kev** [comment]
I wasn't using the latest code. Thanks !

**Comment by csukuangfj** [comment]
Glad to hear you finally made it!
