### ISSUE TITLE
Port to rv1106 , -/bin/sh: ./sherpa-onnx: not found

### ISSUE THREAD

**Issue by hapymaker** [k2-fsa/sherpa-onnx#942]
sherpa-onnx
sherpa-onnx-alsa
sherpa-onnx-alsa-offline
sherpa-onnx-alsa-offline-audio-tagging
sherpa-onnx-alsa-offline-speaker-identification
sherpa-onnx-keyword-spotter
sherpa-onnx-keyword-spotter-alsa
sherpa-onnx-offline
sherpa-onnx-offline-audio-tagging
sherpa-onnx-offline-language-identification
sherpa-onnx-offline-parallel
sherpa-onnx-offline-punctuation
sherpa-onnx-offline-tts
sherpa-onnx-offline-tts-play-alsa
sherpa-onnx-vad-alsa
# chmod 777 * 
# ./sherpa-onnx
-/bin/sh: ./sherpa-onnx: not found
does anyone meet this error ?
cross compiler use :
arm-none-linux-gnueabihf-gcc -v
使用内建 specs。
COLLECT_GCC=arm-none-linux-gnueabihf-gcc
COLLECT_LTO_WRAPPER=/work/SDK231219/HFMedia2/onnx/sherpa-onnx/gcc-arm-10.3-2021.07-x86_64-arm-none-linux-gnueabihf/bin/../libexec/gcc/arm-none-linux-gnueabihf/10.3.1/lto-wrapper
目标：arm-none-linux-gnueabihf
配置为：/data/jenkins/workspace/GNU-toolchain/arm-10/src/gcc/configure --target=arm-none-linux-gnueabihf --prefix= --with-sysroot=/arm-none-linux-gnueabihf/libc --with-build-sysroot=/data/jenkins/workspace/GNU-toolchain/arm-10/build-arm-none-linux-gnueabihf/install//arm-none-linux-gnueabihf/libc --with-bugurl=https://bugs.linaro.org/ --enable-gnu-indirect-function --enable-shared --disable-libssp --disable-libmudflap --enable-checking=release --enable-languages=c,c++,fortran --with-gmp=/data/jenkins/workspace/GNU-toolchain/arm-10/build-arm-none-linux-gnueabihf/host-tools --with-mpfr=/data/jenkins/workspace/GNU-toolchain/arm-10/build-arm-none-linux-gnueabihf/host-tools --with-mpc=/data/jenkins/workspace/GNU-toolchain/arm-10/build-arm-none-linux-gnueabihf/host-tools --with-isl=/data/jenkins/workspace/GNU-toolchain/arm-10/build-arm-none-linux-gnueabihf/host-tools --with-arch=armv7-a --with-fpu=neon --with-float=hard --with-mode=thumb --with-arch=armv7-a --with-pkgversion='GNU Toolchain for the A-profile Architecture 10.3-2021.07 (arm-10.29)'
线程模型：posix
Supported LTO compression algorithms: zlib
gcc 版本 10.3.1 20210621 (GNU Toolchain for the A-profile Architecture 10.3-2021.07 (arm-10.29))

**Comment by hapymaker** [comment]
problem fixed , up load all compiler's so ,it is okay for now

**Comment by csukuangfj** [comment]
太棒啦！

**Comment by Stonedcs** [comment]
@hapymaker RV1106原系统应该是uClibc的工具链编译的吧  sherpa使用glibc工具链编译的  直接跑会有链接器的问题
你是使用glibc重新生成RV1106固件跑的吗？

**Comment by Stonedcs** [comment]
@hapymaker 你那跑起来性能如何？我这跑不起来（芯片CPU性能太弱了，NPU又不支持）

<img width="1831" height="261" alt="Image" src="https://github.com/user-attachments/assets/d942c363-090d-41ad-bceb-2cdd71b14a3b" />
