### ISSUE TITLE
iOS 无法引入 framework

### ISSUE THREAD

**Issue by wujingcheng7** [k2-fsa/sherpa-onnx#952]
我使用 github 提供的 demo，顺利地安装 sherpa-onnx.xcframework onnxruntime.xcframework 并且在真机顺利运行了 SherpaOnnxTts 项目。
但是当我尝试将其引入我自己创建的项目时，我直接将 xcframework 拖入 Xcode 项目，将官方 demo 代码完全 copy 到我的项目里，编译器始终报错找不到类，报了上百个。
<img width="922" alt="image" src="https://github.com/k2-fsa/sherpa-onnx/assets/32445011/8f7e2bf0-9cb3-499c-b859-d42ee1df2030">
<img width="675" alt="image" src="https://github.com/k2-fsa/sherpa-onnx/assets/32445011/6681d3c3-ba75-481b-a257-4c21bba538fd">
<img width="1327" alt="image" src="https://github.com/k2-fsa/sherpa-onnx/assets/32445011/5655bc72-51c0-472b-b5f9-5a40ec3b6bf5">
<img width="1148" alt="image" src="https://github.com/k2-fsa/sherpa-onnx/assets/32445011/738c1617-4955-472d-bc41-82e301c6ea16">
<img width="1088" alt="image" src="https://github.com/k2-fsa/sherpa-onnx/assets/32445011/c25b2b8b-cc8e-4583-a75d-5dbbbd985e8f">

**Comment by csukuangfj** [comment]
https://k2-fsa.github.io/sherpa/ncnn/ios/for-the-more-curious-swift.html

请看这个。

把 ncnn 改成 onnx, 方法是一样的。

---

首先你要明白，依赖不仅仅只有这两个 framework.

你还需要设置 bridge 的.

---

具体的，请按照上面给的文档来

**Comment by wujingcheng7** [comment]
> https://k2-fsa.github.io/sherpa/ncnn/ios/for-the-more-curious-swift.html
> 
> 请看这个。
> 
> 把 ncnn 改成 onnx, 方法是一样的。
> 
> 首先你要明白，依赖不仅仅只有这两个 framework.
> 
> 你还需要设置 bridge 的.
> 
> 具体的，请按照上面给的文档来

好的，感谢大佬。我再试试看。
