### ISSUE TITLE
Flutter android offline speech recognition.

### ISSUE THREAD

**Issue by cakmmak** [k2-fsa/sherpa-onnx#953]
Hello, thank you for this library.  How to extract a wav file for android with Flutter.  Is there any example?

**Comment by csukuangfj** [comment]
We have dart APIs at
https://github.com/k2-fsa/sherpa-onnx/tree/master/sherpa-onnx/flutter


We also provide flutter demo for streaming speech recognition and VAD.
(Pre-built Apps are available at https://github.com/k2-fsa/sherpa-onnx/releases/tag/v1.9.25)

Please develop demos for offline speech recognition by yourself.

Our main goal is to provide dart API.

**Comment by csukuangfj** [comment]
Here is the Dart package for sherpa-onnx
https://pub.dev/packages/sherpa_onnx

---

Pure Dart examples can be found at
https://github.com/k2-fsa/sherpa-onnx/tree/master/dart-api-examples
