### ISSUE TITLE
shaerpa-onnx 在ios上报错：Precondition failed: encoder.int8.onnx does not exist!

### ISSUE THREAD

**Issue by 136323000** [k2-fsa/sherpa-onnx#956]
我按照下面的文档操作
https://k2-fsa.github.io/sherpa/onnx/ios/build-sherpa-onnx-swift.html
得到报错：
<img width="1439" alt="image" src="https://github.com/k2-fsa/sherpa-onnx/assets/49808133/74e61d37-f029-46e3-9ee2-121c7733a532">
我应该怎么解决 谢谢各位

**Comment by csukuangfj** [comment]
1.你在代码里，选择用哪个模型呢？

**Comment by 136323000** [comment]
> 1.你在代码里，选择用哪个模型呢？
我是按照这个教程：https://k2-fsa.github.io/sherpa/onnx/ios/build-sherpa-onnx-swift.html
下载了这个模型：
<img width="1410" alt="image" src="https://github.com/k2-fsa/sherpa-onnx/assets/49808133/bb9912b9-8011-4fd1-87e5-95ec253b0ee8">
并按照教程添加了这4个文件
<img width="1385" alt="image" src="https://github.com/k2-fsa/sherpa-onnx/assets/49808133/39e37b00-4cec-475c-a02a-6260689202cc">

**Comment by csukuangfj** [comment]
代码支持多个模型，你修改了什么，选择了哪个模型？

如果你没做任何修改，请去看看默认使用哪个模型？

如果你还没看过代码，请先去看看代码。注意，就是一行代码，别想复杂了。

**Comment by 136323000** [comment]
哦哦 非常感谢 我刚刚看到了 原来要自己选择对应模型 
<img width="1418" alt="image" src="https://github.com/k2-fsa/sherpa-onnx/assets/49808133/3c5ea97c-631b-4726-b0d5-1ca66bd0b316">
具体模型文件在响应的函数里设置 
非常感谢您的提示
