### ISSUE TITLE
How to disable logs for offline-paraformer-greedy-search-decoder.cc

### ISSUE THREAD

**Issue by bnuzhouwei** [k2-fsa/sherpa-onnx#966]
Each detection write a log in the console, how to disable it!

```
D:\a\sherpa-onnx\sherpa-onnx\sherpa-onnx\csrc\offline-paraformer-greedy-search-decoder.cc:Decode:70 time stamp for batch: 0, 20 vs 0
```

**Comment by csukuangfj** [comment]
please describe which model you are using.

**Comment by bnuzhouwei** [comment]
> please describe which model you are using.

sherpa-onnx-paraformer-trilingual-zh-cantonese-en

**Comment by csukuangfj** [comment]
Please remove
sherpa-onnx\csrc\offline-paraformer-greedy-search-decoder.cc:Decode:70
and re-build.

Or wait our next release.

**Comment by csukuangfj** [comment]
Fixed in the latest master.
