### ISSUE TITLE
[feature request] remember speed

### ISSUE THREAD

**Issue by gilcu3** [k2-fsa/sherpa-onnx#973]
This is somehow a follow-up from #705. 

It would greatly improve usability if the app (tts engine) remembered the reading speed set by the user. Currently, it resets to 1 after each update.

**Comment by csukuangfj** [comment]
Would you like to contribute?

**Comment by gilcu3** [comment]
@csukuangfj #991 is a very simple solution to this. I am not an android developer so it might need improvements.

**Comment by csukuangfj** [comment]
> @csukuangfj #991 is a very simple solution to this. I am not an android developer so it might need improvements.

Thank you so much!
