### ISSUE TITLE
[csharp] SherpaOfflinePunctuationAddPunct. Unhandled exception. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception

### ISSUE THREAD

**Issue by bnuzhouwei** [k2-fsa/sherpa-onnx#975]
一段40分钟音频就别做疲劳测试，随机出现一些文本会报External component has thrown an exception.

说明现实生活中肯定更没有超载了因为现实生活中比这七点五吨还轻呢肯定不能中过八折对吗不多说了啊好继续
Unhandled exception. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at SherpaOnnx.OfflinePunctuation.SherpaOfflinePunctuationAddPunct(IntPtr handle, String text)
   at SherpaOnnx.OfflinePunctuation.AddPunct(String text)

**Comment by csukuangfj** [comment]
Please see
https://github.com/k2-fsa/sherpa-onnx/pull/976

You need to build sherpa-onnx from source.

**Comment by csukuangfj** [comment]
A sample output for your text is given below

```
input: 说明现实生活中肯定更没有超载了因为现实生活中比这七点五吨还轻呢肯定不能中过八折对吗不多说了啊好继续
output: 说明现实生活中肯定更没有超载了，因为现实生活中比这七点五吨还轻呢，肯定不能中过八折。对吗？不多说了啊，好继续。
```
