### ISSUE TITLE
whisper onnx convert to rknn

### ISSUE THREAD

**Issue by Hestinorwu** [k2-fsa/sherpa-onnx#979]
Hello,there! i have looked the `https://github.com/k2-fsa/sherpa-onnx/blob/master/scripts/whisper/export-onnx.py` it's a nice try to use whisper model in different platform by using ONNX format. 
I'm trying to convert it to rknn format(a model type in RKs device) to use rknpu. But i meet some obstacles.

**1.I use the export-onnx.py export encoder and decoder successfully.**

**2.I try to build a script to convert onnx to rknn. By netron i can see the structure of onnx.**
The input seems to be a dynamic shape.[n_audio,80,T],So i use dynamic_input in exporting rknn(code below),Then i successfully export it(encoder.rknn).
But when i run it in RK3568 device ,somethings go wrong. 
Do you have interest in convert to rknn? Hope you can give me some advice.
![image](https://github.com/k2-fsa/sherpa-onnx/assets/89848374/083ac169-134a-4cdb-abb6-529657e525c7)

![image](https://github.com/k2-fsa/sherpa-onnx/assets/89848374/de152233-1e7c-44e3-8d0b-aa6e89af1d29)

```
from rknn.api import RKNN
import os
import onnx
import sys

dynamic_input=[
    [[1,80,3000]]
]

model_path='base-models/base-encoder.onnx'
model = onnx.load(model_path)
onnx.checker.check_model(model)
print("The model is checked!")


# Create RKNN object
rknn = RKNN(verbose=False)

# Pre-process config
print('--> Config model')
rknn.config(target_platform='rk3568',
            dynamic_input=dynamic_input,
            )
print('done')

# Load model
print('--> Loading model')
ret = rknn.load_onnx(model=model_path)
if ret != 0:
    print('Load model failed!')
    exit(ret)
print('done')

 # Build model
print('--> Building model')
ret = rknn.build(do_quantization=False)
if ret != 0:
    print('Build model failed!')
    exit(ret)
print('done')


# Export rknn model
print('--> Export rknn model')
ret = rknn.export_rknn('base-encoder-3568-int8.rknn',gen_cpp_demo=True)
if ret != 0:
    print('Export rknn model failed!')
    exit(ret)
print('done')

# 
rknn.release()
```

rknn.py:
```
import cv2
import numpy as np
import platform
from rknnlite.api import RKNNLite
import argparse
import base64
from typing import Tuple

import kaldi_native_fbank as knf
import onnxruntime as ort
import torch
import torchaudio

from test import *

# get current platform Structure
DEVICE_COMPATIBLE_NODE = '/proc/device-tree/compatible'

def get_host():
    # get platform and device type
    system = platform.system()
    machine = platform.machine()
    os_machine = system + '-' + machine
    if os_machine == 'Linux-aarch64':
        try:
            with open(DEVICE_COMPATIBLE_NODE) as f:
                device_compatible_str = f.read()
                # print(device_compatible_str)
                # SAMPLES : embedfire,lubancat-2-v2rockchip,rk3568
                if 'rk3562' in device_compatible_str:
                    host = 'RK3562'
                elif 'rk3576' in device_compatible_str:
                    host = 'RK3576'
                elif 'rk3588' in device_compatible_str:
                    host = 'RK3588'
                else:
                    host = 'RK3566_RK3568'
        except IOError:
            print('Read device node {} failed.'.format(DEVICE_COMPATIBLE_NODE))
            exit(-1)
    else:
        host = os_machine
    return host

Model_path='base-encoder-rk3568.rknn'

sound_file='1s.wav'
Decoder_path='tiny-decoder.onnx'
Encoder_path='tiny-encoder.onnx'
Tokens='tiny-tokens.txt'

mel = compute_features(sound_file)

print(mel.shape)

np_mel=mel.numpy()
print(type(np_mel))
print(np_mel.shape)

#model = OnnxModel(Encoder_path,Decoder_path)
#n_layer_cross_k,n_layer_cross_v=model.run_encoder(mel)

#print(type(n_layer_cross_k),type(n_layer_cross_v))

# print(n_layer_cross_k.shape,n_layer_cross_v.shape)


#host_name=get_host()
#print(host_name)
rknn_lite = RKNNLite()
# load rknn model
ret = rknn_lite.load_rknn(Model_path)
if ret !=0:
    print('Load rknn model failed')
    exit(ret)
print('Done!')

# Init runtime environment
print('--> Init runtime environment')
# Run on RK356x / RK3576 / RK3588 with Debian OS, do not need specify target.
ret = rknn_lite.init_runtime()
if ret != 0:
    print('Init runtime environment failed')
    exit(ret)
print('done')


# Inference
print('--> Running model')
outputs=rknn_lite.inference(inputs=[np_mel])

print(type(outputs))
```

**Comment by csukuangfj** [comment]
Please remove
https://github.com/k2-fsa/sherpa-onnx/blob/69347ffc8f299060a11e43cf6e194822b6356581/scripts/whisper/export-onnx.py#L104

and
https://github.com/k2-fsa/sherpa-onnx/blob/69347ffc8f299060a11e43cf6e194822b6356581/scripts/whisper/export-onnx.py#L416-L420
and
https://github.com/k2-fsa/sherpa-onnx/blob/69347ffc8f299060a11e43cf6e194822b6356581/scripts/whisper/export-onnx.py#L540-L546

And retry.

**Comment by Hestinorwu** [comment]
Thanks for your attention. i find a part is distinct.
I check my yolov8-pose which successfully use rknn,and i open the verbose when init rknn_runtime, you can see firstlayer all information is complete. but in whisper the first layer DataFormat is missing. I don't know whether this causes Aborted.

yolov8-pose verbose:
![image](https://github.com/k2-fsa/sherpa-onnx/assets/89848374/01ca8832-c606-41fb-b535-047db96ea521)
Netron show:
![image](https://github.com/k2-fsa/sherpa-onnx/assets/89848374/62f05ede-39ba-49d6-8496-4f3db49131e5)

whisper verbose:
![image](https://github.com/k2-fsa/sherpa-onnx/assets/89848374/59371b0e-e1b0-4f65-b095-dc79005bddd8)
whisper Netron show:
![image](https://github.com/k2-fsa/sherpa-onnx/assets/89848374/445f4f1d-951b-439c-8a16-a80f40353472)

**Comment by csukuangfj** [comment]
whisper uses a 3-d input, not a 4-d.

**Comment by csukuangfj** [comment]
Please try to convert the model layer by layer and also debug it layer by layer.

This is issue is out of scope of sherpa-onnx.

**Comment by jinchao123** [comment]
Is the problem solved?

**Comment by briliantnugraha** [comment]
Hi @jinchao123 @HduHestin,  I found that this line is the culprit, since positional_embedding is a fixed size, causing the dynamic conversion to fail on encoder model.
https://github.com/k2-fsa/sherpa-onnx/blob/master/scripts/whisper/export-onnx.py#L105

Possible solution to this is to put positional_embedding as an input, so that when they do the addition, the input and this variable match in size, hope it helps :)

**Comment by briliantnugraha** [comment]
but sadly, it seems that whisper model uses fixed positional_embedding size for both encoder and decoder in the model checkpoint (this is transformer limitation though), so I guess we can just add padding on the input for now xD

FYI, if we're using padding to make it fixed input, it "seems" to work normally~
![image](https://github.com/user-attachments/assets/db4d6af8-e476-4b99-b575-05a67b32c2c5)

**Comment by csukuangfj** [comment]
Please see https://github.com/airockchip/rknn_model_zoo/tree/main/examples/whisper

**Comment by briliantnugraha** [comment]
Thanks for sharing @csukuangfj ~
But yeah, same thing, they also didn't support dynamic shape. Anyway, at least it works for now with fix shape :)

**Comment by slowym** [comment]
发生异常: ValueError
Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 344, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 1945, in rknn.api.rknn_base.RKNNBase.build
  File "rknn/api/graph_optimizer.py", line 893, in rknn.api.graph_optimizer.GraphOptimizer.fold_constant
  File "rknn/api/graph_optimizer.py", line 366, in rknn.api.graph_optimizer._dynamic_check
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: The input 1 of Slice('/Slice') need to be constant! It will cause the graph to be a dynamic graph!
                  Remove Slice('/Slice') manually and try again!
ValueError: The input 1 of Slice('/Slice') need to be constant! It will cause the graph to be a dynamic graph!
                  Remove Slice('/Slice') manually and try again!

During handling of the above exception, another exception occurred:

  File "/home/huidacvbig/002Data2/hym/06_speech_recognition/sherpa-onnx-master/scripts/whisper/convert_rknn_0730.py", line 257, in <module>
    ret = rknn.build(do_quantization=False)
ValueError: Traceback (most recent call last):
  File "rknn/api/rknn_log.py", line 344, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper
  File "rknn/api/rknn_base.py", line 1945, in rknn.api.rknn_base.RKNNBase.build
  File "rknn/api/graph_optimizer.py", line 893, in rknn.api.graph_optimizer.GraphOptimizer.fold_constant
  File "rknn/api/graph_optimizer.py", line 366, in rknn.api.graph_optimizer._dynamic_check
  File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e
ValueError: The input 1 of Slice('/Slice') need to be constant! It will cause the graph to be a dynamic graph!
                  Remove Slice('/Slice') manually and try again!

When converting decoder to rknn, I encountered an issue. Can it be resolved?

**Comment by csukuangfj** [comment]
> 发生异常: ValueError Traceback (most recent call last): File "rknn/api/rknn_log.py", line 344, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper File "rknn/api/rknn_base.py", line 1945, in rknn.api.rknn_base.RKNNBase.build File "rknn/api/graph_optimizer.py", line 893, in rknn.api.graph_optimizer.GraphOptimizer.fold_constant File "rknn/api/graph_optimizer.py", line 366, in rknn.api.graph_optimizer._dynamic_check File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e ValueError: The input 1 of Slice('/Slice') need to be constant! It will cause the graph to be a dynamic graph! Remove Slice('/Slice') manually and try again! ValueError: The input 1 of Slice('/Slice') need to be constant! It will cause the graph to be a dynamic graph! Remove Slice('/Slice') manually and try again!
> 
> During handling of the above exception, another exception occurred:
> 
> File "/home/huidacvbig/002Data2/hym/06_speech_recognition/sherpa-onnx-master/scripts/whisper/convert_rknn_0730.py", line 257, in ret = rknn.build(do_quantization=False) ValueError: Traceback (most recent call last): File "rknn/api/rknn_log.py", line 344, in rknn.api.rknn_log.error_catch_decorator.error_catch_wrapper File "rknn/api/rknn_base.py", line 1945, in rknn.api.rknn_base.RKNNBase.build File "rknn/api/graph_optimizer.py", line 893, in rknn.api.graph_optimizer.GraphOptimizer.fold_constant File "rknn/api/graph_optimizer.py", line 366, in rknn.api.graph_optimizer._dynamic_check File "rknn/api/rknn_log.py", line 95, in rknn.api.rknn_log.RKNNLog.e ValueError: The input 1 of Slice('/Slice') need to be constant! It will cause the graph to be a dynamic graph! Remove Slice('/Slice') manually and try again!
> 
> When converting decoder to rknn, I encountered an issue. Can it be resolved?

Please ask in rknn model zoo.
