### ISSUE TITLE
Runtime option to disable sherpa logs

### ISSUE THREAD

**Issue by manickavela29** [k2-fsa/sherpa-onnx#983]
Currently sherpa logs are controlled at 2 levels

1. Build time with SHERPA_ONNX_ENABLE_CHECK option
2. Runtime with SHERPA_ONNX_LOG_LEVEL env variable

But there is no control at runtime logs to disable,
will be handy in controlling at runtime.

will send a PR for this, let me know your thoughts
cc: @csukuangfj , @pkufool

**Comment by manickavela29** [comment]
Also adding SHERPA_ONNX_ENABLE_CHECK flag as part of the build tests might be necessary,
so that code bugs such as this isn't missed.

I know that it is necessary for all the builds, but I have only tested for linux,
if its good I will send a PR changing all the workflows or it can just be related to linux builds

**Comment by csukuangfj** [comment]
We are switching to
https://github.com/k2-fsa/sherpa-onnx/blob/fc09227cd1aada502e12e3c9b4cc948c7e55d68f/sherpa-onnx/csrc/macros.h#L11

https://github.com/k2-fsa/sherpa-onnx/blob/master/sherpa-onnx/csrc/log.h
is intended to be removed.

---

If you want to disable all logs, just use
```
#define SHERPA_ONNX_LOGE(...)
```
