### ISSUE TITLE
Convert new piper tts models. 

### ISSUE THREAD

**Issue by Violetadhdgd** [k2-fsa/sherpa-onnx#987]
Hi, just a new user here. Don't know what I am doing but can someone convert new tts models from piper, eg. Hfc female, john, Norman, Bryce etc. I tried converting them but I am not that knowledgeable in this.

**Comment by csukuangfj** [comment]
Done!

Please try them at
https://huggingface.co/spaces/k2-fsa/text-to-speech

You can also download them from
https://github.com/k2-fsa/sherpa-onnx/releases/tag/tts-models

---

By the way, you can follow
https://k2-fsa.github.io/sherpa/onnx/tts/piper.html
to convert models from piper to sherpa-onnx
by yourself.
